### ISSUE TITLE
IDE X, SCC history issues

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1527] opened 2016-05-18 16:25 UTC
### Short Summary

SCC - subversion

1. Incorrect (uncommon) order in SCC history.
Should be from last to older (_now from older to last_).
2. (I think related to the previous) When I try to see Project History in bottom pane, history display only 25 first revisions, but should last. (And better to select how many revision to see).
3. Missing Revision column in SCC history in any place or window.
4. When select any revision line, it show diff with next revision, but should with previous.

### Steps to Reproduce

Just use show history from menu.

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

### Additional Information

possible it is important, I have non-US locale in system: `LANG=ru_RU.UTF-8`

**Comment by Naatan** [comment] 2016-05-18 16:40
1. I've seen this too when filtering, thanks for reporting!
2. This is by design, if we list everything here it bogs down the IDE as it is on-screen at all times.
3. Please try toggling it using the column picker at the top right of the list. If this does not work please open a new bug report so we aren't talking about multiple issues in one report.
4. I have not seen this. What VCS are you using?

**Comment by landy2005** [comment] 2016-05-18 18:51
> 2. This is by design, if we list everything here it bogs down the IDE as it is on-screen at all times.
limit this is ok, but I said about uncommon sorting - first 25 **instead last 25**. My project has 7k revisions, but here displayed 1-25 revisions, which toooooo old :)

> 3. Please try toggling it using the column picker at the top right of the list.
Missing in this picker, but ok I will create other issue

VCS - **subversion**.

I think 1,2,4 all same issue about sorting order in history..

**Comment by Naatan** [comment] 2016-05-18 18:57
Definitely sounds like it could be. I've not seen this with git but it's possibly svn is doing things differently.

**Comment by Naatan** [comment] 2016-05-19 20:09
Fixed with https://github.com/Komodo/KomodoIDE/commit/64a3583367ca5d7711aa9f59c2f4ddb12a338b08

**Closed by Naatan** 2016-05-19 20:09 UTC
Labels: Bug
