### ISSUE TITLE
Debugging where one of the Perl modules implemented using PERLXS in C++

### ISSUE THREAD

**Issue by jrheisey** [Komodo/KomodoEdit#1074] opened 2016-02-09 00:37 UTC
Nathan Rijksen of Active State asked me to create this bug report from OTRS#030045966.

-----------------------------------------------------------------------
Working in Windows 7, Perl 5.8.8.
Just downloaded Komodo to debug a Perl application implemented partially in xxx.pl
script and partially in a Perl extension module written in C++ and PerlXS and
built as a DLL.
This application has been around for more than 10 years.

The DLL module has more then 900 variables that are added to the Perl context by C
statements such as

    PUSHs(sv_2mortal(newSVpv("simVarType_flagBit",0)));
    PUSHs(sv_2mortal(newSVnv(simVarType_flagBit)));

This simVarType_flagBit shared variable happens to be an enum constant defined in
C++.
The Komodo debugger is flagging the references as "requires explicit package name"
in the Perl code unless I use the appropriate scoping prefix. Due to the number of
variables manually fixing this would take a lot of work.
I am hoping someone could give me another way to accomplish this.

**Comment by jrheisey** [comment] 2016-02-09 00:41
Note that I ignore the errors and still run my app under the debugger.
One issue I have in this scenario is that the "pause" toolbar button and "Break Now" menu item both remain grayed.

**Comment by Naatan** [comment] 2016-02-09 00:42
Could you clarify whether debugging work despite this error?

Would you be able to create a minimal test case that reproduces the issue?

**Comment by jrheisey** [comment] 2016-02-09 00:59
In researching the effort I discovered that the propagation of the constants into the Perl scope is not performed strictly with PERLXS. I found this code snippet.

BEGIN {

  # The myGetConsts() function implemented in the DLL
  # returns a list of name-value pairs of these constants suitable
  # for converting to a hash.  This code imports all the constants
  # compiled into the DLL into Perl variables like $myVarType_int.

BEGIN {
  %myCoreConsts = ( myGetConsts() );
  foreach my $var (keys %myCoreConsts) {
    no strict 'refs';
    eval "use vars '\$$var'";
    $$var = $myCoreConsts{$var};
  }
}

Perhaps the issue can be replicated by hard coding the initialization of %myCoreConsts from some name value pairs and using this code.

**Comment by Naatan** [comment] 2016-02-09 16:15
Hi @jrheisey, could you please answer the 2 questions in my previous post.

**Comment by jrheisey** [comment] 2016-02-09 19:07
My post one minute before yours says I can use the debugger despite the errors.
I have use the snippet of code above into a complete Perl script to replicate the IDE parsing error.

The site won't let me upload the script file to here is the full text.

```
#!/usr/bin/perl -w
use strict;

our %myCoreConsts;

BEGIN {

  # The myGetConsts() function implemented in the DLL
  # returns a list of name-value pairs of these constants suitable
  # for converting to a hash.  This code imports all the constants
  # compiled into the DLL into Perl variables like $myVarType_int.

  # %myCoreConsts = ( myGetConsts() );
  %myCoreConsts = ( "myconst", 0xfeedbacc );
  foreach my $var (keys %myCoreConsts) {
    no strict 'refs';
    eval "use vars '\$$var'";
    $$var = $myCoreConsts{$var};
  }
}

my $myVariable = $myconst;

printf ("myVariable = %x\n", $myVariable);

```
The reference to $myconst generates a compilation error in the Komodo editor.

**Comment by Naatan** [comment] 2016-02-09 22:39
Ok, it sounds to me like the following is going on:

 * The linter (not the debugger) is flagging an issue with the way you are including libraries
 * The debugger runs despite this apparent issue
 * You believe that the pause / break now buttons are disabled as a result

My impression is that the second and third issue there are not actually issues. Pause and break now would only be enabled if you are in the middle of a debugging session that is currently running and not at a breakpoint. So that just leaves us with the linter. The reason the linter cannot validate your code properly is because you are setting these variables/libraries at runtime. They are not defined in a way such that they can be parsed statically, as such a linter cannot possibly interpret the necessary logic to validate your file.

I'm adding in @andygrundman, our Perl specialist. Andy, do you see any way to work around this issue? Are there any simple modifications he could make to have his code be Perl linter-friendly?

**Comment by andygrundman** [comment] 2016-02-09 23:10
Hi. My first thought is that you could simply use the hash you are already populating with all of the constant values. Instead of using $myconst, just use $myCoreConsts{myconst}. This seems like the simplest solution.

If you are interested to see how such a thing might be done the "proper" way, I would recommend studying the source code to Devel::NYTProf. This module has a Constants.pm which loads in a bunch of constants defined in XS. See the file lib/Devel/NYTProf/Constants.pm and search NYTProf.xs for "newCONSTSUB".

http://cpansearch.perl.org/src/TIMB/Devel-NYTProf-6.02/

**Comment by jrheisey** [comment] 2016-02-10 00:42
- No the code was not halted at a break point when I observed the pause button grayed. The 'stop debugging' button was active and did stop the script when clicked. I wanted to 'pause' so I could see what the script was doing.

- In the example $myCoreConsts initialization is just a contrived way of effecting the same issue without the need of creating a PERLXS module in C that contains the C function myGetConts(). In our production code that function returns an array of name value pairs suitable for a hash.

Creating objects in memory dynamically and referencing them in code is common to dynamic languages. Why does Perl allow the reference $$var = "something" to allocate a variable at all?

Since you are creating a linter specifically for a **dynamic** language I would expect such a linter to effectively execute all of the BEGIN code blocks to let such variables instantiate in such a way that the linter can reference them.

If I had written our C++ module I would have allocated the constants directly into the Perl context from the C code using the Perl API. It has been a while and at the moment I do not remember how to accomplish this.

The example you referenced does not appear to be referencing constants defined in C code.

**Comment by Naatan** [comment] 2016-02-10 16:18
> I would expect such a linter to effectively execute all of the BEGIN code blocks

That made me think of something, go into `Prefs > Syntax Checking > Language > Perl`, then uncheck "Don't execute BEGIN blocks in current document during syntax-checking". I tried this and now the code you shared passes without errors.

As for the break buttons being disabled, please have a look at the documentation here:

http://docs.komodoide.com/Manual/debugperl#debugging-perl-komodo-ide-only_configuring-the-perl-debugger_enabling-break-now

I believe that should resolve your issues. Closing this ticket because as it turns out there is no bug on our end (aside from some UX, which I've made a note of).

**Closed by Naatan** 2016-02-10 16:18 UTC
