### ISSUE TITLE
PHP CodeIntel throws errors at EOF

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#838] opened 2015-11-09 20:28 UTC
Open a new file, set the language as PHP, type in `foo`, your error log should show:

```
[2015-11-09 15:27:35,358] [ERROR] codeintel.oop.driver: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 161, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
[2015-11-09 15:27:35,371] [ERROR] koCodeIntel: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 161, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
```

Navigating to the EOF triggers this again.

**Comment by Defman21** [comment] 2015-11-09 20:30
Is this related to https://github.com/Komodo/KomodoEdit/issues/796? Seems like our error logs are the same.

**Comment by mitchell-as** [comment] 2015-11-09 20:37
Duplicate of #796.

**Closed by mitchell-as** 2015-11-09 20:37 UTC
Labels: Bug
