### ISSUE TITLE
"Tab" enters 8 spaces but file settings say: 4 with tab

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1008] opened 2016-01-14 14:54 UTC
Bug introduced with Komodo 9.3.1, still present in 9.3.2
Platform: WIndows 10 64Bit GER
(why is German important ? - C standard functions may return for the float "1.1" the localized value "1,1" (point replaced by comma). Also French localisation which is native to Canada).
Current File Preferences -> Indentiation:
Set to use tab with a width of 4 (see picture):
![komodo_tab](https://cloud.githubusercontent.com/assets/12413997/12327386/894321ee-bad6-11e5-89a1-a5e495f89757.png)
Now press tab key:
![komodo_tab_ressed](https://cloud.githubusercontent.com/assets/12413997/12327408/a81ef30e-bad6-11e5-9c54-16943c45fee3.png)
Observed behaviour:
8 spaces are inserted
Expected behaviour (true before 9.3.1):
one tab of size 4 is introduced.

This is a no-go bug of the editor, sorry. That was the reason why I desinstalled 9.3.1 and reverted to 9.3.0...

Sorry,
Harald

**Comment by Naatan** [comment] 2016-01-14 15:42
This appears to be a duplicate of https://github.com/Komodo/KomodoEdit/issues/995

Thank you for reporting, we'll get to this asap.

**Closed by Naatan** 2016-01-14 15:42 UTC
