### ISSUE TITLE
Komodo Edit not applying file association settings - version 9.2.1 build 15998

### ISSUE THREAD

**Issue by a289** [Komodo/KomodoEdit#714] opened 2015-10-09 20:12 UTC
I want Komodo Edit to open .js files automatically when double-clicking them.  I go to Edit -> Preferences -> Windows Integration, make sure .js is listed in "Make Komodo the default editor for these file extensions" and click "Re-apply settings to system".

When I double click on .js files though it brings up the "Open With" dialog rather than just opening in Komodo, and even worse, Komodo's not even in the list on that dialog, and if I browse to komodo.exe and select it, it still won't open it.

I've tried reapplying the settings with Komodo Edit running both as admin and non admin.  This is on Windows 7.

I've been using Komodo Edit since version 5 in case there's some old stuff causing an issue.  I had this issue with Komodo Edit 7 as well for sure, and perhaps other versions.

**Comment by Naatan** [comment] 2015-10-10 01:37
Duplicate of #220

**Closed by Naatan** 2015-10-10 01:37 UTC
