### ISSUE TITLE
Symbol browser shows "No Symbols found" for perl

### ISSUE THREAD

**Issue by pju55** [Komodo/KomodoEdit#3205] opened 2017-09-30 13:23 UTC
### Short Summary
After upgrading to Komodo 11 perl scripts/modules no longer show any symbols.
Clicking {} just show "No Symbols found". 
Symbols cannot be browsed either in the "Explorer bar". It just shows "...>(Select Symbol)"

### Steps to Reproduce
Open any perl script/module

### Expected results
Symbols shown in right pane.

### Actual results
At install it showed "Could not load due to an error, if the issue persists please file a bug"
Now it only says "No Symbols found".

Working as expected for .c files.

### Platform Information

*Komodo Edit or IDE? Komodo IDE, version 11.0.0, build 90668, platform win32-x86.
Built on Tue Sep 19 14:50:13 2017. 
*Komodo Version?* 
*Operating System (and version)?* Microsoft Windows [Version 10.0.15063] 64 bit

### Additional Information

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1346415/pystderr.log)

**Comment by mitchell-as** [comment] 2017-10-02 14:28
This is likely a duplicate of #3185.

**Comment by pju55** [comment] 2017-11-04 08:13
Sorry, but I still have no symbols for perl on Windows 10.
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1443057/pystderr.log)

Komodo IDE, version 11.0.1, build 90797, platform win32-x86.
Built on Fri Oct 27 14:40:19 2017.

**Comment by pju55** [comment] 2017-11-06 16:32
Sorry, but I really don't know what to provide. 
No matter which type of perl script I open - I just get the empty symbol browser, well saying "No symbols found".
If I open for instance some c-code, the browser works fine.
If you can help me further down the road, I would be happy to help.

**Comment by Naatan** [comment] 2017-11-06 19:29
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by pju55** [comment] 2017-11-06 20:34
Interesting - symbol browser works in fail-safe mode.

**Comment by Naatan** [comment] 2017-11-07 16:06
The most likely culprit is your language configuration: the import paths or environment variables. Could you share your codeintel3.log file after reproducing the issue? It is located in your profile folder: http://docs.activestate.com/komodo/11/manual/trouble.html#appdata_dir

**Comment by pju55** [comment] 2017-11-07 16:29
Sure:
[codeintel3.log](https://github.com/Komodo/KomodoEdit/files/1450775/codeintel3.log)

**Comment by Naatan** [comment] 2017-11-07 21:01
That log does not appear to cover a symbol request. Did you reproduce your issue (open symbol browser, note that it's empty) before copying that log?

**Comment by pju55** [comment] 2017-11-08 08:27
This is what I do - please correct me if it is wrong.
I open Komodo with a number of remembered files. 
The right pane opens in Toolbox.

I make for instance "Long.pm" active and click on `Long.pm > (Select Symbol)`
Underneath `(Select symbol)` the text `Loading..` occurs. And stays until I click something else on my screen. Nothing is added behind (Select symbol).
The other method is clicking Symbol Browser icon in the right pane. I shortly see a set of small squares followed by the text `No symbols found`.
Nothing is added to codeintel3.log while doing this.

**Comment by Naatan** [comment] 2017-11-08 16:01
Is the pystderr.log file you shared earlier from after reproducing the issue as well?

**Comment by pju55** [comment] 2017-11-09 09:48
Nothing is written to pystderr.log after the initialization of the GUI.
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1457131/pystderr.log)
So no matter what I click in regards of symbols browser stuff does not add anything new to the log.

**Comment by Naatan** [comment] 2017-11-09 16:04
Try executing the following in your Console widget (bottom pane):

```
require("ko/logging").getLogger("jsonrpc").setLevel(10);
```

Then reproduce your issue and share your error log again.

**Comment by pju55** [comment] 2017-11-09 16:28
Here you go.
Does the setting reset at next restart or should I do something?
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1458352/pystderr.log)

**Comment by pju55** [comment] 2017-11-16 17:40
May I ask if there is any news?

**Comment by Naatan** [comment] 2017-11-16 20:01
Sorry, I did not see your response.

Are you sure you reproduced the issue and THEN copied the log? The log shows no evidence of an API call for retrieving symbols.

**Comment by pju55** [comment] 2017-11-16 21:14
No problem :-)
And yes, absolutely. 
It feels to me - not knowing a bit about the design - as if Komodo is relying on a helper process, which does not run. The damage is so to speak done before getting to the point where I can click anything.
That's why I all the way has been in trouble when asked to "reproduce" - nothing just happens when I open the symbol browser. 
I have had a tail running on the logfile, and there is no writing to it when I ask for symbols.

**Comment by Naatan** [comment] 2017-11-16 21:58
Your log shows the helper process is running and is servicing requests. For some reason the symbol list request just isnt happening. Are you certain you have the symbol browser feature enabled under Preferences > Code Intelligence?

**Comment by pju55** [comment] 2017-11-16 22:16
Yes, it is enabled.
I use Komodo for perl (not working), c (working), PowerShell (not supported).
![2017-11-16 23_14_02-preferences](https://user-images.githubusercontent.com/32414636/32918843-0b768d22-cb24-11e7-8ea8-60361862733a.jpg)

**Comment by Naatan** [comment] 2017-11-16 23:07
Could you possibly share your prefs.xml (in your profile folder)? Note this may contain file paths or string values. If uncomfortable please feel free to email it to me directly - nathanr@activestate.com.

**Comment by Naatan** [comment] 2017-11-17 18:14
Ok thanks for the prefs.xml, turns out you have your Perl codeintel set to use the "legacy" API - which does NOT exist for Perl. I'm kind of curious how this got set in the first place, it shouldn't have given you that option at all.

Try running the following code in your console widget (bottom panel), then restart Komodo:

```
require("ko/prefs").deletePref("codeintel.symbolbrowser.use_legacy.Perl")
```

**Comment by pju55** [comment] 2017-11-17 18:37
You're THE MAN!
It did the trick 👍 
I have absolutely no idea either why it was there. I can assure you that I never ever would have played around with it...
Anyway, I'm just happy it works :-)
Thanks a lot for your super support !

**Comment by Naatan** [comment] 2017-11-17 18:52
Very strange, let me know if it happens again. Glad we got it sorted :)

**Closed by Naatan** 2017-11-17 18:52 UTC
Labels: Pending: Response
