### ISSUE TITLE
Code intel pref names are their pref.xml ids

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2989] opened 2017-08-29 22:51 UTC
### Short Summary

*prefs > code intel*:

`prefs.enable_gotodef` & `prefs.enable_jumpsections` should be *Enable Go To Def* & *Enable Jump Sections* respectively.
![capture](https://user-images.githubusercontent.com/655154/29847665-c4377a9c-8cd1-11e7-867d-e2ac7a0137c5.PNG)

**Comment by Naatan** [comment] 2017-08-30 15:34
Duplicate of #2958

**Closed by Naatan** 2017-08-30 15:34 UTC
Labels: Introduced: 11, Type: Bug
