### ISSUE TITLE
IDE X keybinding UI not showing some bindings

### ISSUE THREAD

**Issue by cdcmicro** [Komodo/KomodoEdit#1792] opened 2016-07-10 23:14 UTC
### Short Summary

In #1791, I described a keybinding (KB) that doesn't appear to be bound in the  KB Preferences dialog.

### Steps to Reproduce

Open Preferences/Keybindings and view the setting for "Editor: Go to End of word"

### Expected results

"Editor: Go to End of word" should show both Ctrl+E, and Ctrl+Right.  Both are bound by default.

### Actual results

![screenshot_071016_041013_pm](https://cloud.githubusercontent.com/assets/13684992/16716687/c98e2be0-46b8-11e6-9d51-ff4f7f3ebc28.jpg)

### Platform Information

Komodo IDE, version 10.0.1, build 89237, platform win32-x86.
Built on Wed Jun 15 10:57:56 2016.

### Additional Information

Maybe Ctrl+E and Ctrl+Right are the same.  But, after remapping Ctrl+Right to word-right in #1791, Ctrl+E still shows for Go to end of word.

**Comment by mitchell-as** [comment] 2016-07-11 14:35
Thanks for the report! I think having multiple key bindings for the same command (at least by default) is unintended, and our UI was designed around 1 keybinding per command.

@cgchoffman I think this ticket should be for ensuring that only one keybinding exists for a given command. If you disagree, feel free to re-tag, close, or whatever you see fit.

**Comment by cdcmicro** [comment] 2016-07-11 16:49
FWIW, I like having the flexibility of adding additional keybindings.

For example, in Windows, Ctrl+C and Ctrl+Insert both copy the selection to the clipboard.  Likewise, Ctrl+V/Shift+Insert both paste from the clipboard, and Ctrl+X/Shift+Del both cut the selection to the clipboard.

Shift+Insert to paste wasn't a default in X, and it was easy to add so it works like I expect.

**Comment by cgchoffman** [comment] 2016-07-11 17:22
I'm not seeing this.  There is a drop down arrow indicating that there are two bindings for the command:
![key-bindings](https://cloud.githubusercontent.com/assets/655154/16739896/2dc5efce-4751-11e6-9483-27a3c7b72535.gif)
Can you consistently reproduce this?
I think it's fine to have multiple bindings for one command @mitchell-as.  I think the binding system handles it just fine.

**Comment by cdcmicro** [comment] 2016-07-12 00:26
@cgchoffman I see the dropdown now.  Wish I had seen it before causing the churn here.  In my defense, I think it could be more conspicuous.  But that's a different issue for a different day.  Thank you for showing me.

**Comment by cgchoffman** [comment] 2016-07-12 00:41
@cdcmicro I honestly don't know why a dropdown list was chosen to display those items.  I think a multiline text field would make more sense.  

I'm going to close this ticket in favour of #1797

**Closed by cgchoffman** 2016-07-12 00:41 UTC
Labels: Pending: Response
