### ISSUE TITLE
11: Can't set breakpoints by clicking in editor margin

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2724] opened 2017-07-27 23:28 UTC
### Short Summary

Title

### Steps to Reproduce

- Open a file that can be debugged (Python, JS, PHP, etc.)
- Click the left most portion of the Editor margin

### Expected results

- a breakpoint to appear

### Actual results

No breakpointn.  I have to use the context menu or F4.
![breakpoint](https://user-images.githubusercontent.com/655154/28696120-96552316-72e8-11e7-93c9-53c921fa8157.GIF)

**Comment by Naatan** [comment] 2017-07-28 16:19
I can't reproduce this on either Windows or Linux. Can you reproduce this still? Anything in the error log?

**Comment by cgchoffman** [comment] 2017-07-28 17:34
Restarted, still reproducible.  Nothing in the logs when I click.

Here's the logs any way:
```
[2017-07-28 10:20:57,079] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90273 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-07-28 10:20:57,079] [INFO] Startup: C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\komodo.exe built on Wed Jul 19 09:55:57 2017
[2017-07-28 10:21:00,253] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-07-28 10:21:00,266] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/cgcho/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2017-07-28 10:21:00,674] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-07-28 10:21:02,732] [WARNING] keybindings: unknown version number: 54 -- continuing anyway
[2017-07-28 10:21:02,750] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2017-07-28 10:21:05,157] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-07-28 10:21:05,180] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-07-28 10:21:05,448] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-07-28 10:21:06,194] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-07-28 10:21:06,924] [INFO] komodospellchecker: Spell checker loaded.
[2017-07-28 10:21:06,926] [INFO] komodospellchecker: Using dictionary en-US
[2017-07-28 10:21:07,131] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-07-28 10:21:07,292] [INFO] codeintel/process: Starting CodeIntel
[2017-07-28 10:21:07,298] [DEBUG] codeintel/process: PYTHONPATH: C:\Users\cgcho\Komodo IDE 11.0\lib\python\..\lib\python2.7;C:\Users\cgcho\Komodo IDE 11.0\lib\support\dbgp\pythonlib;C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-07-28 10:21:09,019] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Users/cgcho/Komodo%20IDE%2011.0/lib/mozilla/components/koamAddonManager.js:138
[2017-07-28 10:21:11,306] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-07-28 10:21:11,323] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-07-28 10:21:11,358] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-07-28 10:21:11,484] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:11,484] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:11,486] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:11,490] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:11,490] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:11,490] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:12,519] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:12,519] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:12,519] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-28 10:21:13,022] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2017-07-28 10:21:13,469] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Users/cgcho/Komodo%20IDE%2011.0/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Users/cgcho/Komodo%20IDE%2011.0/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-07-28 10:21:14,661] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-07-28 10:21:14,663] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-07-28 10:21:15,390] [DEBUG] codeintel/process: stdout: 
port:60887

pid:17460

[2017-07-28 10:21:15,390] [INFO] codeintel/process: CodeIntel started on port 60887
[2017-07-28 10:21:15,391] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-07-28 10:21:15,844] [DEBUG] koCodeintelLegacy: Deferring _getLanguages
[2017-07-28 10:21:16,581] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-07-28 10:23:44,951] [DEBUG] codeintel/feature/scanner: Starting scan for C:\Users\cgcho\Projects\komodo\KomodoIDE\src
[2017-07-28 10:23:51,565] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-07-28 10:23:51,565] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-07-28 10:23:52,088] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-07-28 10:23:52,088] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-07-28 10:23:52,234] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-07-28 10:23:52,236] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-07-28 10:23:52,697] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-07-28 10:23:52,700] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-07-28 10:23:58,201] [DEBUG] codeintel/feature/scanner: Found 2343 files
[2017-07-28 10:23:58,201] [DEBUG] codeintel/feature/scanner: Prompting to scan C:\Users\cgcho\Projects\komodo\KomodoIDE\src
[2017-07-28 10:24:06,992] [DEBUG] codeintel/feature/scanner: Starting forced scan of C:\Users\cgcho\Projects\komodo\KomodoIDE\src
[2017-07-28 10:24:08,874] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:24:08,875] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:24:08,875] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:24:08,875] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:24:08,877] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:24:08,877] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-07-28 10:26:10,424] [DEBUG] codeintel/feature/scanner: Reached end of scan queue
[2017-07-28 10:33:38,473] [DEBUG] koCodeintelLegacy: Deferring _getLanguages
[2017-07-28 10:34:24,729] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-07-28 10:34:24,730] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-07-28 10:34:24,730] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-07-28 10:34:24,730] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-07-28 10:34:24,730] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-07-28 10:34:24,732] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by Naatan** [comment] 2017-07-28 18:15
Assigning to you since you can repro. You'll need to debug this code:

https://github.com/Komodo/KomodoIDE/blob/master/src/chrome/komodo/content/bindings/views-buffer.p.xml#L1430

**Comment by cgchoffman** [comment] 2017-08-03 20:06
NOTE: `mousedown` fires before  `onMarginClick` so `this._marginClickPending` never gets set to `truthy` and therefore `_onMarginClick` never fires.

**Comment by cgchoffman** [comment] 2017-08-03 22:17
https://github.com/Komodo/KomodoIDE/commit/2eba3aa5ee2da9515f3fe6aa85346f7b1423489b

**Closed** 2017-08-03 22:18 UTC
Labels: Introduced: 11, Type: Bug
