### ISSUE TITLE
code intel not doing anything for HTML files.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3142] opened 2017-09-20 22:18 UTC
### Short Summary

Title

### Steps to Reproduce

- Open the Code intel tab (it's the new DOM viewer)
- Open HTML file with content

### Expected results

- To see DOM stuff

### Actual results

- no DOM stuffs :(

**Comment by Naatan** [comment] 2017-09-20 23:13
@mitchell-as codeintel does seem to be aware of HTML id's and even classes (I think?), could that info not be used to render the DOM tree?

The problem here is that the DOM rendering in the symbol browser is done by the legacy fallback, but for HTML it's not falling back because codeintel is sending it JS and CSS symbols, but not HTML. It'd be hard to fix this with the legacy fallback.

**Comment by cgchoffman** [comment] 2017-09-20 23:37
I thought this used your Regex stuff @Naatan?

**Comment by mitchell-as** [comment] 2017-09-21 14:43
Originally I expected K10 to show the DOM tree in its symbol browser, but it does not. When I looked into the CodeIntel internals, I discovered that HTML ids and classes are captured, so I mirrored that behavior. That info can be used to render a partial DOM tree, but not one with anonymous nodes.

**Comment by Naatan** [comment] 2017-09-21 15:06
> I thought this used your Regex stuff @Naatan?

That's the legacy fallback I'm talking about.

@mitchell-as that's fine, I'm not showing anonymous nodes either. There is no point to showing anonymous nodes, at that point you'd just be repeating the full DOM structure.

**Comment by mitchell-as** [comment] 2017-10-02 17:46
@cgchoffman Would you please be more specific about what you expect to see? A code sample would help.

**Comment by Naatan** [comment] 2017-10-02 17:54
@mitchell-as please work with me directly if you need any feedback on this. What I would like it to show is any html nodes that have an id="" or name="" attribute. Try opening a .xml file and checking the symbol browser as a point of reference.

**Comment by cgchoffman** [comment] 2017-10-02 17:55
Whatever the DOM viewer is supposed to show.  Sample code would be any HTML file.  I don't know what it's supposed to show exactly.  It just shows nothing, which i know isn't correct.

**Comment by mitchell-as** [comment] 2017-10-02 18:30
Okay, I'm not sure what the issue is then. See screenshot below.

![foo](https://user-images.githubusercontent.com/12902397/31092981-2f8662ec-a77e-11e7-904b-66711d6210ff.png)

**Comment by Naatan** [comment] 2017-10-02 18:32
Huh, how come you don't have JavaScript and CSS sections? Are you running a custom build?

**Comment by mitchell-as** [comment] 2017-10-02 19:23
After slack discussion, fixed via https://github.com/Komodo/codeintel/commit/cfbe56c3816db8b39a5801c74a3a39749c4ced14

**Closed by mitchell-as** 2017-10-02 19:23 UTC
Labels: Introduced: 11, Type: Bug
