### ISSUE TITLE
Fix Perl Unit test integration

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#319] opened 2015-06-03 22:12 UTC
https://bugs.activestate.com/show_bug.cgi?id=82890

it would be a good idea to use TAP::Harness and the prove command (which can run all tests in a folder and recurse subfolders)

http://search.cpan.org/~mschwern/Test-Harness-Straps-0.30/lib/Test/Harness/Straps.pm
and
http://search.cpan.org/~mschwern/Test-Harness-Straps-0.30/lib/Test/Harness/Results.pm

As far as i can tell from the documentation they do exactly the parsing you're
asking about and integrating them directly with Komodo would be extremely nice

**Comment by dnadle** [comment] 2015-06-10 20:11
It's too bad this issue has been demoted from the 9.1 milestone to "Backlog." I find integrated perl unit tests completely unusable in the current IDE. It's not just that using TAP::Harness is better (it is); it's that the current IDE fails to parse Test::More output properly. I know you linked to the old report but I wanted to make sure this fact appears here.

**Comment by tapansino91** [comment] 2015-11-12 20:23
Could we get an update on this from someone on the dev team please? 

At this rate, it seems like this issue really isn't going to be resolved, maybe ever. It's clearly not a priority based on the way it's been handled so far (6+ years since it was first identified, and it's currently sitting in backlog with no one assigned? Really?), yet it continues to be advertised on the front page as a prime feature of the product. For me, this was actually one of the deciding features for me to buy Komodo vs the competition, and yet this feature never even worked, so I'm stuck. In a way, it honestly seems like false advertising, even though I'm sure it wasn't intentional, so I think someone either needs to make this a priority and get it fixed, or else admit it's not going to be resolved and take it off the advertised feature list.

All that aside, in the spirit of one dev trying to help out another, I noticed in the original ticket (back in 2009) that the dev said it was harder to implement this feature because he couldn't subclass the test harness package for Perl, so he had to resort to parsing output instead. In fact, with TAP, I believe this is the intention of doing it this way, it's supposed to be simple to parse with minimal fluff in the output stream. The full spec for TAP is documented [right here](https://testanything.org/tap-specification.html), and it's not overly complex to write a parser for the full thing. I would add that Perl's Test::More/Test::Harness implementation of TAP also has support for what they call "sub-tests", which are collections of ok/not ok statements that are nested and indented in the output slightly. Bonus points if that could be supported as well, as I tend to use them a lot, but at this point any progress at all on this issue would be fantastic.

**Comment by Naatan** [comment] 2015-11-12 20:43
We're likely going to be doing some considerable work on unit testing for Komodo 10, which would also cover its Perl integration.

**Comment by tapansino91** [comment] 2015-11-12 20:52
That's good news. Doesn't help me much with my present situation, but I'll take it. 

What's the timeline for Komodo 10 then? Like are we talking months or years? And any chance that any of that goodness will start as a patch to 9? Sorry, trying not to be too pushy, but I'd really like to be able to get my money's worth out of my purchase of 9 before I have to go buy an upgrade to 10, just to get a working implementation of a feature that was supposed to be part of 9...

**Comment by Naatan** [comment] 2015-11-12 20:55
Komodo 10 is definitely months, not years. I cannot say whether some of this would land in Komodo 9.x, as it depends on what the changes consist of. If it is easily cherry pickable from 10 to 9 or vice versa then there is a very good chance that it will be in a 9.x release. Unfortunately I simply cannot say for certain at the moment as I do not know for certain.

**Comment by Naatan** [comment] 2015-11-12 20:57
I'll target this for 9.4 to serve as a reminder, but consider that a loose target.

**Comment by tapansino91** [comment] 2015-11-12 21:07
Ok, hey thanks, I appreciate the open discussion and the willingness to at least put it on the map, even as a loose target.

Also, if you need test cases or any other random stuff related to implementation, feel free to PM me. We do a lot of Perl development at $work, and virtually no one uses IDEs (except me), but a lot of folks are interested in them. Komodo is one of the best ones I've seen that actually supports Perl, and has much more active development than the Eclipse stuff right now, so if we can get this all working, then I can start really recommending it to people I know.

**Comment by Naatan** [comment] 2015-11-12 22:28
You believe unit testing would be a convincing factor for perl devs at your work to start using an IDE?

**Comment by tapansino91** [comment] 2015-11-12 23:17
Yes, I think it's actually possible, believe it or not. When you combine it with the other benefits of syntax checking, code highlighting, auto-formatting (which reminds me, where can I file an enhancement request to get Perl::Tidy added to the list of supported formatters?), and so forth, it becomes a very appealing product, especially since Komodo has Tcl support as well, and we have a lot of Tcl devs that could benefit from this.

Now, I'm not saying that you should expect an order of like a thousand licenses the day after the unit testing feature is fixed :smile:, but fixing this issue would make it so that Komodo almost exactly fits our development needs, and that means I could start to promote it to my coworkers as something worth looking into.

**Comment by Naatan** [comment] 2015-11-12 23:20
> where can I file .. 

Right here :) (on this github repo, not this issue) 

> Now, I'm not saying that you should expect an order of like a thousand licenses the day after the unit testing feature is fixed

Dangit!

> and that means I could start to promote it to my coworkers as something worth looking into

That sounds good to me ;) I was honestly just curious as to what your co-workers were thinking, since obviously the reason someone would use an editor over an IDE is of great interest to me.

**Comment by dnadle** [comment] 2015-11-12 23:31
I purchased Komodo IDE specifically for convenient integrated testing in my perl development and was annoyed to learn that test output parsing didn't work and hadn't worked for years... If I had known at the time I probably would have stuck with Komodo Edit or Eclipse/EPIC. I like Komodo IDE but it won't be a complete perl IDE until this test output parsing bug is fixed.

**Comment by cgchoffman** [comment] 2015-11-13 21:51
> get Perl::Tidy added to the list of supported formatters?
@tapansino91 
Edit > Preferences > Formatters.  You can add one there.

**Comment by mitchell-as** [comment] 2016-03-22 19:29
Fixed via https://github.com/Komodo/KomodoIDE/commit/f73a16f62eacc3279f7bfb08890ea34fa1210945

**Closed by mitchell-as** 2016-03-22 19:29 UTC
Labels: Bug

**Comment by mitchell-as** [comment] 2016-03-22 19:33
I don't know much about Perl and unittesting, but our TAP parsing was quite buggy (duh) and it now works for Test::Simple and Test::More. I believe it will work for any other test frameworks that have TAP-formatted output.

For reference, I followed this tutorial in testing the new code: http://search.cpan.org/dist/Test-Simple/lib/Test/Tutorial.pod

**Comment by tapansino91** [comment] 2016-03-22 23:37
Great to hear, thanks Mitchell!

By the way, the ok/not ok standard for Perl testing is based on Test Anything Protocol, or TAP ([testanything.org](http://testanything.org)). TAP is generic enough that it works for any language, and in fact has testing modules in most of the big players, so if you cross check your implementation against this spec, you might even be supportting _any_ TAP-based testing framework (and could possible advertise as such ;) )

**Comment by Naatan** [comment] 2016-03-23 03:02
That's very interesting @tapansino91, do you any idea of how widely used this is?

**Comment by tapansino91** [comment] 2016-03-23 04:49
Mmm, I'm not sure. I wouldn't exactly say it's _widely_ used. It seems to me that most folks tend to use one of the packages that are more specific to the language their using for doing any testing, but the nice thing about TAP is that it's all text-based, so you can more easily produce test suites for codebases that contain multiple different languages. At least that's the main benefit of it that I've seen, that and the fact that the output is so simple to comprehend/parse.

Ultimately, if you put "Now Supports TAP!" on the Feature list for the next release of Komodo, would you get more sales? Eh, probably not, but since you already have the implementation done, it certainly can't hurt. Just double check it against the actual TAP spec though, because I'm 99% certain Test::Simple is fully TAP compliant, but I would verify it.

**Comment by Naatan** [comment] 2016-03-23 14:26
Thanks for explaining @tapansino91 :) I agree if it's as simple as updating a few menu entries it's a no brainer.

**Comment by dnadle** [comment] 2016-07-31 22:02
This bug is closed, with a posted commit, but the link the the commit 404's and Komodo IDE 10.0.1 still relies on a Makefile and doesn't seem to be able to recurse the t folder. Now that the parsing of TAP::Harness output is apparently fixed, Komodo perl test plans should use that harness to it's full capability by either using or emulating the 'prove' command and eliminating the need for 'make test'. Will you reopen this issue or should I create a new one?

**Comment by Defman21** [comment] 2016-07-31 22:05
@dnadle GitHub throws 404 error for private repositories you don't have access to because of security reasons.

**Comment by mitchell-as** [comment] 2016-08-01 15:16
@dnadle If there's a bug, please open a new issue with steps to reproduce, etc. Thanks!
