### ISSUE TITLE
Places Pane misses a Refresh feature

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1072] opened 2016-02-08 14:20 UTC
Example:
Open Places in "x:dir"
Now using Explorer, in that dir do "Crate New File"
Go Back to Places, and (AFAIK) there is no way to see the new file.

**Comment by mitchell-as** [comment] 2016-02-08 16:03
I am not able to reproduce this. Every time I create a new file, the file is opened in Komodo's editor view and shows in the places pane. Are you working on a remote filesystem?

**Comment by srgloureiro** [comment] 2016-02-08 18:07
No. I am working with a file on root of the d: unit

**Comment by Naatan** [comment] 2016-02-08 18:56
Do you have `Prefs > Editor > Confirmation Dialogs > Detect when files are changed outside the environment` unchecked?

**Comment by srgloureiro** [comment] 2016-02-09 00:22
I have 
Detect when **networked **files are changed outside the environment 
unchecked.

NB  the _networked _word, which I wrote in Bold

**Comment by Naatan** [comment] 2016-02-10 17:28
What type of drive is x: ?

**Comment by srgloureiro** [comment] 2016-02-10 18:28
A partition of the same physical HDD of c:

**Comment by Naatan** [comment] 2016-02-11 16:40
Can you reproduce the issue with a folder using an very basic name on the c: drive? eg. `C:\foo`.

**Comment by cgchoffman** [comment] 2016-08-08 14:50
Closing

**Closed by cgchoffman** 2016-08-08 14:50 UTC
Labels: Closed: Not Reproducible, Pending: Response
