### ISSUE TITLE
Check for update window broken

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1325] opened 2016-04-28 20:33 UTC
### Short Summary

Check for update window is broken and shows all stages of checking for updates.

### Steps to Reproduce

Help > Check for updates

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.0.0-alpha1, build 88973, platform macosx. Built on Tue Apr 26 10:36:47 2016.
*Operating System (and version)?* El Capitan

### Additional Information

![screen shot 2016-04-28 at 8 19 24 am](https://cloud.githubusercontent.com/assets/517124/14900513/dd938024-0d5e-11e6-83dc-0aef7f295d83.png)

**Comment by Naatan** [comment] 2016-04-28 20:34
Dupe of https://github.com/Komodo/KomodoEdit/issues/1321

But thank you! :)

**Closed by Naatan** 2016-04-28 20:34 UTC
