### ISSUE TITLE
'View in Browser - in a Komodo Tab' lets disappear left Toolbar

### ISSUE THREAD

**Issue by TuxNix** [Komodo/KomodoEdit#1752] opened 2016-06-27 14:54 UTC
### Short Summary
'View in Browser - in a Komodo Tab' lets disappear left Toolbar.
'View in Browser with /urs/bin/firefox works correct.

### Steps to Reproduce
Just click on the browser icon.
Or click on 'View in Browser - in a Komodo Tab'

### Expected results
Left Toolbar should not disappear.

### Actual results
'View in Browser - in a Komodo Tab' lets disappear left Toolbar

### Platform Information
Komodo Edit, version 10.0.1, build 17276, platform linux-x86_64. Built on Wed Jun 15 08:25:28 2016.
archlinux 4.6.2-1, plasma 5.6.5-1, plasma-framework 5.23.0-1

### Additional Information
no

**Comment by Naatan** [comment] 2016-06-27 16:20
By "left toolbar" do you mean the second to the left of "Go to Anything"?

**Comment by cgchoffman** [comment] 2016-06-27 17:12
Screenshot would be helpful here.

**Comment by TuxNix** [comment] 2016-06-27 19:38
In menu 'view' submenu 'toolbars' you can customize (left and right) toolbar and activate it with 'show toolbar'
When you click on the 'Item view in Browser'
![view_in_browser](https://cloud.githubusercontent.com/assets/11775206/16392578/f44b5760-3cac-11e6-894c-5cdcd17a01a5.png)
Browser View will be shown, but the left side of the Toolbar disappears.
![lelt_toolbar_is_gone](https://cloud.githubusercontent.com/assets/11775206/16392707/881c940e-3cad-11e6-95a2-a83190fc8f3d.png)

**Comment by Naatan** [comment] 2016-06-27 19:42
Did you mean to close this?

**Comment by TuxNix** [comment] 2016-06-27 19:44
Of core not.
It is a bug!

**Comment by Naatan** [comment] 2016-06-27 19:47
Reproduced on Edit.

**Comment by Naatan** [comment] 2016-08-11 19:45
This isn't a bug, it's because the focus shifts to the preview tab, which has no preview ability of itself of course,

This UX issue will be resolved in Komodo 11 where we will significantly improve the preview mechanic.

**Closed by Naatan** 2016-08-11 19:45 UTC
Labels: Bug, Limited to: Edit, Severity: Priority
