### ISSUE TITLE
python debug listener stops after very first failure

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#139] opened 2015-04-08 08:46 UTC
To repro:
- restart KO9
- set a breakpoint (I do it with ```from dbgp.client import brk; brk('127.0.0.1')```)
- start the script, hit the breakpoint
- hit ```stop debugging```
- the exception below comes after a while
- the listener dies
- if I re-enable the listener, it does not fail anymore  on ```stop debugging```

```
[2015-04-08 10:11:23,147] [ERROR] dbgp.server: -1 (session timed out while waiting for response)
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/dbgp/server.py", line 1850, in _stdinHandlerThread
    self.currentSession.setStdinHandler(None)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/dbgp/server.py", line 1765, in setStdinHandler
    node = self.sendCommandWait(cmd)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/dbgp/server.py", line 1104, in sendCommandWait
    node = self._waitResponse(tid)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/dbgp/server.py", line 1135, in _waitResponse
    raise DBGPError('session timed out while waiting for response')
koDBGPError: -1 (session timed out while waiting for response)
```

**Comment by Naatan** [comment] 2015-04-08 15:59
I cannot reproduce this. Can you provide a snippet on which you can reproduce this issue?

Are you able to reproduce this issue reliably? Is there a workaround?

**Comment by toddw-as** [comment] 2015-04-09 05:12
Duplicate of issue #102. Should be fixed in a nightly soon.

**Closed by toddw-as** 2015-04-09 05:12 UTC
Labels: Pending Response
