### ISSUE TITLE
Komodo doesn't list all variables in autocomplete window (js)

### ISSUE THREAD

**Issue by shelldweller** [Komodo/KomodoEdit#502] opened 2015-08-07 17:41 UTC
Komodo's autocomplete seems very quirky. Often it just stops working at all. Sometimes it shows incomplete variable list, even after restart.

Here's an example. It lists only ```stack_length``` but not ```stack``` or ```stack_position```:
![image](https://cloud.githubusercontent.com/assets/451485/9141787/29e2fa9e-3d09-11e5-90b9-d2746eda2006.png)

Build info: Komodo IDE, version 9.2.0, build 87616, platform macosx. Built on Tue Aug 4 11:29:06 2015. Had the same issue in previous build.

**Comment by Naatan** [comment] 2015-08-08 00:02
Thanks for reporting. Could you provide that snippet in a textual format?

**Comment by shelldweller** [comment] 2015-08-08 00:19
Here you go. I trimmed down the code and now ```stack``` appears.

```javascript
define(function(){

    function History(element){
        var self = this;
        var stack = [];
        var stack_position = -1;
        var stack_length = 0;
        
        this.push = function() {
            // here I only see stack and stack_length
            
        }
        // here I see all stack* vars
    }
    
    return History;

});
```

Also a new screenshot:
![image](https://cloud.githubusercontent.com/assets/451485/9148142/f2cdebb2-3d40-11e5-8350-08b98b806335.png)

In general closure variables from outer scope tend not to appear in autocomplete. But it was strange to see appear all but one.

**Comment by mitchell-as** [comment] 2015-10-12 19:54
Implementing closures in codeintel looks to be quite difficult, so I'm moving this to the backlog. For what it's worth, I cannot reproduce your most recent screenshot. My autocompletion list only contains the last 3 items.

**Comment by shelldweller** [comment] 2015-10-13 14:03
I don't know if full closure support is really required. Atom's approach to autocomletion seems to be good enough.

**Comment by mitchell-as** [comment] 2015-10-13 14:08
Codeintel's implementation is different than Atom's. Codeintel would need to implement closures in order to get the autocompletions you expect.

**Comment by Naatan** [comment] 2015-10-13 16:07
That is to say, codeintel actually provides intelligent autocompletion. Whereas sublime/atom just dump identifiers that may or may not be relevant.

**Comment by shelldweller** [comment] 2015-10-13 16:47
Exactly. But seeing extra identifiers appears less confusing to me than not seeing valid ones. Plus if I keep using Komodo long enough codeintel stops working at all. As a user of commercial IDE I would expect this feature to be a little bit more robust.

**Comment by mitchell-as** [comment] 2015-10-13 17:17
When it stops working, please log a ticket with your Komodo profile's `codeintel.log` file. That will help us make codeintel even more robust.

**Closed** 2015-12-11 20:39 UTC
Labels: Bug
