### ISSUE TITLE
PHP traits no Symbol List/Browser

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#3200] opened 2017-09-30 05:35 UTC
### Short Summary

There is no symbol list or browsing for PHP traits.

### Steps to Reproduce

Open a trait. Try to open the Symbol List or Symbol Browser.

### Expected results

To have a symbol list for quick search/navigation.

### Actual results

No symbol list and no symbol browsing. Message in symbol browser: "Could not load due to an error, if the issue persists please file a bug"

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.0, build 90668
*Operating System (and version)?* Ubuntu 17.04

## Additional Information

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1346150/pystderr.log)

**Comment by mitchell-as** [comment] 2017-10-02 14:25
Would you please attach a "trait". I don't know enough PHP to understand what the issue is and identify it. Thanks.

**Comment by Naatan** [comment] 2017-10-02 14:59
There's a sample on the docs:

http://php.net/manual/en/language.oop5.traits.php

Sounds like an abstract class, basically.

**Comment by lagbox** [comment] 2017-10-02 14:59
Sorry about that my friend.

```php
<?php

trait TestIt
{
    protected $blah;
    
    public function testIt()
    {
        
    }
}
```

If you change the word 'trait' to 'class' you will have a symbol list show up in the symbol browser.

**Comment by mitchell-as** [comment] 2017-10-02 15:07
Okay, thanks.

**Comment by mitchell-as** [comment] 2017-10-02 15:56
Fixed via https://github.com/Komodo/codeintel/commit/a87809892d584aae308d58e87cf7903fca2726ce

**Closed by mitchell-as** 2017-10-02 15:56 UTC
Labels: Introduced: 11, Type: Bug
