### ISSUE TITLE
Multiline Indentation problem in komodo edit 10.1.2

### ISSUE THREAD

**Issue by felixkk** [Komodo/KomodoEdit#2199] opened 2016-11-30 14:29 UTC
### Short Summary
Increasing/Decreasing indentation problem with multiple line since last komodo update

### Steps to Reproduce
- Select at least 2 lines
- Increase (tab) or decrease (shift + tab) indentation

### Expected results
- The selected lines should be more or less indented
- The resulting line selection should be the same as before

### Actual results
- The selected lines are more or less indented, as expected
BUT
each time increasing/decreasing indentation, the line below the selection will be selected.

Ex : If i do 4 indentations (tabs) on 2 lines, I got 6 lines selected in the end, and they are indented too.

### Platform Information
- Komodo Edit, version 10.1.2, build 17449, platform macosx. Built on Thu Nov 17 
- macOS Sierra Version 10.12.1 (16B2555)

**Comment by mitchell-as** [comment] 2016-11-30 16:21
Hi, this is a duplicate of #2180 . Please go to that issue to download a new nightly build of Komodo that fixes the problem. Thank you.

**Closed by mitchell-as** 2016-11-30 16:21 UTC

**Comment by felixkk** [comment] 2016-11-30 16:33
Oh, Thanks !

**Comment by pmne324** [comment] 2020-01-04 07:57
Thank you very much
