### ISSUE TITLE
Symbols not read in some files (Perl)

### ISSUE THREAD

**Issue by tomascohen** [Komodo/KomodoEdit#3231] opened 2017-10-04 12:19 UTC
### Short Summary

In some files on a Perl project, symbols are not read. For example [this one](http://git.koha-community.org/gitweb/?p=koha.git;a=blob;f=C4/Search.pm;h=9278f262e2e0bb2ad966b4cd26f638eb81e53f5c;hb=HEAD)

### Steps to Reproduce
* Download the linked file
* Open it in Komodo IDE 11
=> FAIL: Error message displayed "Could not load due to an error. If the issue persists please file a bug"

### Expected results

It should load the symbols from the file.

### Actual results

If fails to load the symbols.

### Platform Information

* Komodo IDE
* Version 11 
* Ubuntu 16.04 (amd64) and macOS Sierra 10.12.6

### Additional Information
Error logs when clicking "Try again" on the symbols side bar:

[2017-10-04 09:16:38,349] [ERROR] console-logger: TypeError: this._handleClick is not a function (2) in chrome://global/content/bindings/button.xml:145
Traceback (most recent call last):
  File "chrome://global/content/bindings/button.xml", line 145, in 

[2017-10-04 09:16:38,559] [ERROR] codeintel/service/mediator: Request failed with message: Failed calling API method: getSymbolsInBuffer, message:  (-32603)
[2017-10-04 09:16:38,592] [ERROR] codeintel/feature/symbolbrowser: Failed calling API method: getSymbolsInBuffer, message: 
Traceback from ERROR in 'codeintel/feature/symbolbrowser' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:386:27
    _update</<@chrome://codeintel/content/sdk/feature/symbolbrowser.js:517:13

**Comment by mitchell-as** [comment] 2017-10-04 14:16
Duplicate of #3185.

**Closed by mitchell-as** 2017-10-04 14:16 UTC
