### ISSUE TITLE
Mac OSX - Moving window to secondary monitor does not show application menu

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#1292] opened 2016-04-22 22:22 UTC
### Short Summary
Minor UX issue. When I move the Komodo window to the second monitor (or from the second monitor back to the first) the application menu doesn't appear. If you click on another app on that window and then back to Komodo it resets and displays. 

### Steps to Reproduce
Move Komodo to second monitor. (see image - still shows Chrome menu even though Komodo is active)
![screen shot 2016-04-22 at 3 13 52 pm](https://cloud.githubusercontent.com/assets/16480148/14756389/bf8f8c14-089d-11e6-88f7-5d07487d0cad.png)

### Expected results
Komodo menu should appear.

### Actual results
It remains on the menu for the last application accesses on that monitor.

### Platform Information
Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx. Built on Fri Apr 15 01:43:18 2016

**Comment by Naatan** [comment] 2016-04-22 22:42
Does selecting a different app and then clicking Komodo in the OSX Dock fix it?

**Comment by zoofood** [comment] 2016-04-22 23:44
Yes that works. It's a totally minor issue, but should be fixed up eventually.

**Comment by Naatan** [comment] 2016-04-22 23:54
Yep totally.

**Comment by cgchoffman** [comment] 2016-04-29 20:02
This looks like a dupe of #617

**Comment by Naatan** [comment] 2016-04-29 21:38
Yep, thanks carey.

**Closed by Naatan** 2016-04-29 21:38 UTC
Labels: Bug, OSX Only

**Comment by tonyattwood** [comment] 2016-07-19 11:07
Hello,


I was just  wondering about your opinion  on that stuff, please take a look and tell me what you  think <http://effort.soldoutshowz.com/e4bcemkl>


Warmly, tony.attwood@ntlworld.com
