### ISSUE TITLE
Update xdebug bits to include PHP7

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1992] opened 2016-09-02 16:46 UTC
### Short Summary

Just a reminder to get this in the next release.

For anyone in the public who comes across this, you can use [xdebug's bits](https://xdebug.org/download.php) to debug your code the same way you use our distribution of Xdebug.  

We enable code profiling so you'll need our bits if that's what your looking for, or compile the bits yourself.

**Comment by Defman21** [comment] 2016-12-07 15:51
Dupe of #1707?

**Comment by Naatan** [comment] 2016-12-07 16:01
Perhaps in the meantime we can just update http://code.activestate.com/komodo/remotedebugging/

**Comment by Naatan** [comment] 2016-12-07 16:02
Oh and @Defman21 is right :D

**Closed by Naatan** 2016-12-07 16:02 UTC
Labels: Enhancement: Feature
