### ISSUE TITLE
Komodo shows errors/warnings notifications more than one time

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#682] opened 2015-10-07 16:41 UTC
f you're using Pylint and PEP8, once you make a mistake in the code formatting or something different that causes a warning in Pylint or PEP8, those notifications start spamming until I close them 3 times (after that I get "Repeat notifications truncated bla-bla-bla")

**Comment by Naatan** [comment] 2015-10-07 16:42
Would you be able to record this for me? I don't have an environment set up to attempt to reproduce.

**Comment by Defman21** [comment] 2015-10-07 16:43
Yes :) Give me 2-3 minutes

**Comment by Defman21** [comment] 2015-10-07 16:49
https://youtu.be/xXuJDidajV4

**Comment by Naatan** [comment] 2015-10-07 17:44
Hmm I see, it's just 3 notifications that show one after the other, when you close one the next one shows immediately. I'm not sure if showing syntax checking results in notifications is worth it yet.

Note could you please use the default skin with the nightly? As we do not test it against custom skins (eg. tabula rasa). For example the notifications don't look the way they are supposed to for syntax checking.

**Comment by Naatan** [comment] 2015-10-07 17:44
Closing this as this is technically by design, but rest assured I'll address the underlying UX issue before final release.

**Closed by Naatan** 2015-10-07 17:44 UTC
Labels: Pending Response

**Comment by Defman21** [comment] 2015-10-07 17:47
>For example the notifications don't look the way they are supposed to for syntax checking.

How they should looks then? I've switched to the default skin and I don't see any difference :|

**Comment by tonyattwood** [comment] 2016-07-19 11:08
Hello,
I thought you might  like  the stuff I found  by chance,  it seems so exciting and unusual, please take  a look here <http://favourite.spicandspotless.com/e4mxseee>
tony.attwood@ntlworld.com
