### ISSUE TITLE
cmd_dedent extends selection

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2207] opened 2016-12-05 12:27 UTC
cmd_dedent extends selection down

### Steps to Reproduce
select some code, dedent it

### Expected results
selection should extend on the first dedent to first line start last line end, but should NOT add more and more lines

### Actual results

see:
https://youtu.be/Te-TONz7HMM

### Platform Information

Komodo IDE, version 10.1.2, build 89508, platform linux-x86_64.
Built on Wed Nov 16 16:50:02 2016.

**Comment by mitchell-as** [comment] 2016-12-05 15:05
Duplicate of #2180. See that ticket for fix instructions.

**Closed by mitchell-as** 2016-12-05 15:05 UTC
