### ISSUE TITLE
PHP Remote debugging:  many reports of Komodo crashing while debugging

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1233] opened 2016-04-11 21:15 UTC
### Short Summary

There have been multiple reports over the passed few months of PHP remote debugging crashing Komodo.  The reports are relatively consistent and warrant further investigation. I personally have not been able to reproduce the issue though.

OTRS: http://otrs3.activestate.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=48510

**Comment by mitchell-as** [comment] 2016-04-11 21:19
Possible a duplicate of https://github.com/Komodo/KomodoEdit/issues/1007

**Comment by tonyattwood** [comment] 2016-07-19 11:19
Hello,

I've came across that  information  yesterday and  thought it would  help you, read more here please <http://excellent.baseil.com/e4stwe>

Hope this helps, tony.attwood@ntlworld.com

**Comment by Naatan** [comment] 2018-05-03 18:09
Closing this as it is old and not actionable. Not to mention #1007 might have resolved this?

**Closed by Naatan** 2018-05-03 18:09 UTC
Labels: Type: Bug
