### ISSUE TITLE
Komodo Edit 9 hangs when switch back due to remote files

### ISSUE THREAD

**Issue by Richzendy** [Komodo/KomodoEdit#70] opened 2015-03-26 15:48 UTC
I'm using Fedora21, when i minimize and maximize the window or when i go to other window and back, Komodo Edit 9 hangs and give me a response in a 3 or 5 seconds, with komodo edit 8 and the same files the response it's quickly, i'm using files on sftp.

That is a video showing the behavior:
https://dl.dropboxusercontent.com/u/16073962/out-1.ogv

This is my hardware: http://pcpartpicker.com/p/qB6w6h

Mod edit:

Workaround and cause: https://github.com/Komodo/KomodoEdit/issues/70#issuecomment-87009746

**Comment by cgchoffman** [comment] 2015-03-26 17:30
Hi Richzendy, couple questions:
- Do you have files mounted as an external drive or are you using Komodo's internal Server Prefs?
- Have you tried disabling
 - Prefs > Syntax checking
 - Prefs > Editor > (both) Detect when [networked] files are changed...
 - Prefs > Code Intel

Just want to narrow down the possible culprits.

**Comment by Naatan** [comment] 2015-03-26 18:06
Could you try disabling hardware acceleration?

1. Open a file
2. Preview the file "in a browser" but set it to open in a Komodo tab
3. Replace the file address with about:config to get into the settings
4. Look for `layers.acceleration.disabled` and set it to `true`
5. Restart Komodo

If that doesnt work - please answer @cgchoffman's questions.

**Comment by Richzendy** [comment] 2015-03-26 18:43
* Do you have files mounted as an external drive or are you using Komodo's internal Server Prefs? 
- I have a NAS disc mounted, but any file opened on Komodo from this disc

* Have you tried disabling

    Prefs > Syntax checking
    Prefs > Editor > (both) Detect when [networked] files are changed...
    Prefs > Code Intel

- I tried, but without any change, i've restarted komodo on each change

*  Could you try disabling hardware acceleration?

Yes, i tried too, but without lucky


On Help / Troubleshooting i have: View log file and Memory usage, do you need any? are usefull to this case?

**Comment by Naatan** [comment] 2015-03-26 19:36
The log file could be usefull (after you reproduced the issue).

Could you try disconnecting the NAS mount just to see if it has any effect?

**Comment by Richzendy** [comment] 2015-03-26 19:55
I've umounted my NAS, without any effect on Komodo Edit.

The memory report: https://dl.dropboxusercontent.com/u/16073962/memory-report.json.gz

The log: https://dl.dropboxusercontent.com/u/16073962/pystderr.log

**Comment by Naatan** [comment] 2015-03-26 19:59
The repeated applyScheme warnings are odd, but probably unrelated. Just to eliminate that though; are you using collab? And do those timestamps correspond to you maximizing the window?

Would you be able to download Komodo IDE (trial) and see if you can reproduce the issue there?

**Comment by Richzendy** [comment] 2015-03-26 23:09
* Would you be able to download Komodo IDE (trial) and see if you can reproduce the issue there?

Yes, i will, and i'll share my experience here.

* I'm not using collab, i use komodo  just to write PHP, CSS, HTML and Javascript

* And do those timestamps correspond to you maximizing the window? 

I don't know, i think so...

**Comment by Richzendy** [comment] 2015-03-27 16:38
I've made some test:

With one sftp file, komodo-9 works fine and fluid
With two sftp files, works fine but a little slow compared with one file (almost imperceptible)
With three sftp files, but a little slow compared with two files (a little perceptible)

Wich each new sftp file, komodo 9 is more slow and hangs with many

With many local files works great.

I think can be something related with the sftp cache

**Comment by Naatan** [comment] 2015-03-27 17:01
I think this forum post is related: http://forum.komodoide.com/t/komodo-9-hanging/1343/7

Could you try Todd's suggestion posted there? Ie. 

> Open Komodo preferences and select the Editor category, then uncheck the Detect when network files are changed outside the environment.

**Comment by VeNoMouS** [comment] 2015-05-14 03:08
Cheers for the find @Naatan , one thing you missed was to enable "Show Advanced" in the bottom left, which I saw in your forum thread.

How ever disabling "Detect when network files are changed outside the environment."  didn't do anything for me

I'm running ```Komodo Edit, version 9.0.1, build 15745, platform linux-x86_64```

**Comment by Naatan** [comment] 2015-05-14 14:49
Hey @VeNoMouS, can you please open a new bug report? Since this one is very specific and other bugs can have similar symptoms, if it ends up being the same issue we can always mark it as duplicate.

**Comment by VeNoMouS** [comment] 2015-05-14 23:59
Fail how to see how its "different" as I'm experiencing the exact same issue, cant type for 5+ seconds after coming back to komodo edit 9 from another application on remote files...  does not do it in version 8... but.. what ever i'll create another bug issue...

**Comment by Naatan** [comment] 2015-05-15 01:17
It's not because the symptoms are the same that the cause is also the same. You said yourself that the workaround provided here does not work so that implies that you are experiencing a different (but similar) issue.

**Comment by cgchoffman** [comment] 2015-07-15 22:04
More remote file functionality needs to be made async to get this working in a more friendly manner.

**Comment by lahdekorpi** [comment] 2015-07-16 15:26
I'm having the same issue with "Detect when networked files are changed outside the environment" disabled.
It is impossible to work using Komodo with a slow connection as it takes tens of seconds to recover after getting focus.
Local files work just fine, as does version 8.
Making remote file functionality async is a different bug, it seems that version 9 is totally ignoring the configuration option for not checking remote file changes.

**Comment by lahdekorpi** [comment] 2015-07-16 15:28
Update: disabling "Detect when files are changed outside the environment" solved the issue.
Switching "Detect when networked files are changed outside the environment" on / off has no effect to anything, it still checks the server even if this is disabled.

**Comment by cgchoffman** [comment] 2015-07-16 17:57
@lahdekorpi, that is likely because you have your remote folder mounted locally and therefore Komodo treats it like a local file.  "networked" files means you've open the remote folder/file through File > Open > Remote.  Thanks for updating though.  That will be helpful info for other users.

**Comment by lahdekorpi** [comment] 2015-07-17 07:25
@cgchoffman Nope, I'm using the built-in places sidebar connected with the "Open Remote Directory".

This is the main reason for me to be using Komodo as I've got something like 50 different servers and I can easily copy settings from one installation to another.

**Comment by cgchoffman** [comment] 2015-07-17 15:59
@lahdekorpi thank you for updating.

**Comment by Ruddiger** [comment] 2015-08-17 14:39
Seeing the same as @lahdekorpi.  When I disable only "Detect when networked files are changed outside the environment" it has no effect, even after an app restart on Network Files (SFTP using Open Remote Directory).  When I disable both options, it stops lagging.  It seems the "Detect when networked files are changed outside the environment" does not function as intended.

**Comment by Naatan** [comment] 2015-09-08 15:28
Targeting this for 9.3, just to move the file check to a separate thread. Moving the rest of the remote file stuff to async will be a separate task.

**Comment by 7evenmikser** [comment] 2015-11-17 21:20
Have same problem on 8.5. Installed 9.3 - no changes, same freezes. Also where's option "Detect when files are changed outside the environment" on 9.3? Gone?

**Comment by 7evenmikser** [comment] 2015-11-17 21:22
My bad. Found in in the "all settings". It doesn't care if i turn in on or off, all the same...

**Comment by cgchoffman** [comment] 2015-11-17 23:17
> My bad. Found in in the "all settings". Anyway it doesn't care if i turn in on or off, all the same...

Are you saying this has no effect?  It sounds like you're reporting a different issue then.

**Comment by 7evenmikser** [comment] 2015-11-18 00:43
>Are you saying this has no effect? It sounds like you're reporting a different issue then.
Yes, this has no effect.

I have the same issue as Richzendy and VeNoMouS. Here it is my log file:
'[2015-11-18 02:38:50,262] [INFO] Startup: Welcome to Komodo Edit 9.3.0 build 16396 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-11-18 02:38:50,263] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\komodo.exe built on Fri Oct 30 20:10:45 2015
[2015-11-18 02:38:51,042] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-18 02:38:51,471] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-11-18 02:38:52,492] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/components/koamAddonManager.js:138
[2015-11-18 02:38:52,556] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2015-11-18 02:38:56,086] [ERROR] koScintillaSchemeService: Scheme Tomorrow_Dark is not writeable
[2015-11-18 02:38:56,109] [WARNING] koScintillaSchemeService: Upgraded scheme u'Tomorrow_Dark' from version 14 to 15.
[2015-11-18 02:38:56,826] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-18 02:38:56,828] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-18 02:38:56,828] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-18 02:38:56,831] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-18 02:38:56,831] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-18 02:38:56,831] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-18 02:38:56,831] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-18 02:38:56,832] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-18 02:38:59,397] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-18 02:38:59,398] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-18 02:38:59,400] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-18 02:38:59,891] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
[2015-11-18 02:39:00,756] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-18 02:39:00,910] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-18 02:39:00,910] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-18 02:39:09,461] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-18 02:39:09,461] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-18 02:39:09,463] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-18 02:39:09,463] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-18 02:39:09,463] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-18 02:39:09,463] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-18 02:39:09,463] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-18 02:39:09,464] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-18 02:39:10,463] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-18 02:39:10,466] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-18 02:39:30,641] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-18 02:39:30,642] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-18 02:39:30,642] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-18 02:39:30,642] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-18 02:39:30,642] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-18 02:39:30,644] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-18 02:39:30,644] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-18 02:39:30,644] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-18 02:39:38,220] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-18 02:39:38,223] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
'
>[2015-11-18 02:38:59,398]
it's when comodo starts

>[2015-11-18 02:39:38,223]
when i'm saving any file located on the ftp

**Comment by Naatan** [comment] 2015-11-18 16:13
This issue is strictly about switching back to Komodo, not about saving remote files.

**Comment by Gianca76** [comment] 2015-11-27 08:41
I've the same problem, I've already tried all the solutions you suggested without any improvement. :(

**Comment by Naatan** [comment] 2015-11-27 17:12
If it is the same issue then the workaround should work. If it does not work please report a new issue and provide all the details you can.

**Comment by tonyattwood** [comment] 2016-07-19 11:07
Hi,

Look at that  stuff,  I  like it so much,  I guess you're gonna like it  too.  Look at  it <http://favor.elrevelador.com/e4nrkf>

Yours sincerely, tony.attwood@ntlworld.com

**Comment by Naatan** [comment] 2016-08-23 15:06
Closing this in favor of https://github.com/Komodo/KomodoEdit/issues/1959

**Closed by Naatan** 2016-08-23 15:06 UTC
Labels: Enhancement

**Comment by cgchoffman** [comment] 2017-08-29 19:24
FYI, this issue has been full resolved now in Komodo 11 https://github.com/Komodo/KomodoEdit/commit/03650e4c018e8c34004e1508c51808db4eda839d
