### ISSUE TITLE
Weird handling of "caret positioning" in 10.x

### ISSUE THREAD

**Issue by joho1968** [Komodo/KomodoEdit#2392] opened 2017-03-10 11:21 UTC
### Short Summary

The editor performs unexpected horizontal shifts in viewport

### Steps to Reproduce

Have a few lines of text/code that will not fit in the current viewport. Go to the end of one of those lines so that the editor has to shift the viewport. Go back a few characters with the left arrow key and start typing.

### Expected results

If I scroll the viewport, in any direction, I want it to remain there if there is no reason to move it. And the above is certainly not a reason to move it.

### Actual results

I don't have wordwrap enabled, and quite frequently scroll horizontally "beyond" the visual end of the line. This forces the editor to scroll the viewport to the right (well, left actually) to be able to display the end of the line. So far soo good. If I then jump back a few characters and start typing, all of a sudden the viewport is justified with the caret/cursor. So I cannot see what is to the right of the insertion point.

### Platform Information

IDE
10.2.0 (89833)
Ubuntu 14.04.LTS

### Additional Information

Keep up the great work :)

**Comment by mitchell-as** [comment] 2017-03-10 14:58
Duplicate of #2389 which should be fixed in the latest nightly build and will land in 10.2.1.

**Closed by mitchell-as** 2017-03-10 14:58 UTC
Labels: Enhancement, Enhancement: UX

**Comment by joho1968** [comment] 2017-03-10 15:05
My bad, I really did try to look for a duplicate as I was thinking I couldn't have been the only one. Looking forward to 10.2.1 then. Thanks.

**Comment by mitchell-as** [comment] 2017-03-10 15:07
It's not your fault @joho1968. These kinds of things can be hard to search for.
