### ISSUE TITLE
Tcl linter complains about unused variable

### ISSUE THREAD

**Issue by zoofood** [Komodo/KomodoEdit#2485] opened 2017-04-16 05:56 UTC
### Short Summary

Syntax error on Tcl in 10.2 as reported on comp.lang.tcl.

### Steps to Reproduce
```
set a(1) 2 
proc a {} { 
    variable a 
    puts $a(1) 
} 
```
### Expected results

Should not be listed as error.

### Actual results

Shows: use of undefined variable "a(1)" in line 4 

### Platform Information

Komodo IDE 10.2

*Operating System (and version)?*  Unknown.

### Additional Information

Any source file with a non-ASCII character will cause a failure of the 
syntax checker. 

Thank you, 
Harald

**Comment by Naatan** [comment] 2017-04-17 15:29
> Any source file with a non-ASCII character will cause a failure of the
syntax checker.

This sounds like a different issue altogether, please report them separately.

**Comment by mitchell-as** [comment] 2017-04-17 18:31
Duplicate of #1661.

**Closed by mitchell-as** 2017-04-17 18:31 UTC
Labels: Component: TDK
