### ISSUE TITLE
HTML Continually Autocompletes </script>

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3712] opened 2019-03-06 05:02 UTC
### Short Summary
HTML with script and CDATA results in autocomplete of `</script>`.

### Steps to Reproduce
Use this file and look at the autocomplete at the end.
```html
<html>
<body>
<script>
//<![CDATA[
//]]>
</script>
</
```

### Expected results
`</body>` is autocompleted.

### Actual results
`</script>` is autocompleted.

### Platform Information
Komodo Edit 11.1.1
MacOS Mojave 10.14.2

### Additional Information
I traced this back to `koXMLTreeService.py (locateNode)`.  `node.end` is null on the script tag.  I traced that back to `HTMLTreeParser.Parser(HTMLTreeParser.HTMLTreeBuilder())`.

**Comment by ssigwart** [comment] 2019-03-07 05:00
This may be related to https://github.com/Komodo/KomodoEdit/commit/ef82719e55abb98e3b0a99c6a185de901ed6493b.

It seems like `text_chunks_from_lang` stops a chunk midway through a `<script>`, then starts a new chunk after the ending `</script>`.

**Comment by cgchoffman** [comment] 2019-03-12 04:22
I can't reproduce this one.  I'm consistently getting `body>` suggested after the closing `</script>` tag.

**Comment by ssigwart** [comment] 2019-03-12 12:51
Are you indenting?  It seems like not indenting has the issue, but this does not:
```html
<html>
<body>
	<script>
	//<![CDATA[
	//]]>
	</script>
</
```

**Comment by cgchoffman** [comment] 2019-03-18 03:23
@ssigwart, busy week!  Yes, I was indented.  Good catch.  Looking at your PR.

**Closed** 2019-03-18 03:35 UTC
