### ISSUE TITLE
Komodo IDE 10.0.1 Repeated notifications of errors in codeintel2/citadel.py

### ISSUE THREAD

**Issue by davefultz** [Komodo/KomodoEdit#1874] opened 2016-07-29 22:59 UTC
### Short Summary
Komodo IDE 10.0.1
The notifications list is filled with two errors, irrespective of whether a source file is open.
See the error logs, below.
### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 10.0.1, build 89237, platform macosx

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
[2016-07-29 17:34:00,809] [ERROR] koCodeIntel: convert
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/database/database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/database/langlib.py", line 1137, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'convert'

[2016-07-29 17:34:00,821] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 626, in handleRequest
    meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 889, in do_get_sections
    sections = buf.get_sections()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mitchell-as** [comment] 2016-08-01 14:16
Hi, what were the circumstances surrounding this bug? Can you reproduce it? Without steps I cannot find out what went wrong.

**Comment by davefultz** [comment] 2016-08-01 14:40
If you start Komodo with no source files open, there are no notifications. If I open this one file (the launch point for a very large package) you get a set of notifications:

`#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from process import process,parser

(options, args) = parser.parse_args()
process(options)
`

Notifications:

`AttributeError: 'NoneType' object has no attribute 'get'
                                         Mon Aug 01 2016 09:29:44 GMT-0500 (CDT)
--------------------------------------------------------------------------------
KeyError: u'convert'
                                         Mon Aug 01 2016 09:29:43 GMT-0500 (CDT)
--------------------------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'get'
                                         Mon Aug 01 2016 09:29:43 GMT-0500 (CDT)
--------------------------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'get'
                                         Mon Aug 01 2016 09:29:43 GMT-0500 (CDT)
--------------------------------------------------------------------------------
Repeat notifications truncated, please check your Notifications panel
                                         Mon Aug 01 2016 09:29:43 GMT-0500 (CDT)
--------------------------------------------------------------------------------
TypeError: 'NoneType' object has no attribute '__getitem__'
                                         Mon Aug 01 2016 09:29:43 GMT-0500 (CDT)
--------------------------------------------------------------------------------
KeyError: u'convert'
                                         Mon Aug 01 2016 09:29:44 GMT-0500 (CDT)
--------------------------------------------------------------------------------
KeyError: u'convert'
                                         Mon Aug 01 2016 09:29:44 GMT-0500 (CDT)
--------------------------------------------------------------------------------
AttributeError: 'NoneType' object has no attribute 'get'
                                         Mon Aug 01 2016 09:29:44 GMT-0500 (CDT)`


If you click once on a source code line you get:

`AttributeError: 'NoneType' object has no attribute 'get'
                                         Mon Aug 01 2016 09:31:07 GMT-0500 (CDT)
--------------------------------------------------------------------------------
TypeError: 'NoneType' object has no attribute '__getitem__'
                                         Mon Aug 01 2016 09:31:07 GMT-0500 (CDT)`

with these entries in the log:

`[2016-08-01 09:31:07,477] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 626, in handleRequest
    meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 889, in do_get_sections
    sections = buf.get_sections()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'
[2016-08-01 09:31:07,491] [ERROR] koCodeIntel: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 626, in handleRequest
    meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 889, in do_get_sections
    sections = buf.get_sections()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'

[2016-08-01 09:31:07,787] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 626, in handleRequest
    meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 911, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 916, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 320, in scoperef_from_pos
    blob = self.blob_from_lang[self.lang]
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-01 09:31:07,796] [ERROR] koCodeIntel: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 626, in handleRequest
    meth(request, driver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 911, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/oop/driver.py", line 916, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 320, in scoperef_from_pos
    blob = self.blob_from_lang[self.lang]
TypeError: 'NoneType' object has no attribute '__getitem__'

[2016-08-01 09:32:47,645] [ERROR] codeintel.tree: Unexpected error with evaluator: 'parser' at convert.py#4
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/tree.py", line 295, in eval
    defns = self.eval_defns()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/tree_python.py", line 151, in eval_defns
    start_scoperef = self.get_start_scoperef()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/tree.py", line 263, in get_start_scoperef
    blob = self.buf.blob_from_lang[self.trg.lang]
TypeError: 'NoneType' object has no attribute '__getitem__'
`

I see one thing it's complaining about is the parser (from the optparse module).
By the way, this is running Python 2.7.6
Dave

**Comment by mitchell-as** [comment] 2016-08-01 15:19
Thanks for the response Dave, sadly github decided to munge your post such that I cannot reproduce your problem. I tried using a file that contained the following:

```
#!/usr/bin/env python
-- coding: UTF-8 --

from process import process,parser

(options, args) = parser.parse_args()
process(options)
```

But I only got a syntax error. I tried moving the `-- coding:` line up to the previous line, but I didn't get any errors.

**Comment by davefultz** [comment] 2016-08-01 17:40
Hi Mitchell,
What an excursion . . . 3 hours on this. %^)

You may want to take a relaxing walk. . . .
After removing all the pyc files, deleting the project, removing search paths, endless Komodo restarts, and reconstituting the whole thing on a different drive, it worked--no errors.

However, the original worked if I started it in Safe Mode. No Safe Mode? Errors.

So, eventually, I tried something that was gently nagging at me.

I renamed:
Debugging Version:
        27
            convert.py

to
Debugging_Version

No errors.

Best
Dave

**Comment by mitchell-as** [comment] 2016-08-02 14:49
I'm a bit confused by your response, but it sounds like there was no bug after all. I'm going to close this issue then. Please correct me if I'm wrong.

**Closed by mitchell-as** 2016-08-02 14:49 UTC
Labels: Pending: Response

**Comment by davefultz** [comment] 2016-08-02 14:58
Somewhere in Komodo code, not mine, spaces are not being handled correctly in paths. The place to start, I think, are errors like: " KeyError: u'convert' ". 'convert' was the name of the module that caused the notifications I noticed and I subsequently discovered that similar notifications happened whenever I viewed  *any* module in the package with pathname spaces upstream.

Dave

**Comment by mitchell-as** [comment] 2016-08-04 15:26
Okay, well in my tests I can use code intelligence (codeintel2/*.py) on files with spaces in names. If you have a specific example that consistently reproduces the problem you originally described, please post it and I'll re-open the issue.
