### ISSUE TITLE
Word wrap, editor width causing words to shift and shift back

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1659] opened 2016-06-03 23:12 UTC
### Short Summary

With wordwrap on with a certain editor width causes some twitching when moving the cursor through blank lines. Some lines seem to move words to the next line, then instantly move them back to how they were; creating an odd effect.

### Steps to Reproduce

Edit a markdown file.
Enable wordwrap.
Resize the editor to a smaller width.
(Resize until it adjusts some of the wrapping text, then decrease it slightly more)
Move cursor up and down through blank lines.

### Expected results

No changes in the editor while moving the cursor.

### Actual results

Certain lines have words being pushed to the next line, then are immediately shifted back to where they were.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1, build 89196
*Operating System (and version)?* Ubuntu 15.10

### Additional Information

You may have to keep adjusting the width ever so slightly smaller and smaller until this starts happening. I noticed this as I was editing a markdown file and had the preview open, so I had adjusted the editor to half the width of the application. If I just increase the width slightly it stops happening.

[Video](https://dl.dropboxusercontent.com/u/104974948/komodo/out.ogv)

**Comment by mitchell-as** [comment] 2016-06-06 14:18
I'm not managing to reproduce this. Does it happen when you first move the caret to the beginning of a non-blank line and then cycle? Would it be possible for you to make a screencast that demonstrates the effect?

**Comment by lagbox** [comment] 2016-06-06 16:49
Added a video

**Comment by mitchell-as** [comment] 2016-06-07 14:41
Thanks so much for the video link. This looks to be an artefact from our editing component Scintilla when it calculates line widths during redraw. I would venture a guess the caret width has something to do with the calculation. Do you get the same effect when you change the caret style to "block" or "invisible"? (Edit > Preferences > Editing > Cursor Options > Cursor Style)

**Comment by lagbox** [comment] 2016-06-07 19:44
I tried the 'block' and 'invisible' cursor style and it is still happening.
Now on: version 10.0.1, build 89206

**Comment by mitchell-as** [comment] 2016-06-08 15:03
Okay, thanks. I cannot see this being anything other than caused by our editing component. Fixing this would involve investigating how line widths are calculated and patching it. I'm not sure spending time on this is justifiable given that a workaround appears to be resizing to a slightly larger view.

**Comment by Naatan** [comment] 2016-06-08 15:07
That might not always be an option though; eg. if someone has maximized their window. Is this being tracked by scintilla as a bug?

**Comment by mitchell-as** [comment] 2016-06-08 16:12
Logged bug on Scintilla bug tracker: https://sourceforge.net/p/scintilla/bugs/1837/

**Comment by mitchell-as** [comment] 2016-09-26 15:35
@lagbox: Neither myself nor Scintilla's maintainer are able to reproduce this problem. However, there may be some leads.

* Does this happen immediately when you open the file, open the markdown preview, and the do the resizing of panes? Or do you need to switch away from the Komodo app, change font settings, or do something else to trigger it?
* When this happens, please open the console pane and type `require('ko/editor').scimoz().layoutCache=2`. Then hide the console pane and try moving the caret again. Do you still get the same behavior?

@Naatan when you look at the video, notice how when the caret moves from line to line, the statusbar changes to reflect the new line (and column) number. Is it possible that the statusbar is "resizing" itself internally? (I've noticed it can do this in other situations, changing the editor width along with it.) Obviously in the video there is no ultimate change in horizontal width of the editor view, but it's possible the resize event is forwarded to Scintilla, which triggers a recalculation of line widths, which causes this issue.

**Comment by Naatan** [comment] 2016-09-26 15:54
@mitchell-as the box that contains those values is fixed width, so there should not be any resize event fired. 

Are we able to reproduce this? Should be easy to verify by simply removing or hiding the statusbar.

**Comment by mitchell-as** [comment] 2016-09-26 15:55
No, I mentioned that I could not reproduce. You can suggest how to remove/hide the statusbar to @lagbox . That might be useful.

**Comment by Naatan** [comment] 2016-09-26 16:01
@lagbox see if executing the following (from the console) has an effect:

```
document.getAnonymousNodes(ko.views.manager.currentView)[1].setAttribute("collapsed", "true")
```

To undo change true to false.

**Comment by lagbox** [comment] 2016-09-26 22:09
Updating Komodo and I will give it a shot.

**Comment by lagbox** [comment] 2016-09-26 22:25
I didn't have to try any work arounds. It seems it is working as expected now, at the moment I can't reproduce that issue. Im going to keep trying but this is way tighter now than it was before, seems like the problem is gone.

**Comment by mitchell-as** [comment] 2016-10-06 18:45
Thanks for reporting back. I'm going to close this ticket then.

**Closed by mitchell-as** 2016-10-06 18:45 UTC
Labels: Component: Scintilla, Pending: Response
