### ISSUE TITLE
Publishing: Allow force push from Places context menu

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#927] opened 2015-12-02 19:31 UTC
- Right click publishing file
- Publishing > Push
- Conflict is detect
- prompt user to force push or open Publishing dialog to resolve conflict

NOTE: This should NOT cause a full sync of the entire project.  We're only interested in one file, only one file should be diff'd/forced push/pull remote.

**Comment by Naatan** [comment] 2016-03-17 15:30
Duplicate of #148

**Closed by Naatan** 2016-03-17 15:30 UTC
Labels: Duplicate
