### ISSUE TITLE
Debugging & nginx

### ISSUE THREAD

**Issue by eco747** [Komodo/KomodoEdit#815] opened 2015-11-05 19:15 UTC
Windows 8 & 10,
I have setup nginx to serve my files on my machine (127.0.0.1).

If debugging is actived (listen for debugging connections), each time I open a file in the editor, i get a message in the debug output pane (the php version)
> It seem that Komodo do not filter it's own interaction with php.

Moreover, each time Komodo send a command to php (when i type something), the cursor move in the text, the 'find dialog' is closed or the 'goto line' is dismissed.

ie. i cannot leave the debugger active because i cannot work on my files.

**Comment by Naatan** [comment] 2015-11-05 19:18
I'm confused, where does this message come from?

>  It seem that Komodo do not filter it's own interaction with php.

That doesn't seem like something we would output.

**Comment by cgchoffman** [comment] 2015-11-06 01:29
> Moreover, each time Komodo send a command to php (when i type something), the cursor move in the text, the 'find dialog' is closed or the 'goto line' is dismissed.

Are you talking about editing your PHP file in Komodo while you're debugging it?   There are no commands sent to your PHP server by you editing a file. 
The find dialog going away when you focus on the editor is expected behavior.
The goto line dialog going away when you click on the editor is expected behavior.

**Comment by eco747** [comment] 2015-11-06 08:51
Sorry, i will try to be more clear:

I listen debugging connections:

<img width="184" alt="im8" src="https://cloud.githubusercontent.com/assets/2598404/10992600/ba94c50e-8467-11e5-92e4-2ee28b52eb1a.png">


If I choose the option 'Ask me to allow connection'  in 'Preferences/Debugger

<img width="436" alt="im6" src="https://cloud.githubusercontent.com/assets/2598404/10992569/602c43b2-8467-11e5-8182-865c7cc2e0d5.png">

When I open a file, I switch to another file with tabs, or I type something in a PHP file, after a short time (may be 2 seconds), I get this dialog:
<img width="480" alt="im7" src="https://cloud.githubusercontent.com/assets/2598404/10992585/915098d0-8467-11e5-8f5c-900e1ddc944f.png">

If I do not select  'Ask me to allow connection' but 'Allow the connection' then the cursor is moved away from the current position.

It seem to be the PHP syntax checker that do this action: as if Komodo is calling PHP to check the syntax and when PHP is called, it start the Komodo debugger.
My Komodo installation is totally new without any special addon, and i can reproduce this in safe mode.

I never saw that before with my wamp server.
Here is my php.ini concerning debugging:


[xdebug]
xdebug.remote_enable=on
xdebug.remote_autostart=true
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000


By the way, if i set the option 'break on first executable line', a temp file is opened with this content
- this is not my code

<?php echo("--- Start of Good Stuff ---\n");echo(phpversion()."\n");echo(ini_get("include_path")."\n"); ?>

Sometimes, I get this error message:
<img width="487" alt="im9" src="https://cloud.githubusercontent.com/assets/2598404/10992955/60020c4c-846b-11e5-846c-b4b3532f0fab.png">

Sometimes this one:
<img width="490" alt="im10" src="https://cloud.githubusercontent.com/assets/2598404/10992968/7e36c202-846b-11e5-88ab-8c92337a73bf.png">

In safe mode, i get this in my console:

<img width="426" alt="im11" src="https://cloud.githubusercontent.com/assets/2598404/10993011/cc97b2a8-846b-11e5-9765-e8d07b83fd87.png">

**Comment by cgchoffman** [comment] 2015-11-06 15:50
You haven't specified an xdebud executable for pho to use so it's likely using the default which is the wrong one for komodo.  Please have a look at the docs for configuring PHP debugging in komodo and make sure you use the right xdebug executable that we provide. http://docs.komodoide.com/Manual/debugphp#debugging-php-komodo-ide-only_remote-php-debugging_configuring-remote-php-debugging

**Comment by eco747** [comment] 2015-11-09 14:10
thanks

sorry i didn'nt include this line
> zend_extension = "./php_xdebug-komodo.dll"
this dll is the one provided by komodo 9.3.0 installer.

I absolutely need xdebug.remote_autostart=true

**Comment by Naatan** [comment] 2015-11-09 16:56
I'm not sure why Komodo would be executing for syntax checking calls or the like, do you have anything else invoking the PHP interpreter?

A simple workaround would be to create an identical php.ini file but with xdebug disabled, which you then point Komodo (and only Komodo) at.

**Comment by eco747** [comment] 2015-11-09 17:09
No, nothing.
I removed the syntax checking for php in preferences & it seem to be better.

By the way, i switched to php 5.4.45 and the komodo php_xdebug.dll seem to crash every 5mn :(
i switch back to the last xdebug dll.

I also follow your suggestion:
- in the preferences/language PHP i choose a new php.ini without auto_start.
- in that .ini i remove everything concerning debugging

but now the debugger configuration tell me that 'error determining php version...' although it seem to work.

**Comment by Naatan** [comment] 2015-11-09 17:13
I believe that error is simply miss-leading, and actually means "error checking debugging settings". If it works it works.

Could you share your php.ini with the debugging settings? We'll see if we can repro the issue.

**Comment by eco747** [comment] 2015-11-09 17:19
of course, but github do not allow me to upload nor .ini, nor big .txt

**Comment by Naatan** [comment] 2015-11-09 17:20
You could gist it; https://gist.github.com/

**Comment by eco747** [comment] 2015-11-09 17:23
great :)
https://gist.github.com/eco747/b0e6fe8abd1751be0752

**Comment by Naatan** [comment] 2015-11-09 17:24
Thank you :)

**Comment by eco747** [comment] 2015-11-09 17:25
my php version is 5.4.45.

**Comment by cgchoffman** [comment] 2015-11-11 00:08
Hi @eco747,  could you rename the Komodo xdebug dll to it's original name and try again, `php_xdebug.dll`?

**Comment by mitchell-as** [comment] 2016-10-05 19:34
After spending some time with this ticket, it's really not clear if there is a problem any more.

* Having `xdebug.remote_autostart` turned on in `php.ini` causes the original behavior of the debugger being triggered each time syntax checking is invoked. The solution is to use a separate `php.ini` with that setting turned off.
* I tried using the supplied `php.ini` in my Edit > Preferences > Languages > PHP and it worked. (Note that I did not have a few of the enabled extensions installed, and that resulted in some "error determining version" errors in my troubleshooting log. Commenting out those non-existant modules solved my problem.)

If you're still having trouble @eco747, please show the contents of your Help > Troubleshooting > View Log File. I'm going to close this issue until then, because it's either no longer an issue, or a configuration issue -- nothing on the part of Komodo.

**Closed by mitchell-as** 2016-10-05 19:34 UTC
Labels: Bug
