### ISSUE TITLE
view whitespace confusing, contradictory

### ISSUE THREAD

**Issue by garretwilson** [Komodo/KomodoEdit#996] opened 2016-01-09 15:05 UTC
I went to Preferences > Editor and turned on "Show whitespace characters" and "Show end-of-line (EOL) characters". Then I opened up an XHTML file. No whitespace or EOL characters shown.

Then I went to View > View Whitespace and View > View EOL Markers and they came on. This is the "confusing" part --- what is the difference between the two settings?

But then comes the "contradictory" part. Now that I've turned them on in the View menu, I go back to Preferences > Editor and turn them off here. They disappear from the editor --- but View > View whitespace is still checked in the menu! So I turn it _off_ and the whitespace shows up again --- exactly the opposite of what is selected in the View menu! So I select View > View Whitespace again, and the whitespace turns off --- and the check in the View menu stays off, so finally the settings are synchronized again. Whew! Some settings synchronization bug here.

Update: as if all that weren't enough, Komodo doesn't remember the View > View Whitespace setting across files. If I turn on View Whitespace in one file, it is forgotten for another file. Or put another way, even stranger Komodo seems to remember this setting on a per-file basis (across reloads). That's just completely confusing. You might have an argument if you kept track of it by file "language"---but just be simple and let me toggle it on and off for the editor. I'd rather it just worked than it be all fancy and take up half my day. Look at the confusion it caused e.g. http://forum.komodoide.com/t/komodo-indent-preventing-beautify-js-tabs/2432/1 .

**Comment by cgchoffman** [comment] 2016-01-11 17:46
I'm fairly certain this is a dupe of #861.

**Closed by cgchoffman** 2016-01-11 17:46 UTC
Labels: Bug
