### ISSUE TITLE
Doesn't work DevDocs searcher by basic PHP functions

### ISSUE THREAD

**Issue by mikhalenia** [Komodo/KomodoEdit#3243] opened 2017-10-04 21:24 UTC
### Short Summary
When I focus on some basic PHP function in Komodo IDE 10 and press Ctrl+K, Ctrl+G (by default key settings) it goes to php.net on page when I see information about using this function. When I do it on Komodo IDE 11 I'm going to DevDocs and see a message "No results."

**Dev Edit**:
Either PHP in general is disabled or PHP 7 docs are disabled.  They should be enabled by default: https://github.com/Komodo/KomodoEdit/issues/3243#issuecomment-334299768

### Steps to Reproduce
1. Open Komodo IDE 11
2. Open DevDocs and Enable PHP
3. Create a simple PHP file which contains using of some basic PHP function
```
<?php

var_dump(1);
```
4. Focus on var_dump() and press Ctrl+K, Ctrl+G

### Expected results
I think It has to show an information about using var_dump()

### Actual results
I see a message "No results."

### Platform Information
Komodo IDE 11
It's reproduced on Ubuntu 15.10 and Mac OS Sierra 10.12.6

### Additional Information
When I try to find var_dump by typing var_dump in DevDocs widget - it works correct.
Also I've got two versions of Komodo IDE on my computer at the same time: Komodo IDE 10 and Komodo IDE 11. It's reproduced on Safe-Mode of Komodo.

**Comment by Naatan** [comment] 2017-10-04 21:35
Cannot reproduce. Where is your caret position exactly?

**Comment by cgchoffman** [comment] 2017-10-04 21:37
Ctrl+K, Ctrl+G is go to definition.  Did you mean a different key binding?

**Comment by cgchoffman** [comment] 2017-10-04 21:46
SOrry, my comment is beside the point.  I'm getting the same thing when I assign a key binding to trigger dev dock:
![capture](https://user-images.githubusercontent.com/655154/31201237-d5aad410-a912-11e7-9668-37709b65d88c.PNG)

**Comment by mikhalenia** [comment] 2017-10-04 21:47
Yes I've tried to find a definition of basic function in PHP. No mater where is the caret now. I've tried on the start of line.

**Comment by cgchoffman** [comment] 2017-10-04 21:49
Ok got it.  Apparently it's disabled:
![devdocs](https://user-images.githubusercontent.com/655154/31201342-2ea2b786-a913-11e7-881b-e9be75cc9f78.GIF)

**Comment by cgchoffman** [comment] 2017-10-04 21:50
Apologies for the inconvenience @mikhalenia.  Thanks for your patience so far.

**Comment by Naatan** [comment] 2017-10-04 21:53
@cgchoffman PHP docs being disabled is not the bug he is raising, he says he doesnt get var_dump results at all.

@mikhalenia you're talking about go to definition, which is a completely different thing altogether. Are you confusing 2 features?

**Comment by cgchoffman** [comment] 2017-10-04 21:54
oh man, sorry!  It's step two in the repro.  Then ya, `ctrl+k, Ctrl+g` is code intel.  Not devdocs.

**Comment by mikhalenia** [comment] 2017-10-04 22:15
@Naatan Ok, I understand. But Can I quickly jump from my file to offline DevDocs dictionary?

**Comment by Naatan** [comment] 2017-10-04 22:47
You can, using the command I gave (which you can set a keybinding for) or using the devdocs icon at the bottom of the side toolbar (looks like a book).

Closing this as this is not a bug, you're using the wrong thing to invoke devdocs.

**Closed by Naatan** 2017-10-04 22:47 UTC
Labels: Pending: Response

**Comment by mikhalenia** [comment] 2017-10-05 07:37
Yes It works. Thank you!
