### ISSUE TITLE
Komodo freezes if it loses temporarily network connection while remote dir is opened via sftp

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#1955] opened 2016-08-22 21:57 UTC
### Short Summary

Komodo freezes if it loses temporarily network connection while remote dir is opened via sftp

### Steps to Reproduce

- Open a remote dir vis sftp, then open a file
- disconnect the network in any way (disconnect the cable, shut down vpn, whatever)
- reconnect the network

### Expected results

Komodo should let me work with local copy offline and reconnect seamlessly as soon as the network is back

### Actual results

It freezes with no hope, and I have to kill it via process manager and reopen it several times, answering no to the question "restore files...?" where in spite of this choice it continues to attempt the sftp reconnection.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Windows 8.1

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment] 2016-08-23 00:02
1. *It freezes with no hope, and I have to kill it via process manager*, it sounds like you're not waiting for the timeout to be reach which is set in the server prefs.  Can you please try that for now?

2. *Komodo should let me work with local copy offline*, This is the action.  Support offline editing of remote file.  This could hook into the autosave tooling.
 
3. *answering no to the question "restore files...?" where in spite of this choice it continues to attempt the sftp reconnection.*  This is a related but separate issue.   Please file another bug.

**Comment by ANSI-C** [comment] 2016-08-23 08:16
Hello,

I know about server timeouts setting, and tested several ones from 1 to 
8 seconds with no luck, the program hangs forever (minutes). My feeling 
is that the sftp connection is not handled properly (async/separate 
threads), but just a feeling. The actual experience is to be forced to 
kill the program at every network flap/hiccup.

Il 23/08/2016 02:03, Carey Hoffman ha scritto:

**Comment by Naatan** [comment] 2016-08-23 15:06
I've opened a tracking issue for this here:

https://github.com/Komodo/KomodoEdit/issues/1959

Closing this in favor of that one.

**Comment by cgchoffman** [comment] 2016-08-23 15:15
The action item for this ticket is offline editing, not async handling.  I'd like this to remain open and tracked with remote file UX improvements.

**Comment by Naatan** [comment] 2016-08-23 17:04
That should already work, the only reason it currently doesn't is because of sync stuff hanging up Komodo. I'll add a reference to this bug in that ticket to ensure that this is fixed once async is implemented, but I'm fairly certain it will be.

**Closed by Naatan** 2016-08-23 17:04 UTC
Labels: Component: Remote Files, Enhancement: Feature

**Comment by cgchoffman** [comment] 2016-08-23 17:07
That works.

**Comment by ANSI-C** [comment] 2016-08-30 09:47
![useless](https://cloud.githubusercontent.com/assets/7015883/18084349/320b8724-6ea7-11e6-8227-c5ad399a017e.png)

Hello, this issue is serious, it makes Komodo IDE nearly useless for my needs. If async requires time to develop please at least do something to prevent freezes, setting timeout to few seconds does not work.

**Comment by vanoden** [comment] 2017-12-05 12:27
I have this problem all the time with occasionally slow servers over VPN with SFTP.  I work remotely for a number of companies, and several times a week I have to kill the komodo process and restart.  I've learned to save often so I don't lose too much work.  A couple of times a year I get frustrated and switch to another editor.  But I like komodo, and would buy the IDE (I've done so in the past), but this problem is really, really annoying.

**Comment by cgchoffman** [comment] 2017-12-05 18:47
@vanoden, what version of Komodo are you using?

**Comment by vanoden** [comment] 2017-12-05 19:47
Komodo Edit, version 11.0.1, build 18119, platform win32-x86. Built on Fri
Oct 27 23:54:50 2017.

But this has happened in every version I can remember, going back for
years.  It's a really difficult problem to search for on the
internet...it's not really a crash and there is no error.  It seems like
the file dialog is modal and if it doesn't appear before the timeout, you
can't get to it.  Thus any click on the application just plays the error
sound.  Attempts to close the window or exit the application from the task
bar do nothing.  I have to kill the process in the task manager.

**Comment by cgchoffman** [comment] 2017-12-05 19:50
@vanoden, thanks for confirming the version.

Could you please file a new bug?  We addressed the root issue for this ticket.  We can't reliably base any digging done in this ticket on the issue you're seeing.

**Comment by ANSI-C** [comment] 2017-12-05 20:06
@vanoden , @cgchoffman , seems that the bug that would fix this for good is still open:

[https://github.com/Komodo/KomodoEdit/issues/1959](https://github.com/Komodo/KomodoEdit/issues/1959)

hence I assume that this is still not working in v11 (I have Komodo IDE v11.0.1 but do not test this since ages)

**Comment by vanoden** [comment] 2017-12-05 20:17
#1959 looks a bit all over the place.  It does seem at the very least
related to the problem, though most of the listed issues are tagged as
Closed and there doesn't seem to be any interest since May.

I'll file a new bug.  Thank You.

**Comment by cgchoffman** [comment] 2017-12-05 21:55
@ANSI-C #1959 was far too broad to ever really close.  Or at least it ended up not being as simple as just implementing async remote files.  If you look through that ticket many thing references #1959 and are closed.  We should just close that ticket.

@ANSI-C, I take it that means you're still experiencing this issue?  What exactly is the trigger of the issue for you?  I setup a remote connection to a VM, opened a file, paused the VM (connection killed essentially) and Komodo will tick away no problem *until* I save then Komodo will hang for the timeout duration then spit out an error.  You've already said the timeout period doesn't elapse for you so I don't know what the root of your issue is.

@vanoden , thanks for filing a new ticket.  You're issue doesn't sound like this issue.  From what @ANSI-C, wrote there is no dialog involved.  You're hitting some buried modal window which you suggested already.  I'll comment more on that in your ticket.

**Comment by cgchoffman** [comment] 2017-12-05 22:09
Confirmed that setting the timeout to 1 seconds basically makes the issue go away for me so I'm guessing it's a different trigger for you @ANSI-C

**Comment by ANSI-C** [comment] 2017-12-06 08:46
@cgchoffman just tested this now after months. It works, but there still an issue: if I connect to a remote server via pubkey and try to yank the ethernet cable, Komodo does not freeze anymore, but when I reconnect the cable and try to save the file, Komodo IDE prompts for password, despite the pubkey setup.
If you can fix this bug Komodo would be finally very very nice to work with remote servers.

**Comment by ANSI-C** [comment] 2017-12-06 16:30
Hello, was trying to use this feature, it works nice, but at one point it doesn't anymore:

first I get this:
![image](https://user-images.githubusercontent.com/7015883/33672665-0d53f580-daab-11e7-93ec-b7874e643d2e.png)

then this:
![image](https://user-images.githubusercontent.com/7015883/33672604-e43d4c8c-daaa-11e7-9e25-846724df4daa.png)

**Comment by cgchoffman** [comment] 2017-12-07 17:34
> Hello, was trying to use this feature, it works nice, but at one point it doesn't anymore:

What feature?

> Komodo does not freeze anymore, but when I reconnect the cable and try to save the file, Komodo IDE prompts for password, despite the pubkey setup.

Thanks for confirming that things are almost working.  Please file a new ticket for this.  It sounds like #3399 but there isnt enough information in that ticket to narrow down what the issue is.

**Comment by ANSI-C** [comment] 2017-12-08 05:33
The open via SFTP feature. The issue seems like the 3399, I can only say that it happens after some time, probably after a timeout from remote server, the only thing that I know is that Komodo says that "socket is closed" so probably something closes the connection, possibly the remote server due to a timeout. You could either set a keepalive to prevent this, or set up an "automatic reconnection" feature, or (best) both. When Komodo tries to reconnect it disregards both username/password and (in my case) public key authentication. Hope this helps. About the "almost working" I can say I cannot use this feature cause it is so unreliable that I lost work/edits couple times. For an example of seamless management of connection disruptions have a look to MIT's mosh.

**Comment by cgchoffman** [comment] 2017-12-11 18:28
I'm not able to reproduce this issue.  Here are the steps I followed:
- Setup a SFTP connection with a Linux VM using an OpenSSH key
- Open remote folder in Komodo
- Open remote file from above folder
- Pause VM and save file
- Komodo pauses waiting for timeout to elapse then says connection failed
- unpause VM, save file, completes without issue

I also tried stopping Komodo with the remote folder and file open, pausing the VM, starting Komodo, Komodo tries to connect and fails.  I then unpause the vm and reopen the remote folder without issue.  

Komodo used the configured key both times.  Are you configuring a key in the Server prefs?  Or are you setting up a key with PuTTY + Pageant?  Both should work fine but maybe there is an issue in the method you're using that could shed some light.

Komodo already attempts to reconnect depending on the scenario.  This sounds like your server is configured in correctly.

> "socket is closed"

Sounds like the remote is closing connections on you.

**Comment by ANSI-C** [comment] 2017-12-15 11:41
Hi, for me it suffices to open a file remotely, do something else, then after some time (could be half hour) make a change on a file and attempt to save it, then the issue arises. Seems to me a timeout issue, not sure if on server or on client (Komodo). I cannot say about ssh timout from the target server, since I use mosh and it reconnects seamlessly. Will try to test with a normal ssh session the next time I will encounter this problem. I would suggest to double check the (re)connection routine anyway.

**Comment by holmes20** [comment] 2019-10-10 08:42
For me it was sufficient to kinda disable the SSH timeOut 
on Client and server (Ubuntu 18.04)

http://queirozf.com/entries/disabling-ssh-timeout-when-connecting-to-from-ubuntu

SSH Client ConfigurationPermalink
In the server/computer you are connecting from

Open file /etc/ssh/ssh_config and set directive ServerAliveInterval to a value like 100:

# other configs
ServerAliveInterval 100
This causes your SSH client to send keep-alive messages every 100 seconds so that the server doesn't drop your connection.

Server ConfigurationPermalink
In the server you are connecting to

You must also configure the SSH remote Server you are connecting to (or ask whoever is responsible for doing it).

Open file /etc/ssh/sshd_config and add these configurations at the end of the file to ensure they're not overriden by later lines:

# other configs
ClientAliveInterval 600
TCPKeepAlive yes
ClientAliveCountMax 10
These are conservative settings that will make your SSH Server only disconnect after (600 * 10 = 6000) seconds of user inactivity. Customize these if you need more.
