### ISSUE TITLE
HTTP Inspector fails to run in Mac OS X in 9.3.1 and 9.3.2 (Nightly)

### ISSUE THREAD

**Issue by playanywheredesigns** [Komodo/KomodoEdit#981] opened 2016-01-02 20:17 UTC
When running Komodo IDE on Mac OS X 10.11.2 the HTTP Inspector fails to load.  I confirmed this runs fine in Komodo IDE 9.2.  The logged exception is below.

-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: chrome://httpinspector/content/httpInspector.js :: httpInspector_onLoad :: line 1223"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]'
+ result (number) 2153185302
+ name (string) 'NS_ERROR_XPC_GS_RETURNED_FAILURE'
+ filename (string) 'chrome://httpinspector/content/httpInspector.js'
+ lineNumber (number) 1223
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
onload@chrome://httpinspector/content/httpInspector.xul:1:0
'
+ location (object) JS frame :: chrome://httpinspector/content/httpInspector.js :: httpInspector_onLoad :: line 1223
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://httpinspector/content/httpInspector.js'
| + name (string) 'httpInspector_onLoad'
| + lineNumber (number) 1223
| + columnNumber (number) 40
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://httpinspector/content/httpInspector.xul :: onload :: line 1
| + formattedStack (string) 'httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
onload@chrome://httpinspector/content/httpInspector.xul:1:0
'
| + stack
    httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
    onload@chrome://httpinspector/content/httpInspector.xul:1:0
-- EXCEPTION END --

**Comment by mitchell-as** [comment] 2016-01-04 15:22
@cgchoffman would you please look into this when you get the chance? Thanks.

**Comment by cgchoffman** [comment] 2016-01-04 18:43
I'm not seeing this in 9.3.2 (build # 88190).  HTTP Inspector loads and works.

**Comment by playanywheredesigns** [comment] 2016-01-04 18:45
I had tried this across 2 Macs.  Both gave the same error.  On one of them I completely removed Komodo IDE and reinstalled it.  I also tried a complete reset in Komodo and still had the same outcome.

**Comment by cgchoffman** [comment] 2016-01-04 18:46
Oh you did get it.  I added to my message above.  Please review and get back to us.

**Comment by playanywheredesigns** [comment] 2016-01-04 18:53
I updated to the listed build and still no go.  Error log below.
[2016-01-04 12:50:53,784] [ERROR] httpInspector: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: chrome://httpinspector/content/httpInspector.js :: httpInspector_onLoad :: line 1223"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]'
+ result (number) 2153185302
+ name (string) 'NS_ERROR_XPC_GS_RETURNED_FAILURE'
+ filename (string) 'chrome://httpinspector/content/httpInspector.js'
+ lineNumber (number) 1223
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
onload@chrome://httpinspector/content/httpInspector.xul:1:0
'
+ location (object) JS frame :: chrome://httpinspector/content/httpInspector.js :: httpInspector_onLoad :: line 1223
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://httpinspector/content/httpInspector.js'
| + name (string) 'httpInspector_onLoad'
| + lineNumber (number) 1223
| + columnNumber (number) 40
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://httpinspector/content/httpInspector.xul :: onload :: line 1
| + formattedStack (string) 'httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
onload@chrome://httpinspector/content/httpInspector.xul:1:0
'
| + stack
    httpInspector_onLoad@chrome://httpinspector/content/httpInspector.js:1223:40
    onload@chrome://httpinspector/content/httpInspector.xul:1:0
-- EXCEPTION END --

**Comment by cgchoffman** [comment] 2016-01-04 19:43
Can you try starting in SafeMode? Help > Troubleshooting > Restart in SafeMode

**Comment by playanywheredesigns** [comment] 2016-01-05 00:49
I tried safemode and it still did not work.  I also re-downloaded 9.21 on my Machine and confirmed it works in that version without issue.  
Other steps I tried
Allowed unsigned applications (nope)
Turned off System Protection (nope)

At this point I am not sure what else to provide you.  Can @cgchoffman confirm you are on 10.11.2 and it is not a OS bug?

**Comment by cgchoffman** [comment] 2016-01-06 17:47
> Can @cgchoffman confirm you are on 10.11.2

confirmed.  It works fine on 10.11.

Could you open the *View > Tabs & Sidebars > Console* and enter the following line of code and see if it runs:

```javascript
var koHttpInspectorSvcSvc = Components.classes["@activestate.com/koHttpInspector;1"].getService(Components.interfaces.koIHttpInspector);
```

Please confirm the build number you're running as well *Komodo > About Komodo*.

- Carey

**Comment by playanywheredesigns** [comment] 2016-01-06 18:07
I ran the command output below.
var koHttpInspectorSvcSvc = Components.classes["@activestate.com/koHttpInspector;1"].getService(Components.interfaces.koIHttpInspector);
12:06:18 593ms
Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
12:06:18 602ms
Boolean
false

As to the build here it is
Komodo IDE, version 9.3.2, build 88191, platform macosx. Built on Thu Dec 10 13:22:09 2015.

**Comment by cgchoffman** [comment] 2016-01-06 22:52
Ahhh, you said HTTP doesn't run which I took as it not opening.  Sorry for the delay @playanywheredesigns.  Looks like I broke this with a fix a few months ago and you're the only one to notice.

I have to look into why I made the change before I fix this...time passes...this was fixed due to an issue on Linux and Windows.  The fix appeared to be fine on OSX but alas, that wasn't the case.  Sorry again @playanywheredesigns.  It's working on Linux and Windows but not OSX.  I'm working on a fix now.

Refs:
Fix https://github.com/Komodo/KomodoIDE/commit/bdf8b5709e735bbf98e2b8c8469a5d7b0256cebe
Bug https://github.com/Komodo/KomodoEdit/issues/780

**Comment by playanywheredesigns** [comment] 2016-01-07 03:36
@cgchoffman Not sure if this is why but in 9.2.1 (even now just tested) autoupdate is not telling me there is a newer version available on the Mac.  You may want to check that as well.

**Comment by cgchoffman** [comment] 2016-01-07 18:06
There is no auto-upgrade path from 9.2.1 any more.  It's been about 8 months since that was release.  Everyone should have been updated by now so we removed that entry.  You'll have to install 9.3.2 fresh.

**Comment by cgchoffman** [comment] 2016-01-07 19:12
I think I have an acceptable solution for this. Standby.

**Comment by cgchoffman** [comment] 2016-02-01 23:48
Closed by commit in IDE repo. THe following link is not public accessible, it's for devs if they need it later: https://github.com/Komodo/KomodoIDE/commit/06a0bf5dbb7e13627f926128437e750ee33e345f

**Closed by cgchoffman** 2016-02-01 23:48 UTC
Labels: Pending Internal
