### ISSUE TITLE
Sections breaks with this sample code

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1844] opened 2016-07-25 15:25 UTC
### Short Summary

```scss
pre, code {
    background: rgba($base, 0.08);
}

.div.div {
    color: red;
}
```

Open Sections scope of Commando or Code Toolbox - you won't see `.div.div` anywhere. Remove `rgba($base, 0.08)` and replace it with `red` and everything will work fine.

**Comment by Defman21** [comment] 2016-07-25 15:27
If you comment `rgba`:
```scss
pre, code {
    background: #ff0000; //rgba($base0D, 0.08);
}

.div.div {
    color: red;
}
```

Code will be:

![img](http://imgur.com/qtnLHtv.png)

**Comment by Defman21** [comment] 2016-07-25 15:29
`rgb` is also affected. Non-hex will break it.

**Comment by mitchell-as** [comment] 2016-07-25 15:30
Duplicate of #1370 and has been fixed.

**Closed by mitchell-as** 2016-07-25 15:30 UTC

**Comment by Defman21** [comment] 2016-07-25 15:31
Oops, sorry. Thanks for pointing me to the issue :)

**Comment by mitchell-as** [comment] 2016-07-25 15:32
No need to apologize. There's no build out that has this issue fixed, so you wouldn't know :)

**Comment by Defman21** [comment] 2016-07-25 15:35
Applied the diff of the fix-commit of the original issue and it's working like a charm, yay!
