### ISSUE TITLE
Komodo update requires manual double restart

### ISSUE THREAD

**Issue by cavac** [Komodo/KomodoEdit#1001] opened 2016-01-13 14:42 UTC
When using the "Check for update" function in Komodo to install an update, Komodo prompts you to  restart Komodo. After it restarts, another prompt (bar under the icon bar) prompts you to restart again to apply changed settings.

In this case, Komodo should restart automatically the second time round, since it doesn't make much sense to install an upgrade and not having half of the changes and bugfixes applied during the first editing session.

Also noticed: After the second restart, Komodo doesn't automatically re-open the last open project and files.

**Comment by Naatan** [comment] 2016-01-13 16:36
What Komodo version and OS?

**Comment by cavac** [comment] 2016-01-13 20:24
Xubuntu 14.04 x64 (based on Ubuntu 14.04 but different Desktop), Upgrade from Komodo IDE 9.3.1 (i think) to 9.3.2.

**Comment by Naatan** [comment] 2016-01-13 22:16
This is a duplicate of #29, it will be fixed in Komodo 10.

**Closed by Naatan** 2016-01-13 22:16 UTC
Labels: Pending Response
