### ISSUE TITLE
Suggesting completions after commas/parentheses seems premature

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#3089] opened 2017-09-14 22:42 UTC
Code intelligence is suggesting completions after I type a comma, apparently with a list of all the names in scope. This gets in the way when I'm writing comma-separated terms in a multi-line context, e.g. initializing a dictionary in Python:

d = {
  'foo': 'bar',
  'baz': 'bort',
}

After each comma I'm wanting to hit enter to start a new line; now I have to clear the suggestion popup, first (or I hit enter reflexively and get the first suggestion inserted). The same goes for an open parenthesis (e.g. when initializing a keyed array in PHP) - it's a tossup whether the next thing I'm going to be typing is a newline or something else.

I would say suggesting completions is reasonable after I've typed a word character, but not without any context to narrow the list of suggestions. Even if the next thing I want to input is something that's on the suggestion list, it's unlikely to be at or close enough to the top of the list that I can select it without first typing a couple characters of its name, anyway.

Komodo IDE 11.0.0 build 90665
Mac OS X 10.11.6

**Comment by cgchoffman** [comment] 2017-09-14 22:49
Looks like this needs to be PHP, though there could be use cases that trigger this in other languages.  It is quite frustrating.

**Comment by damienprystay** [comment] 2017-09-14 22:50
I'm encountering it in Python as well, yes.

**Comment by cgchoffman** [comment] 2017-09-14 22:51
Confirmed.  Thanks @damienprystay

**Comment by damienprystay** [comment] 2017-09-14 23:16
Relatedly (in that so far I only see this behaviour with post-delimiter suggestions), typing sufficiently fast can cause the completion popup to occur (and remain) after the character that triggered it has been obsoleted.

E.g. (in PHP) typing `foo();` one character at a time shows the suggestion popup (other than for as many of the initial letters produced suggestions) occurs after `(`, and disappears after `)`; however, typing it at speed can result in the popup only occurring after the `;`. Again, if the next character is a newline, that can result instead in selecting the first suggestion.

**Comment by Naatan** [comment] 2017-09-15 14:47
@damienprystay can you please log that separately? Only one issue per report :)

**Comment by mitchell-as** [comment] 2017-09-21 15:44
Fixed via https://github.com/Komodo/codeintel/commit/4889ca07109c599bf80cd0b00023b5dc96f81dbe

**Closed by mitchell-as** 2017-09-21 15:44 UTC
Labels: Introduced: 11, Type: Bug

**Comment by mjainQA** [comment] 2017-10-11 19:46
Verified in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.
