### ISSUE TITLE
No progress bar when updating

### ISSUE THREAD

**Issue by clokep** [Komodo/KomodoEdit#1308] opened 2016-04-27 15:53 UTC
### Short Summary

There's no progress bar on the download to update Komodo.

### Steps to Reproduce

Install an old version of Komodo and check for updates.

### Expected results

You see progress of the download.

### Actual results

The counter updates, but there's no progress bar (I think there normally is one here).

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.0.0-alpha1, build 88973, platform macosx. Built on Tue Apr 26 10:36:47 2016. (this is the version I updated *to*, not the one I updated *from*, but it was the previous nightly)
*Operating System (and version)?* OS X El Capitan

### Additional Information

![screen shot 2016-04-27 at 11 49 40 am](https://cloud.githubusercontent.com/assets/517124/14858578/9d9946a2-0c6e-11e6-8e13-adfa71c39463.png)

**Comment by Naatan** [comment] 2016-04-27 17:30
Thanks patrick. Since this is an issue in the old UI I'll mark this as wontfix. We'll have to ensure this doesn't persist in the new UI though.

**Comment by clokep** [comment] 2016-04-27 17:31
@Naatan What do you mean "the old UI"? To be clear, it was updating from 10 alpha to a newer nightly.

**Comment by cgchoffman** [comment] 2016-04-27 17:33
Ya confirmed this is happening in 10.  It looks like there is some styling missing.  I can have a hack at this @Naatan. If you install 88858 nightly then "check for updates" on OSX you'll see this.

Link to 88858: http://downloads.activestate.com/Komodo/nightly/komodoide/2016/04/2016-04-15-00-master/

**Comment by Naatan** [comment] 2016-04-27 18:13
@clokep ah sorry, I thought you were talking about 9.x

**Comment by cgchoffman** [comment] 2016-05-10 22:49
This should be fixed.

**Closed by cgchoffman** 2016-05-10 22:49 UTC
Labels: Bug, New
