### ISSUE TITLE
Code intelligence crashes for the Go language

### ISSUE THREAD

**Issue by dqd** [Komodo/KomodoEdit#461] opened 2015-07-28 08:12 UTC
Hello,

when I open in Komodo Edit (version 9.1 on Linux with Go 1.4 and recent Godef and Gocode) a simple [Hello world example in Go](https://gobyexample.com/hello-world) and click on the `Println` function to see its annotation, codeintel crashes with the following error message and does not work anymore:

```
ERROR:xpcom:Unhandled exception calling 'G     int8 * scopestart(out retval int32);'
TypeError: int() argument must be a string or a number, not 'NoneType'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1255, in handle
    callback(request, response)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
    return fn(*args, **kwargs)
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1675, in callback
    handler.done()
  File "<XPCOMObject method 'done'>", line 3, in done
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-07-28 09:59:35,556] [ERROR] codeintel.komodo.KoCodeIntelManager: Error reading data from codeintel
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1177, in run
    self.handle(response)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-07-28 09:59:35,557] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelDefinition.scopestart] (2) in chrome://komodo/content/codeintel/codeintel.js:1312
Traceback (most recent call last):
  File "chrome://komodo/content/codeintel/codeintel.js", line 1312, in 
```
Can you please take a look at that?

**Comment by Naatan** [comment] 2015-07-28 16:00
So while testing this I ran into a bug where godef was not being found properly, which I ended up fixing: https://github.com/Komodo/KomodoEdit/commit/cb73f0c26d14673e6d87af7da73276346b2cbcc7

However I am not able to reproduce your issue after fixing that bug. Please try the latest nightly tomorrow (which should contain this fix) and let me know if you still have this issue.

**Comment by dqd** [comment] 2015-07-28 16:07
Thank you for your quick reaction, I will.

**Comment by dqd** [comment] 2015-07-29 08:02
I tried the 9.2.0-15956-linux-x86_64 build and unfortunately, I do not see any difference, it still crashes with the same error message.

One more thing regarding my environment — I use [GVM](https://github.com/moovweb/gvm) instead of standard Go distribution package. So my Go location settings is:
* /home/dqd/.gvm/gos/go1.4/bin/go (Go tool)
* /home/dqd/.gvm/pkgsets/go1.4/global/bin/gocode (Gocode)
* /home/dqd/.gvm/pkgsets/go1.4/global/bin/godef (Godef)

Furthermore, I set the `GOPATH` environment variable to my project's directory and adding `/home/dqd/.gvm/gos/go1.4/bin` and `/home/dqd/.gvm/pkgsets/go1.4/global/bin` to the `PATH`.

Is there anything else which I could miss?

**Comment by Naatan** [comment] 2015-07-29 15:46
Sorry I should have specified; our nightlies build at night but are not pushed out until 12pm pacific time. I'll ping here when it's out.

**Comment by cgchoffman** [comment] 2015-07-29 16:49
You should be able to Help > Check for Updates to get the newest bits, after 12 pm.  I'm pushing the bits to staging right now.

**Comment by Naatan** [comment] 2015-07-29 20:22
They're live now.

**Comment by dqd** [comment] 2015-07-30 05:46
Oh, I live in Central Europe, so we have 9 hours difference. However, the build 15958 behaves in the same way.

**Comment by Naatan** [comment] 2015-07-30 15:34
> I set the GOPATH environment variable to my project's directory

I'm no go pro, but shouldn't that be set to where your go libs are installed? Or maybe I missunderstand what you mean by "project directory". I would "guess" GOPATH would need to be set to `/home/dqd/.gvm/gos/go1.4/` for you. Again though, I don't know much about GO so only assuming here.

When I go to definition on `Println` Komodo opens `/usr/lib/go/src/fmt/print.go`, does that file exist in your .gvm folder? 

Do simple go to def calls work? Ie. ones that go to functions you have defined yourself?

**Comment by dqd** [comment] 2015-07-31 09:34
You are right, it was a silly idea to set up the `GOPATH` variable to my project directory. The code for `Println` lives in the `/home/dqd/.gvm/gos/go1.4/src/fmt` directory and when I run the following command from console, it seems to work:
> $ godef -f /home/dqd/.gvm/gos/go1.4/src/fmt/print.go 'Println'
> /home/dqd/.gvm/gos/go1.4/src/fmt/print.go:263:6

However, after changing the Komodo's `GOPATH` variable to `/home/dqd/.gvm/gos/go1.4`, codeintel crashes with the same error message when I click on the `Println` function. It is weird that when I only hover on it with the cursor while holding the Ctrl key, the annotation and location are displayed correctly, regardless of `GOPATH` settings.

![komodo-println-definition](https://cloud.githubusercontent.com/assets/574700/9004590/8bd5c70a-3777-11e5-97e1-3a35dc2fbe24.png)

**Comment by Naatan** [comment] 2015-07-31 15:21
Few things to try:

 * Do simple go to def calls work? Ie. ones that go to functions you have defined yourself?
 * See if goto definition works if you right click the word and select "Go to Definition"
 * See if it works with a different language (eg. Python)

**Comment by dqd** [comment] 2015-08-03 05:40
*Do simple go to def calls work?*
No, it behaves the same even for definitions in the same file.

*See if goto definition works if you right click the word and select "Go to Definition"*
When I press the right mouse button on a function name, the codeintel crashes. But when I use the keyboard shortcut (Ctrl + K, Ctrl + G), it works like a charm!

*See if it works with a different language (eg. Python)*
Yes, it seems to be working.

**Comment by dqd** [comment] 2015-10-30 08:29
Hello, my issue still persist, even with 9.3.0-16352-linux-x86_64.

**Comment by Naatan** [comment] 2015-10-30 15:02
Please see if you can reproduce the issue on Komodo 9.3 with a clean profile, on the new tab page (File > New > New Tab) hit Troubleshooting > Restart in Safe-Mode.

**Comment by dqd** [comment] 2015-11-02 07:12
I have always cleaned my profile by removing the `~/.komodoedit` directory first. However, when I try the safe-mode, the *Go To Definition* functionality is not available at all.
![komodo-safe-mode](https://cloud.githubusercontent.com/assets/574700/10876043/55563104-8139-11e5-8add-4a95701077f0.png)

**Comment by Naatan** [comment] 2015-11-02 15:20
Note that after restarting in safe-mode Komodo needs to rebuild your codeintel database. Go to Definition will not appear unless codeintel has finished and your language is properly configured.

**Comment by dqd** [comment] 2015-11-03 08:15
I see. And where can I see that the rebuilding of codeintel finished? Anyway, when I set up the executables for the Go language in the safe-mode and open a `.go` file, the codeintel crashes with the following error message:

```
[2015-11-03 08:48:43,031] [ERROR] codeintel.komodo.js: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelService.scan_document]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/codeintel/codeintel.js :: CodeIntel_scan_document :: line 249"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelService.scan_document]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/codeintel/codeintel.js'
+ lineNumber (number) 249
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
viewManager.prototype.'...309 chars
+ location (object) JS frame :: chrome://komodo/content/codeintel/codeintel.js :: CodeIntel_scan_document :: line 249
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/codeintel/codeintel.js'
| + name (string) 'CodeIntel_scan_document'
| + lineNumber (number) 249
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 633
| + formattedStack (string) 'CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
viewManager.prototype.'...309 chars
| + stack
    CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:633:8
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:11
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:19
-- EXCEPTION END --
```

**Comment by Naatan** [comment] 2015-11-03 19:33
Anything else in the log?

**Comment by dqd** [comment] 2015-11-04 07:09
This is the whole log:

```
ERROR:xpcom:Creation of class '<class 'component:koInitService.KoInitService'>' failed!
Exception details follow

ERROR:xpcom:Unhandled exception calling 'int8 * createInstance(in nsISomething, in nsIID &, out retval InterfaceIs *);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/server/factory.py", line 57, in createInstance
    return self.klass()
  File "/opt/komodo/lib/mozilla/components/koInitService.py", line 321, in __init__
    except Exception (e):
NameError: global name 'e' is not defined
[2015-11-04 08:05:54,622] [WARNING] koXMLPrefs: dePickleCache: Can't open file u'/opt/komodo/lib/support/prefs.xmlc'
[2015-11-04 08:05:54,623] [WARNING] koXMLPrefs: the dePickledCache object was None
[2015-11-04 08:05:54,665] [INFO] Startup: Welcome to Komodo Edit 9.3.0 build 16352 (platform linux-x86_64, running on Linux 3.16.0-49-generic version #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015)
[2015-11-04 08:05:54,665] [INFO] Startup: /usr/bin/python built on Thu Oct 22 08:00:05 2015
[2015-11-04 08:05:54,688] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-04 08:05:54,716] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-11-04 08:05:55,023] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-11-04 08:05:55,106] [WARNING] keybindings: [Ctrl+D] was used for 'cmd_addNextWordToCaretSet', overriding to use 'cmd_vim_scrollHalfPageDown'
[2015-11-04 08:05:55,106] [WARNING] keybindings: [Ctrl+U] was used for 'cmd_convertUpperCase', overriding to use 'cmd_vim_scrollHalfPageUp'
[2015-11-04 08:05:55,106] [WARNING] keybindings: [Ctrl+F] was used for 'cmd_startIncrementalSearch', overriding to use 'cmd_vim_pageDown'
[2015-11-04 08:05:55,106] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_vim_pageUp'
[2015-11-04 08:05:55,107] [WARNING] keybindings: [Ctrl+Y] was used for 'cmd_redo', overriding to use 'cmd_vim_lineScrollUp'
[2015-11-04 08:05:55,107] [WARNING] keybindings: [Ctrl+E] was used for 'cmd_endOfWord', overriding to use 'cmd_vim_lineScrollDown'
[2015-11-04 08:05:55,108] [WARNING] keybindings: [Ctrl+V] was used for 'cmd_paste', overriding to use 'cmd_vim_toggleVisualBlockMode'
[2015-11-04 08:05:55,108] [WARNING] keybindings: [Ctrl+R] was used for 'cmd_toolsRunCommand', overriding to use 'cmd_vim_redo'
[2015-11-04 08:05:55,289] [ERROR] koScintillaSchemeService: Scheme Tomorrow_Dark is not writeable
[2015-11-04 08:05:55,289] [WARNING] koScintillaSchemeService: Upgraded scheme u'Tomorrow_Dark' from version 14 to 15.
[2015-11-04 08:05:55,361] [WARNING] koSkin: Detected GTK theme via libgtk: Raleigh
ERROR:xpcom:Unhandled exception calling 'int8 * keys(optional out uint32, out retval Array[]);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koEnviron.py", line 429, in keys
    return self._userEnviron.keys()
AttributeError: 'NoneType' object has no attribute 'keys'
Exception in thread CodeIntel Manager:
Traceback (most recent call last):
  File "/opt/komodo/lib/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1157, in run
    self.init_child()
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 845, in init_child
    self._send_init_requests()
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1074, in _send_init_requests
    self.set_global_environment()
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1085, in set_global_environment
    env = self._global_env.env
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1823, in env
    for name in self.environment.keys())
  File "<XPCOMObject method 'keys'>", line 3, in keys
Exception: 2147500037 (NS_ERROR_FAILURE)

[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-04 08:05:55,912] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-04 08:05:55,913] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-04 08:05:56,099] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///opt/komodo/lib/mozilla/components/koamAddonManager.js:138
[2015-11-04 08:05:57,982] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-04 08:06:01,219] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-04 08:06:01,220] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-04 08:06:01,220] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-04 08:06:03,856] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-04 08:06:38,612] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [koIAppInfoEx.FindExecutables] (2) in chrome://golang/content/pref/pref-golang.js:33
Traceback (most recent call last):
  File "chrome://golang/content/pref/pref-golang.js", line 33, in 

[2015-11-04 08:07:07,332] [WARNING] views: Inconsistent view count in view_closed event
[2015-11-04 08:07:07,373] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-04 08:07:07,373] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-04 08:07:07,373] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-04 08:07:07,374] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-04 08:07:07,374] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-04 08:07:07,374] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-04 08:07:07,374] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-04 08:07:07,374] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-04 08:07:07,422] [WARNING] views: Inconsistent view count in view_opened event
ERROR:xpcom:Unhandled exception calling 'int8 * GetEnvironmentStrings(out uint32, out retval Array[]);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koEnviron.py", line 432, in GetEnvironmentStrings
    self._initialize()
  File "/opt/komodo/lib/mozilla/components/koEnviron.py", line 238, in _initialize
    self._UpdateFromStartupEnv()
  File "/opt/komodo/lib/mozilla/components/koEnviron.py", line 254, in _UpdateFromStartupEnv
    raise RuntimeError("cannot decode startup environment: "
RuntimeError: cannot decode startup environment: `startupEnvironEncoding' is not set
ERROR:xpcom:Unhandled exception calling 'int8 * scan_document(in nsISomething, in int32, in boolean);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 245, in scan_document
    env=buf.env,
  File "/opt/komodo/lib/mozilla/components/koCodeIntel.py", line 1561, in env
    koprocessutils.initialize()
  File "/opt/komodo/lib/mozilla/python/komodo/koprocessutils.py", line 78, in initialize
    for piece in userEnvSvc.GetEnvironmentStrings():
  File "<XPCOMObject method 'GetEnvironmentStrings'>", line 3, in GetEnvironmentStrings
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-11-04 08:07:07,424] [ERROR] codeintel.komodo.js: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelService.scan_document]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/codeintel/codeintel.js :: CodeIntel_scan_document :: line 249"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelService.scan_document]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/codeintel/codeintel.js'
+ lineNumber (number) 249
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
viewManager.prototype.'...309 chars
+ location (object) JS frame :: chrome://komodo/content/codeintel/codeintel.js :: CodeIntel_scan_document :: line 249
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/codeintel/codeintel.js'
| + name (string) 'CodeIntel_scan_document'
| + lineNumber (number) 249
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 633
| + formattedStack (string) 'CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
viewManager.prototype.'...309 chars
| + stack
    CodeIntel_scan_document@chrome://komodo/content/codeintel/codeintel.js:249:12
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:633:8
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:11
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:19
-- EXCEPTION END --
```

**Comment by Naatan** [comment] 2015-11-04 15:56
@mitchell-as assigning this to you, I've had multiple looks at the Go interpreter issue and fixed a few things, but I think this needs a fresh set of eyes and you are by now far more accustomed to codeintel and languages than I am.

**Comment by mitchell-as** [comment] 2015-11-04 17:16
What is more concerning to me right now is that your Komodo user directory is in /opt, which doesn't appear writeable. That may be why codeintel is not functioning properly, as it writes things to the user directory.

**Comment by mitchell-as** [comment] 2015-11-04 17:21
It's possible I'm interpreting the log incorrectly though. I'll look into this more and report back.

**Comment by Naatan** [comment] 2015-11-04 17:53
I only see his install directory mentioned in the log, I see no way of identifying his user directory.

**Comment by tudorels** [comment] 2015-11-07 08:07
I have the same problem with komodo go on windows x64. I use Komodo 9 nightly.
Here is some content from log:
ERROR:xpcom:Unhandled exception calling 'G     int8 * scopestart(out retval int32);'
TypeError: int() argument must be a string or a number, not 'NoneType'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntel.py", line 1261, in handle
    callback(request, response)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\xpcom\components.py", line 268, in wrapperFn
    return fn(*args, **kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntel.py", line 1681, in callback
    handler.done()
  File "<XPCOMObject method 'done'>", line 3, in done
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-11-07 10:04:52,596] [ERROR] codeintel.komodo.KoCodeIntelManager: Error reading data from codeintel
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntel.py", line 1183, in run
    self.handle(response)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\xpcom\components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-11-07 10:04:52,599] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koICodeIntelDefinition.scopestart] (2) in chrome://komodo/content/codeintel/codeintel.js:1313
Traceback (most recent call last):
  File "chrome://komodo/content/codeintel/codeintel.js", line 1313, in 

Exception in thread CodeIntel XPCOM Helper:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntelXPCOMSupport.py", line 60, in run
    mgr.send(command="xpcom-connect", host=host, port=port)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntel.py", line 324, in send
    self.mgr.send(**kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koCodeIntel.py", line 1110, in send
    raise RuntimeError("Manager already shut down")
RuntimeError: Manager already shut down

[2015-11-07 10:04:59,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-07 10:04:59,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-07 10:04:59,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-07 10:04:59,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-07 10:04:59,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-07 10:04:59,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-07 10:04:59,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-07 10:04:59,081] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'

**Comment by Naatan** [comment] 2015-11-13 20:06
Reopening this so that it's integrated to 9.3.2, please do not integrate until 9.3.1 is out the door.

**Comment by mitchell-as** [comment] 2015-11-19 17:29
Merged for 9.3.2 release.

**Closed by mitchell-as** 2015-11-19 17:29 UTC
Labels: Bug, Priority

**Comment by dqd** [comment] 2015-12-11 11:10
I can confirm that the bug has been fixed for me. Thank you very much indeed.

**Comment by tudorels** [comment] 2015-12-11 11:36
Yes, now is working on my computer. Thank you!
