### ISSUE TITLE
Theme is not applied to Help, Check Configuration window

### ISSUE THREAD

**Issue by rrone** [Komodo/KomodoEdit#1521] opened 2016-05-18 10:09 UTC
### Short Summary

The current theme is incorrectly applied to the Check Configuration window

### Steps to Reproduce

With default color scheme, select Check Configuration in Help menu

### Expected results

Able to read it

### Actual results

White font on white window not readable

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* OSX 10.11.4

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![komodo10 issue535](https://cloud.githubusercontent.com/assets/3722760/15355130/e1dfce66-1ca5-11e6-9a94-88b7ca915631.png)

**Comment by mitchell-as** [comment] 2016-05-18 14:41
Thanks for catching this!

**Comment by Naatan** [comment] 2016-05-18 15:31
This is a duplicate of #716

Thanks for reporting :)

**Closed by Naatan** 2016-05-18 15:31 UTC
Labels: New, UX
