### ISSUE TITLE
Flickering issues on OSX

### ISSUE THREAD

**Issue by damienprystay** [Komodo/KomodoEdit#293] opened 2015-05-25 19:12 UTC
*ActiveState Edit:* This issue encompasses any editor/scrollbar flickering issues on OSX.

The contents of the source control diff window (the text and scrollbars) flicker, consistently but irregularly, and often in bursts.

Komodo IDE 9.0.1 on OS X 10.9.5

**Comment by Naatan** [comment] 2015-05-28 15:13
Does this go away when setting your OSX scrollbars to "alwas" show, rather than just when needed?

**Comment by damienprystay** [comment] 2015-05-28 21:16
Nope, I already have them set to always show. (If I change the setting to When Scrolling, the window's scrollbars constantly pulse, but the text still flickers irregularly/at random.)

**Comment by Naatan** [comment] 2015-05-28 21:31
Seen this in some places but am unable to reproduce it consistently. Either way something we'll want to look into. I think it has to do with Todd's fix where he manually forces scintilla refreshes to ensure that it is showing.

**Comment by mitchell-as** [comment] 2015-07-30 20:03
Since we decided to push this back to 9.3, I need to store my notes here when I come back to this in a few weeks.

* I can reproduce this 100% of the time by opening the diff view, the macro properties view, and any other dialog-based view with OSX's scrollbar option set to "when scrolling".
* These dialog-based views are "buffers" (views-buffer.p.xml) as opposed to "editors" (views-editor.p.xml).  It's worth noting that "editors" inherit from "buffers".
* Substituting a "buffer" for an "editor" (e.g. in macro properties dialog) makes the problem go away. This leads me to think the issue has to do with "editors" having something that "buffers" do not have.
* However, substituting an "editor" for a "buffer" (e.g. Komodo's main editor, which is not dialog-based) does not cause the issue 100% of the time. This issue *does not* arise when opening a file from the side pane, open dialog, or macro. The issue *does* arise when loading a file from a previous session and also when switching away from and then back to a file opened from the side pane, open dialog, or macro.
* Right now there there are two possibilities I can think of:
(1) "editors" have some property that "buffers" do not have. While this appears to explain why substitution of "buffers" for "editors" works, it does not explain why "editors" can be substituted for "buffers" on occasion.
(2) When switching between "buffers" or "editors", some code behind the scenes is doing something only to "editors" and not to "buffers". This makes the most sense right now, but does not explain why loading a file from a previous session vs. loading a file from the side pane, open dialog, or macro is different.

Right now investigation is heavily biased towards analyzing the behavior of "buffers" in place of "editors" in Komodo's main editor window. Whenever the cause for the anomalies is found, that will probably not explain why flickering is happening in dialog-based "buffers". However it may shed light on the next step in debugging the problem.

**Comment by dtwist** [comment] 2015-11-19 23:16
Just upgraded to 9.3 and started seeing this issue. Editor screens are flickering pretty rapidly (.3s to 5 seconds apart. Not quite seizure-inducing territory, but not far off. :/ ) I hadn't seen this previously at all. The conditions I'm seeing though don't match those @mitchell-as lists:

- Do not see the issue at all in diff, macro views, color scheme prefs, etc. regardless of MacOS scrolling setting.
- Editor tabs all exhibit the behavior, regardless of how the file is opened: from project sidebar/open dialog/from previous session/tabbing between editors
- In Safe Mode the problem was still present, but not as frequent

I tested with a brand-new OSX User account, to rule out my Komodo profile.

I hope this is helpful.

**System Info**

System Attribute | Value
------------ | -------------
Model Name: | Mac mini
Model Identifier: | Macmini7,1
Processor Name: | Intel Core i7
Processor Speed: | 3 GHz
Number of Processors: | 1
Total Number of Cores: | 2
L2 Cache (per Core): | 256 KB
L3 Cache: | 4 MB
Memory: | 16 GB
System Version: | OS X 10.10.4 (14E46)
Kernel Version: | Darwin 14.4.0

**From Komodo»about:telemetry**
*(This is from my usual account's profile)*

Property  |  Value
------------ | -------------
reason  | gather-payload
OS  | Darwin
appID  | {b1042fb5-9e9c-11db-b107-000d935d3368}
appVersion  | 9.3.0
appName  | Komodo Edit
appBuildID  | 16396
appUpdateChannel  | release
platformBuildID  | 20150911191257
revision  | http://hg.mozilla.org/releases/mozilla-release/rev/32e36869f84a
locale  | en-US
previousBuildID  | 15998
cpucount  | 4
memsize  | 16384
arch  | x86-64
version  | 14.4.0
hasMMX  | true
hasSSE  | true
hasSSE2  | true
hasSSE3  | true
hasSSSE3  | true
hasSSE4A  | false
hasSSE4_1  | true
hasSSE4_2  | true
hasEDSP  | false
hasARMv6  | false
hasARMv7  | false
hasNEON  | false
adapterVendorID  | 0x8086
adapterDeviceID  | 0x a2e
addons  | inspector%40mozilla.org:2.0.14,spacemodo%40activestate.com:1.0,autocode%40xjsfl.com:1.1,emmet%40chikuyonok.ru:1.0.4,NST%40nisza.org:0.63,analytics%40activestate.com:1.0.0,breadcrumbs%40activestate.com:1.0,commando%40activestate.com:1.0,getstarted%40activestate.com:1.0,icomoon%40activestate.com:1.0,iconset_ambiance%40activestate.com:1.0,iconset_blue%40activestate.com:1.0,iconset_classic%40activestate.com:1.0,iconset_cupertino-blue%40activestate.com:1.0,iconset_cupertino%40activestate.com:1.0,iconset_dark%40activestate.com:1.0,iconset_light%40activestate.com:1.0,iconset_orange%40activestate.com:1.0,iconset_radiance%40activestate.com:1.0,iconset_yosemite%40activestate.com:1.0,industrial%40openoffice.org:1.0.0,klint%40dafizilla.sourceforge.net:1.4.0,koextgen%40activestate.com:0.2,komodospellchecker%40ActiveState.com:1.0,markdown-viewer%40activestate.com:0.3,openfiles%40activestate.com:1.0,railstools%40activestate.com:0.3.1,skin_classic%40activestate.com:1.0.1,trackchanges%40activestate.com:1.0,zendframework%40ActiveState.com:0.8,editorconfig%40activestate.com:1.0.1,console%40activestate.com:1.0,fontawesome%40activestate.com:1.0,kopy%40activestate.com:1.0,scope-bookmarks%40activestate.com:1.0,scope-combined%40activestate.com:1.0,scope-commands%40activestate.com:1.0,scope-openfiles%40activestate.com:1.0,scope-tools%40activestate.com:1.0,focusmode%40activestate.com:1.0.2,scope-packages%40activestate.com:1.0,scope-files%40activestate.com:1.0,check-compatibility%40dactyl.googlecode.com:1.3.1,elastic-tabstops%40activestate.com:0.1
flashVersion  | 19.0.0.226

**Comment by cgchoffman** [comment] 2015-11-19 23:32
I'm not able to reproduce this but someone else is seeing it OTRS #030043195

**Comment by mitchell-as** [comment] 2015-11-20 15:43
The fact that it is cropping up in wildly varying circumstances leads me to thinking this is a Mac OSX system issue (widget drawing layer perhaps). I'm really doubtful this is something we can fix on our end.

**Comment by Naatan** [comment] 2015-11-20 16:23
@dtwist can you reproduce it with Help > Troubleshooting > Restart in Safe-Mode?

Also, try following these steps:

http://docs.komodoide.com/Troubleshooting/Komodo-has-weird-graphical-artifacts

**Comment by damienprystay** [comment] 2015-11-20 19:55
Having upgraded to 9.3.1, I'm likewise seeing it in the editor window, now (and still in diff windows). Still occurs in Safe Mode, and with hardware acceleration disabled.

**Comment by Naatan** [comment] 2015-11-20 19:59
Are you saying this started happening when you upgraded to 9.3/9.3.1?

@cgchoffman so we have an in-house reproduction now, could you go by Damien's desk and get a feel for when this happens? Then we can discuss your findings in our daily.

I'm interested primarily in what is triggering the flickers.

@mitchell-as anything you'd want to add?

**Comment by cgchoffman** [comment] 2015-11-20 20:09
There is no indication of whats triggering it.  It's sporadic to say the least.  I cannot reproduce it on my dev machine but I WAS seeing it on Monday.  It no longer occurs though.  I looked over Damiens shoulder for several minutes as he messed with Komodo windows.

**Comment by damienprystay** [comment] 2015-11-20 20:09
Prior to 9.3.1 (I updated from 9.2.1 yesterday), I had the flickering in the diff windows; since upgrading, I now also see it in the editor. It's possible it was there before and I'm only noticing it now due to increased scrutiny, but I would be surprised, as it's fairly eye-catching.

**Comment by Defman21** [comment] 2015-11-20 20:09
>OTRS #030043195 

What is it, @cgchoffman?

**Comment by dtwist** [comment] 2015-11-21 00:45
@mitchell-as Given that I don't see the issue at all with v9.2.1 or earlier, using the same hardware, OS version, user profile, etc. I wouldn't jump to the conclusion it's an unaddressable system issue.

@Naatan Yes, I checked in safe mode. It still happens, but not as frequently (maybe one to ten seconds apart). I also tried it using a fresh user account.

@Naatan Correct, this just started happening with 9.3. I just downloaded the update for 9.3.1 and the behavior persists. Zero hint of the issue in previously installed version (buildID 15998, aka 9.2.1, from the looks of the telemetry data I posted above) or earlier.

**Comment by dtwist** [comment] 2015-11-21 01:02
@Naatan Tried disabling acceleration, per the instructions in your link above. Issue persists.

**Comment by Naatan** [comment] 2015-11-21 06:23
Did either of you use 9.3.0 before upgrading to 9.3.1? Did it occur on that version too?

**Comment by damienprystay** [comment] 2015-11-23 20:13
I didn't use 9.3.0 (seems I was on the wrong update track at the time).

**Comment by dtwist** [comment] 2015-11-30 23:36
@Naatan [Was away for holiday, sorry for delayed reply.] Yes, as I said above, started with 9.3 and still is an issue with 9.3.1

**Comment by Naatan** [comment] 2015-12-01 15:56
Is everyone here using OSX 10.9?

**Comment by cgchoffman** [comment] 2015-12-01 17:11
@damienprystay and I are.

**Comment by mitchell-as** [comment] 2015-12-01 17:29
It appears I was thoroughly confused by this ticket. I thought flickering scroll bars in the diff view was the original problem. The way I see it, there are two issues at play:

(1) Constantly flickering (or "pulsing") scroll bars that always happen (in any view) when OSX's scroll bar behavior is set anything other than "always", and Komodo's skinning of the scrollbars setting is unchecked.
(2) Seemingly random, whole-editor-view, once-per-occurrence flickers that are not triggered by anything.

With regard to (2), which is new to me, I have seen this happen very rarely, not as frequently as others' reports seem to indicate (nowhere near seizure inducing, and nowhere near enough to be annoying). I am on OSX 10.10.2. This is just another data point though, as I'm not an authority.

**Comment by dtwist** [comment] 2015-12-01 20:33
@Naatan I'm on OS X 10.10.4. See my initial comment for detailed system specs.

@mitchell-as Sorry if my joining the thread confused things. This seemed the appropriate bug to comment on, since you had described "text and scrollbars" as flickering. My suspicion was that what I was seeing was a different manifestation of an underlying issue causing the behavior you initially reported with buffers, but that I was now seeing it in the editor windows.

**Comment by mitchell-as** [comment] 2015-12-01 20:39
@dtwist It's not your fault at all :) I was confused from the very beginning...

We have identified the source of the flickering. In attempting to fix #564, I inadvertently caused the main editor views to start flickering. I've reverted that change and we're running a new build that we hope to push out shortly to address that issue.

Flickering in the diff, userscript, rxx, etc. views, which are the original source of this ticket, are caused by an OSX-specific workaround introduced back in Komodo 9.0.0. We aren't sure how to workaround this at the moment. The build we're pushing out addresses the regression that is causing plenty of headaches in the main editor view right now.

Thanks for all of your patience.

**Comment by dtwist** [comment] 2015-12-01 20:47
@Naatan In addition to the system specs above, I'll also mention that I have two 24" monitors attached to this Mini, one via thunderbolt->DP and one via HDMI->DVI adapter. Both are HP LCDs running at 60hz. Full graphics/displays info:
```
Intel Iris:

  Chipset Model:	Intel Iris
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0a2e
  Revision ID:	0x0009
  Displays:
HP ZR24w:
  Resolution:	1200 x 1920
  Pixel Depth:	32-Bit Color (ARGB8888)
  Mirror:	Off
  Online:	Yes
  Rotation:	90
  Connection Type:	DisplayPort
HP ZR24w:
  Resolution:	1920 x 1200
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
```

**Comment by dtwist** [comment] 2015-12-01 20:51
@mitchell-as That's great news. :) Cheers!

**Comment by cgchoffman** [comment] 2015-12-02 00:50
> (1) Constantly flickering (or "pulsing") scroll bars that always happen (in any view) when OSX's scroll bar behavior is set anything other than "always", and Komodo's skinning of the scrollbars setting is unchecked.

Filling this as a new bug btw.

**Comment by KaanErturk** [comment] 2015-12-08 14:20
@Naatan I'm on Mac OS X 10.9.5, using Komodo Edit 9.3.1 (build 16424) and having the flickering issues on editor. I have tried suggestions above and none fixed the issue. Happy to provide more information, if need be. Please feel free to ask.

**Comment by mitchell-as** [comment] 2015-12-08 15:38
Hi, there are nightly builds out that fix the flicker issue in the editor window: http://downloads.activestate.com/Komodo/nightly/

**Comment by KaanErturk** [comment] 2015-12-08 15:50
@mitchell-as Thanks, got the latest one and it looks good.

**Comment by mitchell-as** [comment] 2016-04-27 14:02
@Naatan I'm not seeing this anymore in master due to your handling of scrollbars in the new UI. Can you confirm? Just make sure your OSX scrollbar setting (in OSX preferences) is set to something other than "always" and right-click > properties on a long userscript that needs scrolling. You shouldn't see any flickering, native scrollbars.

**Comment by Naatan** [comment] 2016-04-27 14:53
I'm still seeing it in some places. I'm going to try and force skinned scrollbars to see if that solves it.

**Closed** 2016-04-28 21:01 UTC
Labels: Bug, New, OSX Only, Priority
