### ISSUE TITLE
Wrong cursor on Projects title

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1520] opened 2016-05-18 09:14 UTC
When the projects pane is at the very bottom and only the Title "Projects", the Wheel and the Triangle is shown (no contents below, probably minimized state or whatever):
- when mouse hoovers over the title it shows an "Up-Down-Arrow" (Resize vertically Mouse pointer). Unfortunately pressing and pushing up does not show the pane.
- Double-Clicking shows the pane and then, the resizing works.

- If you resize the pane to the minimized position, it looks like in the upper state, but resizing works now.

Quite funny, you never know if double-click or click and pull will show the pane.

Other points:
- The sliders are nearly invisible, but better than in 9, as they are larger now. They still don't support all slider modes as traditional sliders with buttons etc.
- How may I remove the pane on the very-left side with the Icons and Triangles I never use ?
- The search pane got back stable focus, great!!! This was really anoying in 9

**Comment by lagbox** [comment] 2016-05-18 12:58
>How may I remove the pane on the very-left side with the Icons and Triangles I never use ?

Right click on the left side toolbar -> Customize -> Look for "Show Side Toolbar"

**Comment by oehhar** [comment] 2016-05-18 13:04
> Right click on the left side toolbar -> Customize -> Look for "Show Side Toolbar"
Thank you. Indeed, this option was covered as my main window was not wide enough.
Thanks, Harald

**Comment by mitchell-as** [comment] 2016-05-18 14:40
I'm going to mark this as a duplicate of #1483 as the points raised are very similar.

**Closed by mitchell-as** 2016-05-18 14:40 UTC
