### ISSUE TITLE
Using interpolation %L in Debug Print Statements gets the wrong line

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3182] opened 2017-09-28 23:02 UTC
### Short Summary

The print statement is always placed on the line below the clicked line so the line used for the print is one above the print state.

### Steps to Reproduce

Open a JS file
Edit the Toolbox > Print DEbugging > javascript print Statement snippet to add the `current line` interpolation; `[[%L]] `
Trigger the print statement by `Ctrl+click`ing the editor left gutter, to the left of the line numbers

### Expected results

Print statement with the correct line

### Actual results

**EDIT** Print statement with `Line -1`

**Comment by Naatan** [comment] 2017-09-29 15:34
It shows the line the print statement is on right?

This is by design then, that is in fact the line the snippet is invoked on. Fixing this would require the new print debugging tool, which is scheduled for 11.1.

**Comment by cgchoffman** [comment] 2017-09-29 16:04
Oops I meant `line - 1`.

**Comment by Naatan** [comment] 2017-09-29 16:08
I see. Well in that case wouldn't this actually be more desirable? It's showing you the line number you clicked on. Why would you want to print the line number your print statement is on, that's not the actionable code you're interested in.

**Comment by cgchoffman** [comment] 2017-09-29 16:24
The way I use the print statements, I want it to print the line the print statement is at.  I don't care about the line I clicked on, it's just the only way to put the print state in the file so I click on a line.  The code I'm actually interested in is posted into the print statement by me using tabstops.  Essentially, I want the print statement NOT to move one line down, I want it to push everything below it.

**Comment by Naatan** [comment] 2017-09-29 16:27
I think we should consider both these use cases for when we do the print debugging tool for 11.1, both seem like they have value.

Closing this as the underlying "issue" is the new print debugging tool.

**Closed by Naatan** 2017-09-29 16:27 UTC
Labels: Introduced: 11, Type: Bug

**Comment by cgchoffman** [comment] 2017-09-29 16:29
Ok but where is the new printing tool being tracked so this point can be added?

**Comment by Naatan** [comment] 2017-09-29 16:45
https://github.com/Komodo/KomodoEdit/issues/2966

**Comment by cgchoffman** [comment] 2017-09-29 16:56
Thank you
