### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by ginko** [Komodo/KomodoEdit#1993] opened 2016-09-02 18:08 UTC
### Short Summary
When I highlight a function or a class in my ruby code and select Go To Definition nothing happens.

### Steps to Reproduce

**Dev Edit:** See minimal reproduction steps here : https://github.com/Komodo/KomodoEdit/issues/1993#issuecomment-244464217

I have an initializer file in my rails app's initializers folder that contains the definition

```
COMPUTE_REGIONS = YAML::load_file(Rails.root.join('config', 'regions.yml'))[Rails.env]
```

COMPUTE_REGIONS is declared in an erb template file the view directory of the app 

```
 <div class='control-group' id="stage_region_group">
  <%= label :stage, :region, 'Amazon Region', :class => 'control-label' %>
  <div class='controls'>
    <%= select(:stage, :region, regions_list_pretty[COMPUTE_REGIONS['default_account']], {}, { "disabled" => !@stage.new_record?, :class => 'wide_box' }) %>
  </div>
</div>
```

### Expected results

When I highlight the COMPUTE_REGIONS and right click or select Go To Definition from the menu it should take me to the file that contains that declaration (in this case the file I mentioned above in the initializers directory.) I used sublime text 3 before purchasing komodo and had no issues with this at all.

### Actual results
nothing happens. Looking at the log it just states no definition found

### Platform Information

*Komodo Edit or IDE?* 
Komodo IDE, version 10.1.0, build 89455, platform macosx. Built on Mon Aug 22 09:05:23 2016.
*Komodo Version?* 
version 10.1.0
*Operating System (and version)?* 
mac OS X 10.11.6

### Additional Information

<img width="1414" alt="screen shot 2016-09-02 at 1 51 13 pm" src="https://cloud.githubusercontent.com/assets/183611/18213526/b3898096-7116-11e6-86b8-2a3b269dba45.png">

**Comment by Naatan** [comment] 2016-09-02 18:36
How is COMPUTE_REGIONS being passed to your erb file?

Note that Sublime does a lot of guessing when it comes to this type of stuff, whereas Komodo does no guessing. It inspects your code exactly as its written and tries to provide intelligent codeintel. If it cannot interpret your code properly then codeintel will not work. This seems to be what is happening here. We'll want to find out what you're doing in your code in order to address it.

**Comment by ginko** [comment] 2016-09-02 18:49
It's passed through an initializer (which is part of the rails framework) 
COMPUTE_REGIONS = YAML::load_file(Rails.root.join('config', 'regions.yml'))[Rails.env]. Also I used rubymine from JetBrains and I have no issues with that IDE. It finds the origin of the file fine. I'm not sure what you mean by guessing in reference to sublime text 3. It works great so I'm not sure you are correct in your assumption.

**Comment by Naatan** [comment] 2016-09-02 18:53
You can correctly guess something and it'd still be guessing. Let's focus on Komodo though, whether something works elsewhere has no relevance.

Could you provide a minimal example of the file which contains the `COMPUTE_REGIONS` definition? We'll need to be able to reprocuce the problem in order to address it.

**Comment by ginko** [comment] 2016-09-02 19:06
Sorry, did not mean to get pesky. I have a file called regions.rb in the config/initializers in the rails app that contains COMPUTE_REGIONS = YAML::load_file(Rails.root.join('config', 'regions.yml'))[Rails.env]
it makes that regions.yml file with configuration available for usage at runtime.

**Comment by Naatan** [comment] 2016-09-02 19:16
Ok I made a minor test case:

**test.rb:**

```
require 'erb'

COMPUTE_REGIONS = "foo"

template = ERB.new File.read("test.erb")
puts template.result()
```

**test.erb**:

```
<div>
  <%= COMPUTE_REGIONS %>
</div>
```

Calling Go to def on `COMPUTE_REGIONS` in test.erb does nothing.

@mitchell-as I guess what might be the problem is we don't consider erb as Ruby files? Which technically they both are and aren't. Is this an easy fix?

**Comment by ginko** [comment] 2016-09-02 19:29
Here is another example and this is not an erb file but rb. The rubymine lookup works but komodo can't find it. See screenshots
<img width="1434" alt="ruby-mine" src="https://cloud.githubusercontent.com/assets/183611/18215963/f620c4fe-7121-11e6-80df-320d893c938f.png">

<img width="1430" alt="komodo" src="https://cloud.githubusercontent.com/assets/183611/18215969/fd0e7540-7121-11e6-8151-5897612d759a.png">

**Comment by Naatan** [comment] 2016-09-02 19:35
Thanks @ginko. Removed the rubymine screenshot though, again lets keep this on topic. We have no affiliation with them.

**Comment by mitchell-as** [comment] 2016-09-02 19:37
@Naatan I'm not certain, but since `test.erb` isn't "linked" to `test.rb` (from a static analysis point of view), codeintel doesn't really know to look inside `test.rb` for a possible definition.

**Comment by Defman21** [comment] 2016-09-02 19:41
But it's linked to global scope, isn't it?

Something like 

```
test.rb: define COMPUTE_REGIONS in global scope
global scope:
COMPUTE_REGIONS (file: test.rb, line: 3)
test.erb: look up for COMPUTE_REGIONS in * scope
local scope: nil
global scope: COMPUTE_REGIONS in test.rb on line 3
```

**Comment by mitchell-as** [comment] 2016-09-02 20:44
I don't know what you posted @Defman21 :(

**Comment by Defman21** [comment] 2016-09-02 21:31
Yeah it's kinda complicated but I'll try to clarify that.

Nathan's example defined COMPUTE_REGIONS variable in global scope (outside of any functions, classes, etc.), so I assume Komodo puts it somewhere.

Whenever you're trying to perform goto jump, CodeIntel should look for a symbol. Since you've declared the variable in global scope, I assume it can be easily accessed from anywhere. But I may be wrong because I don't know how CodeIntel keep variables (if it, of course, keep variables and don't interpolate them dynamically each time you want to do a goto jump).

**Comment by Naatan** [comment] 2016-09-02 21:35
@Defman21 it's irrelevant if there is no static link between the files. Komodo has no awareness of test.rb even looking at test.erb

The File.read is the only reference, and that's not something static analysis would look at as File.read doesn't imply it's executing dependant code.

We're discussing this internally, seeing what's possible/feasible.

**Comment by Defman21** [comment] 2016-09-02 21:37
@Naatan ah, thanks for clarifying that.

**Comment by ginko** [comment] 2016-09-06 14:49
Gents, I noticed that this has been marked for milestone 11. Does this mean that the problem will not be addressed in the short-term and potentially only be in fixed for version 11?

**Comment by Naatan** [comment] 2016-09-06 15:26
Correct, this will likely fall into a bigger codeintel rework.

**Comment by ginko** [comment] 2016-09-06 15:35
Ok whom do I speak to to get a refund?

On Tuesday, September 6, 2016, Nathan Rijksen <notifications@github.com>
wrote:
> Correct, this will likely fall into a bigger codeintel rework.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/yl5XSU-WKNEHHa6Mi93GXIYXlEyUamT6ZJmCoOAUa8kCFwG0QtINuuOE9oQyZlT9IPNdg5QLW_FY91L0p3e6zvTLrJ5R8QeXhgN6nNtD8d-9RqF1yiPI7IhXxLhGIDphtZUvcXZ5ySjSULYef_IuK-7LZXVnjw=s0-d-e1-ft#https://github.com/notifications/beacon/AALNOwAOAskDjV6-W5dP1ynzWsXov6VQks5qnYY5gaJpZM4Jz9Df.gif>

**Comment by Naatan** [comment] 2016-09-06 16:00
You can email sales@activestate.com

**Comment by ginko** [comment] 2016-09-06 16:02
Will do. Thank you.

**Comment by mitchell-as** [comment] 2016-09-27 19:01
After internal discussion, we should be able to support intelligent "guessing" for queries like these once the scheduled architecture changes are complete. I'm going to close this ticket since we're tracking the umbrella issue internally.

**Closed by mitchell-as** 2016-09-27 19:01 UTC
Labels: Pending: Internal

**Comment by ginko** [comment] 2017-10-18 14:19
I originally started this thread because Komodo 10 had some issues getting the "Go to Definition" in my ruby on rails app. It was suggested that this would be fixed in Komodo 11.  I downloaded 11 and tried but I'm having the same problem. Has this really been fixed or is it still in the works?

**Comment by Naatan** [comment] 2017-10-18 14:36
Komodo 11.0 currently has a go to definition bug which will be fixed in 11.0.1 (nightly available here: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/).

The "guessing" mechanic did not make it into 11.0, but will likely be in 11.1.

**Comment by ginko** [comment] 2017-10-18 16:09
Naatan, I just downloaded the 11.0.1 build. Not sure but I'm still getting the " Could not find definition " Message. What am I not doing right?
<img width="1389" alt="screen shot 2017-10-18 at 12 07 59 pm" src="https://user-images.githubusercontent.com/183611/31729498-264aae00-b3fd-11e7-9378-a715c6cf5e63.png">

**Comment by Naatan** [comment] 2017-10-18 16:55
Hard to say without having reproduction code. Can you share the code in question, or equivalent code that reproduces your issue?

**Comment by ginko** [comment] 2017-10-18 17:10
I have the method below residing the app/controllers/alarms_controller.rb. 
```def display_config
    respond_to do |format|
      format.json { render(json: ALARMS_CONFIG) }
    end
  end
```

ALARMS_CONFIG lives in an initializer config/initializer/alarms.rb

```ALARMS_CONFIG = YAML.load_file(Rails.root.join('config', 'alarms.yml'))[Rails.env] || {}```

I guess what I'm trying to do is highlight ALARMS_CONFIG in the controller method and hit "Go To Definition". My understanding is that this action should take you to the file containing that ALARMS_CONFIG variable. Am I wrong?

**Comment by Naatan** [comment] 2017-10-18 17:14
How is alarms.rb being included?

**Comment by ginko** [comment] 2017-10-18 17:17
All initializers are included automatically. It's part of the rails framework.

**Comment by mitchell-as** [comment] 2017-10-18 17:18
I'd guess it's not being included explicitly. Like PHP, stuff is automagically imported.

**Comment by Naatan** [comment] 2017-10-18 17:52
Bah, so we need to do the same thing with Ruby?

**Comment by mitchell-as** [comment] 2017-10-18 17:54
Yes, but just for Rails. And maybe only for particular Rails files.

**Comment by ginko** [comment] 2017-10-18 17:58
Sorry to bring this up but I'm experiencing this issue with all files in my project and not only serializers.

**Comment by mitchell-as** [comment] 2017-10-18 18:00
Sorry, but this will not work until 11.1 at the earliest.

**Comment by ginko** [comment] 2017-10-18 18:01
I understand. I will be back then :-)

**Comment by ginko** [comment] 2018-01-08 19:07
Hello, has someone made a note of the above problem and is it being tracked somewhere? I'm asking because this issue seems to be closed.  Thanks again.

**Comment by Naatan** [comment] 2018-01-08 21:01
Since the solution to this problem entails a "feature" of sorts it is not tracked on github. Rest assured we are tracking it internally. In fact we have a working version of this feature for our internal nightlies.

**Comment by ginko** [comment] 2018-01-09 17:31
Would you mind letting me know when it actually makes the cut for a public release? Thanks a million.

**Comment by Naatan** [comment] 2018-01-09 18:55
Komodo will notify you when the release is out. Sorry I cannot follow up individually, that'd be a slippery slope for me ;) I can tell you it's not due "soon", we still have some work to put into the next big version (11.1).

**Comment by ginko** [comment] 2018-10-16 18:18
Hello, has the above feature been implemented in the 11.1 version of Komodo?

**Comment by ginko** [comment] 2018-10-19 00:47
Can anyone answer my question above? I was considering getting this editor and I have waited for the fix/feature mentioned in the this thread for quite awhile but I'm now loosing hope this will ever get fixed. It's really a shame.

**Comment by Naatan** [comment] 2018-10-22 15:23
Hi, 11.1 is currently the latest version, unfortunately the guessing mechanic did not make it in. That might follow in 11.2.

Please note this issue is closed, you could either open a new issue or post about your question on our forums.
