### ISSUE TITLE
Lower pane size spanning the whole width of the screen? is it possible to have a window arrangement similar to Komodo 8?

### ISSUE THREAD

**Issue by jjarava** [Komodo/KomodoEdit#405] opened 2015-07-08 14:53 UTC
Hi!

I'm trying to get the panes set up in a similar way to the "default" in Komodo 8, where the lower pane stretched from side to side.. That's where the interactive python console "lives" and it benefits from having as much width as possible.

But although I can move "things" between panes, and change the width of the sides ones, it doesn't appear to be possible to basically change their "relationship".

This is the kind of "layout" I'm looking for (Komodo 8):

![komodo-8-pane-arrangement-2015-07-08_16-31-28](https://cloud.githubusercontent.com/assets/2682444/8573379/8508e346-2591-11e5-99c1-d2f6d245ae63.jpg)

But the Komodo 9 "pane" editor won't let me change the relationship between the side and lower pane:

![komodo-9-pane-editor-2015-07-08_16-44-37](https://cloud.githubusercontent.com/assets/2682444/8573424/bbf639f8-2591-11e5-8333-06cda14b2546.jpg)

So finally what I get is something like this:

![komodo-9-pane-arrangement-2015-07-08_16-31-33](https://cloud.githubusercontent.com/assets/2682444/8573292/2d4afb08-2591-11e5-8698-bbc3e8ee3079.jpg)

**Comment by cgchoffman** [comment] 2015-07-08 15:27
hi @jjarava, this new design is, well, by design.  If you would like to ask for assistance in changing the layout please ask in the [forums](forum.komodoide.com).  Closing as this is not a bug. 

...Time passes...

Oh i found the forum post about this: http://forum.komodoide.com/t/how-to-change-the-debugger-pane-layout/1203

**Closed by cgchoffman** 2015-07-08 15:27 UTC
Labels: By Design
