### ISSUE TITLE
Ruby Interactive Shell don't show output

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1396] opened 2016-05-05 17:52 UTC
### Short Summary

In `irb` (default REPL for ruby), if I type `p 1`, I'll get this:
```
2.3.0 :001 > p 1
1
 => 1 
```

In Komodo Interactive Shell if I type the same `p 1`, I won't get anything.

![Imgur](http://i.imgur.com/fxQynqx.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 beta
*Operating System (and version)?* Ubuntu 16.04 /w Openbox
**Ruby version:** ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
**IRb version:** irb 0.9.6(09/06/30)

**Comment by mitchell-as** [comment] 2016-05-05 18:08
I cannot reproduce this. `p 1` prints and returns 1. However, I have Ruby 2.2 installed.

**Comment by Defman21** [comment] 2016-05-05 18:15
I have the one from rvm.

**Comment by Naatan** [comment] 2016-05-05 18:15
Reproduced on Ruby 2.3

**Comment by Defman21** [comment] 2016-05-05 18:16
The second priority label on my issues for K10! Ha-ha

**Comment by Naatan** [comment] 2016-05-05 18:16
So close!

**Comment by mitchell-as** [comment] 2016-05-05 18:35
Note: this affects Ruby 2.x debugging's interactive prompt. I cannot get anything from it. I'd consider elevating this to blocker, but it's @Naatan's call.

**Comment by Naatan** [comment] 2016-05-05 18:48
Effectively that means it only affects the Ruby 2.3 REPL though, no?

**Comment by mitchell-as** [comment] 2016-05-05 18:56
Yes, after internal discussion I agree that this should remain priority and not be elevated.

**Comment by mitchell-as** [comment] 2016-05-05 20:58
Fixed via https://github.com/Komodo/KomodoIDE/commit/2967cbf511b656283ea917753e7cf9db53e21c1c

**Closed by mitchell-as** 2016-05-05 20:58 UTC
Labels: Bug, Priority
