### ISSUE TITLE
hide toolbars not persisting

### ISSUE THREAD

**Issue by sgperkins** [Komodo/KomodoEdit#1616] opened 2016-05-27 06:43 UTC
### Short Summary
I hide the syntax checker and launch in browser toolbars but they reappear when I close and relaunch komodo edit

### Steps to Reproduce
click customise. click the 'eye' icon to hide the toolbars. exit komodo. relaunch komodo and presto! they're back !

### Expected results
remain hidden

### Actual results

don't 

### Platform Information

*Komodo Edit or IDE?* edit
*Komodo Version?* 10
*Operating System (and version)?* linux mint 17.3

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment] 2016-05-27 14:31
Thanks for the report. Related to #1482.

**Comment by Naatan** [comment] 2016-05-27 15:07
This is a duplicate of #1482 in fact, as there is no option to hide the individual sidebar buttons.

**Closed by Naatan** 2016-05-27 15:07 UTC
Labels: Bug, New
