### ISSUE TITLE
Elastic Tabstops slows down Komodo significantly when used on large files

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3307] opened 2017-10-19 19:11 UTC
Reference: http://otrs.activestate.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=68181#

If you open a file with a few thousand lines editing is fast at the top, but extremely slow towards the bottom. Notepad++ which also uses Scintilla and supports Elastic Tabstops does not have this problem, so it does not appear that it is an inherent problem with ET.

**Comment by mitchell-as** [comment] 2017-10-19 20:08
Duplicate of #2329

**Closed by mitchell-as** 2017-10-19 20:08 UTC
Labels: Type: Bug
