### ISSUE TITLE
Komodo regains focus after save

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#1331] opened 2016-04-29 12:56 UTC
### Short Summary

It seems if you save, then change to another window quickly Komodo will regain focus.
### Steps to Reproduce

This is happening for me in my profile and in safe mode.

Use Commando's File Scope to open a file.
Save any file you have open.
Change focus to any other application, or change desktops.
Komodo regains focus within 0.5-1 second.

**Update:**
If I activate Commando File Scope via key bindings, even without selecting or opening a file from it, this issue occurs from that point.
### Expected results

For Komodo to not regain focus after focus has been given to something else.
### Actual results

Komodo will regain focus.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10 Alpha build 88986
_Operating System (and version)?_ Ubuntu 15.10

**Comment by mitchell-as** [comment] 2016-04-29 14:20
Sadly, I'm not fast enough of a ninja to trigger this.

The thing that comes to mind is an "after-save" action that takes a while to complete. When it does, Komodo refocuses on something.

Can you reproduce this in safe mode? (Help > Troubleshooting > Restart in Safe Mode)

**Comment by lagbox** [comment] 2016-04-29 14:56
Doesn't appear that I can reproduce in safe mode.

**Comment by lagbox** [comment] 2016-04-29 14:58
Now that I am back in regular mode, it seems it isn't happening any more, so far.

**Comment by Naatan** [comment] 2016-04-29 15:01
I'll close this for now then, let us know if it happens again.

**Comment by lagbox** [comment] 2016-04-29 15:57
Started happening again, while in regular operation.

**Comment by lagbox** [comment] 2016-04-29 18:00
Updated with a method that I can reproduce consistently after opening a project.

**Comment by Defman21** [comment] 2016-04-29 18:12
Reproduced. You have about 500-1000ms after saving a file to do alt-tab.

**Comment by Defman21** [comment] 2016-04-29 18:17
And just saying - you don't have to modify it, so I don't know why Komodo still doing save operation if there were no changes made.

**Comment by cgchoffman** [comment] 2016-04-29 18:32
I can't reproduce this on Windows.  I'm hitting Alt+Tab in less than 1 second for sure.

**Comment by cgchoffman** [comment] 2016-04-29 18:33
> you don't have to modify it

@Defman21 are you saying you have the issue with a clean profile?

**Comment by Defman21** [comment] 2016-04-29 18:53
Yeah.

**Comment by Naatan** [comment] 2016-04-30 00:05
> And just saying - you don't have to modify it, so I don't know why Komodo still doing save operation if there were no changes made.

A save is a save. If you don't modify it it's equivalent to touching the file. I don't like apps that try to be smarter than they need to be.

On topic - I still cannot reproduce this. Maybe it's a Ubuntu thing? @mitchell-as do the new steps above work for you?

**Comment by lagbox** [comment] 2016-04-30 08:29
I have limited this to the use of selecting a file to open via Commando's File Scope, even without using bindings to open it or using enter to select it. Just using it to open the file, from that point on this happens.   I will update the steps again, to remove the unneeded steps to reproduce.

**Comment by robclancy** [comment] 2016-04-30 08:54
This happens for me on Arch Linux with i3.

**Comment by mitchell-as** [comment] 2016-05-02 14:58
@Naatan I still cannot reproduce this, even with the updated steps. I am using a clean profile.

1. I open a project.
2. I use commando to open a file in that project.
3. I type space and backspace, save, and immediately Alt+Tab.
4. Komodo stays in the background.
5. I go back to Komodo, open another file via commando, go back to the first file, save, and Alt+Tab.
6. Again, nothing; Komodo stays in the background.

This is on Ubuntu 14.04.

**Comment by Naatan** [comment] 2016-05-02 15:07
@robclancy @lagbox have you guys had this issue on a clean profile (in safe mode)?

**Comment by lagbox** [comment] 2016-05-02 15:07
yes I can reproduce in safe mode.

**Comment by Naatan** [comment] 2016-05-02 15:13
Does the timing of the file open and the method to open the file play into this?

**Comment by robclancy** [comment] 2016-05-02 15:30
I have been using komodo for a while today and avoiding commando and it never happened. Right after using commando to open a file it happens and for me you don't even need to be very fast to make it happen. And the file doesn't need to change at all. Also it doesn't just regain focus once it tries to refocus during the time of it happening. So if I am fast enough to change again after it regains focus the first time it will steal it back again.

Since I have some performance issues sometimes and this issue lasts longer for me I would guess that those with no performance issues also on a fast computer simply can't do it fast enough to trigger the issue which is why you are having trouble reproducing it.

**Comment by lagbox** [comment] 2016-05-02 15:31
I have isolated it to Command File Scope to open any file. From that point on, this issue happens.

**Comment by Naatan** [comment] 2016-05-02 16:27
> Also it doesn't just regain focus once it tries to refocus during the time of it happening. So if I am fast enough to change again after it regains focus the first time it will steal it back again.

That gave me what I needed. Thanks!

**Comment by lagbox** [comment] 2016-05-06 17:12
This is still present in 10.0.0-beta1, build 89095

**Comment by Naatan** [comment] 2016-05-06 18:28
I don't think it's commando related then. Wish I could repro :\

**Comment by lagbox** [comment] 2016-05-06 18:37
I can reproduce in safe-mode and in my profile. Ill play with it more to see if I can come up with alternate steps.

**Comment by robclancy** [comment] 2016-05-06 18:56
It's fixed for me so far, tried steps I did before to make it work and it doesn't happen.

**Comment by lagbox** [comment] 2016-05-06 19:05
Its still there for me with my profile if I just load Command File Scope, the problem exists after that point.
In safe-mode, I am opening a project, opening a file from the places, then using the file scope to open any file. After that this happens for me.

**Comment by robclancy** [comment] 2016-05-06 19:16
I was just able to reproduce. My settings had changed so the same steps were actually slightly different. I guess I hadn't noticed it before because not used the Command File Scope.

**Comment by Naatan** [comment] 2016-05-06 19:43
Are you getting this on Komodo 9 also?

**Comment by robclancy** [comment] 2016-05-06 19:50
Yes. It only triggers if I use a bind to go to Command File Scope. I couldn't reproduce until I add the bind. Using everything scope and going to files then open never caused it to happen.

**Comment by lagbox** [comment] 2016-05-06 20:00
In 9.3 with my profile I can't reproduce via the File Scope in Commando. I will play with some alternate methods and in safe-mode to confirm.

**Comment by lagbox** [comment] 2016-05-06 20:06
I can reproduce on 9.3 when using the File Scope via bindings to open a file. After that point it will steal focus back after a save.

**Comment by lagbox** [comment] 2016-09-26 23:08
Present on latest.

Komodo IDE, version 10.1.1, build 89474, platform linux-x86_64.
Built on Thu Sep 1 14:52:01 2016.

**Closed** 2016-11-15 23:20 UTC
Labels: Bug, Bug: New

**Comment by lagbox** [comment] 2016-11-15 23:25
Thanks for looking and putting in the time guys. I appreciate it. :)

**Comment by Naatan** [comment] 2016-11-16 01:21
Thanks for helping me look :)
