### ISSUE TITLE
Cannot remove 'Rails Tools' from the toolbox

### ISSUE THREAD

**Issue by sgeard** [Komodo/KomodoEdit#1580] opened 2016-05-22 09:02 UTC
### Short Summary
'Rails Tools' in the toolbox cannot be deleted. Since I never use Ruby anything I don't want this to be cluttering up the toolbox.

### Steps to Reproduce
Open K IDE, go to the toolbox, try to delete the 'Rails Tools' entry from the menu popup.

### Expected results
The 'Rails Tools' entry should be removed

### Actual results
A dialogue saying it can't be deleted.

### Platform Information

*Komodo IDE
*Komodo Version X
*Operating System (and version) Linux x64

### Additional Information
The same bug existed in Komodo 9 IDE

**Comment by mitchell-as** [comment] 2016-05-23 14:56
Thanks for the report. @cgchoffman I'm not sure if this is a regression or not. Feel free to tag it based on what you think/find.

**Comment by Defman21** [comment] 2016-05-23 15:13
@mitchell-as dupe of #1078

**Comment by Defman21** [comment] 2016-05-23 15:24
@mitchell-as dupe of #1078

**Comment by mitchell-as** [comment] 2016-05-23 15:37
So it is, thanks!

**Closed by mitchell-as** 2016-05-23 15:37 UTC
Labels: Bug
