### ISSUE TITLE
Some graphic relics...

### ISSUE THREAD

**Issue by ffurger** [Komodo/KomodoEdit#3250] opened 2017-10-06 12:03 UTC
### Graphic glitches...

I have just started playing around with Komodo IDE 11, here are some fairly minor issues I have encountered

### Steps to Reproduce

1. Check boxes: Most check boxes in the Preferences menu look fine, but a few seem to have been forgotten. Screenshot 1 shows the ok ones, screenshot 2 and 3 the hell-of-a-ugly-ones. There may be more, but those are the ones I have found so far.

2. Scroll bar in the left-hand column: Is it really necessary to extend a selection beyond the scrolling area? It just looks terrible. See screenshot 4.

3. Check boxes or radio buttons or both? See screenshot 5. I really don't see a need for changing how selected radio-buttons look like. Every since html 1, a selected radio button has a small black circle in it, not a check mark!

### Platform Information

*Komodo IDE 
v 11.0
Mac OS High Sierra 

<img width="504" alt="screenshot 1" src="https://user-images.githubusercontent.com/30805047/31276949-d05b015a-aa9e-11e7-9c28-2ba99a762400.png">
<img width="422" alt="screenshot 2" src="https://user-images.githubusercontent.com/30805047/31276952-d087b984-aa9e-11e7-9704-5480010a9921.png">
<img width="225" alt="screenshot 3" src="https://user-images.githubusercontent.com/30805047/31276953-d08809c0-aa9e-11e7-8e6a-cd3f07ed9359.png">
<img width="256" alt="screenshot 4" src="https://user-images.githubusercontent.com/30805047/31276951-d0827bfe-aa9e-11e7-9622-8a4572710b6e.png">
<img width="444" alt="screenshot 5" src="https://user-images.githubusercontent.com/30805047/31276954-d08f5860-aa9e-11e7-894a-bd43fc1fab28.png">

**Comment by Naatan** [comment] 2017-10-06 14:51
Hi @ffurger, the checkbox issue has been fixed on master, you can test this fix in our latest nightly:

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

As for the scrollbar, this is by design. We have had some suggestions on this and might be looking into some changes in the future, but for now this is what it is and is not considered a bug.

As for the radiobox, this is highly subjective and frankly I don't really see this being significant enough to consider actionable. I appreciate you hold your own set of preferences, but at the end of the day we cannot please everyone with every single decision.

**Closed by Naatan** 2017-10-06 14:51 UTC

**Comment by ffurger** [comment] 2017-10-06 17:38
Hi Nathan,

I appreciate your not being in a position to fulfil all wishes, that’s perfectly reasonable. In this case however, I simply don’t understand the rationale for deviating from a well-established design standard, one that has been around for may be 20 years. So this is hardly my personal wish. 

The same is true for the scroll bars. I don’t think you’ll find anywhere on the web scroll bars implemented that way. Again, there may be good reasons for taking a different road, but in this case I personally  don’t see any. The more so, as all other scroll bars in Komodo IDE are implemented in the traditional way. Personally, I tend to stick with well-established design expectations, unless there really is something to be gained from taking a different approach.

In any event, thank you for getting back on this, I really appreciate it.

Best,
Franco

**Comment by Naatan** [comment] 2017-10-06 19:07
> In this case however, I simply don’t understand the rationale for deviating from a well-established design standard, one that has been around for may be 20 years. So this is hardly my personal wish.

We're talking about a dot in a circle versus a checkmark. I'm not disagreeing that the dot seems well established, I'm simply saying that this is very insignificant in my mind. I'd be happy to accept a PR for this but I'd rather have us focused on bugs and enhancements that have significant value.

> The same is true for the scroll bars. I don’t think you’ll find anywhere on the web scroll bars implemented that way. Again, there may be good reasons for taking a different road, but in this case I personally  don’t see any. The more so, as all other scroll bars in Komodo IDE are implemented in the traditional way. 

The reasoning is we don't want scrollbars to show when you do not need them, nor their space to be reserved. Komodo has a lot of panels and widgets, and having all scrollbars on screen at all times is very awkward. Like I said though, we're looking into ways of improving this, such as only reserving the space if a scrollbar is required.

Floating scrollbars is hardly a new concept though, have a look at macOS and Gnome.

**Comment by ffurger** [comment] 2017-10-06 19:31
> On 6 Oct 2017, at 21:07, Nathan Rijksen <notifications@github.com> wrote:
> 
> In this case however, I simply don’t understand the rationale for deviating from a well-established design standard, one that has been around for may be 20 years. So this is hardly my personal wish.
> 
> We're talking about a dot in a circle versus a checkmark. I'm not disagreeing that the dot seems well established, I'm simply saying that this is very insignificant in my mind. I'd be happy to accept a PR for this but I'd rather have us focused on bugs and enhancements that have significant value.
> 
I fully agree with you on this. I simpy was wondering why you would change the look of a radio box, as such a change requires additional work, or so I would think. And from a usability standpoint it tends to blurry the difference between a checkbox and a radio button. But I’ll admit it is a detail. I am a bit of a stickler for such details, so things like that tend to jump to my eyes.

> The same is true for the scroll bars. I don’t think you’ll find anywhere on the web scroll bars implemented that way. Again, there may be good reasons for taking a different road, but in this case I personally don’t see any. The more so, as all other scroll bars in Komodo IDE are implemented in the traditional way.
> 
> The reasoning is we don't want scrollbars to show when you do not need them, nor their space to be reserved. Komodo has a lot of panels and widgets, and having all scrollbars on screen at all times is very awkward. Like I said though, we're looking into ways of improving this, such as only reserving the space if a scrollbar is required.
> 
> Floating scrollbars is hardly a new concept though, have a look at macOS and Gnome.
> 
Mmh, I am beginning to think that we are not talking about the same thing here. See the screenshot attached for a clarification.

.

**Comment by Naatan** [comment] 2017-10-06 19:52
I can't tell from what you said why we wouldn't be talking about the same thing, the screenshot doesn't add any additional context for me. What needs clarification?

**Comment by Naatan** [comment] 2017-10-06 20:29
That is what they are currently doing, except that they "float" on top of the content, which is what you describe as the selection stretching beyond the scrollbar.
