### ISSUE TITLE
Find All Issue

### ISSUE THREAD

**Issue by ziplizard** [Komodo/KomodoEdit#710] opened 2015-10-09 16:06 UTC
Just got the 9.3 nightly update and the find all (Cmd + Shift + F) does not work. 

1) It does not allow to search (should default to) the project.
2) I hit enter on my keyboard and it does nothing (does not search), so I click the "Find All" button, and it also does nothing. It will not search.

**Comment by babobski** [comment] 2015-10-11 07:29
got the same bug, did a find in folder using the breadcrumb, but when hitting on enter or clicking on the findall button, nothing happends.

And the errors from my log file:
<pre>[2015-10-11 09:22:08,726] [ERROR] console-logger: mismatched tag. Expected: </box>. (0) in chrome://komodo/content/find/findResultsTab.xul:90
Traceback (most recent call last):
  File "chrome://komodo/content/find/findResultsTab.xul", line 90, in 

[2015-10-11 09:22:08,805] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:08,821] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:12,476] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:12,493] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:18,351] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:18,368] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:44,368] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:44,384] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,306] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,322] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,509] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,526] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,665] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:45,681] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:55,901] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:22:55,917] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:06,933] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:06,933] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:07,323] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:07,338] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:07,496] [ERROR] findResultsTab: 
-- EXCEPTION START --
TypeError: treeWidget is null
+ stack
    this.FindResultsTabManager.prototype.initialize@chrome://komodo/content/find/findResultsTab.js:163:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:110:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
[2015-10-11 09:23:07,496] [ERROR] ko.widgets: 
-- EXCEPTION START --
TypeError: descWidget is null
+ stack
    this.FindResultsTabManager.prototype.configure@chrome://komodo/content/find/findResultsTab.js:499:5
    Find_FindAllInFiles@chrome://komodo/content/find/find_functions.js:1930:1
    FindResultsTab_GetTab/<@chrome://komodo/content/find/findResultsTab.js:73:13
    _FindResultsTab_Create/<@chrome://komodo/content/find/findResultsTab.js:129:9
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:17
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:15
-- EXCEPTION END --
</pre>

**Comment by Naatan** [comment] 2015-10-12 16:34
Duplicate of #669

**Closed by Naatan** 2015-10-12 16:34 UTC

**Comment by Naatan** [comment] 2015-10-12 16:37
@babobski fixed those errors you posted, should be in next nightly.
