### ISSUE TITLE
Syntax checking indicates command "info object" is invalid

### ISSUE THREAD

**Issue by WheelDogs** [Komodo/KomodoEdit#1960] opened 2016-08-23 17:49 UTC
### Short Summary
Editor identifies this option as invalid for use with 'info' command. Similar to other I reported that seems closed.

Guess it, the dev team forgot something...
### Steps to Reproduce

Simple, enter "info object ..." etc. see attached.

### Expected results
No error

### Actual results

Does not seem to impact execution. However, if one disable msgs of this type, how is one to know if there really is a syntax error.

### Platform Information

*Komodo Edit or IDE?* Komodo IDE commercially licensed 
*Komodo Version?* 10.0.1
*Operating System (and version)?* 
win7/win10
![info_object](https://cloud.githubusercontent.com/assets/21134598/17903120/5026ee84-6938-11e6-8e2f-c47514a5597e.jpg)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment] 2016-08-23 18:00
Yes, you closed it 17 minutes ago @WheelDogs. https://github.com/Komodo/KomodoEdit/issues/1944

**Comment by WheelDogs** [comment] 2016-08-23 18:02
Proof that I am clueless about how to effectively use github...

**Comment by mitchell-as** [comment] 2016-08-23 18:03
Hi, please post the code snippet that exhibits this issue. The tooltip in your screenshot obscures it.

**Comment by cgchoffman** [comment] 2016-08-23 18:04
> Proof that I am clueless about how to effectively use github...

S'ok.  We're here to help :)

**Comment by WheelDogs** [comment] 2016-08-23 18:11
Please see attached...

**Comment by WheelDogs** [comment] 2016-08-25 00:17
Here it is an example. Seems any 'info' command that is applied to an object produces this response.

![image 45](https://cloud.githubusercontent.com/assets/21134598/17952373/cf61db82-6a37-11e6-911d-e3b530643a6b.png)

**Comment by mitchell-as** [comment] 2016-08-25 14:36
Thanks for the example. I just realized this is a duplicate of #1944, which was accidentally closed. I'm going to close this ticket in favor of it.

**Closed by mitchell-as** 2016-08-25 14:36 UTC
Labels: Pending: Internal

**Comment by WheelDogs** [comment] 2016-08-25 15:41
Gracias...Just don’t want this to fall through the cracks...

 

Am beginning to use tclOO and this is my first experience with it...Am not the best coder, so don’t want to disable the warning cause I know for sure that I messed up for real elsewhere.
