### ISSUE TITLE
Perl identifiers coloring crossed with hash keys

### ISSUE THREAD

**Issue by SleepyJay** [Komodo/KomodoEdit#1532] opened 2016-05-18 18:44 UTC
### Short Summary
Perl "identifiers" element type should not include hash-keys in Komodo Edit 9. They were not the same element type in Komodo Edit 8. 

### Steps to Reproduce

Write an identifier (package, sub, method, etc.):
`package foo; sub foo {} object->foo();`

Write a hash key:
`bar->{foo} = { foo => 9 };`

Note that all foo's above will be colored the same in Komodo Edit 9, but in Komodo 8 identifiers and hash keys were different element types. 

### Expected results
Should be able to set hash keys different color from package, sub, and method names.

### Actual results
All same color.

### Platform Information

*Komodo Edit* 
*Komodo 9.3.2* 
*Mac OS  10.10.5*

**Comment by Naatan** [comment] 2016-05-18 18:52
@mitchell-as I believe this is cause we switched to Scintilla's native implementation, right?

**Comment by mitchell-as** [comment] 2016-05-18 18:54
We updated to a new and improved upstream Perl lexer from Scintilla.

**Comment by Naatan** [comment] 2016-05-18 18:56
Right, so it's by design. Though there is definitely merit in having more versatile syntax highlighting.

Thanks for reporting. I'll close this as the topic at hand is not a bug, and the enhancement this would become is tracked at a higher level.

**Comment by SleepyJay** [comment] 2016-05-18 18:57
Ok. Thanks. I noticed it awhile ago, and just now got around to reporting. :)

**Closed by Naatan** 2016-05-18 18:56 UTC
Labels: Pending Internal
