### ISSUE TITLE
Find Next (F3) doesn’t respect search settings

### ISSUE THREAD

**Issue by mrbucketeer** [Komodo/KomodoEdit#1146] opened 2016-03-10 23:10 UTC
I hit **Ctrl-F** to bring up find bar. 
I type **herp**
Case setting is 'case insensitve'
Instances of herp and Herp are highlighted :)
I hit **Enter** and a brighter highlight moves between instances of herp and Herp :)
I hit **Esc** to get cursor back to edit window,
I hit **F3** to find next instance of herp or Herp. Komodo only finds herp (not Herp). ie is finding case sensitively :(

Komodo IDE, version 9.3.0, build 88117, platform win32-x86. Built on Thu Oct 29
On Windows 7

Others have reported this, but supposedly it's not reproducible. Not sure why not.
http://forum.komodoide.com/t/serching-by-f3-key-doesnt-consider-case-sensitivity-setting/1511
https://github.com/Komodo/KomodoEdit/issues/889

![1 find bar](https://cloud.githubusercontent.com/assets/5013130/13687693/00f52bd0-e771-11e5-8c81-a4872cb78446.png)

![2 f3](https://cloud.githubusercontent.com/assets/5013130/13687699/06b8da8a-e771-11e5-9736-722df567c891.png)

Thanks! Very much looking forward to a fix to this one.

**Comment by cgchoffman** [comment] 2016-03-10 23:12
Please try the latest to start: http://downloads.activestate.com/Komodo/releases/

**Comment by cgchoffman** [comment] 2016-03-10 23:21
Oh look at that.  I reproduced it.  This is a dupe of #219

**Closed by cgchoffman** 2016-03-10 23:21 UTC
