### ISSUE TITLE
The file will not close

### ISSUE THREAD

**Issue by chalda-pnuzig** [Komodo/KomodoEdit#1776] opened 2016-07-01 09:31 UTC
### Short Summary

Sometimes when I click on x on file tab or click on "Close current file" in file menu nothing is appening and file doesn't close.
### Platform Information

Komodo Edit
Version 10.0.1, build 17276, platform win32-x86. Built on Wed
Windows 10 Pro
### Additional Information

In the logs when I try to close the file appears this:

> [ERROR] commands: An error occurred executing the cmd_bufferClose command
> -- EXCEPTION START --
> [Exception... "[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 272"  data: yes]
> - QueryInterface (function) 3 lines
> - message (string) '[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]' when calling method: [nsIController::doCommand]'
> - result (number) 2153185313
> - name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
> - filename (string) 'chrome://komodo/content/library/commands.js'
> - lineNumber (number) 272
> - columnNumber (number) 0
> - location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 272
>   | + QueryInterface (function) 3 lines
>   | + language (number) 2
>   | + languageName (string) 'JavaScript'
>   | + filename (string) 'chrome://komodo/content/library/commands.js'
>   | + name (string) 'command_doCommand'
>   | + lineNumber (number) 272
>   | + columnNumber (number) 0
>   | + sourceLine (string) ''
>   | + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync/< :: line 229
>   | + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:272:0
>   command_doCommandAsync/<@chrome://komodo/content/library/commands.js:229:12
>   '
>   | + inner (object) null
>   | + data (object) [xpconnect wrapped nsISupports]
>   | + QueryInterface (function) 3 lines
>   | + initialize (function) 3 lines
>   -- EXCEPTION END --
>   [2016-07-01 11:30:30,141] [ERROR] commands: 
>   -- EXCEPTION START --
>   2147500037
> - 0 (number) 2147500037
>   -- EXCEPTION END --
>   [2016-07-01 11:30:30,144] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1181
>   Traceback (most recent call last):
>   File "vieweditor", line 1181, in

**Comment by mitchell-as** [comment] 2016-07-01 14:20
Hi, does this happen with a particular file or in a particular situation? Any steps to help us reproduce this (I cannot) would be appreciated. Thanks.

**Comment by cgchoffman** [comment] 2016-07-04 16:55
This sounds really familiar and I feel like it was a misbehaving addon or Userscript.

@chalda-pnuzig could you try *Help > troubleshooting > Restart without Addons* and *Restart without Tools* and see if you can reproduce the issue?

**Comment by chalda-pnuzig** [comment] 2016-07-07 13:02
I found the problem: it happens when I apply a new Color Scheme Editor.
The problem persists if I start Komodo without addons, but everything works poperly if I restart without tools.

**Comment by Naatan** [comment] 2016-07-07 15:28
@chalda-pnuzig I'm not seeing this. So the following steps consistently reproduce the problem for you?

1. Start up Komodo fresh
2. Change the color scheme
3. Try to open a file

**Comment by cgchoffman** [comment] 2016-07-07 16:48
> but everything works properly if I restart without tools.

@chalda-pnuzig wouldn't this mean there is a tool in your toolbox causing the issue then?  It's likely set to run on Komodo start or perhaps when a file is opened.

**Comment by shful** [comment] 2016-09-14 13:50
I see the same - I cannot close my first two files with a fresh installation.

`Komodo Edit, version 10.1.1, build 17414, platform macosx.
Built on Thu Sep 1 21:26:18 2016.`

I selected classic color schema on installation. I did not modify any preferences, and I did not activate additional plugins.

What else could I provide ?
Ruben


> [Exception... "[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1181}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 272"  data: yes]
>                                         Wed Sep 14 2016 15:39:07 GMT+0200 (CEST)
> --------------------------------------------------------------------------------
> Pre-loading code intelligence database
>                                         Wed Sep 14 2016 15:21:05 GMT+0200 (CEST)
>   Pre-loading code intelligence database. This process will improve the speed of first time autocomplete and calltips. It typically takes less than a minute.
>   Pre-loading standard library data...
>   JavaScript standard library...
>   Determining necessary updates...
>   Adding javascript stdlib
>   Node.js standard library...
>   Determining necessary updates...
>   Adding node.js stdlib
>   PHP 5.4 standard library...
>   Determining necessary updates...
>   Adding php-5.4 stdlib
>   Perl 5.16 standard library...
>   Determining necessary updates...
>   Adding perl-5.16 stdlib
>   Python 2.7 standard library...
>   Determining necessary updates...
>   Adding python-2.7 stdlib
>   Python3 standard library...
>   Determining necessary updates...
>   Adding python3-3.1 stdlib
>   Determining necessary updates...
>   Adding python3-3.2 stdlib
>   Determining necessary updates...
>   Adding python3-3.3 stdlib
>   Determining necessary updates...
>   Adding python3-3.4 stdlib
>   Determining necessary updates...
>   Adding python3-3.5 stdlib
>   Ruby 2.0 standard library...
>   Determining necessary updates...
>   Adding ruby-1.9.3 stdlib
>   Pre-loading catalogs...
>   Determining necessary catalog updates...
>   Adding 'angular.cix' API catalog
>   Adding 'dojo.cix' API catalog
>   Adding 'ember.cix' API catalog
>   Adding 'jquery.cix' API catalog
>   Adding 'mochikit.cix' API catalog
>   Adding 'prototype.cix' API catalog
>   Adding 'python3-pywin32.cix' API catalog
>   Adding 'pywin32.cix' API catalog
>   Adding 'rails.cix' API catalog
>   Adding 'xbl.cix' API catalog
>   Adding 'xpcom.cix' API catalog
>   Adding 'yui.cix' API catalog
>   Saving catalog indices...
>   Code intelligence database pre-loaded.
> --------------------------------------------------------------------------------
> 100% Pre-loading code intelligence database
>                                         Wed Sep 14 2016 15:21:28 GMT+0200 (CEST)
> --------------------------------------------------------------------------------
> Pre-loading code intelligence database
>                                         Wed Sep 14 2016 15:21:05 GMT+0200 (CEST)

**Comment by Naatan** [comment] 2016-09-14 15:13
Is the issue reproducible after a restart?

**Comment by shful** [comment] 2016-09-14 18:34
On Wed, 14 Sep 2016 08:13:13 -0700
Nathan Rijksen <notifications@github.com> wrote:

> Is the issue reproducible after a restart?
> 

No. To my anger, I could not reproduce that :-(

**Comment by cgchoffman** [comment] 2016-12-21 18:03
Is anyone able to still reproduce this?  So far it looks like it was a bad Tool in the toolbox.  If there is no further follow up I think we can close this.

**Comment by cgchoffman** [comment] 2016-12-21 18:04
Actually, closing until someone chimes in.

**Closed by cgchoffman** 2016-12-21 18:04 UTC
Labels: Pending: Response
