### ISSUE TITLE
Servers-Open Remote File "authentication failed" error - should not force password

### ISSUE THREAD

**Issue by prplpanther** [Komodo/KomodoEdit#2189] opened 2016-11-28 22:27 UTC
### Short Summary
I have created "Servers" entry in Preferences using an OpenSSH key for authentication.  I have no password (not needed with my key).  When I try to open a "Remote File," I am asked to enter a password (but I don't have one, not needed), and when I just click "Login" without entering something, I get "Authentication Failed."

### Steps to Reproduce
(1) Create a "Remote Account" via the "Servers" Preferences:
  * <server_name>
  * SFTP
  * <host_name>
  * <user_name>
  * (enter NO PASSWORD, as it is not required for me, since I have my key)
  * OpenSSH key file:  (I've tried my *.ppk file, and my *.pem file)

(2)  File->Open->Remote File.
(3)  I am prompted to enter a password.  I just click "Login" since I do not have a password.
(4)  I receive the window again, prompting me to enter a password.  I click "Login" again, or try to just type something, and I receive "Authentication Failed"

Also, this doesn't appear to use PuTTy, so is there a way to set "agent forwarding" through Komodo?  

### Expected results
I see my files on my remote server.

### Actual results
"Authentication Failed".  I'm being forced to enter a password, even though one is not required for me to log in.

### Platform Information

*Komodo Edit or IDE?*   Komodo Edit
*Komodo Version?*   Version X
*Operating System (and version)?*  Windows 10, Version 1607

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment] 2016-11-28 22:33
If you're using PuTTY you'll still need to add the key to Pageant.  This sounds like a config issue, not a bug.  Have a look at the docs here: http://docs.komodoide.com/Manual/files#working-with-files_opening-files_opening-remote-files_using-public-key-authentication

I'm going to close this for now.

**Closed by cgchoffman** 2016-11-28 22:33 UTC

**Comment by prplpanther** [comment] 2016-11-28 22:52
Hi Coop, I am using Pageant.  I have my key loaded into it and PuTTy uses it just fine (as does WinSCP).  Am I supposed to do something different to Komodo to tell it to use Pageant? Thank you!

**Comment by cgchoffman** [comment] 2016-11-28 22:57
Does your key require a password to be used?  If yes then you can just Pageant without specifying the key in Komodo.  With no key specified in the server prefs, Komodo will look for a Pageant install, then look for a valid key for the URL you're trying to access.

If your key doesn't require a password then there might be a bug here that may require more digging.

Regardless though, if you remove the key from Komodo server prefs and simply enable it in Pageant, it should work in Komodo.

This sounds familiar.  I believe there is a known issue where Komodo doesn't support certain types of keys being specified in the server prefs.

**Comment by prplpanther** [comment] 2016-11-28 23:06
Hi Coop, My key does require a password.  Komodo did ask for, and accepted, it the first time I entered it.  Per your suggestion, I removed the key path from the Preferences in the Server set up, in the hopes that it would use what is in Pageant; but it doesn't.  I am still prompted for a password, along with my user name, when I try to open a file.  Is there some environment variable I am supposed to set for Komodo to use Pageant?  It just doesn't seem to be using it, regardless of whether I "Specify an OpenSSH key file for authentication." Thanks!

**Comment by cgchoffman** [comment] 2016-11-28 23:15
That sounds like you're either connecting to the wrong URL or your username is wrong.  There is no environmental variable needed.  Assuming PuTTY is properly installed (everything on your path) and your Pageant key is configured, it should work automatically, as per the docs I linked.

You mentioned you're using an OpenSSH key.  I don't recall off the top of my head but I would think you should use a PuTTY key, not an OpenSSH key.

With the key configured in Pageant, are you able to connect to your server using PuTTY in your commandline?  ie. `putty username@server.url`

**Comment by prplpanther** [comment] 2016-11-28 23:34
Hey!  If it helps, here is the error:

``` [2016-11-28 15:08:01,940] [WARNING] koSFTPConnection: do_authenticateWithPassword:: SSHException: Incompatible ssh peer (no acceptable kex algorithm)
[2016-11-28 15:08:01,940] [WARNING] koSFTPConnection: SSH error: Invalid username/password
[2016-11-28 15:08:05,040] [WARNING] koSFTPConnection: do_authenticateWithPassword:: SSHException: Incompatible ssh peer (no acceptable kex algorithm)
[2016-11-28 15:08:05,040] [WARNING] koSFTPConnection: SSH error: Invalid username/password
[2016-11-28 15:08:05,811] [WARNING] koSFTPConnection: do_authenticateWithPassword:: SSHException: Incompatible ssh peer (no acceptable kex algorithm)
[2016-11-28 15:08:05,811] [WARNING] koSFTPConnection: SSH error: Invalid username/password
[2016-11-28 15:08:05,811] [ERROR] koSFTPConnection: SFTP open ERROR: Authentication failed.
```
For the server, there is no URL, it is a server name.  My user name here is the same one I am using in PuTTy, as is the server name.  In Komodo itself, it seems you can only use the OpenSSH.  The *.ppk doesn't work there (Komodo doesn't recognize it).  

I am able, via the commandline, to connect to my server via:  `putty username@server` using the same credentials/server name I have set up in Komodo.

You mentioned about having "everything in your path," which made me realize that the location of my `putty.exe` was not in my main path.  So, I added it, and still, no luck.

**Comment by cgchoffman** [comment] 2016-11-28 23:50
Tested a bit further and came across two existing issues.  Basically, you should just delete your current server config in Komodo and create a new one.  Do not specify a private key this time.

The two issues that I think you might have hit:
- https://github.com/Komodo/KomodoEdit/issues/923 (you might think you removed the server key but didn't actually)
- https://github.com/Komodo/KomodoEdit/issues/918 (Komodo doens't support PuTTY Keys, my bad...I reported that...)

**Comment by cgchoffman** [comment] 2016-11-28 23:51
Mine was working but I wasn't actually setting a key due to #923.  Once I got around that I hit #918 :\

**Comment by prplpanther** [comment] 2016-11-29 00:02
Hey!  So, I did as you suggested.  I deleted the Server config, closed Komodo, reopened, created a new Server config, without specifying a key this time; and... still, I am being prompted for a password.  Aarrggh.  I also tried this on Komodo 8 and 9 as well, and I get the same results.  Next up, while you continue to search, I'm going to reboot my Windows machine.  Maybe that'll help ;)  Stay tuned...

**Comment by prplpanther** [comment] 2016-11-29 00:22
...and... rebooting didn't help.  I'm still getting the dreaded password request.

**Comment by cgchoffman** [comment] 2016-11-29 00:24
Unfortunately, that's all the digging I can do.  I don't have time to delve into the code to see what nuances there might be.  If you don't specify a Key in the Komodo prefs and all the PuTTY tools are on your system PATH then it should be working.  This seems like a better topic for the forums.  The issue tracker isn't a place for tracking down configuration issue. http://community.komodoide.com/

If you're getting a password request for the server name you're using then that means Komodo can't see Pageant as far as I know.  GIven PuTTY wasn't on your path, it sounds like you need to reinstall PuTTY as a package so it's on your path.

**Comment by prplpanther** [comment] 2016-11-29 00:28
Thanks for looking.  I'll open a conversation on the Forum then.  But, if it cannot be solved then, can we reopen this issue as a bug?  This has never worked for me, but hopefully someone will have an answer.  Either way, maybe another part of the Server config can be added.. add a path to point to Pageant and explicitly tell Komodo to use it.  Just a thought...  Thanks again!

**Comment by cgchoffman** [comment] 2016-11-29 16:09
> add a path to point to Pageant and explicitly tell Komodo

You can open a new request for this but I don't see the point.  It should be on your path if properly installed.  Usually the reasons we provide an interface to specify an executable for a tool is because there could be multiple options.  As far as I know, PuTTY is the industry standard on Windows.  

> But, if it cannot be solved then, can we reopen this issue as a bug?

If someone else can reproduce this and can show us how to reproduce the issue then yes of course but as it stands it is working for me and it sounds like your system isn't properly configured but with out me being at your computer, it's very difficult for me to determine why.
