### ISSUE TITLE
Performance issues when holding down keyboard shortcuts

### ISSUE THREAD

**Issue by 6d6f6f** [Komodo/KomodoEdit#1026] opened 2016-01-24 19:43 UTC
I've been experiencing severe performance issues with keyboard shortcuts after upgrading from Komodo Edit 9.2 to Komodo IDE 9.3. Holding down a keyboard shortcut, such as CTRL+Z, results in extreme CPU usage and Komodo IDE freezing up until well after I let go of the keys.

Previously I would hold down CTRL+Z to undo a series of changes, watching the changes unfold, letting go of the keys when reaching the change I was looking for. This is no  longer possible and  I have to repeatedly press CTRL+Z to undo a single change at a time.

The problem does not seem to be related to any specific command as I get the same issue when holding CTRL+A or a number of other keyboard shortcuts. The problem persists when restarting in Safe-Mode.

To reproduce:
1. Open new file
2. Hold CTRL+Z for a few seconds
3. Watch CPU usage rise and Komodo  IDE freeze

Version info:
Komodo IDE, version 9.3.2, build 88191, platform linux-x86_64

**Comment by Naatan** [comment] 2016-01-25 16:10
I'm not able to reproduce this myself on Linux. Can you try if `Help > Troubleshooting > Restart in Safe mode` resolves it?

**Comment by mitchell-as** [comment] 2016-01-25 16:26
He said he tried safe mode already.

**Comment by Naatan** [comment] 2016-01-25 16:51
Ah, in that case, can you try some precise reproduction steps?

**Comment by Defman21** [comment] 2016-01-30 09:20
I'm able to reproduce it. Create lipsum of 100 words and start deleting it by a character - for me Komodo starts lagging a lot and CPU usage jumps to 100% (I've AMD FX8350 4.0GHz). Then hold <kbd>Ctrl+Z</kbd>. Komodo is lagging when undoing the text and again CPU usage jumps to 100-120%. This happens mostly when I delete long strings (about 30+ characters in them). If I just type 5 characters and do something with them (remove or add something) and then hold <kbd>Ctrl+Z</kbd> - Komodo deals with it very good and fast.

**Comment by mitchell-as** [comment] 2016-02-01 15:51
High CPU usage is expected when holding down keys that edit buffer contents (the editor not only needs to keep track of edits, but also display them in real-time). The lag is something I cannot reproduce.

With a new buffer open and with the console, I entered the following commands:

    sci=require('ko/editor').scimoz()
    for (i=0;i<1000;i++){sci.beginUndoAction();sci.appendText('a');sci.endUndoAction()}

This appends 1000 characters to the end of the buffer, creating a single undo step for each. Holding down `Ctrl+Z` I get the expected high CPU, but not the lag (i.e. Komodo does not keep undoing after I release `Ctrl+Z`).

**Comment by Naatan** [comment] 2016-02-01 16:38
I'm also not able to reproduce it. This may simply be an issue with weaker processors where the CPU starts queueing the requests.

Closing as this is not something that we can resolve, and holding down ctrl+z to undo a ton of changes, while possible, is not its intended use. Try using track changes instead.

**Closed by Naatan** 2016-02-01 16:38 UTC
Labels: Pending Response

**Comment by tonyattwood** [comment] 2016-07-19 11:09
Hey,

Are you  still lookinf for  that  stuff? I think I've just seen someething you may like, look <http://fact.kimberlynicoleking.com/e4dcly>


Take care, tony.attwood@ntlworld.com
