### ISSUE TITLE
New file from template not working

### ISSUE THREAD

**Issue by Francesco1975** [Komodo/KomodoEdit#3418] opened 2018-01-05 15:02 UTC
"New file from template" not working:  blank page appears selecting any possible template

Platform:
Komodo Edit  
Komodo Edit, version 11.0.2, build 18122, platform win32-x86
Windows7

I tried to re-install Komodo edit and also to reset the installation but nothng changed.

**Comment by mitchell-as** [comment] 2018-01-05 15:18
I think this is a duplicate of #3087. @cgchoffman can confirm.

**Closed by mitchell-as** 2018-01-05 15:18 UTC

**Comment by cgchoffman** [comment] 2018-01-05 15:42
They sounds the same to me.

**Comment by Francesco1975** [comment] 2018-01-05 15:50
Ok I confirm. Thank you.
