### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by oleksiybondar** [Komodo/KomodoEdit#1281] opened 2016-04-20 17:09 UTC
### Short Summary
it's impossible to work on UltraHD scree, since toolbars/menu items has fixed size 16px

### Steps to Reproduce
1. deploy Ubuntu LTS 14.04 to a machine with 4K display or virtual machine and set resolution to 3840x2160(VMWare allows you to do so)
2. set scale factor to 2
3. install KomodoIDE
4. launch KomodoIDE
5. all controls should looks fine out of the box or there should be option to set scale factor

### Expected results
all controls should looks fine
providing screen shot of a different tool(Jetbrains PyCharm) as an example
http://prntscr.com/auodra

### Actual results
http://prntscr.com/auo7du

### Platform Information
OS: Ubuntu LTS 14.04
KomodoIDE: both 9 and 10

**Comment by cgchoffman** [comment] 2016-04-20 17:16
Awesome. Thanks very much for filing this @oleksiybondar.  @Naatan any idea what's up here?

**Comment by Naatan** [comment] 2016-04-20 20:18
Does a scale of 1 "resolve" the issue?

**Comment by oleksiybondar** [comment] 2016-04-20 20:39
not sure that we are on the same way, when scale factor is 1icons/fonts/widow decorators etc. draw in original size and too small http://prntscr.com/aurdcc, scale factor adjust everything for comfort usage and without a need to configure each application separately(same apps with scale factor eql. 2 http://prntscr.com/aurer2)
in KomodoIDE only fonts affected by this variable,

**Comment by Naatan** [comment] 2016-04-20 20:43
I understand, I'm simply trying to establish a baseline.

**Comment by Naatan** [comment] 2016-04-20 20:46
Also, could you tell me the output of `window.devicePixelRatio` (you can enter this in the Console widget, in the bottom pane)?

**Comment by oleksiybondar** [comment] 2016-04-20 20:49
sure

```
    window.devicePixelRatio 23:48:06 390ms
    Number 1 23:48:06 396ms
```

**Comment by Naatan** [comment] 2016-04-20 20:52
Are you running some type of custom skin? Your toolbar color is different from the default.

**Comment by oleksiybondar** [comment] 2016-04-20 20:59
I was trying to use skins on v9 to see if it change something, and when I reinstalled v10 it was like this, and seems it's default skin http://prntscr.com/aurs2a

**Comment by Naatan** [comment] 2016-04-20 21:33
Ok, I would suggest you uninstall any skins you installed. v9 skins do not work with v10. They're not the root of the problem here, but they won't help.

**Comment by Naatan** [comment] 2016-04-20 23:54
Took a while to get my virtualbox to behave but I've finally been able to reproduce this. Turns out Firefox doesn;t handle the scaling properly either, so the chances of us doing it aren't looking good (we're base on the same foundation as Firefox).

One thing I noticed is that Ubuntu's scaling setting seems to be scaling up mainly the font and only certain UI elements. It's not performing proper scaling, proper scaling would mean anything on the screen gets scaled. That's not meant to sound as an excuse as to why it won't work for Komodo, just explaining why it's difficult.

I'll dig more on this tomorrow but to be honest it's not looking good.

**Comment by oleksiybondar** [comment] 2016-04-21 09:03
hmm that's really strange, and I was also wondered why KomodoIDE doesn't scale items since it based on Firefox, but Firefox work just fine.
I use Firefox as my default browser and I don't have any issues with scaling, neither on hot and virtual machine(http://prntscr.com/auxqji)

**Comment by oleksiybondar** [comment] 2016-04-21 10:57
If you have issues with environment I can give you access to my VM via Team Viewer or something like that

**Comment by Naatan** [comment] 2016-04-21 15:16
That's odd, in my tests I do not see any scaling on Firefox. That was using Ubuntu 16.04.

**Comment by Naatan** [comment] 2016-04-21 15:17
Ah nevermind, seems a restart was in order. I'll continue to dig.

**Comment by Naatan** [comment] 2016-04-21 15:39
It appears the latest version of Firefox has resolved this issue (at least partly - https://bugzilla.mozilla.org/show_bug.cgi?id=1214470)

We are based on Firefox 35 which does not have a fix for this. I'll look into the feasibility of backporting it though.

**Comment by Naatan** [comment] 2016-04-21 19:03
Assigning to me to fix the last remaining issue (ko-icon rendered icons).

**Closed** 2016-04-22 17:17 UTC
Labels: Enhancement
