### ISSUE TITLE
Indent/dedent breaks on closing brackets

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#631] opened 2015-09-27 01:06 UTC
Create a new file (text is fine), paste in the following:

```
    });
```

Hit Ctrl+A, then Shift+Tab - Dedents but looses selection
Hit Ctrl+A, then Tab - Deletes selection

**Comment by mitchell-as** [comment] 2015-10-06 13:43
Odd, I cannot reproduce this. @Naatan can you still reproduce this?

**Comment by mitchell-as** [comment] 2015-10-08 17:05
Closing, as I still cannot reproduce in HEAD. Please re-open if you see this again.

**Closed by mitchell-as** 2015-10-08 17:05 UTC
Labels: Bug, Pending Internal, Priority

**Comment by Naatan** [comment] 2015-10-08 21:40
Nope, can no longer reproduce it either, no idea what it was.
