### ISSUE TITLE
Enhancement Request: add "ignore" option to spell check right-click menu when there are no suggestions

### ISSUE THREAD

**Issue by sfsccn** [Komodo/KomodoEdit#586] opened 2015-09-06 14:15 UTC
From http://forum.komodoide.com/t/how-do-i-add-a-custom-word-in-spell-check-when-theres-no-suggestions/2007

I'm using Komodo IDE 9.2.0, in-line spell checking. In the right-click menu, when there are suggestions for an unknown word you can select "ignore". When there are are no suggestions there is no "ignore" option. Please add an "ignore" option for this case.

**Comment by mitchell-as** [comment] 2015-09-08 14:21
Thanks for the suggestion. This is a good idea.

**Comment by Naatan** [comment] 2015-09-08 15:19
Duplicate of #493

**Closed by Naatan** 2015-09-08 15:19 UTC
Labels: Enhancement
