### ISSUE TITLE
Preferences Web&Browser - Proxy settings cannot be saved

### ISSUE THREAD

**Issue by aloyse** [Komodo/KomodoEdit#1604] opened 2016-05-25 07:58 UTC
### Short Summary

in Preferences->Web&Browser->Connection->Settings the proxy settings can be changed but there is no apply or save button.

changes are lost after closing and reopening the window.

### Steps to Reproduce

Preferences->Web&Browser->Connection->Settings

### Expected results

the new proxy settings should be applied

### Actual results

no way to change proxy settings

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform win32-x86

windows7-64 

### Additional Information

- could not find proxy settings in a preferences file.
- after starting Komodo pops up a dialog asking for credentials for old proxy (configured in a prior version of Komodo - these settings are not shown in the actual Settings window)

**Comment by babobski** [comment] 2016-05-25 13:12
The pref window is currently missing his binding #1506 this is why the buttons are not showing up.

As work around you can add these lines in you're [custom less](forum.komodoide.com/t/komodo-x-customization-tips-tricks/2749/1) in the color scheme editor.
```
prefwindow,
prefwindow:root /* override :root from above */ {
  -moz-binding: url("chrome://global/content/bindings/preferences.xml#prefwindow") !important;
}
```
Then the buttons will appear again on the window:
![2016-05-25 15_10_03](https://cloud.githubusercontent.com/assets/3530262/15541060/e06e2ef2-228a-11e6-94eb-09456280fc4f.jpg)

**Comment by mitchell-as** [comment] 2016-05-25 14:15
Thanks for the report @aloyse and thanks for the temporary workaround @babobski.

**Comment by Naatan** [comment] 2016-05-25 15:46
Marking as duplicate of #1506

**Closed by Naatan** 2016-05-25 15:46 UTC
Labels: Bug, Regression

**Comment by aloyse** [comment] 2016-05-30 11:03
thanks for your help
