### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#3420] opened 2018-01-08 09:23 UTC
### Short Summary

autocompletion for module methods doesn't work anymore along several other automations previously working

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.1
*Operating System (and version)?*  Windows 8.1

### Additional Information

Sirs, this is irrelevant to the topic, but I have to say this: I spent over 300$ on Komodo 10/11 IDE to have in exchange a slow editor with just syntax highlighting.
Notepad++ does same things with superb elastic tabstop support. If you don't get at least the method completion working back the only nice feature of Komodo IDE over Notepad++ would be mere Vim mode.
It is a shame since the 8.x branch was working great, seems that you are busy in the effort to cripple what once was the best and only real Perl IDE. Sorry for putting it so bluntly but I think you need to get the sense of the level of service/product you are actually delivering to your paying customers.

**Comment by mitchell-as** [comment] 2018-01-08 15:11
Duplicate of #3117.

**Closed by mitchell-as** 2018-01-08 15:11 UTC
