### ISSUE TITLE
Per-project autoabbreviation snippets

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2052] opened 2016-09-24 08:44 UTC
### Short Summary

I can't get them working. I have the "Abbreviations" folder under my project-specific toolbox item and `test` snippet inside the folder. `ko.abbrev.findAbbrevSnippet("test", null)` does not give any results.

**Comment by babobski** [comment] 2016-09-24 10:58
@Defman21 Tested it, but got it working.
The problem is that you didn't defined the language folder.
The structure of you're Abbreviations should be **Abbreviations > language > snippet**.
Also this function looks at the sub-language in you're current document.
I created a folder "Abbreviations" under my project tools, added the folder "PHP" and created the snippet test in it. 
When I now have a php file open and i am working inside php.
If I then run the `ko.abbrev.findAbbrevSnippet("test")` command in the console it's returning the snippet I created under the "PHP" folder.
If I'm outside a php tag the sub-language is HTML and the snippet will not be found.
If I now want to find the snippet I will have to define the language and sub-language,
like this: `ko.abbrev.findAbbrevSnippet("test", "PHP", "PHP")`

If you want the snippet to be available in any (sub)language you can put the snippet under the "General" folder (and then calling `ko.abbrev.findAbbrevSnippet("test")` in any language will be enough).

**Comment by Defman21** [comment] 2016-09-24 12:04
Hmm, thanks. I thought it would work in the same way as in global Abbreviations. ko.abbrev.findAbbrevSnippet finds any snippet even if it's under Abbreviations, not Abbreviations - General/HTML/CSS/etc.

**Comment by babobski** [comment] 2016-09-24 13:38
That would be nice, but when you look at the [code](https://github.com/Komodo/KomodoEdit/blob/356fb6765bf5f53d1404638bc620ab0163eb8d8f/src/chrome/komodo/content/library/abbrev.js#L405), its not doing anything fancy.
If you don't provide a language and/or sub-language, [it will try](https://github.com/Komodo/KomodoEdit/blob/356fb6765bf5f53d1404638bc620ab0163eb8d8f/src/chrome/komodo/content/library/abbrev.js#L413) to get it from the currentview, and default it is including the General folder, but that's it.

**Comment by mitchell-as** [comment] 2016-09-26 14:00
So @Defman21 is this still a valid issue?

**Comment by Defman21** [comment] 2016-09-26 16:29
Hmm, yes? It works fine if I put it under global Abbreviations folder (not in Abbreviations - General). Doesn't work if it's under <Project> - Abbreviations.I don't really know would you agree with me here :)

**Comment by cgchoffman** [comment] 2016-09-26 16:37
This sounds like a reasonable enhancement request.  But it needs to be made more clear what you want.  The title says "per-propject autoabbrev snippet" which we've determined already works as expected.  You want an enhancement to have autoabbrevs be found in the root directory of the `Abbreviations` folder, regardless of language.  

If i'm correct in my guess i suggest closing this and filing a new ehnancement request, but to be fair, we already provide the functionality for storing arbitrary snippets in `general`.

**Comment by Defman21** [comment] 2016-09-26 16:49
> You want an enhancement to have autoabbrevs be found in the root directory of the Abbreviations folder, regardless of language. 

This is already working for global Abbreviations directory. 
![image](https://cloud.githubusercontent.com/assets/7100645/18843593/b6f850b4-842a-11e6-9c5d-9f69fc1ca92c.png)

I want it to be working in per-project Abbreviations directory as well :)

**Comment by cgchoffman** [comment] 2016-09-26 16:56
Huh, kind of defeats the purpose of having the `General` folder :S.  Thanks for clarifying.  This wouldn't be high priority.  I'd almost say this is open for pull requests.  All that code is in the Edit repo. We don't get any benefit from changing this since you can use `General` for arbitrary snippets any way.

**Comment by Defman21** [comment] 2016-09-29 21:06
Agree with Carey.

**Closed** 2016-09-29 21:05 UTC
Labels: Pending: Response

**Comment by Naatan** [comment] 2016-09-30 15:16
I think General is just for organization purposes. I mean otherwise every snippet would be under a categorized folder, except for the general ones, they would just be directly under Abbreviations? My OCD would trigger.
