### ISSUE TITLE
Python Console (with ActiveState Python) - Issue with multinline strings input

### ISSUE THREAD

**Issue by jjarava** [Komodo/KomodoEdit#292] opened 2015-05-25 14:40 UTC
Hi!

Commercial user of Komodo version (latest):

![komodo-license-2015-05-25_16-25-33](https://cloud.githubusercontent.com/assets/2682444/7798578/af6f7b80-02fb-11e5-8373-dd40180a65f5.jpg)

In the Console, when trying to add a multi-line string of the form:

```python
>>> txt1="""BEGIN:VEVENT
DTSTART;TZID="Europe/Madrid":"""
```

I get an error and the variable is not initialized.
```python
txt1="""BEGIN:VEVENT
DTSTART;TZID="Europe/Madrid":  File "<console>", line 1
    BEGIN:VEVENT
         ^
SyntaxError: invalid syntax
```
I get an error and the variable is not initialized.

 I can make it somewhat work if the line is the 3 "commas" and then I paste the rest:

```python
txt2="""
BEGIN:VEVENT
DTSTART;TZID="Europe/Madrid":
"""
```
but it's klunkier and I get an extra `\n` at the beginning of the string.

Same thing with Idle works fine in both formats:

Issue in Komodo:

![komodo-bug-issue-in-komodo-2015-05-25_16-24-29](https://cloud.githubusercontent.com/assets/2682444/7798652/c12e4f9e-02fc-11e5-985b-f7186266473b.jpg)

Works in IDLE:

![komodo-bug-works-in-idle-2015-05-25_16-24-57](https://cloud.githubusercontent.com/assets/2682444/7798655/c77fa154-02fc-11e5-8474-f9c8458728ef.jpg)

**Comment by Naatan** [comment] 2015-05-25 15:30
I cannot reproduce this, seems alright to me?

![9geacfe2ficarv0xdk9njpxhwyuqxkcypvjvkbg0agm](https://cloud.githubusercontent.com/assets/278649/7799232/6c541b8c-02d1-11e5-8d88-e6c2d1cf0ba3.png)

**Comment by jjarava** [comment] 2015-05-25 17:44
Platform-specific issue?

I'm using ActivePython 2.7.8.10 on OSX (10.9.5) vs your case that is 2.7. on Linux?

**Comment by jjarava** [comment] 2015-05-25 17:49
Even more odd...

If I copy and paste the whole "line":

```python
txt1=BEGIN:VEVENT
DTSTART;TZID="Europe/Madrid":"""
```
on the editor it works -- BUT if I start typing the beginning:

```python
txt1="""
```

And then I PASTE the other 2 lines of data following the """

```
BEGIN:VEVENT
DTSTART;TZID="Europe/Madrid":"""
```
THEN is when I get the error in the Editor.

I've done the same test on IDLE and on the "command line" python interactive interpreter and in both places it works.

**Comment by Naatan** [comment] 2015-06-30 16:54
@cgchoffman can you repro this on windows?

**Comment by cgchoffman** [comment] 2015-06-30 17:06
Yes, this is easy to repro on Windows.  
You can simplify it a bit more by just starting with the triple quote then pasting in additional lines and the closing triple quote.

"""blah #start

then past in

blah
blah
""""

It seems it's interpreting new lines as carridge returns rather than just a char (eg."\n").

**Comment by mitchell-as** [comment] 2015-11-25 22:08
Fixed via https://github.com/Komodo/KomodoIDE/commit/0480dc336ead80f77d2aa45d0777156478795f4a

**Closed by mitchell-as** 2015-11-25 22:08 UTC
Labels: Bug
