### ISSUE TITLE
weird symbols on tab's editor

### ISSUE THREAD

**Issue by heliogabalo** [Komodo/KomodoEdit#2198] opened 2016-11-30 13:47 UTC
### Short Summary

When i run some html-index.html, it shows some weird symbols above letters.
[screenshot](https://goo.gl/photos/fJvLaUjyWdxjZbkX9)
### Steps to Reproduce
1 - cclick on 'View in Browser'
2 - click on 'Preview' (Default browser - Komodo Tab).

### Actual results

image above ^.

### Platform Information

Komodo Edit, version 10.1.2, build 17449, platform linux-x86_64.
*Operating System (and version)?* 
Linux -Fedora 25

**Comment by mitchell-as** [comment] 2016-11-30 16:30
Hi, would you please share at least the `<title>` attribute of your source file. I cannot reproduce this on my machine, so maybe it has something to do with your title text, which Komodo displays in the tab.

**Comment by heliogabalo** [comment] 2016-12-03 22:50
isn't have any

**Comment by mitchell-as** [comment] 2016-12-05 15:13
Then where does "Gamedev Canvas Workshop" come from?

**Comment by babobski** [comment] 2016-12-05 21:57
@heliogabalo are you using split screen to preview the file or just in a new tab?

Looked in to this, but if you use the preview in browser button in Edit and you view it inside Komodo.
The browser preview button and the syntax checking button disappear when you are viewing the preview.
Because these buttons are a bit larger then the others, is this causing the toolbar to resize.

@mitchell-as if you look at the screenshot it looks like he is not using a split screen, but has the preview in a different tab. I f you then switch tabs from the source to the preview, the buttons keep appearing and disappearing. I think he might see's a blimp of the previous position of the tab.

To reproduce:
 * Open a browser preview in edit
 * Drag the previewed view next to you're source (exiting split screen)
 * Switch tabs (source - preview)

You will see the toolbar will resize in height, this might be causing the issue.

**Comment by heliogabalo** [comment] 2016-12-06 11:03
I think you are right, lol, now what? sorry, i can see that 'notation',
but i don't understant, are you suggesting to never use the split view
to avoid that?
Can i do something to fix it? Any way, i'm glad to check that behaviour
if it will help 'us' to solve the problem, call me tester if you want!.

**Comment by heliogabalo** [comment] 2016-12-06 11:18
Do you mean where i get the file? (i'm working on a mozilla personal
proyect)

**Comment by mitchell-as** [comment] 2016-12-08 19:09
@heliogabalo in your screenshot the tab's title is "Gamedev Canvas Workshop", and in your original post it appears that you are using Komodo's web preview for a file. Our web preview tab uses the `<title>` tag as the tab text, yet in a later post you said there is no `<title>` text for your file. That's why I'm asking where the title comes from. I don't mean literally, but I'm wondering why that text is there. Sorry for the confusion.

**Comment by heliogabalo** [comment] 2016-12-14 20:52
I use both(to browser preview and split tab). The problem always come from the tab on _html_, cuz it share the splitted window with other source files. The other splited window(preview) have the whole space and the name of the tab can render fine(i think). So the shorted tab would be nice if it will render something as `Game...`

**Comment by heliogabalo** [comment] 2016-12-14 21:01
I don't know if you r checking the `str.length`on `html` tag || evor `xml` tag implementing an interface structure.???

**Comment by Naatan** [comment] 2016-12-14 22:22
@heliogabalo could you please share a file with which you can reproduce this issue? For us to fix it we need to be able to reproduce it.

**Comment by heliogabalo** [comment] 2016-12-16 15:21
this is the repo [ARKA-NO-ITS](https://github.com/heliogabalo/The-side-of-the-source/tree/master/Games/Browser-game)

**Comment by Naatan** [comment] 2016-12-16 16:09
Ok, what file?

**Comment by heliogabalo** [comment] 2016-12-16 19:53
index.html & Js/main.js or mainDevel.js or which ever refact*.js

**Comment by Naatan** [comment] 2016-12-16 21:49
To be clear, if you open index.html from that repository in Komodo and hit the browser preview button you end up with artifacts on the tab title?

**Comment by heliogabalo** [comment] 2016-12-18 10:37
Not know!. do you fixed the  problem?
I changed the title -under `<title>`, to check it again and it is rendering properly, it is rendering short and
large `string` as we should expects.

Sorry, i'm involved in other project for next weeks**, so i parted all that stuff for now!

**Comment by Defman21** [comment] 2016-12-18 17:17
It appears to be a linux font rendering glitch or something. Sometime I have the same glitch in my tabs, but there are no reproduce steps.

**Comment by Naatan** [comment] 2016-12-19 15:40
Ok, I really don't think this is something we can fix for 2 reasons

 * The issue seems to originate either from Linux or Mozilla
 * The issue is hard to reproduce

As such I'm closing this, as it is just not actioanable for us.

**Closed by Naatan** 2016-12-19 15:40 UTC
Labels: Pending: Response
