### ISSUE TITLE
ko/editor.setSelection works incorrectly with tabs

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2123] opened 2016-11-01 19:37 UTC
### Steps to Reproduce

```
<p>
[tab width = 2]
[tab width = 2]p@cursor;
</p>
```

Run

```
e = editor.getCursorPosition();
e.ch -= 1;
e.absolute -= 1;
editor.setSelection(editor.getCursorPosition(), e);
```

### Expected results

`p` selected

### Actual results

some space after `p` selected.

### Platform Information

*Komodo Edit or IDE?* IDE/Edit
*Komodo Version?* 10.1.1
*Operating System (and version)?* -

### Additional Information

```
<p>
[tab width = 2]
@cursor;[tab width = 2]p
</p>
editor.getCursorPosition(); -> Object {line: 2, ch: 0, absolute: 50}
---
<p>
[tab width = 2]
[tab width = 2]@cursor;p
</p>
editor.getCursorPosition(); -> Object {line: 2, ch: 2, absolute: 51}
---
<p>
[tab width = 2]
[tab width = 2]p@cursor;
</p>
editor.getCursorPosition(); -> Object {line: 2, ch: 3, absolute: 52}
```

**Comment by cgchoffman** [comment] 2016-11-01 20:53
Looks like tabs are interpreted as single characters.  I don't understand your test data though @Defman21, in your examples they are all on line 3, not 2, and there are def no 50 chars to get a abs pos of 50, unless you tested with `[tab width = 2]` literally in the file?

**Comment by cgchoffman** [comment] 2016-11-01 20:53
To clarify, confirmed this.  When you use Tab instead of spaces, set selection breaks as tabs are interpreted as single chars.

**Comment by cgchoffman** [comment] 2016-11-01 20:54
Assigning to @mitchell-as for now as I don't know who to properly deal with tabs vs. spaces.

**Comment by Defman21** [comment] 2016-11-01 21:01
I don't understand your test data though @Defman21, in your examples they are all on line 3, not 2, and there are def no 50 chars to get a abs pos of 50, unless you tested with [tab width = 2] literally in the file?

Oops. My bad.

**Comment by Defman21** [comment] 2016-11-01 21:02
@mitchell-as https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/sdk/editor.js#L976 looks like there should be used `pos.absolute` without any math.

**Comment by Defman21** [comment] 2016-11-01 21:32
At least it works in Xemmet :)

**Comment by cgchoffman** [comment] 2016-11-01 21:35
> looks like there should be used pos.absolute without any math.

Scintilla (aka, scimoz) uses line numbers starting at `0`.  But the line numbers output to users from this Editor SDK start at 1.  Since that is being passed to a scimoz function that decremented is correct.  That's unrelated to the bug.  

> At least it works in Xemmet :)

Can you clarify?  Are you saying the bug reported here is not reproducible when using Xemmet?

**Comment by Defman21** [comment] 2016-11-01 21:38
It works if I select using `scimoz.setSel(pos.absolute, ...)`

https://github.com/Defman21/Xemmet/blob/ff56baa0d2f29a22eb6f4dd444c8ef739993395f/content/xemmet.js#L486

**Closed** 2016-11-01 21:48 UTC
Labels: Bug

**Comment by Defman21** [comment] 2016-11-01 21:49
In which version the fix will arrive?

**Comment by mitchell-as** [comment] 2016-11-01 21:50
@cgchoffman tabs are supposed to only count as one character, never more.

@Defman21 The next one.

**Comment by Defman21** [comment] 2016-11-01 21:50
10.1.2?
