### ISSUE TITLE
Color Scheme Editor: After cloning the default scheme to edit it, CSE resets the item I selected to edit

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1238] opened 2016-04-12 19:44 UTC
### Short Summary

After cloning a default scheme to edit it, CSE resets the active item.

If I wanted to change Font, after cloning a scheme to the new one I'll be at the first item of All: Languages pane/page/tab/whatever it is. ("Interface - window" atm)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by mitchell-as** [comment] 2016-04-12 19:47
Duplicate of #1150

**Closed by mitchell-as** 2016-04-12 19:47 UTC
