### ISSUE TITLE
Komodo 10.0 - Uncommenting code crashes when it includes an empty commented line

### ISSUE THREAD

**Issue by fjossandon** [Komodo/KomodoEdit#1574] opened 2016-05-21 18:38 UTC
### Short Summary
This has appeared in the new 10.0 release, since it was not on the previous version... When I un-comment a single line whose only character is a '#', or a code region that include such line, the un-commenting fails throwing an error in the Notifications panel (details below), and at the same time the cursor also dissapears (is still there if I press letters, but is invisible). This is very troublesome because comment/uncomment its a very frequent action.

### Steps to Reproduce
1) Write a few code lines with an empty line in the middle like this:
my $foo = 1;

my $var = 2;

2) Comment the whole region:
#my $foo = 1;
#
#my $var = 2;

3) Now try to un-conmment the whole region, or just the empty middle line.

### Expected results
The expected result would to complete the un-commenting of the whole block without errors.

### Actual results
When un-commenting the region, the process stops on the first empty commented line:
my $foo = 1;
#
#my $var = 2;

And it generates 2 identical error messages in the Notifications panel:
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://xtk/content/controller.js :: ForwardingController_doCommand :: line 203"  data: no]
                                               Sat May 21 2016 14:09:23 GMT-0400
```

### Platform Information
Komodo-IDE-10.0.0-89159, both in Windows 10 x64 and Ubuntu 16.04 x64

### Additional Information
This bug is exacerbated if the "Clean trailing whitespace" is activated (like in my case), since it will also generate these empty commented lines in indented blocks when saving. This means that now I can't un-comment a big code region in a single step.

**Comment by Defman21** [comment] 2016-05-21 21:22
Sounds like a duplicate of this: https://github.com/Komodo/KomodoEdit/issues/1509

**Comment by mitchell-as** [comment] 2016-05-23 14:22
Yes, this is a duplicate, was fixed, and will be in the next nightly.

**Closed by mitchell-as** 2016-05-23 14:22 UTC

**Comment by fjossandon** [comment] 2016-05-23 15:22
Excellent! Thanks for fixing.
Where I can download that nightly when its released?

**Comment by mitchell-as** [comment] 2016-05-23 15:26
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/ is where you'll find our nightlies.

**Comment by fjossandon** [comment] 2016-05-23 15:28
Thanks!

 

De: mitchell [mailto:notifications@github.com] 
Enviado el: lunes, 23 de mayo de 2016 11:26
Para: Komodo/KomodoEdit <KomodoEdit@noreply.github.com>
CC: Francisco J. Ossandon <fco.j.ossandon@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Komodo/KomodoEdit] Komodo 10.0 - Uncommenting code crashes when it includes an empty commented line (#1574)

 

http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/ is where you'll find our nightlies.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub <https://github.com/Komodo/KomodoEdit/issues/1574#issuecomment-221010159> 



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by Defman21** [comment] 2016-05-23 15:31
notice me github
