### ISSUE TITLE
Publishing causes error in 9.2

### ISSUE THREAD

**Issue by krazypengwin** [Komodo/KomodoEdit#465] opened 2015-07-30 14:34 UTC
Since upgrading to 9.2, I can no longer publish my sites from within the applications.
I get the error: 

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingService.pushLocalUri]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://publishing/content/publishing.js :: publishing_push :: line 202"  data: no]
                                         Thu Jul 30 2015 15:29:52 GMT+0100 (BST)

**Comment by krazypengwin** [comment] 2015-07-30 14:42
This may not actually be an issue, I deleted my publishing profiles and recreated them, now there is not a problem

**Comment by cgchoffman** [comment] 2015-07-30 17:44
Sorry you had to reconfigure @krazypengwin.  Definitely not our intentional UX.  Looks like the config became corrupted.  If this ever happens again could you save your Prefs.xml file and the publishing folder from you profile so we can have a look at what might be wrong?  Closing this for now as I'm not able to reproduce the issue and clues have been blown away on your system.

**Closed by cgchoffman** 2015-07-30 17:44 UTC
