### ISSUE TITLE
Find All in Project is not Working

### ISSUE THREAD

**Issue by gautamdharmapuri** [Komodo/KomodoEdit#707] opened 2015-10-09 06:58 UTC
If i wanna search in all the folder it is not allowing me to do after taken the update on today(09-10-2015).Please fix this issue

**Comment by Defman21** [comment] 2015-10-09 12:02
What is your Komodo version? (Help - About Komodo).
Anything in the error log? (Help - Troubleshooting - View log file)

**Comment by gautamdharmapuri** [comment] 2015-10-09 12:09
It is version 9.3.0

**Comment by Naatan** [comment] 2015-10-09 14:53
Can you see if changing the "Where" selection from something else and then back to "Project" fixes it? I think this is a duplicate of an issue we are already tracking but want to make sure.

**Comment by dsynott** [comment] 2015-10-14 22:19
Same issue, changing the "where" didn't help.  Error is:
XML Parsing Error: mismatched tag. Expected: </box>.
Location: chrome://komodo/content/find/findResultsTab.xul
Line Number 90, Column 3:</page>
--^

**Comment by cgchoffman** [comment] 2015-10-14 22:26
I'm not seeing this in the latest (not released) 9.3.  But I wasn't seeing it in the latest released version of 9.3 either.  Could one of you clarify the use case?  What are the exact steps you're taking to reproduce this?

**Comment by Naatan** [comment] 2015-10-14 23:46
This is an Edit-only issue that should be resolved in the next nightly (it was caused by a bad merge).

**Closed by Naatan** 2015-10-14 23:46 UTC
Labels: Pending Response
