### ISSUE TITLE
Copy Menu item appears disabled

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#100] opened 2015-03-31 11:02 UTC
I can't tell the exact context, it is a new file not yet saved. I do "Select All" and when I try to copy the "Copy" menu item appears disabled.

**Comment by Defman21** [comment] 2015-03-31 11:03
Cannot reproduce to that. What's your OS and Komodo verison? (`Help - About Komodo`)

**Comment by srgloureiro** [comment] 2015-03-31 11:04
Komodo Edit, version 9.0.0, build 15707, platform win32-x86.
Built on Thu Mar 19 07:01:30 2015.

**Comment by srgloureiro** [comment] 2015-03-31 11:04
Komodo Edit, version 9.0.0, build 15707, platform win32-x86.
Built on Thu Mar 19 07:01:30 2015.

**Comment by Naatan** [comment] 2015-03-31 14:52
I'm unable to reproduce this also. Can you reproduce the issue reliably?

**Comment by srgloureiro** [comment] 2015-03-31 15:10
No. It must be an intermittent issue.

**Comment by Naatan** [comment] 2015-03-31 15:12
Hmm ok, will keep an eye out - please let us know if you figure out steps to reproduce. Closing this until we have more info as I can't do anything with the current data.

**Closed by Naatan** 2015-03-31 15:12 UTC
