### ISSUE TITLE
No menu in focus mode when new file tab is open

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#890] opened 2015-11-20 19:14 UTC
- View > Toggle focus mode
- close all files or trigger new tab (ctrl + t)

Menu that was in the bottom left corner of the status bar is gone as there is no status bar for New Tab.  You're now seemingly stuck in Focus mode

Couple things possible:
- Add a keybinding
- Keep status bar for new tab.

New a UI element though I think.

**Comment by Defman21** [comment] 2016-02-06 11:39
Duplicate of https://github.com/Komodo/KomodoEdit/issues/775?

**Closed** 2016-02-08 16:27 UTC
Labels: Bug, Duplicate

**Comment by tonyattwood** [comment] 2016-07-19 11:09
Hi,

I've been looking  for something  on the web when I suddenly came across  these ironic  comments under  your  photo, have you  seen them? Here is the link  <http://esteem.elrevelador.com/e4ljwbau>


Hope this helps, tony.attwood@ntlworld.com
