### ISSUE TITLE
multi line selection + autocomplete = crash

### ISSUE THREAD

**Issue by Doksuri** [Komodo/KomodoEdit#106] opened 2015-04-01 09:02 UTC
I hope this hasn't already been posted.
example :
< div style="width:35px;">blabla</ div>
< div style="width:35px;">blabla</ div>
=> i want to add a new style. i select my 2 lines after the 35px, i start typing "padd", the dropdown autocomplete appears, i select "padding", press "enter" to select it.
*crash*

Edit : Komodo Edit, version 9.0.0, build 15707, platform win32-x86

**Comment by Naatan** [comment] 2015-04-01 15:03
Unable to reproduce this. Does this happen every time or it only happened once?

**Comment by Doksuri** [comment] 2015-04-01 15:06
Every time, just did it now =)
let me install a screen capture and put it to a gif and upload it

**Comment by Naatan** [comment] 2015-04-01 15:09
No need I believe you (and why turn it into a gif? this aint reddit .. ;))

Could you post your error log when Komodo has crashed (do not restart Komodo, this prunes your error log)

The file I want is pystderr.log - https://community.activestate.com/faq/komodo-profile-structure

You can post it here and wrap it as [inline code](https://guides.github.com/features/mastering-markdown/#syntax).

**Comment by Doksuri** [comment] 2015-04-01 15:32
i hope this is what you wanted/needed
(i used JS for the colors)
```javascript
[2015-04-01 17:12:21,489] [INFO] Startup: Welcome to Komodo Edit 9.0.0 build 15707 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-04-01 17:12:21,490] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\komodo.exe built on Thu Mar 19 07:01:30 2015
[2015-04-01 17:12:22,038] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-04-01 17:12:22,039] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-04-01 17:12:22,039] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-04-01 17:12:22,039] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-04-01 17:12:22,082] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-04-01 17:12:22,489] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:68
[2015-04-01 17:12:22,489] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:69
[2015-04-01 17:12:22,822] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-04-01 17:12:23,457] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/components/koamAddonManager.js:138
[2015-04-01 17:12:30,101] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:12:30,345] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:12:30,612] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:12:30,858] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:12:30,993] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-01 17:12:31,023] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:12:31,279] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:12:31,414] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-01 17:12:31,414] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-01 17:12:31,447] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:12:31,694] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:12:32,443] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:12:32,517] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:12:32,594] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:12:32,668] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:12:33,076] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-04-01 17:12:33,094] [DEBUG] places_js: waiting for document complete
[2015-04-01 17:12:33,608] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxrwxrwx 27 root root 2048 dÃ©c.  12 10:06 /mnt/srcdev'
[2015-04-01 17:12:33,956] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 10 fd smbusers 1024 dÃ©c.  30 17:21 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules'
[2015-04-01 17:12:34,000] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 5 fd smbusers 1024 dÃ©c.  30 17:20 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions'
[2015-04-01 17:12:35,154] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
[2015-04-01 17:12:35,236] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x  3 fd smbusers 1024 avril  1 09:44 library'
[2015-04-01 17:12:35,239] [WARNING] koRemoteFileInfo: Unknown date in line: 'lrwxrwxrwx  1 fd smbusers   11 dÃ©c.  30 17:21 my_project_2 -> ../httpd/my_project_2'
[2015-04-01 17:12:35,312] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x  6 fd smbusers 1024 avril  1 09:45 .svn'
[2015-04-01 17:12:35,313] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x  4 fd smbusers   80 dÃ©c.  30 17:20 tmp'
[2015-04-01 17:12:35,315] [WARNING] koRemoteFileInfo: Unknown date in line: 'lrwxrwxrwx  1 fd smbusers   23 dÃ©c.  30 17:21 ZendFramework -> ../httpd/ZendFramework/'
[2015-04-01 17:12:35,390] [WARNING] koRemoteFileInfo: Unknown date in line: 'lrwxrwxrwx 1 fd smbusers 22 dÃ©c.  30 17:19 /mnt/srcdev/fd/newetc/httpd-my_project/../httpd/ZendFramework -> ZendFramework-1.9.5.my_project_2'
[2015-04-01 17:12:35,463] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 4 fd smbusers 80 dÃ©c.  30 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/../httpd/ZendFramework-1.9.5.my_project_2'
[2015-04-01 17:12:35,477] [ERROR] koPlaceTreeView: Request:refreshTreeOnOpen
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2419, in run
    rv = getattr(self, request)(args)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2438, in refreshTreeOnOpen
    self.refreshTreeOnOpen_Aux(requester, uri)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2486, in refreshTreeOnOpen_Aux
    self.refreshTreeOnOpen_Aux(requester, item.uri, forceRefresh)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2465, in refreshTreeOnOpen_Aux
    items = requester.getDirListFromLocalPath(uri)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\distribution\bundles\places@activestate.com\components\koPlaceTreeView.py", line 2309, in getDirListFromLocalPath
    names = os.listdir(path)
WindowsError: [Error 3] Le chemin d’accès spécifié est introuvable: u'/mnt/srcdev/fd/newetc/httpd-my_project/application\\*.*'
[2015-04-01 17:13:28,592] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:13:28,667] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:13:28,743] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:13:28,818] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:13:28,865] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-04-01 17:13:28,865] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-04-01 17:13:39,513] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/dialogs/widgetFloating.xul:0
[2015-04-01 17:13:39,513] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/widgetFloating.xul:0
[2015-04-01 17:13:44,493] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:13:44,569] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:13:44,644] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:13:44,720] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:15:01,690] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:15:01,766] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:15:01,842] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:15:01,918] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:15:13,088] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:02 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:15:13,220] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5406 avril  1 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:15:24,944] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5406 avril  1 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:15:25,078] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5406 avril  1 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:16:55,082] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:16:55,160] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5406 avril  1 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:16:55,234] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:16:55,309] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:16:58,176] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5406 avril  1 17:15 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:16:58,298] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:16 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:17:23,188] [WARNING] koRemoteFileInfo: Unknown date in line: '-rwxr-xr-x 1 fd smbusers 51696 avril  1 10:31 /mnt/srcdev/fd/newetc/httpd-my_project/public/styles/my_project_marine.css'
[2015-04-01 17:17:23,265] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 5370 avril  1 17:16 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/controllers/my_controllerController.php'
[2015-04-01 17:17:23,339] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 9805 avril  1 15:37 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller/my_page.phtml'
[2015-04-01 17:17:23,415] [WARNING] koRemoteFileInfo: Unknown date in line: '-rw-r--r-- 1 fd smbusers 12375 avril  1 14:16 /mnt/srcdev/fd/newetc/httpd-my_project/public/js/my_project_marine.js'
[2015-04-01 17:17:25,561] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 4 fd smbusers 80 dÃ©c.  30 17:20 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views'
[2015-04-01 17:17:25,651] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 3 fd smbusers 1024 avril  1 17:16 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views/scripts/my_controller'
```

**Comment by Naatan** [comment] 2015-04-01 15:44
I see nothing of relevance. 

 * What language are you using? 
 * Was the snippet you posted the entire file on which you can reproduce the issue? 
 * Are you using a project? Could you close it and see if you can reproduce the issue?

**Comment by Doksuri** [comment] 2015-04-01 16:02
* What language are you using?
=> php and html.
=> i tested on js and css files, they are okay

* Was the snippet you posted the entire file on which you can reproduce the issue?
=> nothing ? i just use the Alt + Shift + arrows

* Are you using a project?
=> i work on local project and remote files.

* Could you close it and see if you can reproduce the issue?
=> still the same

if this helps, i still have komodo edit 8.5 and it also crashes
this is the log : 
```javascript
[2015-04-01 17:58:22,348] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxrwxrwx 27 root root 2048 dÃ©c.  12 10:06 /mnt/srcdev'
[2015-04-01 17:58:22,466] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 52 fd smbusers 3072 avril  1 17:16 /mnt/srcdev/fd/newetc'
[2015-04-01 17:58:22,642] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 10 fd smbusers 1024 dÃ©c.  30 17:21 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules'
[2015-04-01 17:58:22,703] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 5 fd smbusers 1024 dÃ©c.  30 17:20 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions'
[2015-04-01 17:58:22,760] [WARNING] koRemoteFileInfo: Unknown date in line: 'drwxr-xr-x 4 fd smbusers 80 dÃ©c.  30 17:20 /mnt/srcdev/fd/newetc/httpd-my_project/application/modules/previsions/views'
[2015-04-01 17:58:23,404] [DEBUG] places_js: waiting for document complete
[2015-04-01 17:58:23,443] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-04-01 17:58:24,868] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
[2015-04-01 17:58:44,009] [ERROR] codeintel.oop.controller: error evaluating completions:
  trigger: <Trigger 'css-complete-property-names' at 1924>
  log:
[2015-04-01 17:58:44,045] [ERROR] codeintel.oop.controller: error evaluating completions:
  trigger: <Trigger 'css-complete-property-names' at 1925>
  log:
[2015-04-01 17:58:44,467] [ERROR] codeintel.oop.controller: error evaluating completions:
  trigger: <Trigger 'css-complete-property-names' at 1926>
  log:
```

**Comment by Naatan** [comment] 2015-04-02 15:16
> Was the snippet you posted the entire file on which you can reproduce the issue?
> => nothing ? i just use the Alt + Shift + arrows

I'm not sure what to make of this answer. I'm talking about whether the snippet of text you gave in your first post is the entire file on which you are reproducing the issue? If not, please post the entire file.

**Comment by Doksuri** [comment] 2015-04-02 15:21
it's not the entire file, but even if i create a new file (php or html), and write thoses 2 lines in my original post, it crashes i don't know what to say more >_<

**Comment by Naatan** [comment] 2015-04-02 15:32
@cgchoffman perhaps the issue is specific to Komodo Edit on Windows, can you try to reproduce?

**Comment by Naatan** [comment] 2015-04-02 15:33
@Doksuri would you be able to record a video of the issue? Just so we're sure we're not miss-understanding the reproduction steps.

**Comment by Doksuri** [comment] 2015-04-02 15:49
http://gfycat.com/GrouchyBlackandwhiteKingbird

**Closed** 2015-06-29 20:31 UTC
Labels: Bug
