### ISSUE TITLE
Windows Crash

### ISSUE THREAD

**Issue by eco747** [Komodo/KomodoEdit#877] opened 2015-11-17 10:06 UTC
Komodo 9.3 crash sometimes if   'listen for debugging connections' option is set.
Since update to 9.3 version i get some crashs, may be 2 or 3 times a day. 
Each time, it's when Komodo ide is not active. It seem that it's when another program make some access on localhost (127.0.0.1) but i cannot confirm for now.
The crash occur in moz code but i do not have debug info ; so i cannot give more information.

Windows 10. Komodo IDE, version 9.3.0, build 88117, platform win32-x86.
Built on Thu Oct 29 09:49:58 2015.

**Comment by eco747** [comment] 2015-11-17 11:42
Hop, crash trace

<img width="627" alt="im12" src="https://cloud.githubusercontent.com/assets/2598404/11210450/888dedaa-8d28-11e5-9fad-ba2f710c3494.png">

**Comment by Naatan** [comment] 2015-11-17 16:35
What do you have running that makes debugging connections? We'll need to figure out what exactly causes this crash in order to solve it.

**Comment by eco747** [comment] 2015-11-18 08:14
You should have received crash info because I allow minidump to be send to Komodo (ServerURL=https://komodo.activestate.com/crash/submit).
But, it seem that there is a bug in Mozila when blockedDlls are listed in the minidump so I don't know if somebody received something. I can send you the .dmp file if you think it's usefull.

In response to the question, i think last time it was Visual C++ but i'm sure other softwares also do it because i do not spend my time to start VC.

**Comment by Naatan** [comment] 2015-11-18 16:12
Sorry, I think you miss-understood my question; I'm asking what apps you are running that interface with Komodo's remote debugging connection? Ie. things that you use Komodo to debug.

**Comment by eco747** [comment] 2015-11-18 16:41
i'm using chrome
It's a local debugging session.
I'm debugging php sources over an nginx server.
I have no breakpoint set & my config says that the debugger should not stop at 1st line.

Hope i understood your question

**Comment by Naatan** [comment] 2015-11-18 17:00
I assume by local you mean it is on the same machine.

Could you please be mindful of the next time it happens and backtrack what you were doing when the crash occurred? I suspect it has to do with a specific script being called or several calls being made at once.

We'll need to figure out the steps to reproduce in order for us to fix this.

**Comment by eco747** [comment] 2015-11-18 17:27
I know, but for now I did'nt find a way to reproduce it

**Comment by mitchell-as** [comment] 2016-02-09 15:54
I'm pretty sure this is a duplicate of https://github.com/Komodo/KomodoEdit/issues/1007. We've got random crashing when Komodo is listening for remote debugging on Windows, OSX, and Linux. We'll track the status of this bug in #1007 since it's more generic.

**Closed by mitchell-as** 2016-02-09 15:54 UTC
Labels: Pending Response
