### ISSUE TITLE
Command Output tab on Komodo's Bottom Pane doesn't show output as a list

### ISSUE THREAD

**Issue by vokiput** [Komodo/KomodoEdit#486] opened 2015-08-05 19:31 UTC
Command Output tab on Komodo's Bottom Pane doesn't show output as a list if I select option 'Parse output with:' and 'Show parsed output as a list'. 
It worked on Komodo IDE 8.5 and earlier.

Now I need manually click on button 'Toggle Raw/Parsed Output View'

Komodo IDE, version 9.2.0, build 87616, platform win32-x86.
Built on Tue Aug 04 10:31:35 2015.

**Comment by vokiput** [comment] 2015-08-05 19:54
It doesn't work for 'Find in Files' example from Samples (9.2.0) too.

**Comment by Naatan** [comment] 2015-08-05 20:55
Sounds like a duplicate of:

https://github.com/Komodo/KomodoEdit/issues/174

Please check the comments there and respond there if your issue is not resolved.

**Closed by Naatan** 2015-08-05 20:55 UTC
Labels: Duplicate
