### ISSUE TITLE
JavaScript macro: syntax validation message displayed on the wrong line

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#381] opened 2015-06-29 03:13 UTC
*Problem*
I created a JavaScript macro that performs an assignment (not a test) in a `while` loop's test expression, as in `while (x = doSomething()) {...}`. The syntax checker detects it, but it tells me the problem is on the line before the `while` keyword. 

The problem also occurs for me with errors and other warnings. No message is displayed if the warning or error is on line 1 of the macro.

*Steps to Reproduce*
1. Open Komodo Edit.
2. Create a new JavaScript macro.
3. Write in the following code:
```javascript
var x;
var y;
alert("I'm not the problem!");
while (x = y) {
    break;
}
```
`
4. Save the file for good measure.
5. Wait a few seconds for the syntax checker to do its thing.

*Expected*
The syntax checker produces a warning on the line containing `while (x = y) {`.

*Actual*
The syntax checker produces a warning on the line containing `alert("I'm not the problem!");`.

![syntax warning in a JS macro](https://cloud.githubusercontent.com/assets/13005338/8400114/f040b5d6-1dde-11e5-8618-68e6b38d7cfe.png)

The same code produces the correct warning in a regular JS file:

![syntax warning in a regular JS file](https://cloud.githubusercontent.com/assets/13005338/8400133/353bb1f4-1ddf-11e5-8a5f-ed29fea99a8c.png)

I tried my best to trick the macro into working and the regular file into breaking -- opening, closing, copying, pasting -- but didn't have any luck either way. 

> Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version 64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)

**Comment by Naatan** [comment] 2015-06-29 14:49
I cannot reproduce. Could you upload the actual file so line endings/encoding is intact?

**Comment by ervumlens** [comment] 2015-06-29 18:37
Thanks for taking a look. 

>  Could you upload the actual file so line endings/encoding is intact?

I recreated the bug and uploaded the corresponding `.komodotool` file to [here](https://github.com/ervumlens/_misc/blob/master/bug-test.komodotool). Let me know if there are other files to upload. I can't think of any.

**Comment by ervumlens** [comment] 2015-06-29 19:42
I'm able to reproduce this (from scratch, following the steps above) in Windows Vista. 

![image](https://cloud.githubusercontent.com/assets/13005338/8416698/06b7080e-1e6d-11e5-9a52-6dd47e552ac9.png)

**Comment by cgchoffman** [comment] 2015-06-29 19:59
I was able to reproduce this on my Windows machine and OSX.  Nathanr, not sure if you were "editing" the macro in Komodo or if you were editing it in the Macro properties dialog. The latter doesn't produce the error.

**Comment by Naatan** [comment] 2015-06-29 20:33
My bad, I didnt create it as a macro. Able to reproduce it as well now.

I suspect this is because when you edit a macro in the main editor it creates a virtual file, which does not appear to offset the linter properly.

@mitchell-as assigning to you since this relates to Scintilla. But @cgchoffman feel free to steal, considering you've been looking at a lot of that toolbox code.

**Closed** 2015-08-10 18:46 UTC
Labels: Bug
