### ISSUE TITLE
RX Toolkit / regex os x editor text invisible

### ISSUE THREAD

**Issue by ckris** [Komodo/KomodoEdit#42] opened 2015-03-20 21:20 UTC
OS X 10.10.2 not visible text on all text areas

**Comment by Naatan** [comment] 2015-03-20 21:21
What build are you using? `Komodo > About Komodo`

**Comment by ckris** [comment] 2015-03-20 21:29
Komodo IDE, version 9.0.0-rc1, build 87167, platform macosx. Built on Fri Mar 20

**Comment by Naatan** [comment] 2015-03-20 21:47
@toddw-as sorry.. :p

**Comment by toddw-as** [comment] 2015-03-21 17:27
Hi Chris, I'm not able to reproduce this as yet (same OS version and Komodo version), running MacBook Pro (15" Retina), though I certainly believe it's true (as we've had a number of issues around blank editor text on Mac).

@ckris do you get the same problem in other editor dialogs - like the "File > Show Unsaved Changes" or "Help > Troubleshooting > View log file" ?

Also for Rx, does resizing the Rx dialog make the editor text re-appear?

**Comment by ckris** [comment] 2015-03-27 16:55
Hi, my MacBook is 13" Retina. Komodo no have log. The problem is fix when resize a popup window.

First screen
![screen shot 2015-03-22 at 8 08 37 pm](https://cloud.githubusercontent.com/assets/2426479/6872554/c17b3778-d4b2-11e4-83f2-d59a973e159b.png)

**Comment by Naatan** [comment] 2015-03-27 16:58
You're likely seeing the same problem with your log file as you are with your regex dialog.

Please confirm whether you still have the same issue with the final Komodo 9.0 version thats currently available on our website.

If so - please post your [pystderr.log](http://community.activestate.com/faq/komodo-profile-structure) file (after having opened the regex tool)

**Comment by ckris** [comment] 2015-03-27 19:10
Sry and error log window have same problem.

[2015-03-27 18:48:47,750] [INFO] Startup: Welcome to Komodo IDE 9.0.0-rc1 build 87167 (platform macosx, running on Darwin 14.1.0 version Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64)
[2015-03-27 18:48:47,751] [INFO] Startup: /Applications/Komodo IDE 9.app/Contents/MacOS/komodo built on Fri Mar 20 02:18:05 2015
[2015-03-27 18:48:47,845] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2015-03-27 18:48:48,110] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-03-27 18:48:48,110] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-03-27 18:48:48,110] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-03-27 18:48:48,111] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-03-27 18:48:48,157] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-03-27 18:48:48,236] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2316
[2015-03-27 18:48:48,259] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2316
[2015-03-27 18:48:48,318] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-03-27 18:48:48,318] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-03-27 18:48:48,568] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-03-27 18:48:48,624] [WARNING] keybindings: [Ctrl+Shift+U] was used for 'cmd_convertLowerCase', overriding to use 'cmd_scope-sections'
[2015-03-27 18:48:49,593] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-03-27 18:48:49,638] [DEBUG] places_js: waiting for document complete
[2015-03-27 18:48:51,414] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/components/koamAddonManager.js:138
[2015-03-27 18:49:28,266] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Text
[2015-03-27 18:49:28,266] [WARNING] koLanguage: Asked for unknown language: 'None'
[2015-03-27 18:49:42,041] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:49:42,042] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:49:42,043] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:04,995] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:04,995] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:04,995] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:20,796] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:20,796] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 18:54:20,797] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 21:02:07,138] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 21:02:07,139] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 21:02:07,139] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/rxx/rxx.xul:0
[2015-03-27 21:02:29,974] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-03-27 21:02:29,975] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-03-27 21:02:29,976] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by toddw-as** [comment] 2015-04-03 17:49
@ckris could you try downloading the official release build from:
http://komodoide.com/download/
to see if that makes a difference (as I think your running the nightly build version).

**Comment by Naatan** [comment] 2015-04-14 15:48
I am still able to reproduce this with the latest nightly. All I do is launch the regex editor, reproducible 100% of the time for me.

Its shortly visible at first, then becomes invisible.

**Comment by Naatan** [comment] 2015-07-21 14:51
@mitchell-as I've gathered some of the commits Todd did on this that were meant to work around the issue (which it does, in most cases). Note that these are hacks, ideally I'd like to revert these and find a proper fix, rather than a workaround.

I can relay questions to Todd if you have any.

https://github.com/Komodo/KomodoIDE/commit/f641c4b56abf72b7ff44e17a7b1913b5fc1d8b35
https://github.com/Komodo/KomodoEdit/commit/43ac87178d44e707c906c53ee8cb74dc78309549
https://github.com/Komodo/KomodoEdit/commit/4a35b3d15289418c76dd379b5716a206169726da
https://github.com/Komodo/KomodoEdit/commit/e062a1289f8b241397f52a1b35c3a990694adb48
https://github.com/Komodo/KomodoEdit/commit/d097b2c6ccb8b1e9982a8af48ad9027a75596447

**Comment by mitchell-as** [comment] 2015-07-27 19:25
This will be fixed in 9.2 along with similar bugs in other dialog-based tools.

**Comment by Naatan** [comment] 2015-07-27 19:26
Relevant commit: https://github.com/Komodo/KomodoEdit/commit/d635ace7da379aa68634196049103903006fc1eb

**Closed by mitchell-as** 2015-07-27 19:25 UTC
Labels: Bug, OSX Only, Priority
