### ISSUE TITLE
Disruptive screen flicker when starting search in Komodo 9.0.1

### ISSUE THREAD

**Issue by vitaly-krugl** [Komodo/KomodoEdit#205] opened 2015-04-23 23:15 UTC
On Mac OS X Yosemite, MacBookPro.

While editing python code, key in Command-i or Command-f to start a search. The edit window flickers as focus switches to the search text field. This behavior causes one to momentary "lose place" in the code, which is disruptive and annoying.

**Comment by cgchoffman** [comment] 2015-04-25 00:29
Resizing the bottom pane cause this to occur as well.

**Comment by mitchell-as** [comment] 2015-10-14 17:14
Note: I can only reproduce this when alternating between Cmd+F and Cmd+I. If I do Cmd+F twice, I cannot cause the flicker.

**Comment by mitchell-as** [comment] 2015-10-15 16:39
I've traced the flicker issue to this line:

https://github.com/Komodo/KomodoEdit/blob/e881f6cfec930766a95a1c9ac0d0b39243b70005/src/chrome/komodo/content/find/findbar.xml#L264

When I comment out that line, the flicker very rarely happens.

Unfortunately it's a Mozilla/XUL method, so there's not much we can do short of delving into Mozilla code and patching it ourselves. Moving to backlog.

**Comment by Naatan** [comment] 2015-10-16 15:09
XUL textbox elements have a .select() method that does what this function appears to be doing, I'll see if using that resolves the issue.

**Comment by Naatan** [comment] 2015-10-20 17:17
I cannot reproduce this issue at all. I'm on El Capitan though.

**Comment by doughemi** [comment] 2015-11-29 04:13
I am seeing this issue when scrolling  the main window. No keyboard commands are being used. Yosemite 10.10.5; Komodo Edit, version 9.3.1, build 16424, platform macosx.
Built on Tue Nov 17 17:48:44 2015.

It makes the editor just about unusable.

**Comment by Naatan** [comment] 2015-11-30 16:40
Does this happen on a clean profile to? Help > Troubleshooting > Restart in Safe-Mode.

Could you post your system specs?

**Comment by cschmid** [comment] 2015-12-07 18:42
yes, i restarted in safe mode just a moment, but its always the same. Looks like a bug in render engine. I tried some themes, cause i guessed the problem is caused there... but seems not so.

... As Doughemi said, its not usable with this bug.
You want to bang your head on the desk after a while :p 
Now I have to find something else looking good to me until then.

Please fix as soon as possible

**Comment by cgchoffman** [comment] 2015-12-07 20:16
This issue shoudl be fixed in the [latest nightly](http://downloads.activestate.com/Komodo/nightly/komodoide/)

Please download and install the nightly and confirm whether you find the issue fixed or not.

**Comment by Naatan** [comment] 2015-12-08 03:48
Still worth giving the latest nightly a shot, there's a chance it may have been the same issue, or related to the same issue.

**Comment by doughemi** [comment] 2015-12-08 04:04
I tried it, and it seems to have done some good.  I can't say for sure, since the problem would not appear for hours, and then start showing up every 5 or 10 seconds.
I'm looking forward to seeing a build of Komodo Edit with this patch.

**Comment by Naatan** [comment] 2015-12-08 04:05
The Komodo Edit build is right here:

http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/

**Comment by cschmid** [comment] 2015-12-08 15:06
Looks like you solved my problem at least! :+1: 

Thank you very much!

**Comment by Naatan** [comment] 2015-12-08 16:09
Perfect, thanks for reporting back! :)

**Closed by Naatan** 2015-12-08 16:09 UTC
Labels: Bug, OSX Only

**Comment by wheffner** [comment] 2015-12-10 18:25
Thank you! Hope to see this soon in a Komodo IDE patch. :-)

**Comment by cgchoffman** [comment] 2015-12-10 18:45
HI @wheffner, it's already out: https://github.com/Komodo/KomodoEdit/issues/205#issuecomment-162647359

Unless you are referring to a non nightly release?

**Comment by tonyattwood** [comment] 2016-07-19 11:07
Hey,

I've got some good news for you, read more about it here  <http://explore.sportbros.com/e4nkyy>

In haste, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment] 2016-07-19 11:08
Hi,

I've  found  some fresh and cool stuff, don't miss it  up! More  info  here <http://favourite.topdocsneworleans.com/e4myssm>

tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment] 2016-07-19 11:09
Hi,

I've just came across that stuff  on the web and  completely fell in love with it! You've got to see that! Here is the link <http://fact.caspergroup.us/e4pvlxii>


My best to you, tony.attwood@ntlworld.com
