### ISSUE TITLE
Edit 9 missing "replace all" button

### ISSUE THREAD

**Issue by xdestiny** [Komodo/KomodoEdit#143] opened 2015-04-09 06:36 UTC
This seems to have fallen off the development at some point. The find/replace dialog is missing the "Replace All" button. Only the "Find All" button is still there. This makes it quite tiresome to transform, for example, an XML file into a text file by removing all tags with an appropriate regular expression. Now, you have to "Find Next" and "Replace" manually for every appearance.

This is the case on a Windows 7 environment. Don't know if this is the case everywhere.

**Comment by Defman21** [comment] 2015-04-09 08:04
Duplicate of https://github.com/Komodo/KomodoEdit/issues/79

**Closed** 2015-04-09 08:22 UTC
