### ISSUE TITLE
commando: scope files not working in 9.3 nightly

### ISSUE THREAD

**Issue by twhiteman** [Komodo/KomodoEdit#700] opened 2015-10-08 21:49 UTC
Komodo IDE, version 9.3.0, build 87940, platform macosx.
Built on Thu Oct 8 02:25:32 2015.

Commando file scope no longer working (i.e. for relative OR absolute path search):
```
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 77, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147942487 (NS_ERROR_ILLEGAL_VALUE)
```

**Comment by Naatan** [comment] 2015-10-08 21:57
Duplicate of https://github.com/Komodo/KomodoEdit/issues/667

Thanks :)

**Closed by Naatan** 2015-10-08 21:57 UTC
