### ISSUE TITLE
Spinning wheel

### ISSUE THREAD

**Issue by pvernaglia** [Komodo/KomodoEdit#199] opened 2015-04-22 22:04 UTC
Hi, I am using Komodo Edit version 9.0.1, build 15745, whenever I switch back to Komodo from any other application I get the mac spinning pinwheel for about 3 to 5 seconds.  It's only happening when I switch to Komodo, and it seems it started when I upgraded to version 9.  Is there something I can check for to fix this?  it's starting to make me nuts and I love Komodo.

Thanks
Peter

**Comment by Naatan** [comment] 2015-04-23 15:02
I think this is the same as #70, can you try the suggestions there? In particular the one given in the last post, to which the OP never responded so I guess that did fix it for him.

**Comment by pvernaglia** [comment] 2015-04-24 13:04
uncheck the option "Detect when files are changed outside the environment” seems to have fixed it, thanks very much!

**Comment by Naatan** [comment] 2015-04-24 15:15
Ok, closing then as duplicate of #70

**Closed by Naatan** 2015-04-24 15:15 UTC
Labels: Pending Response
