### ISSUE TITLE
Bug Report when saving

### ISSUE THREAD

**Issue by Emjiz** [Komodo/KomodoEdit#1082] opened 2016-02-11 08:39 UTC
TypeError: this._hookedMacrosByTrigger is undefined

Exception: TypeError: this._hookedMacrosByTrigger is undefined

Traceback:
MacroEventHandler.prototype.callHookedMacros@chrome://komodo/content/project/peMacro.js:317:9
MacroEventHandler.prototype.hookPreFileSave@chrome://komodo/content/project/peMacro.js:543:12
save@vieweditor:1277:21
viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1836:5
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
command_doCommand@chrome://komodo/content/library/commands.js:263:1
command_doCommandAsync@chrome://komodo/content/library/commands.js:215:1
@chrome://komodo/content/keybindings/keybindings.js line 2488 > eval:1:1
this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2488:23
this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2657:17
gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2543:5

Komodo Edit, version 9.3.2, build 16460.
Built on Thu Dec 10 19:37:30 2015.

**Comment by mitchell-as** [comment] 2016-02-11 16:00
Can you reproduce the issue? What are the steps? The error message doesn't give us much to go on, unfortunately.

**Comment by Emjiz** [comment] 2016-02-25 07:30
Hi Mitchell

It happens when I edit and save a file, It works fine when I restart in safe mode.

**Comment by mitchell-as** [comment] 2016-02-25 15:47
And when you start Komodo normally (not safe mode) the issue comes back? If so, it's possible your Komodo user directory has something in it that is causing the problem (perhaps a misbehaving add-on?). It might be worth closing Komodo, backing up your user directory, deleting that directory, and starting Komodo again. Note that you will lose all settings, themes, etc. that you have set. However this will start Komodo with a "fresh slate", as safe-mode temporarily does.

**Comment by cgchoffman** [comment] 2016-02-25 17:54
> MacroEventHandler.prototype.callHookedMacros@chrome://komodo/content/project/peMacro.js:317:9
> MacroEventHandler.prototype.hookPreFileSave@chrome://komodo/content/project/peMacro.js:543:12

That definitely looks like a broken macro.  You're going to have to find that macro and see why it's broken.  looks like it's Triggering on Save.

**Comment by cgchoffman** [comment] 2016-02-25 18:34
BTW, I just tested a Userscript that runs pre file save and it's fine.  This is very very likely a broken Userscript.  Feel free to reopen if you rule that out.

**Closed by cgchoffman** 2016-02-25 18:34 UTC
Labels: Pending Response
