### ISSUE TITLE
python 3 file type and code intel

### ISSUE THREAD

**Issue by trogne** [Komodo/KomodoEdit#3702] opened 2019-02-27 02:02 UTC
### Short Summary
When associating ".py" files with file type "python 3", the code intel does not work well. The code intel suggestions appears too late.

Example : 
### Expected results
```
something=123
print(s  # code intel already suggesting "something" after typing "s"
```

### Actual results
```
something=123
print(somethin  # code intel finally suggests "something" after typing letter "n"
```

### Platform Information

*Komodo Edit or IDE?* 
IDE
*Komodo Version?* 
11.1
*Operating System (and version)?* 
Windows 10

**Comment by cgchoffman** [comment] 2019-02-27 18:22
Thanks for filing this with the repro steps @trogne.  I'm still not able to reproduce this, Python 2 and 3 both work fine.  You might benefit from a codeintel reset?

**Comment by trogne** [comment] 2019-02-27 20:02
codeintel reset ? 

I've tried by deleting all files in "C:\Users\patri\AppData\Local\ActiveState\KomodoIDE\11.1".

Is there another way to reset the codeintel ?

**Comment by cgchoffman** [comment] 2019-02-27 20:18
What fixed it?  Deleting the codeintel3.db file?

**Comment by trogne** [comment] 2019-02-27 20:25
I don't know.  It was working bad after deleting this and restart.  And today it works fine.  Sorry I have no idea what happened !

**Comment by cgchoffman** [comment] 2019-02-27 20:35
It's gotta be load.  I'm not sure why you don't think it is but that's the only explanation I can think of unless you had altered the code intel trigger code to some how only ever trigger on the `xth` character.   The load could be caused by a very large project and not necessarily your computer resources being maxed out.  I'm gonna close this but if you find you're hitting it again and can identify new information please do comment and we can reopen to investigate.

**Closed by cgchoffman** 2019-02-27 20:35 UTC
