### ISSUE TITLE
OSX: Editor goes blank after being restored from being minimized

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1254] opened 2016-04-13 20:58 UTC
### Short Summary

I lose my code content from a file when I bring Komodo back from being minimized

### Steps to Reproduce

Open Komodo
Open a file
Minimize the screen
Bring back the screen

### Expected results

There to be text in the editor

### Actual results

The code flashes on the screen then disappears.

**Comment by mitchell-as** [comment] 2016-04-13 21:01
Duplicate of #564

**Closed by mitchell-as** 2016-04-13 21:01 UTC
Labels: Bug, New
