### ISSUE TITLE
Komodo gets really slow after a while (OSX)

### ISSUE THREAD

**Issue by jhihn** [Komodo/KomodoEdit#2696] opened 2017-07-21 16:22 UTC
I've been following the existing bug, but I've been pressured to create a new one.

OSX. KOMODO IN SAFE MODE.
After 2 days of being open, typing gets really slow.
In the attached video you can see where it freezes because he cursor | stops flashing. You can also see at times all the text that gets queued up. In general it takes about 2-3 days of usage to get to this point. I'm working normal work days, it sits idle at night. Unfortunately, you don't get to see the beachballing. But it beach-balled several times while recording. (I guess quicktime doesn't capture that). I'm only feeding keystrokes and shift-home/end to komodo.

[slow_komodo.zip](https://github.com/Komodo/KomodoEdit/files/1166100/slow_komodo.zip)

-- Special OSX Build ---
Komodo IDE, version 10.2.3, build 89902, platform macosx.
Built on Tue Jul 11 23:48:43 2017.

**Comment by cgchoffman** [comment] 2017-07-21 17:51
@jhihn when you recorded this video did you have the JS process running as well?  You seem to have left out a lot of details from what you mentioned in #2424.  This is a brand new Komodo install?

**Comment by jhihn** [comment] 2017-07-21 17:54
It's the 89902 build, in safe mode. 'New install'? I replaced Komodo with that build.

Good question about the s process. I apparently have 2 now. 

![screen shot 2017-07-21 at 1 52 52 pm](https://user-images.githubusercontent.com/5502325/28475910-1a0d673a-6e1c-11e7-92e0-b799723281f0.png)

**Comment by cgchoffman** [comment] 2017-07-21 18:19
"New Install" aka, fresh install.  Safe Mode is what I'm looking for.

Could you try disabling the following in your prefs:
- syntax & spell checking
- Source Code Control for any you might have installed (Komodo automatically configures them if it finds them)
- code intel

**Comment by jhihn** [comment] 2017-07-21 19:01
I've made those disabled.
Interestingly, I tried to do that in Safe Mode and got:
<img width="649" alt="screen shot 2017-07-21 at 2 53 22 pm" src="https://user-images.githubusercontent.com/5502325/28478197-4dfc3130-6e25-11e7-8f98-bc5b981d23a3.png">
<img width="655" alt="screen shot 2017-07-21 at 2 53 06 pm" src="https://user-images.githubusercontent.com/5502325/28478199-50bba75c-6e25-11e7-9447-3ee65c46dbd3.png">

Then it crashed. Would you like me to continue testing with those options disabled in regular or safe mode?

**Comment by cgchoffman** [comment] 2017-07-21 19:09
No as long as you've now reproduced it in safe mode you can work in regular mode.  Let me know how it goes with those prefs disabled in reg. mode.

**Comment by jhihn** [comment] 2017-07-25 14:28
I've disabled all that stuff and abbreviations as well.
I'm still seeing it. Also, while there is no rigue JS process Komodo istaking up ~20 CPU constantly, with spikes over 50.

![screen shot 2017-07-25 at 10 20 42 am](https://user-images.githubusercontent.com/5502325/28576896-2cd44b18-7123-11e7-90ed-49285b097b32.png)

I am approaching a level of frustration that will likely end my use of Komodo and further license purchases. I cannot understand why it is so hard to have a consistent response time to basic typing. The only consistent usage pattern I have is leaving the editor open over night, for multiple nights. Within a day or two, I experience a lot of beachballing, and keystroke queueing which results in a very unconfident usage experience. And this is on new macbook pro.

I appreciate the help but I've been complaining about this for months, and there's no real resolution. I'm left to conclude that either no one on the team uses Komodo on OSX for multiple days a a time, or it just goes unnoticed. It's starting to affect my work, and that's where I have to draw the line. 

I'm willing to run a profiled build if it will help. But I don't understand why keystroke response times are so erratic.

**Comment by Naatan** [comment] 2017-07-25 15:03
@jhihn obviously the typing delay is not by design, nor is it a widespread issue. I'm not seeing anything like that myself, nor am I aware of any significant reports on this issue besides your own. Just to give you some perspective.

I'm attaching a zip that contains two userscripts to start and stop the profiler in Komodo. Please add these to your toolbox, start the profiler and then stop it once you've reproduced the issue. Try to make the reproduction steps as short as possible, you shouldn't be recording for more than 10 seconds.

The results will be saved to your [profile directory ](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data) in a folder called "profiler". Please share the report here.

In addition could you please share your system specs?

[profiler.zip](https://github.com/Komodo/KomodoEdit/files/1173793/profiler.zip)

**Comment by jhihn** [comment] 2017-07-25 15:34
Thanks!

![screen shot 2017-07-25 at 11 34 25 am](https://user-images.githubusercontent.com/5502325/28580360-3dc8cae8-712d-11e7-94a6-3b0a22b66df5.png)

**Comment by Naatan** [comment] 2017-07-25 16:04
Alright so it's not the specs ;) Please get back to me with those profiler results.

**Comment by jhihn** [comment] 2017-07-25 18:48
[unnamed-1501007938797.cleo.zip](https://github.com/Komodo/KomodoEdit/files/1174412/unnamed-1501007938797.cleo.zip)

Here you go, just a few minutes of normal code editing. Plenty of beach-balling going on. 

Thanks in understanding my frustrations. I have no idea why I seem to be alone in this, it's a brand new machine and all, but I saw it on an older mac mini as well, Though I can't say if the new patch would have fixed the mini and if I am having some other issue on this one. I really like komodo, i just can't explain why the performance degrades so fast. I use it on linux occasionally and I never see this. I am beginning to suspect it might be an Apple problemm but I have other OSX apps that remain key-stroke responsive for long periods of time 🤷‍♂️

**Comment by Naatan** [comment] 2017-07-25 23:39
@jhihn that's an incredibly large profile sample. Could you please run it again and as said keep it under 10 seconds. When it's that big it's very hard to see the forest through the trees. My apologies.

I also have no idea why it's running so slow for you. The fact that you have a js process running at 100% CPU is a clear indication something is wrong, but what? Hard to say at this point. Let me know if you can think of anything about your setup that is out of the ordinary.

**Comment by jhihn** [comment] 2017-07-26 13:36
[unnamed-1501076119900.cleo.zip](https://github.com/Komodo/KomodoEdit/files/1176704/unnamed-1501076119900.cleo.zip)

A few seconds, with a beachball event.

**Comment by Naatan** [comment] 2017-07-26 15:15
Hmm, there are no significant slowdowns in JS there, however it does indicate there were 2 hangups happening on the XPCOM side, which unfortunately javascript profiling logs don't detail. Would it be accurate to say that typing was smooth except for 2 hangups?

I'm sharing another userscript with you which should profile the Python side of things. This works slightly differently in that it records for 10 seconds and then saves the log to /tmp/koprofile, you can edit the userscript to change the path or length of time.

Please share the results of this as you did with the Javascript profiler.

Apologies for having to ask all this of you, if we were able to reproduce this ourselves it would've been much easier.

By the way, any thought on my question of whether there is anything out of the ordinary about your setup?

[python-profiler.zip](https://github.com/Komodo/KomodoEdit/files/1177035/python-profiler.zip)

**Comment by jhihn** [comment] 2017-07-26 15:50
Yes, that would be accurate.

Well, the hardware setup is the mac, a dell KM636 K&M, dual external monitors.
The software is not all that involved. I'm a developer that uses Komodo, Chrome, Python, Git (but not often) Node, Iterm2. XCode is installed, but seldom used. I use Karabiner Elements to remap some keys, but I first suspected this and tried running without it (as that would be the most likely culprit) and the issue persists without it running in any way.

I don't suspect the hardware as there is never any delay entering text into this box in Chrome, or the iterm2 console. The iterm2 console hasn't been restarted in a _very_ long time. I've been experiencing the slow-downs as far as I can remember, this laptop was delivered May 1, of this year.

**Comment by jhihn** [comment] 2017-07-26 15:58
[koprofile.zip](https://github.com/Komodo/KomodoEdit/files/1177231/koprofile.zip)

**Comment by vrwired** [comment] 2017-07-26 17:46
I also have this issue. Have for a couple months at least. Usually takes about an hour of Komodo IDE 10 to be open for it to freeze. Quick/erratic typing (misspelled code, etc) or sudden switch apps (using cmd+tab) usually seems to trigger the freeze. Perhaps my profile may also help but for now here's my specs:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/833536/28635198-f69f5090-71f6-11e7-9b67-28de2d3f30ce.png">

**Comment by Naatan** [comment] 2017-07-26 18:11
Looking at the profile results for JS and Python I am fairly certain the slowdown is caused by CodeIntel. Luckily we have rewritten large parts of codeintel entirely for Komodo 11, so this will be fixed in Komodo 11 once it releases (in a couple months). Unfortunately there is no interim solution aside from maybe limiting codeintels scope. See the CodeIntel preferences under the Preferences window.

I'm going to close this ticket as the issue has already been addressed, we just have to wait for the release of Komodo 11.

**Closed by Naatan** 2017-07-26 18:11 UTC
Labels: Bug, Bug: UX

**Comment by cgchoffman** [comment] 2017-07-26 18:13
@vrwired, it would be worth your while to try 10.2.3 if you're not already using it: http://downloads.activestate.com/Komodo/releases/10.2.3/

**Comment by vrwired** [comment] 2017-07-26 18:20
Cool I'll give that a go... currently I'm on:
Komodo IDE, version 10.2.2, build 89895, platform macosx.
Built on Fri Apr 28 17:57:38 2017.

Will let you know..

**Comment by jhihn** [comment] 2017-07-27 18:04
Would it be possible to do a build before 11 that has a master off-switch for code intel?

**Comment by cgchoffman** [comment] 2017-07-27 18:14
Try *Prefs > Code Intel: uncheck "Enable automatic autocomplete..." and "Enable Automatic calltip..."*

**Comment by Naatan** [comment] 2017-07-27 18:17
@jhihn sadly the codeintel version in Komodo 10 is extremely embedded. The version in Komodo 11 will allow you to turn it off, but in Komodo 10 that's not a simple task to facilitate. I really wish I had a better solution for you, but sadly I do not :(

**Comment by jhihn** [comment] 2017-07-27 18:19
Ok thanks. At least there is hope on the horizon.

**Comment by vrwired** [comment] 2017-07-28 17:30
2 days running on new release and no more crashes... thanks!

**Comment by cgchoffman** [comment] 2017-07-28 17:40
That's great news @vrwired.  You must have been experiencing issue #2424.  This issue is about delays while typing and periodic, short hangs, but not about crashes.  @jhihn did disabling the suggested prefs help at all?

**Comment by ctkjose** [comment] 2018-12-27 15:49
I experience the same lag typing, on a clean install of Komodo Edit, version 11.1.0, build 18196 running a Mojave 10.14.2 on a MacBook Pro 2016, 16GB.

The longer that Komodo is open the slower it gets. Editing HTML files becomes unbearable fairly quick. But usually restarting Komodo was my acceptable workaround.

Since my Mojave 10.14.2 upgrade, the lag with the typing happens almost instantly. 

Lag is present in CSS, HTML, HTML5, php and JS files, but worst in HTML files.

Things that I have tried:

I do have a large project, I added a couple of exclude paths for javascript autocomplete scans.

No Source Control in use or enabled.

Removing Code Intel features alone made a significant improvement, but key typing was still lagging and visible.

Disabling Syntax Check alone made NO visible improvement.

Disabling Syntax Check and Code Intelligence makes it better, typing still slow.

I truncated the symbols.db for code intel

Now Komodo is somewhat useful but it is just a plain editor without code intel and syntax check!

Any pointers?

**Comment by cgchoffman** [comment] 2019-01-02 18:30
> I truncated the symbols.db for code intel

@ctkjose meaning you deleted it?  Did this improve performance more when combined with disabling code intel?  I'm guessing no since but want to confirm.

Can you confirm that Komodo isn't still scanning your project?  You would see notifications popping up in the *Notifications* panel, **View > Tabs & Sidebars > Notifications**.

- Carey

**Comment by thatguypark** [comment] 2019-06-21 02:56
Have given up on my trial of Komodo and have moved to another IDE which is just gliding along.  Sorry Komodo, just to problematic for me, when I just need to get coding done.
