### ISSUE TITLE
macOS Sierra: Scrolling in editor not working/unresponsive using trackpad

### ISSUE THREAD

**Issue by recrof** [Komodo/KomodoEdit#2064] opened 2016-09-28 12:42 UTC
### Short Summary

When scrolling using built-in trackpad, content doesn't scroll
### Steps to Reproduce

Open Any document that doesn't fit whole screen
Slow-Scroll using 2-finger gesture on built-in trackpad (Macbook Pro).
### Expected results

Fluent movement of the text in desired scrolling direction (worked fine on El Capitan)
### Actual results

Content jumps, but is not moving.
In case of fast strolling, content moves, but jumps and feels unresponsive.
### Platform Information

Komodo Edit
10.1.1
macOS Sierra (10.12.0)

**Comment by Naatan** [comment] 2016-09-28 15:13
It seems this is an issue with Sierra and non native apps:

https://discussions.apple.com/thread/7679256?start=0&tstart=0

Either Apple is actively sabotaging third party apps or it's simply a bug. We'll investigate and observe.

**Comment by Naatan** [comment] 2016-09-30 21:37
Reproduced on Sierra. Note you have to move very slowly to reproduce. Fast scrolling works fine.

**Comment by mitchell-as** [comment] 2016-10-06 21:35
This issue has been acknowledged by the main developer of our editing component Scintilla. We're awaiting word on a workaround or solution.

**Comment by mitchell-as** [comment] 2016-10-07 15:38
https://groups.google.com/forum/#!topic/scintilla-interest/7L-wZ5ORkfM

**Comment by pascalscheffers** [comment] 2017-07-26 09:11
Any progress on this? It is becoming more and more annoying. Scrolling should be smooth, it is very jittery on 10.12.6.

**Comment by mitchell-as** [comment] 2017-07-26 15:11
Hi @pascalscheffers, sorry there is no progress on this to report. We are dependent on a third party to look at this.

**Comment by pascalscheffers** [comment] 2017-07-26 15:14
Maybe push a bit harder because it has been like this for a while now. It is really quite unpleasant. Every time you scroll it jumps and shudders around.

**Comment by Naatan** [comment] 2017-07-26 15:17
@mitchell-as can you ask Neil for an update, or insights on how we might be able to supply a patch?

**Comment by mitchell-as** [comment] 2017-07-26 22:06
Neil's response:

```If you don't mind turning line snapping off (smooth scrolling) then you could implement a control API and maybe a get/set for the fractional position. Then test that configuration.

Terminal.app does momentum scrolling and line snap but doesn't show the same problem.```

It looks like we're on our own. This would not be a small undertaking, especially since it will require delving into Cocoa + Objective C.

**Comment by Naatan** [comment] 2017-07-27 00:04
Another solution would be to handle scrolling through Mozilla, but that would mean handle it for all scrolling, not just trackpad (no way to differentiate).

**Comment by pascalscheffers** [comment] 2017-07-27 09:15
It needs to be fixed for all scrolling, because this problem exists with the Magic Mouse as well. Now that you mention it, I just tested - scrolling with a Logitech mouse with regular scroll wheel is fine. 

I took a short slow motion clip with my iPhone (240fps) to look at the difference between Komodo and other apps. You're clearly not hitting the 60fps required for smooth scrolling. Without measuring, it is more like 15-30fps. The trick to that is to render a fairly big buffer above and below the visible area so you have something ready when the OS asks for more of the view (OSX handles this for you. Just render to a bigger view and set a smaller window (or was it bigger window and smaller view... I forget))

**Comment by Naatan** [comment] 2017-07-27 15:25
> Just render to a bigger view and set a smaller window

It's not that simple when you're dealing with third party non-native components unfortunately.

@mitchell-as I'm a bit confused with Neil not taking this issue more seriously, aren't other products affected by this? What's your guesstimate for doing this ourselves?

**Comment by mitchell-as** [comment] 2017-08-11 13:39
@Naatan I do not have a guesstimate on doing this ourselves. I do not know Cocoa or Obj-C and I am not familiar with Scintilla's drawing code.

**Comment by Naatan** [comment] 2017-09-20 20:39
Awesome. The patch looks fairly simple, let's see if we can get this into 11.0.1.

**Comment by mitchell-as** [comment] 2017-09-20 21:54
After looking into whether or not I can apply this patch, I ran into https://bugs.activestate.com/show_bug.cgi?id=99862, which interferes with the new patch. Since I do not have a magic mouse or MacBook with a trackpad to test with, I am very reluctant to attempt a merge, as it may very well cause a regression.

**Comment by Naatan** [comment] 2017-09-20 21:56
That's why we have QA :) Go ahead and integrate to the best of your ability. QA can test whether this works properly.

**Comment by mitchell-as** [comment] 2017-09-21 15:14
Fixed via https://github.com/Komodo/KomodoEdit/commit/f5bb16ee46b3d33e01d2e7d5056b0511c882144c

**Closed by mitchell-as** 2017-09-21 15:14 UTC
Labels: Component: Scintilla, Introduced: 10, Limited to: OSX, Pending: Third Party

**Comment by Naatan** [comment] 2017-09-21 15:20
@mjainQA please verify this one thoroughly.

**Comment by cgchoffman** [comment] 2017-10-10 18:16
This seems to be working nicely for me. Tested on retina and non-retina screens.

**Comment by cgchoffman** [comment] 2017-10-10 18:19
Notes:
- two finger scroll up and down work
- two finger scroll left and right work
- Mouse wheel scroll is smooth both with shift (horizontal) and without (vertical)

**Comment by cgchoffman** [comment] 2017-10-10 18:21
This should already be available in a nightly build if anyone is interested:
http://downloads.activestate.com/Komodo/nightly/komodoide/latest-master/

**Comment by cliaw22** [comment] 2017-10-18 18:44
I just downloaded and installed the build suggested above and the issue is still persisting in mac osx 10.13

**Comment by Naatan** [comment] 2017-10-18 19:25
@cliaw22 please confirm the build number you see in the about window

**Comment by cliaw22** [comment] 2017-10-19 12:58
Komodo Edit, version 11.0.1, build 18116

**Comment by Naatan** [comment] 2017-10-19 15:16
@mjainQA can you test this on both edit and ide?

**Comment by Naatan** [comment] 2017-10-19 16:13
To clarify, you are using the trackpad on a  macbook?

**Comment by cliaw22** [comment] 2017-10-19 16:25
Yes, I am using the trackpad on a macbook pro

**Comment by claudeschneider** [comment] 2018-09-03 06:07
Seeing this in Komodo Edit 11.1.0 build 18196, on Mac OS X High Sierra 10.13.6

If I slow scroll with the trackpad, the content doesn't move at all.
If I scroll a little faster, it tries to move the content, but 'sticks', until you scroll fast enough, and it actually scrolls. And if you drop below the minimum scroll-speed threshold, it sticks again.

It feels like an intentional design decision to keep on the same line number until you've scrolled fast enough. However, it should be aware of how far you've scrolled, such that even if you scroll slowly, it will still move to the next line.

I've made a video comparing it with Komodo 8.5.4 on the same OS, where scrolling works perfectly.

https://youtu.be/y72N_cE1Jrs

**Comment by Prodeguerriero** [comment] 2019-03-27 17:44
Using Komodo Edit 11.1.1 and experiencing the exact same behaviour as Claude Schneider.

I will try to update MacOs to 10.14 and see if the issue disappears.
