### ISSUE TITLE
Odd behaviour when dialogs are opened

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1972] opened 2016-08-28 05:14 UTC
### Short Summary
The dialog behavior is a bit odd, as can be seen [here](https://www.youtube.com/watch?v=q_zOd9HFEFk&feature=youtu.be&hd=1)
### Platform Information
Komodo IDE X - Windows 10

**Comment by Naatan** [comment] 2016-08-30 15:26
Huh, that's odd. Thanks for reporting!

**Comment by Defman21** [comment] 2016-08-30 15:31
The behavior is:

If you're in maximized mode, a tutorial will change Komodo to window mode. The position after that will be the same as before going into maximized mode.

**Comment by Naatan** [comment] 2016-08-30 18:43
Duplicate of #1971

**Closed by Naatan** 2016-08-30 18:43 UTC
Labels: Bug: New

**Comment by Defman21** [comment] 2016-08-30 18:48
FYI Carey said that dialog behavior and tutorial behavior are two different things.

**Comment by cgchoffman** [comment] 2016-08-30 18:49
@Naatan wrote the code.  It's his call.

**Comment by Defman21** [comment] 2016-08-30 18:50
Hah okay! :)
