### ISSUE TITLE
code completion (intellisence) stops working after renaming file (Komodo Edit 10)

### ISSUE THREAD

**Issue by trwr2010** [Komodo/KomodoEdit#2637] opened 2017-06-04 00:34 UTC
### Short Summary
Code completion stops working after renaming a Python 2.7 file created in Komdo Edit 10.

### Steps to Reproduce
1. create a Python file (montage.py)  in Komodo Edit 10 and code completion works
2. close Komodo Edit 10
3. rename the file (new filename: get_montage.py)
4. open Komodo Edit 10
5. code completion no longer works

### Expected results

I expect that code completion should work.

### Actual results
Code completion stops working.

### Platform Information

Komodo Edit 10
macOS Sierra Version 10.12.5

**Comment by Defman21** [comment] 2017-06-04 13:33
I'm not able to reproduce. I created a file named `test.py` with the following content:
```
def test123():
    print(123)
```

Code completion works for me and I see my test123 function when I type `test`. I've closed Komodo, renamed the file to `get_test.py`, opened it in Komodo, gave Komodo a sec or two to scan it and I still get completions. Would you share your log file once you reproduce the issue? (Help - Troubleshooting - View Log File). # #

**Comment by trwr2010** [comment] 2017-06-05 14:10
Thanks a lot, Defman21, for help trouble shooting.

I have attached the code and log file as you suggested.

- Completion works **(I type par, I see parameters pop up**) when I first created the file test.py (in Documents folder).
- Then I close the Komodo Edit.
- Rename test.py as get_test.py
- Open Komodo Edit
- Komodo Edit says '/Users/ygchang/Documents/test.py' : it does not exist. I clicked on OK.
- Then I type par, even paramet, and I do not see parameters show up.

Thanks again for helping me out. Great software.

**Code:**
#!/usr/bin/env python
# coding=utf-8

import os
import montage
import pprint


#-------------------------------------------------------------------------
#            Style 1 (image_in_proportion_and_optional_resizing)
#-------------------------------------------------------------------------

cwd = os.getcwd()
parameters = {
    'image_formats': ('.jpg', '.jpeg', '.png', '.tiff'),
    'montage_save_format': 'png',
    #RGBA mode (red, green, blue, alpha)
    'montage_background_color': (255, 255, 255, 255),
    'current_dir': cwd,
    'image_dir': cwd + '/' + 'pic',
    'image_matrix_size': (3, 4),
    'margin_between_images': 10,
    'montage_dir': cwd + '/' + 'montage_1_image_in_proportion_and_optional_resizing',
    'shuffle_images': False,
    #use empty tuple () to suppress resizing
    #'max_size_for_montage': ()
    'max_size_for_montage': (2048, 2048)
}


**Log file:**
[2017-06-05 07:02:53,581] [INFO] Startup: Welcome to Komodo Edit 10.2.2 build 17703 (platform macosx, running on Darwin 16.6.0 version Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64)
[2017-06-05 07:02:53,582] [INFO] Startup: /Applications/Komodo Edit 10.app/Contents/MacOS/komodo built on Sat Apr 29 00:10:11 2017
[2017-06-05 07:02:54,760] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-06-05 07:02:56,257] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-06-05 07:02:56,399] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2017-06-05 07:02:57,289] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2017-06-05 07:02:57,290] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2017-06-05 07:02:57,711] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-06-05 07:03:03,077] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-06-05 07:03:03,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-06-05 07:03:03,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-06-05 07:03:03,078] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-06-05 07:03:03,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-06-05 07:03:03,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-06-05 07:03:03,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-06-05 07:03:03,079] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-06-05 07:03:03,459] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-06-05 07:03:03,459] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-06-05 07:03:03,459] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-06-05 07:03:03,459] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-06-05 07:03:03,460] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-06-05 07:03:03,460] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-06-05 07:03:03,460] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-06-05 07:03:03,461] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-06-05 07:03:03,567] [WARNING] view.tabbed: Couldn't re-open file: '/Users/ygchang/Documents/test.py', it does not exist.
[2017-06-05 07:03:03,691] [DEBUG] console: log: {"ViewinBrowser":{},"Share":{},"PreviewMarkdown":{},"SyntaxCheckingResult":{}}
[2017-06-05 07:03:03,881] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-06-05 07:03:05,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-06-05 07:03:05,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-06-05 07:03:05,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-06-05 07:03:05,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-06-05 07:03:05,885] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-06-05 07:03:05,885] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-06-05 07:03:05,885] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-06-05 07:03:05,886] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-06-05 07:03:06,459] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-06-05 07:03:33,881] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-06-05 07:03:33,899] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-06-05 07:03:34,692] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:34,782] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:34,789] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:34,812] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:34,818] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:34,826] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2017-06-05 07:03:36,080] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-06-05 07:03:36,083] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-06-05 07:03:36,408] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-06-05 07:03:36,409] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-06-05 07:03:36,409] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-06-05 07:03:36,473] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-06-05 07:03:36,475] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-06-05 07:03:36,476] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-06-05 07:03:36,476] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-06-05 07:03:36,477] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-06-05 07:03:36,562] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:305:17
    initWithDocument@vieweditor:418:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:20
-- EXCEPTION END --
[2017-06-05 07:03:36,569] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:305:17
    initWithDocument@vieweditor:418:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:20
-- EXCEPTION END --
[2017-06-05 07:03:36,575] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:305:17
    initWithDocument@vieweditor:418:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:20
-- EXCEPTION END --
[2017-06-05 07:03:37,569] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-06-05 07:03:37,975] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-06-05 07:03:40,419] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2017-06-05 07:04:46,761] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2017-06-05 07:05:11,437] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-06-05 07:05:11,438] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-06-05 07:05:11,438] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-06-05 07:05:11,438] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-06-05 07:05:11,439] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-06-05 07:05:11,439] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-06-05 07:05:11,440] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-06-05 07:05:11,440] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'

**Comment by Defman21** [comment] 2017-06-05 14:23
Please wrap your code example with ```. Still, I'm not able to reproduce. I've created `test.py`, inserted the code and I get the `parameters` completion. I close Komodo, rename `test.py` to `get_test.py`, wait for a while (1-3 secs) and then I get the `parameters` completion again.

**Comment by trwr2010** [comment] 2017-06-05 14:44
Hullo Defman21. Thank for the "wrapping code with ```" tip.

It seems working now after waiting for a few minutes. Maybe I just need to wait a little longer (than 3 seconds).

Thanks a lot. I shall post it here if I encounter any further issues.

**Comment by Defman21** [comment] 2017-06-05 17:15
Just a recommendation: create Projects for your projects so CodeIndel don't have to scan unnecessary files that are not related to your project. This could speed up the scanning process as well :)  (because the time you need to wait is too big, there's something weird going on)

**Comment by trwr2010** [comment] 2017-06-06 00:38
Thanks a lot Defman21 for the recommendation. I greatly appreciate your help.

**Comment by Naatan** [comment] 2017-06-06 13:37
Closing as it seems the file just needed to be indexed. Thanks for providing him with help @Defman21 !

**Closed by Naatan** 2017-06-06 13:37 UTC
Labels: Pending: Response

**Comment by trwr2010** [comment] 2017-06-06 13:44
Thank you Naatan as well for making this great Komodo Edit.
