### ISSUE TITLE
K11 windows are blank/white on macOS High Sierra

### ISSUE THREAD

**Issue by bolandross** [Komodo/KomodoEdit#3533] opened 2018-04-16 08:19 UTC
Hey folks,
I started to try Komodo IDE 11 yesterday and ran into the problem, that opened dialogues are initially blank. I have to click somewhere else first to make the content of it visible.
Right now I am using macOS High Sierra 10.13.4 on an early 2016 MacBook and for me, this glitch is affecting every dialogue window that is opened by K11. So each prompt that appears and asks for my interaction is completely blank and I have to click somewhere else first to force a "repaint" of it. Please watch my attached video for a demo of the problem:
[https://gfycat.com/DazzlingShamelessArachnid](url)

**Comment by Naatan** [comment] 2018-04-16 15:00
Hi @bolandross, this is most likely a duplicate of #3475 and will be fixed in the upcoming 11.1 release.

**Closed by Naatan** 2018-04-16 15:00 UTC
