### ISSUE TITLE
Edit 9 Find over files doesn't seem to work properly anymore

### ISSUE THREAD

**Issue by xdestiny** [Komodo/KomodoEdit#144] opened 2015-04-09 06:49 UTC
When searching over files in directories for a word, no result is found although there should be results.
I have a folder structure with PHP files in which I look for a word, like "disableVolume". None of the checkboxes for Regex, Match case, Word, Multiline, Replace are checked. 

"Search in" is set to "Files", the "Directories" specified is the root folder of a project on a network drive that has been connected to my Windows 7 machine (Y:\www). "Search in sub-directories" has been checked, "Include" is empty and "Exclude" has the default ".svn;CVS;.git;.hg;.bzr;*~" content. 

Issuing the "Find All" process will not find a single file that contains the text. It tells me that is has looked in a completely different folder and only searched 485 files while there should be more than 10000 files in the correct directory structure. 

I can't really tell why this is happening, it seems the directory specified in the "Find" dialog is not used at all. Komodo Edit 8 is and was installed prior to the installation of Komodo Edit 9 on the Windows system which may have something to do with this issue. Maybe the newer version took over some settings it shouldn't have?

**Comment by cgchoffman** [comment] 2015-04-09 16:01
This sounds like issue [94969](https://bugs.activestate.com/show_bug.cgi?id=94969#c5).  Could you see if you see similar behavior?

**Comment by we3geeks** [comment] 2015-04-10 03:05
... or it may be [106307](https://bugs.activestate.com/show_bug.cgi?id=106307)?

**Comment by xdestiny** [comment] 2015-04-10 13:26
Sorry, both don't seem to have anything to do with this. For 94969, I cannot get in a state where the search function works. Computer has been restarted and the problem still exists. Also I haven't done the steps described in that issue to reach the state I am in right now.

Regarding issue 106307, opening the Find dialog by Ctrl+Shift+F (on Windows) doesn't change the situation. (This has however produced a different issue that will be described in another entry)

In addition, this seems to affect the "Search in sub-directories" feature, too. Seems no setting in the find dialog has any effect on the search. It seems clicking "Find all" from that dialog just starts the search without applying that setting.

**Comment by cgchoffman** [comment] 2015-04-10 15:28
@xdestiny when you have the find dialog open, can you try selecting the "..." button beside the Directories field and see if it displays the correct directory.  If it does, don't change it, close the directory selection window and perform your search as normal.  If its the issue I think it is, this might work around it.

**Comment by laurentj** [comment] 2015-04-11 07:58
Hi,

I have the same issue (Komodo 9 on linux) : I right-click on a folder in the directories tree, select "find" item. The search dialog box opens with the right directory selected in the "directories" field. But when i launch the search, it searches in a previous directory or it doesn't do the search at all.

The workaround I found is, in the search dialog to open the list of directories, re-select the directory where I want to to the search.

Very anoying.

**Comment by xdestiny** [comment] 2015-04-13 10:41
@cgchoffman yes, this procedure makes it possible to specify the directory and issue a search correctly.

**Comment by Naatan** [comment] 2015-04-13 15:16
@cgchoffman assigning to you since you seem to have a handle on this :)

**Comment by Naatan** [comment] 2015-04-14 18:13
I'm not able to reproduce this any longer with the latest nightly. You can try it here: http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/

I think this was fixed with https://github.com/Komodo/KomodoEdit/commit/32ed693246ad9958dc4b3629d5e305ba0979c6f5

**Closed by Naatan** 2015-04-14 18:13 UTC
Labels: Bug
