### ISSUE TITLE
VI mode: Editor pane flashes/redraws when switching from insert to edit mode and back

### ISSUE THREAD

**Issue by cftarnas** [Komodo/KomodoEdit#1710] opened 2016-06-15 22:34 UTC
### Short Summary

In VI mode the editor pane flashes/redraws when switching from insert to edit mode and back on OS X

Edit: 

Also happens (sometimes) when clicking on different identifiers in the editors, or switching editor panes.

### Steps to Reproduce

Enable VI mode. Switch to and from edit mode (using esc, I, etc).

### Expected results

Editor appearance should not change, just should go into or out of edit mode.

### Actual results

 When the "--INSERT--" notice is added or removed at the bottom of the edit pane, the whole editor with go blank and then be redrawn. The flash is very distracting and can break the flow of work.

### Platform Information

*Komodo IDE* 
*Komodo IDE, version 10.0.0, build 89159, platform macosx.* 
*OS X10.10.5*

**Comment by Naatan** [comment] 2016-06-16 15:36
@mitchell-as thoughts? We know what the issue is, but is there anything we can do? Besides upgrading mozilla, which isn't sure to do anything.

**Comment by cftarnas** [comment] 2016-06-16 21:08
I have noticed this slow redraw/flashing when panes are resized. And strangely sometimes clicking on a different term in a pane will cause the pane to slightly resize and then do the slow redraw.

**Comment by cftarnas** [comment] 2016-07-13 07:18
Any updates or work arounds? Having the editor go blank for just about a complete second when switching tabs or switching to insert mode (or other random events) is a real hinderance to me using it - even though I purchased it.

**Comment by mitchell-as** [comment] 2016-07-13 13:59
Thanks for the ping @cftarnas . I will look into this today and let you know what I come up with.

**Comment by mitchell-as** [comment] 2016-07-13 15:29
@Naatan the flickering happens because we're drawing a statusbar (vim-deck) over the editing widget at the bottom (e.g. `--INSERT--`). In Komodo 9 we used the existing statusbar to display the mode, so there was no possibility for flickering in this way.

@cftarnas sadly it does not appear there is any workaround for this in Komodo X :(

**Comment by cftarnas** [comment] 2016-07-13 17:28
Thank you for the looking into it and the update.  Hopefully I can start using it at v10.1.

**Comment by cftarnas** [comment] 2016-07-21 06:13
I've done a little bit more poking around with X without VI mode turned on and I think the issue might be related to how redraws are happening and how fast (slow) in Komodo X. In Komodo 8.x when a pane is resized, the text basically reflows seamlessly and never goes blank. In Komodo X there is very distinct redraws where the pane flashes to black (the background color) and then redraws. Much much slower, especially considering the whole pane is getting wiped to black first.
Moving the divider fast enough I can make the screen blank more than not blank.
This is on a latest generation 15" MPB Retina.

**Comment by Naatan** [comment] 2016-08-15 16:10
@mitchell-as closing this in favour of the redraw issue. Opened a new bug for that here:

https://github.com/Komodo/KomodoEdit/issues/1927

**Closed by Naatan** 2016-08-15 16:10 UTC
Labels: Bug: New
