### ISSUE TITLE
Vim block deletion does not work

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#2028] opened 2016-09-20 15:30 UTC
### Short Summary

Vim block deletion does not work

### Steps to Reproduce

- activate visual block mode (ctrl+v)
- select a text block
- try to delete it with "d"

### Expected results

only the block should be deleted

### Actual results

all lines are deleted

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.1.1, build 89474, platform win32-x86. Built on Thu Sep 01 14:27:01 2016.
*Operating System (and version)?* Windows 8.1

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Naatan** [comment] 2016-09-20 16:00
Reproduced

**Comment by mitchell-as** [comment] 2016-09-29 16:13
This is a duplicate of #1711 .

**Closed by mitchell-as** 2016-09-29 16:13 UTC
Labels: Bug
