### ISSUE TITLE
Notifications ParseError error

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#103] opened 2015-03-31 19:22 UTC
These errors started happening for no apparent reason after running KomodoEdit 9 for about 5 hours. I opened a Python 3 file with only a docstring and one assignment statement, started to type a new line, and KE started showing these error notifications:

`ParseError: Syntax error at ('\\') in text ('):\\n    pass\\n\\n\\ndef b(') -- unexpected token ('ERRORTOKEN')`
`ParseError: Syntax error at ('\\') in text ('):\\n    pass\\n\\n\\n# Foo\\n# Bar\\n\\ndef b(') -- unexpected token ('ERRORTOKEN')`
`ParseError: Syntax error at ('\\') in text ('):\\n    pass\\n\\ndef b(n') -- unexpected token ('ERRORTOKEN')`
`ParseError: Syntax error at ('\\') in text ('):\\n    pass\\n\\n\\n\\ndef b(n') -- unexpected token ('ERRORTOKEN')`
`Repeat notifications truncated, please check your Notifications panel`

None of the text mentioned in the syntax error is in my file, though. Also at that point KE started filling the pystderr.log file with messages, which I didn't manage to save before restarting KE. This problem has happened a couple times before, so presumably it will happen again, and I'll save pystderr.log.

**Comment by Naatan** [comment] 2015-04-01 15:11
Are you able to reproduce this issue? Could you provide a test case?

**Comment by hobbsd** [comment] 2015-04-01 17:21
I've just now inadvertently reproduced it and saved the pystderr.log. It looks like the problem might be extension-related. I have NST installed, and it triggered an error just before the codeintel errors:

	[2015-04-01 12:41:18,107] [WARNING] views: Inconsistent view count in view_closed event
	[2015-04-01 12:41:18,732] [ERROR] console-logger: TypeError: self.refresh is not a function (2) in chrome://nst/content/NST.js:2312
	Traceback (most recent call last):
	  File "chrome://nst/content/NST.js", line 2312, in 

	[2015-04-01 12:41:39,588] [ERROR] pythoncile: Couldn't parse ('):\\n    pass\\n\\n\\ndef b(')
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\pythoncile1.py", line 1508, in _clean_func_args
		arglist = parser.parse_bare_arglist(argdef)
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\tdparser.py", line 576, in parse_bare_arglist
		arglist = self.token.argument_list()
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\tdparser.py", line 549, in argument_list
		self.advance(":")
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\tdparser.py", line 123, in advance
		self.token = self.next()
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\tdparser.py", line 126, in gen_python_symbols
		for id, value, begin, end in gen_python_tokens(source):
	  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\komodo\codeintel2\tdparser.py", line 45, in gen_python_tokens
		tokenize.tok_name[token]))
	ParseError: Syntax error at ('\\') in text ('):\\n    pass\\n\\n\\ndef b(') -- unexpected token ('ERRORTOKEN')
    ...

That's followed by a whole bunch of javascript exceptions, like this:

	[2015-04-01 12:43:07,134] [ERROR] analytics: 
	-- EXCEPTION START --
	TypeError: proxy is undefined
	+ stack
		ko.analytics</this._proxyGa@chrome://analytics/content/analytics.js:476:9
		ko.analytics</this._proxySend@chrome://analytics/content/analytics.js:457:9
		ko.analytics</this.trackPageView@chrome://analytics/content/analytics.js:403:9
		ko.analytics</this.onWindowFocus@chrome://analytics/content/analytics.js:378:9
		ko.analytics</this._eventProxy@chrome://analytics/content/analytics.js:500:13
	-- EXCEPTION END --
	[2015-04-01 12:43:07,288] [ERROR] ko.extensions.todo: 
	-- EXCEPTION START --
	[Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://todo/content/todo-ko7.js :: this.TodoSearcher.prototype.observe :: line 223"  data: no]
	+ toString (function) 3 lines
	+ message (string) ''
	+ result (number) 3253927937
	+ name (string) 'NS_ERROR_NOT_INITIALIZED'
	+ filename (string) 'chrome://todo/content/todo-ko7.js'
	+ lineNumber (number) 223
	+ columnNumber (number) 0
	+ inner (object) null
	| + data (object) null
	| + stack (string) 'this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
	CheckFile@chrome://komodo/content/tail/tail.js:87:12
	@chrome://komodo/content/tail/tail.js:73:0
	'
	+ location (object) JS frame :: chrome://todo/content/todo-ko7.js :: this.TodoSearcher.prototype.observe :: line 223
	| + QueryInterface (function) 3 lines
	| + language (number) 2
	| + languageName (string) 'JavaScript'
	| + filename (string) 'chrome://todo/content/todo-ko7.js'
	| + name (string) 'this.TodoSearcher.prototype.observe'
	| + lineNumber (number) 223
	| + columnNumber (number) 48
	| + sourceLine (string) ''
	| + caller (object) JS frame :: chrome://komodo/content/tail/tail.js :: CheckFile :: line 87
	| + formattedStack (string) 'this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
	CheckFile@chrome://komodo/content/tail/tail.js:87:12
	@chrome://komodo/content/tail/tail.js:73:0
	'
	| + stack
		this.TodoSearcher.prototype.observe@chrome://todo/content/todo-ko7.js:223:48
		CheckFile@chrome://komodo/content/tail/tail.js:87:12
		@chrome://komodo/content/tail/tail.js:73:0
	-- EXCEPTION END --

Those go on and on until I killed KE. A lot of those errors appear to be related to the TODO extension, which I also have installed.

**Comment by cgchoffman** [comment] 2015-04-01 19:11
Can you uninstall those add-ons and see if the issue persists?  If the issue is resolved you'll need to contact the add-on maintainers to resolve the bugs there.

**Comment by hobbsd** [comment] 2015-04-01 19:34
I'll do that, thanks.

**Comment by hobbsd** [comment] 2015-04-02 03:05
I uninstalled the two non-standard extensions (TODO Helper and NST), and the `ParseError`s mentioned above persist.

**Comment by Naatan** [comment] 2015-04-02 15:18
Could you please post your full log file, after reproducing the error? The ones I see above only appear to be partial portions of the log file.

**Comment by hobbsd** [comment] 2015-04-02 17:46
It's a big file -- is there a way to attach/send it, or should I just copy it all in a comment?

**Comment by Naatan** [comment] 2015-04-02 20:18
You can just add it here (wrap it in code tags) or use github gist.

**Comment by hobbsd** [comment] 2015-04-02 21:37
Here's a [gist](https://gist.github.com/hobbsd/a13a2a80194fab3044b3#file-pystderr-log).

**Comment by Naatan** [comment] 2015-04-07 16:18
Thanks @hobbsd, so you are not able to reproduce the issue reliably? Ie. it happens randomly? If so - how often? Any correlations?

**Comment by hobbsd** [comment] 2015-04-07 16:57
It happens sporadically, and it's not like I'm doing anything out of the ordinary, so I have no idea how to reproduce it.

**Comment by hobbsd** [comment] 2015-04-08 17:19
This time it happened while Komodo was trying to figure out code completion. I'm editing a models.py file and type `models.`; I see the syntax icon change to the throbber; it displays those ParseError messages, and then provides the wrong code completion options. I've added the pystderr.log to the same gist.

**Comment by hobbsd** [comment] 2015-04-08 20:02
It seems to happen when I keep typing before KE has finished its scan for code completion.

**Comment by Naatan** [comment] 2015-06-30 16:28
Please update to the latest version of Komodo and see if the issue persists. You may consider simply disabling the notification for these errors, as so far this appears to be a very edge case issue.

If you ever find out reliable steps to reproduce the issue please let us know, until then I'll have to close this issue.

**Closed by Naatan** 2015-06-30 16:28 UTC
Labels: Pending Response

**Comment by xofer** [comment] 2019-09-06 19:42
I encountered this exact same issue in 11.1.1. I found that it was choking on `pycodestyle.py` and I fixed it with `pip uninstall pycodestyle`.
