### ISSUE TITLE
Indentation broken (again) in Komodo 10

### ISSUE THREAD

**Issue by AtmanActive** [Komodo/KomodoEdit#1533] opened 2016-05-18 18:46 UTC
### Short Summary
Indentation started acting up again in Komodo 10.

My prefs:
- Prefer Tab characters over spaces: ON
- Number of spaces per indent: 2
- Width of each tab character: 2

Loading up an existing file from an existing project, and Komodo inserts spaces instead of tabs!
Checking file preferences and project preferences just to find out that indentation options have been removed (ok with me).
After pulling out my hair, found out a workaround: after opening a file I need to go to global Preferences, then turn OFF 'Prefer Tab characters over spaces', hit APPLY, then turn back ON 'Prefer Tab characters over spaces', hit APPLY again, and then Komodo starts working as expected.
But, I need to do that for EACH and EVERY file I open!

### Steps to Reproduce
Load up a project that was working just fine in Komodo 9.
Start loading and editing files from that project.

### Expected results
Global preferences indentation settings respected!

### Actual results
Global preferences indentation settings overridden by an invisible force.

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform win32-x86.
Built on Wed May 11 15:04:59 2016.

### Additional Information

![komodo_10_indentation_settings](https://cloud.githubusercontent.com/assets/7526717/15370898/4b45617a-1d39-11e6-9227-131c3b013c2a.jpg)

**Comment by mitchell-as** [comment] 2016-05-18 18:50
Duplicate of #1518. Sorry for the trouble :( This one slipped through the cracks.

**Closed by mitchell-as** 2016-05-18 18:50 UTC
