### ISSUE TITLE
Screen minimize / maximize on OS X causes edit window text to be blank until window refresh

### ISSUE THREAD

**Issue by scottg** [Komodo/KomodoEdit#564] opened 2015-08-30 20:06 UTC
When viewing a file in the edit window, minimizing the application to the dock and then un-minimizing it causes the text to be blank until I resize the window or perform some other operation that generates a window refresh. I'm on OS 10.5.5, MacBook Pro.

Komodo IDE, version 9.2.0, build 87616, platform macosx.
Built on Tue Aug 4 11:29:06 2015.

Screenshots attached for before minimize and after un-minimize.

![screen shot 2015-08-30 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/10080/9569178/b4ff149e-4f30-11e5-82ec-a442a0a07a66.png)
![screen shot 2015-08-30 at 4 02 38 pm](https://cloud.githubusercontent.com/assets/10080/9569180/b94ac9d0-4f30-11e5-9d39-9725a4b733e1.png)

**Comment by Naatan** [comment] 2015-08-31 15:10
@mitchell-as we should trigger the redraw workaround when the window is resized (on a timeout, so it doesnt trigger continuously when resizing).

**Comment by mitchell-as** [comment] 2015-12-01 20:31
Reopening because the fix originally committed has undesirable consequences, causing the main editor view to flicker. A new solution will need to be found.

**Comment by rvanleeuwen96757** [comment] 2016-05-31 19:17
Re-open

**Comment by mitchell-as** [comment] 2016-05-31 19:19
This ticket is still open. Github's linking of closed tickets is really confusing.

**Comment by jshrek** [comment] 2016-05-31 21:21
Posted video of bug in my bug report here: 
https://github.com/Komodo/KomodoEdit/issues/1642 [marked as duplicate of this one]

The problem still occurs in Komodo Edit, version 10.0.0, build 17209, platform macosx. Built on Wed May 11 22:00:40 2016

**Comment by jshrek** [comment] 2016-07-04 17:46
Just updated to v10.0.1 and this bug still exists.

**Comment by cgchoffman** [comment] 2016-07-04 17:54
> Just updated to v10.0.1 and this bug still exists.

It hasn't been fixed yet and is still open, thanks for checking though.

**Comment by mitchell-as** [comment] 2016-07-19 17:29
@cgchoffman perhaps this is worthy of being tagged for 10.0.2.

**Closed** 2016-07-19 17:28 UTC
Labels: Bug, Severity: Priority

**Comment by jshrek** [comment] 2016-09-10 12:49
Just updated and confirmed bug is fixed in v10.1.1

Thanks :)
