### ISSUE TITLE
codeintel: python completions triggered after `def` and shouldn't be

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3141] opened 2017-09-20 21:45 UTC
### Short Summary

Given that I'm about to define a new function it's highly unlikely that I want completions triggering.

### Steps to Reproduce

- open a python file
- type `def` then a space

### Expected results

Nothing to happen other than me keep typing

### Actual results

Completions appear

Sorry if this is a dupe.  I know other issues like this have come up and I"m not sure if they are language specific or not.  I think they must be given context is often lang specific.

**Comment by Naatan** [comment] 2017-09-20 21:57
@mitchell-as I'm thinking I will handle this in the router by blacklisting/whitelisting certain words, unless you have a better idea of going about this.

**Comment by Naatan** [comment] 2017-09-20 21:58
Actually, come to think about it this should be handled at a lower level. Assigning back to @mitchell-as.

**Comment by mitchell-as** [comment] 2017-09-21 21:17
Fixed via https://github.com/Komodo/codeintel/commit/a05e64a8471f986a8b50b8cd21ea6d23b19657d8

**Closed by mitchell-as** 2017-09-21 21:17 UTC
Labels: Component: CodeIntel, Type: Enhancement

**Comment by mjainQA** [comment] 2017-10-11 22:23
Unable to reproduce in Komodo IDE, version 11.0.1, build 90755, platform macosx.
Built on Tue Oct 10 09:26:02 2017.
