### ISSUE TITLE
Places doesn't support paths or filenames with "?" in them

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#872] opened 2015-11-16 21:01 UTC
I get this error when trying to open dir in tree view:
```
Exception: request:toggleOpenState_Open, message:'/Users/mike/observium/devel/raw.php?i=VvYR3Kdk' does not appear to be a proper local path [/Users/mike/observium/devel/raw.php]
                                         Mon Nov 16 2015 23:52:16 GMT+0300 (MSK)
```
In log:
```
[2015-11-16 23:52:16,155] [ERROR] koPlaceTreeView: Request:toggleOpenState_Open
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2435, in run
    rv = getattr(self, request)(args)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2509, in toggleOpenState_Open
    self.refreshTreeOnOpen_Aux(requester, uri, forceRefresh)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2481, in refreshTreeOnOpen_Aux
    items = requester.getDirListFromLocalPath(uri)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2352, in getDirListFromLocalPath
    item = self._finishGettingItem(uriparse.localPathToURI(full_name), name, itemType)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/komodo/uriparse.py", line 59, in localPathToURI
    % (localPath,koFileEx.path))
ValueError: '/Users/mike/observium/devel/raw.php?i=VvYR3Kdk' does not appear to be a proper local path [/Users/mike/observium/devel/raw.php]
```

and yes here really exist this file:
```
mks-mac:devel mike$ ls -l raw.*
-rw-rw-r--  1 mike  staff  50562 Nov  4 12:51 raw.php?i=VvYR3Kdk
```

OS X, Komodo IDE 9.3

**Comment by cgchoffman** [comment] 2015-11-16 22:44
I think I would agree with the error.  That's doesn't appear to be a proper path.  Why is there a question mark in your files name?  Does the issue go away if you `mv raw.php?i=VvYR3Kdk raw.php`?

**Comment by landy2005** [comment] 2015-11-17 07:05
This is error in the processing such paths!
Question mark complete valid character for files/dirs (in posix systems).
This file is created by accident, when I download raw content from github by wget cmd..
```
$ mkdir '????'
$ ls -l |grep ?
drwxrwxr-x  2 mstupalov mstupalov     4096 Nov 17 10:04 ????
```

Important thing is that the display of the tree, should not stop with "error" on the wrong files.
Can just ignore this files and display all other (and probably log with "warning").

I want to develop, and not to find out why I have not displayed files.

**Comment by Naatan** [comment] 2015-11-17 16:42
Right, while it is not a valid filename (to PHP, not the filesystem) we should still be able to show it and handle it where relevant. Things like debugging will probably still break, but that'd be intended.

**Comment by Defman21** [comment] 2016-07-20 17:14
Duplicate of #367

**Comment by cgchoffman** [comment] 2016-07-20 19:23
I'm going to go with #1510

**Closed by cgchoffman** 2016-07-20 19:23 UTC
Labels: Bug
