### ISSUE TITLE
Refactor code confirmation issues

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#2652] opened 2017-06-08 16:38 UTC
### Steps to Reproduce

1. Open project/code (I use php)
2. select function name
3. Code -> Refactoring -> Rename Class Member
4. Set additional info like "Replace", "Dirrectories", etc, click "Replace..."
5. Now opened window "Confirm Replacements" where should be displayed changes and confirm checkboxes

Second issue:
6. Click "Show changes"
7. Close this window with changes

### Expected results

1. Checkboxes should be smaller.
2. I should keep ability for any changes after close window "show changes"

### Actual results

1. Too big confirmation checkboxes, they cropped.
2. After close "Changes window", Komodo freeze, no any action can be used..
3. window with "Confirmation Replacements" now on top over all other windows.

Please see screencast from here:
https://owncloud.stupalov.ru/s/HvlHtfZXUt0Xu4c

### Platform Information

MacOS Sierra (10.12.5)

Komodo IDE, version 10.2.2, build 89895, platform macosx.
Built on Fri Apr 28 17:57:38 2017.

**Comment by cgchoffman** [comment] 2017-11-21 01:14
Issue 1 was fixed elsewhere: https://github.com/Komodo/KomodoEdit/issues/3081

The hanging dialog issue is something we've hit before but I can't for the life of me find the previous ticket and I can't find anything around OSX that helps with the issue.  From what I remember, the issue is  that we spawn 4  generations of  windows from a parent (the komodo ide window) and something breaks on OSX when you do that.  I believe the issue was a result of the "Show Changes" dialog you could open while doing a find replace in files.  

I've tried closing the first dialog so only 2 are open when the Show Changes dialog is opened.  This had no effect.  
I've tried changing the dialog from a `<window>` to a `<dialog>` (without much hope) to no effect.  

I'm not sure what to try as I'm not exactly sure what would be causing the issue here.

**Comment by cgchoffman** [comment] 2018-01-24 00:54
https://github.com/Komodo/KomodoIDE/commit/31fc3cb88c483a90e7f852a1774fe3f1f38cd1b6

Just had to take the `modal` option out of the line that opens the confirmation window *head to desk*.

**Closed by cgchoffman** 2018-01-24 00:54 UTC
Labels: Severity: Priority, Type: Bug
