### ISSUE TITLE
Tab is blank after minimize and restore window

### ISSUE THREAD

**Issue by jshrek** [Komodo/KomodoEdit#1642] opened 2016-05-31 20:44 UTC
### Short Summary
An open tab in Komodo Edit becomes blank when you restore application after minimizing it. Clicking on a second tab and then clicking back on the first tab makes it visible again.

### Steps to Reproduce
Open a new file and then minimize the Komodo Edit application and then restore the application.

### Expected results
Code in tab should still be visible.

### Actual results
Code in tab is not visible.

### Platform Information
Using Komodo Edit, version 9.3.2, build 16460
OSX 10.11.4

### Additional Information
Here is link to video of issue:
http://iwebss.com/test/bug.mov

**Comment by mitchell-as** [comment] 2016-05-31 21:16
Duplicate of #564.

**Closed by mitchell-as** 2016-05-31 21:16 UTC
Labels: Duplicate

**Comment by jshrek** [comment] 2016-05-31 21:19
Just upgraded to Komodo Edit, version 10.0.0, build 17209, platform macosx. Built on Wed May 11 22:00:40 2016 and the problem still exists.
