### ISSUE TITLE
Error loading template on fresh install.

### ISSUE THREAD

**Issue by jason-c-daniels** [Komodo/KomodoEdit#2165] opened 2016-11-19 19:41 UTC
### Short Summary
Error loading template for Python3 template when creating a new file on a fresh install of the 21 day trial of the KomodoIDE.

### Steps to Reproduce
0. Install Komodo 21 day trial and ActivePython
1. On windows 10, create the bolded part of the following path: C:\users\jdaniels\**Projects\Python**
2. Create a project named Project1 in the path from item 1 above.
3. Add a file from template, select the Python3 template. Make the file named "test1", lacking the extension.
4. Answer yes to the prompt asking to automatically add the extension.

### Expected results
I expected the file to be created according to the template.

### Actual results
I got an error message dialog with the following error message. _See Additional Info for the full message._
```
Error loading template 
'file:///C:/Program%20Files%20%28x86%29/ActiveState%20Komodo%20IDE%2010/lib/support/default-templates/Common/Python3.py'
```
After clearing the dialog an empty file with the correct name is created.

### Platform Information

*Komodo Edit or IDE?* 
Komodo IDE, version 10.1.1, build 89474.
Built on Thu Sep 01 14:27:01 2016.

*Operating System (and version)?* 
Windows 10

### Additional Information
```
Error loading template 'file:///C:/Program%20Files%20%28x86%29/ActiveState%20Komodo%20IDE%2010/lib/support/default-templates/Common/Python3.py'

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createFileFromTemplateURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._doFileNewFromTemplate :: line 325"  data: no]

Traceback:
viewManager.prototype._doFileNewFromTemplate@chrome://komodo/content/views.js:325:18
viewManager.prototype._newTemplate@chrome://komodo/content/views.js:240:15
viewManager.prototype.newTemplateAsync/<@chrome://komodo/content/views.js:278:19

```

**Comment by mitchell-as** [comment] 2016-11-21 15:11
Thanks, reproduced.

**Comment by cgchoffman** [comment] 2016-11-21 16:59
Is this 100% reproducible for you @jason-c-daniels ?

**Comment by jason-c-daniels** [comment] 2016-11-21 17:14
Here's what I know.
1. I did the steps as indicated. It was the first launch of the Komodo IDE.
2. I tried to create two files. Both of which exhibited that behavior. 
3. On starting the IDE this morning, the problem seems to have cleared up. 
4. I have not tried reinstalling. So this appears to be a post-install/FIRST install related issue.

Did you perform the steps exactly as indicated? (i.e. Do them on a machine that never had Komodo IDE installed before...)

**Comment by jason-c-daniels** [comment] 2016-11-21 17:18
Another thought I just had... perhaps Windows was indexing the files as it was just after install, and the service that does that left a file handle open, causing the failure to open the file? 

If this is reproducible under that circumstance, locking the template file, then perhaps it's worth improving the error message to indicate the file was locked by another process and calling it done?

**Comment by cgchoffman** [comment] 2016-11-21 17:18
I'm trying them right now.  Just wanted to confirm the issue.  This has already been reported but you thankfully actually included reproduction steps so I'm closing the other ticket in favor of yours.

**Comment by mitchell-as** [comment] 2016-11-21 17:18
@cgchoffman I reproduced with the provided steps. My error message box has the following

```Error interpolating template 'file:///home/mitchell/code/komodo/mozilla/build/moz3500-ko10.10/mozilla/ko-rel/dist/komodo-bits/support/default-templates/Common/Python3.py'

Exception: TypeError: scimoz(...) is undefined

Traceback:
sdkEditor/this.getCursorPosition@chrome://komodo/content/sdk/editor.js:424:32
sdkEditor/this.getLineNumber@chrome://komodo/content/sdk/editor.js:500:19
sdkEditor/this.getLine@chrome://komodo/content/sdk/editor.js:411:1
Interpolate_getViewData@chrome://komodo/content/run/interpolate.js:284:33
viewManager.prototype._doFileNewFromTemplate@chrome://komodo/content/views.js:364:24
viewManager.prototype._newTemplate@chrome://komodo/content/views.js:240:16
viewManager.prototype.newTemplateAsync/<@chrome://komodo/content/views.js:278:20


Komodo IDE, version 10.10.0-devel, build 89006.
Built on Thu Mar 24 12:17:56 2016.```

**Comment by jason-c-daniels** [comment] 2016-11-21 17:20
Oh, and It's always valid to ask if the steps to reproduce are intermittent/consistent. I feel guilty for not restarting the IDE and checking again. :-)

**Comment by cgchoffman** [comment] 2016-11-21 17:34
Ugh, I can never reproduce this.  I did a fresh install, removed my entire `ActiveState` folder, created a similar path and project. Created the file with no extension and allowed Komodo to add the extension and the file opens fine.  I'll have to pass ownership to you @mitchell-as.

**Comment by jason-c-daniels** [comment] 2016-11-21 17:39
I've been involved in fixing fresh install related bugs for the dev work I've done. I've found virtual machines to be helpful in reproducing issues.

If file locking is suspected as the culprit (it bears the ear marks of it so far), I've found [Process Exporer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) very helpful in identifying lock owners. 

Also, if needed I can hunt down, or if need be, write, a tool to hold an exclusive lock on an arbitrary file.

**Comment by mitchell-as** [comment] 2016-11-21 18:10
@cgchoffman According to the error message, the `scimoz()` function is undefined here: https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/sdk/editor.js#L424
To me it looks like there is no document available at the time, but I don't know enough about the template handling stuff to ascertain what to do or where to look. Do you have any ideas? Just try going up the stack from the error message I posted. You'll have a better idea than me. Thanks.

**Comment by cgchoffman** [comment] 2016-11-21 20:14
I'm not familiar with the template code either.  If I can't reproduce the issue then I can't test fixes.  I can certain walk the stack and see what it did but there is no way for me to test any theories.

@mitchell-as, how did you reproduce the issue?  It looks like you just reset your profile and started your development build.

**Comment by cgchoffman** [comment] 2016-11-21 20:15
@jason-c-daniels, Those tools are definitely helpful.  I've used them before, but I can't reproduce the issue so Process Explorer won't help me.  I have some old VMs in my old hard drive.  I might try and start one but I have little hope that will work.

**Comment by jason-c-daniels** [comment] 2016-11-21 20:49
@cgchoffman understood. about process explorer not being useful to help track down a potentially offending process when you're not seeing it happen. 

I neglected to add @mitchell-as in that comment. That's who I intended to use it as he's reproduced the issue. :-)

**Comment by mitchell-as** [comment] 2016-11-21 21:17
@cgchoffman Yes I started with a brand new profile and followed the steps in the original post.

**Comment by cgchoffman** [comment] 2016-11-22 17:01
Alright, so did I.  I don't really have time to install a VM and dig into this and since it only effects first boot I have to prioritize this.

**Comment by cgchoffman** [comment] 2016-11-29 19:02
Just discussed this with @Naatan, I think this is eventually going to be resolved by us replaceing the current template mechanic all together.  

one question for @jason-c-daniels, could you confirm your install dir.  Komodo was trying to load the template from
`'file:///C:/Program%Files%20%28x86%29/ActiveState%20Komodo%20IDE%2010/lib/support/default-templates/Common/Python3.py'

ie. `C:\Program Files (x86)\ActiveState Komodo IDE 10`

Is that the correct folder?

**Comment by jason-c-daniels** [comment] 2016-11-29 20:27
@cgchoffman That's the correct path/folder.

**Comment by cgchoffman** [comment] 2016-11-29 20:56
Thanks for confirming @jason-c-daniels

**Comment by cgchoffman** [comment] 2017-07-17 19:48
This feature is being replaced in Komodo 11 so I'm closing this.

**Closed by cgchoffman** 2017-07-17 19:48 UTC
Labels: Bug
