### ISSUE TITLE
Places: Can't show content of folder that has files or folders with "?" in their names

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1113] opened 2016-02-26 17:18 UTC
- create folder with any name
- in that folder create a folder with a name that contains a "?"
- create multiple files, one of them should have a "?" in it's name
- open the parent in Places

Expect:  to open the folder and see it's contents

Actually:
There are two results here;
1. When the folder has a "?" in it's name Places will show nothing and spit out an error
2. If the folder is renamed to remove the "?" then just the file that has a "?" in it's name will be missing.

**Comment by mitchell-as** [comment] 2016-04-25 17:11
Duplicate of #872

**Closed by mitchell-as** 2016-04-25 17:11 UTC
Labels: Bug
