### ISSUE TITLE
I can't reconnect with the server when I use OpenSSH Key file for authentication

### ISSUE THREAD

**Issue by yeraytac7** [Komodo/KomodoEdit#3535] opened 2018-04-23 09:32 UTC
### Short Summary

Hello,

Excuse me  for my English level. I'll try to explain myself as best I can

I found a problem when Komodo tries to reconnect with the server when the socket has been closed. Although the configuration specifies that it is used OpenSSH Key file for authentication, Komodo always ask for Login and Password.
![autentificacion_server_komodo_problem](https://user-images.githubusercontent.com/38651204/39117474-d3bfb7aa-46de-11e8-939e-de4c462c9ac1.jpg)

### Steps to Reproduce
Open Remote Directory with a server that uses OpenSSH Key file for authentication. 
Close the socket (edit a file and disabled the internet connection, try to save the file for Komodo detect that the socket was closed, and enabled the internet connection)

### Expected results
Reconnect to the server without asking for login and password that I don't use for connect to the server

### Actual results
I can't reconect, I close Komodo and reopen to reconnect with the server

### Platform Information

Komodo Edit, version 11.0.2
Windows 10

**Comment by cgchoffman** [comment] 2018-04-23 16:42
This is a dupe of #3399 but I'm closing that in favour of this ticket since this very succinctly explains the reproduction steps.  Thanks @yeraytac7.

**Comment by cgchoffman** [comment] 2018-04-23 23:06
After all that I STILL can't reproduce this.  I thought I could but it just turned out I had multiple servers configs for one server and Komodo was (correctly) using the wrong config.  Once I reconfigured my Publishing service (the other ticket references the publishing service so I was also testing that) to use the sshkey enabled config it used my key just fine.

@yeraytac7, do you have multiple configurations for one server by any chance?
Could you try opening *View > Tabs & Sidebars > Console* and running the following command then reproduce the issue:
```
require("ko/logging").getLogger("koRemoteConnectionService").setLevel(require("ko/logging").DEBUG)
```

Make sure you restart Komodo THEN do the above and reproduce the issue.  After that please send us your logs: *Help > Troubleshooting > View Log File*

**Comment by yeraytac7** [comment] 2018-04-24 07:53
Hello,

Yes, I have 2 different configurations for the same server (same IP, same User and same OpenSSH Key file, but different ports to connect to 2 different virtual machines).

When I star Komodo I can connect to both without problems and change from one to another, although I have to press the refresh button to see the folders of each machine. While the socket is open, I can work without problems with both machines (even having open files of both simultaneously).

When the connection with a machine is closed (timeout exceeded), it is impossible to reopen it and it is necessary to restart Komodo.

Log file:

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1941474/pystderr.log)

**Comment by cgchoffman** [comment] 2018-04-24 15:25
Thanks for the additional details.  It doesn't look like you ran the command I requested you run in the *console* before you sent those logs.  There are no DEBUG statements in it.  Can you make sure you did that and redo the steps?  Make sure you restart Komodo before doing anything otherwise the logs will be full other output that won't help.

**Comment by yeraytac7** [comment] 2018-04-25 07:10
Hello,

I run in the console that command:

require("ko/logging").getLogger("koRemoteConnectionService").setLevel(require("ko/logging").DEBUG)

![debugkomodo](https://user-images.githubusercontent.com/38651204/39230802-c66ec8e8-485f-11e8-9153-7070fbe0ab1a.jpg)

and then I closed Komodo and started it again. This is the file that it was generated , although I do not see any Debug and I have repeated the steps twice

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1945840/pystderr.log)
).

[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1945783/pystderr.log)

**Comment by cgchoffman** [comment] 2018-04-25 16:51
@yeraytac7, sorry for the confusion.  I said *Make sure you restart Komodo before doing anything*, meaning before you do any of the instructions I gave you, restart Komodo.
The steps are:
- restart Komodo
- run console command
- reproduce issue
- send logs

**Comment by yeraytac7** [comment] 2018-04-26 06:17
Hello,

Today I repeated the steps twice.

1. I start Komodo, the second I restart Komodo.
2. I run  console command
3. I reproduce the issue

But in the files I don't see any Debug. Here are the files:
[pystderr - copia.log](https://github.com/Komodo/KomodoEdit/files/1949924/pystderr.-.copia.log)
[pystderr - copia (2).log](https://github.com/Komodo/KomodoEdit/files/1949925/pystderr.-.copia.2.log)

**Comment by cgchoffman** [comment] 2018-04-26 17:26
Could you do the same process but change the console command to `require("ko/logging").getLogger("koSFTPConnection").setLevel(require("ko/logging").DEBUG)`?  Apologies for the back and forth and thank you for your patience.

**Comment by cgchoffman** [comment] 2018-05-01 17:29
My apologies @yeraytac7.  We need to set the logging lvl in the Python code which is actually creating the connections.  I've been having you set it in the Javascript code of Komodo.  

We're going to create a Userscript in your toolbox.  I've attached the Userscript which you can drag and drop onto Komodo but first you must rename it to give it a `.ktf` file extension rather than `.txt`.  I've also included a sample below of the code that we will run:
```
import logging
logging.getLogger("koRemoteConnectionService").setLevel(logging.DEBUG)
logging.getLogger("koSFTPConnection").setLevel(logging.DEBUG)
```
### The File
[Enable_Logging.txt](https://github.com/Komodo/KomodoEdit/files/1964605/Enable_Logging.txt)

Steps:
1. Download attached file
2. Rename to *Enable_Logging.ktf*
3. Drag and drop on Komodo
4. Click *Ok* to import tool
5. Either restart Komodo (I enabled a trigger to run it at start up) or find it in the toolbox and double click on it.
6. Repro issue.

**Note** since I added a "on Startup" trigger, you'll want to delete or disable this Userscript once we're done with it other wise you will have debug lvl logging enabled all the time.

Sorry for the lapse in helpful instructions here and thank you again for your patience.

**Comment by yeraytac7** [comment] 2018-05-03 11:04
Hello,

This is the file (just now with Debug). I changed a few things like my IP address for A.B.C.D
[pystderr - copia (5) - copia.log](https://github.com/Komodo/KomodoEdit/files/1970543/pystderr.-.copia.5.-.copia.log)

**Comment by yeraytac7** [comment] 2018-05-09 12:47
Hello,

As I explained in the reply email, the patch file created is good enough to consider that the bug is already resolved.

**Comment by cgchoffman** [comment] 2018-05-09 16:36
>Hello Carey,
The file you sent me works well enough for me even though it's not perfect.
I'll try to explain myself as best I can.
Following the steps I initially explained, I cannot reproduce this error again (now Komodo reconnects perfectly).
However, in these two days a few times the reconnection dialog box has appeared.
Obviously if I press 'Login' does not work, but if I press 'Cancel' and after the dialog box appears that the socket is already closed.
If later this, if I try to save the file again now work well (without the need to restart Komodo).

**Comment by cgchoffman** [comment] 2018-05-09 16:37
> However, in these two days a few times the reconnection dialog box has appeared.
What are you doing when this happens?

**Comment by cgchoffman** [comment] 2018-05-09 20:40
@yeraytac7 also you didn't send the logs I asked for.  I need those to check one other possible problem code path.  Please sent those logs.

**Comment by yeraytac7** [comment] 2018-05-10 07:29
Hello,

I have sent a email with the log file that is generated when I reproduce the steps that reproduced the bug but now works well.

**Comment by cgchoffman** [comment] 2018-05-10 17:55
I think we might have got it.  Thanks very much for those logs @yeraytac7.  I'll wait for you to try out the new file then I'll push my fix if you confirm it fixes the issue for you.

**Closed** 2018-05-11 17:50 UTC
Labels: Type: Bug

**Comment by yeraytac7** [comment] 2018-05-14 13:48
Yes,
That file resolves the issue. 
I have sent you a email with the log file.

**Comment by cgchoffman** [comment] 2018-05-14 17:16
That's GREAT.  It's rare to be able to fix a bug when we can't reproduce it internally.  Thanks for your patience.
