### ISSUE TITLE
"Open Files Widget" image missing in "Open Files" help topic

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#66] opened 2015-03-26 13:49 UTC
In the Komodo help content, it appears that the image showing the Open Files widget in the help topic for Open Files is missing.

![ke9-20150326](https://cloud.githubusercontent.com/assets/2390335/6847463/9b64794a-d38c-11e4-96ee-447a7e86ef4f.png)

Komodo Edit, version 9.0.0, build 15707, platform macosx.
Built on Thu Mar 19 06:08:01 2015.

**Comment by Naatan** [comment] 2015-03-26 14:44
Duplicate of #67 

Thanks for noticing :)

**Closed by Naatan** 2015-03-26 14:44 UTC
Labels: duplicate
