### ISSUE TITLE
Requesting a Bookmarks list like the Breakpoints list

### ISSUE THREAD

**Issue by AvalonNZ** [Komodo/KomodoEdit#2013] opened 2016-09-10 03:29 UTC
### Short Summary

I'd like to see a list of bookmarks similar to the existing list of breakpoints. 

I often set a lot of bookmarks in a file (some of my worst files are 4000+ lines long and can't be broken up) and then want to jump to a specific one, or remove a few that are no longer required. In both cases I'd rather not bounce through the file trying to find the one I want. 

ie: I'd like to be able to manage the bookmarks list for a file and jump to specific bookmarks from a sidebar panel, just like I can with the breakpoints list.

**Comment by mitchell-as** [comment] 2016-09-12 14:11
Duplicate of #844. This is on our TODO list :)

**Closed by mitchell-as** 2016-09-12 14:11 UTC

**Comment by AvalonNZ** [comment] 2016-09-12 14:38
Thanks Mitchell :-)

**Comment by cgchoffman** [comment] 2016-09-12 15:23
In the meantime you could use QuickBookmarks: http://docs.komodoide.com/Manual/editor#editing_navigating-within-files_bookmarks-and-marks

**Comment by AvalonNZ** [comment] 2016-09-14 14:52
Thanks for the thought Carey. Unfortunately the file I have the most
problems with has over 4000 lines of code in it (it's my main common-CRUD
class for a hellishly complex set of tables with all kinds of complex
validation rules) and 10 bookmarks just aren't enough. The other issue is
that I'm likely to set 15 bookmarks on day one, another 12 on day two, and
then on day three I'm suddenly trying to remember what I did two days ago.

Cheers,
Simon

**Comment by Naatan** [comment] 2016-09-14 15:10
Note as mentioned in #844 the intend is to extend the Bookmarks scope with more functionality. We won't be adding a full on panel like we have for breakpoint management.
