### ISSUE TITLE
Komodo IDE get stuck sporadically

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#2492] opened 2017-04-19 06:19 UTC
### Short Summary

Sometimes while working Komodo get stuck (beach ball is rotating all the time and the window is not accessible anymore). I have to kill Komodo and get the crash report attached (in the last two hours it happened two times).

### Steps to Reproduce

None. Komodo get stuck sporadically.
I am just editing some text files - nothing special.

### Platform Information

*Komodo IDE* 
*Komodo 10.2.1* 
*macOS Sierra 10.12.4* 

### Additional Information

[log.txt](https://github.com/Komodo/KomodoEdit/files/931991/log.txt)

**Comment by kevinlieser** [comment] 2017-04-19 08:33
And again...

**Comment by mitchell-as** [comment] 2017-04-19 14:14
This looks like a duplicate of #2424, which appears to be an OSX bug introduced during a Sierra update. Try the suggestion(s) here: https://github.com/Komodo/KomodoEdit/issues/2424#issuecomment-292198581

**Closed by mitchell-as** 2017-04-19 14:14 UTC
