### ISSUE TITLE
New file from Template is not working

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2773] opened 2017-08-08 18:36 UTC
### Short Summary

New file from Template option opens up Commando and does not let you create a file

### Steps to Reproduce
1. Right click on folder in places pane to select 'New file from template' option

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 11
*Operating System (and version)?* mac

### Additional Information

 
![image](https://user-images.githubusercontent.com/26605593/29088385-c0789076-7c2d-11e7-841c-7dd8eb2b20a6.png)

**Comment by cgchoffman** [comment] 2017-08-08 18:38
@mjainQA, make sure you include your build number with K11 reports.  This should be fixed.  Also include your log file.

**Comment by mjainQA** [comment] 2017-08-08 19:10
Komodo IDE, version 11.0.0-alpha1, build 90318, platform macosx. Built on Wed Aug 2 23:44:27 2017.

**Comment by cgchoffman** [comment] 2017-08-08 19:22
@mjainQA logs please.  Reproduce the issue, share your logs then get the latest.  You're a few builds behind.  Latest OSX build is http://komodo.nas1.activestate.com/builds/11.0.0a1/DevBuilds/assvn-master-90346/

**Comment by mjainQA** [comment] 2017-08-08 23:31
Able to reproduce the issue:

Komodo IDE, version 11.0.0-alpha1, build 90376, platform macosx.
Built on Tue Aug 8 14:47:33 2017.

Log file: 
[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/1209821/pystderr.txt)

**Comment by Naatan** [comment] 2017-08-09 15:12
This is actually fixed but since you already upgraded your profile the fix won't land for you. It's probably best if you backup and delete your Komodo 11.0 profile directory and let it re-import.

**Comment by mjainQA** [comment] 2017-08-11 18:05
Resolved by deleting the profile dir.

**Closed** 2017-08-11 18:39 UTC
Labels: Pending: Internal
