### ISSUE TITLE
snippet

### ISSUE THREAD

**Issue by JeremieRousseau** [Komodo/KomodoEdit#1368] opened 2016-05-04 13:42 UTC
### Short Summary

not very important but i tried to create a snippet called "con"
to create a snippet : console.log("|");
(add this snippet in autocomplete words for javascript users )
i had a bug, but with "co" that worked find !
good software.

### Steps to Reproduce
Abbreviations->JavaScript-common->JavaScript->Add->New Snippet->"con" --->wait... some time that save auto abbreviation never work.

### Actual results
if i clicked on the snippet that worked and with key binding too.

### Platform Information

*Komodo  IDE 9.3 trial version* 
 window 7

**Comment by mitchell-as** [comment] 2016-05-04 14:45
Hi, did you check the "auto-abbreviation" box in the "add new snippet" dialog? I followed your steps, checked the box, typed `con`, pressed "tab", and my snippet was inserted.

**Comment by Naatan** [comment] 2016-05-04 15:12
I'm confused about the steps. Your steps only mention creating the snippet; do you mean the issue is with creating or using the snippet?

**Comment by JeremieRousseau** [comment] 2016-05-08 12:28
that created a snippet but i never can used "con" i use "co".

**Comment by cgchoffman** [comment] 2016-05-09 17:42
> Abbreviations->JavaScript-common->JavaScript->Add->New Snippet->"con" --->wait... some time that save auto abbreviation never work.
> 
> Expected results

This is the part that is confusing me.  You just wait for it to complete?  You need to trigger it by pressing tab (or space depending on your preference settings).  I was able to create a snippet with the same name and set to Auto-Abbrev and it works as expected for me.

**Comment by cgchoffman** [comment] 2016-06-22 22:17
Closing in favour of #1737

**Closed by cgchoffman** 2016-06-22 22:17 UTC
Labels: Pending Response
