### ISSUE TITLE
Elastic tabstops not working anymore in 10.1.0

### ISSUE THREAD

**Issue by ANSI-C** [Komodo/KomodoEdit#1989] opened 2016-09-01 15:36 UTC
### Short Summary

They don't work anymore in last release

### Steps to Reproduce

Paste this code in a perl file:

	my $a	= 1;
	my $longvariablename	= 2;

### Expected results

equal signs should align

### Actual results

the don't (used to do)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* version 10.1.0, build 89455, platform win32-x86
*Operating System (and version)?* Windows 8.1

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by ANSI-C** [comment] 2016-09-01 15:37
Probably web form turned tabs to spaces, but you get the idea.

**Comment by mitchell-as** [comment] 2016-09-01 15:43
You must have both "Prefer Tabs over Spaces" and "Enable Elastic Tab Stops" checked in Edit > Preferences > Editor > Indentation before pasting in text with tabs in it. Once I did that, it works.

**Comment by ANSI-C** [comment] 2016-09-01 15:50
I already had it that way, double checked before opening the ticket, it does not work:

![sshot-2016-09-01- 17-49-03](https://cloud.githubusercontent.com/assets/7015883/18174077/74479b98-706c-11e6-8cb0-7a72e648ade4.png)

**Comment by ANSI-C** [comment] 2016-09-01 15:59
Can you acknowledge the bug, or is there any other setting to change to make it working?

**Comment by mitchell-as** [comment] 2016-09-01 16:06
I cannot reproduce the bug. See my image (sorry for the contrast). Does your per-language indentation settings also prefer tabs? What happens when you press Tab in the file? If there are any other steps you are following that I'm not aware of, please let me know.

![ets](https://cloud.githubusercontent.com/assets/12902397/18174730/8a10a44a-703c-11e6-8c3f-d2fd7bfb1a16.png)

**Comment by ANSI-C** [comment] 2016-09-01 16:32
Hi, language setting is preferring tabs over spaces as well, this is puzzling for me too, it used to work before latest update. I made no changes to the configuration.

![sshot-2016-09-01- 18-30-03](https://cloud.githubusercontent.com/assets/7015883/18175645/52c22546-7072-11e6-9765-661d52d49313.png)

**Comment by mitchell-as** [comment] 2016-09-01 16:55
I believe you. I don't believe the elastic-tabstops module is being loaded. The only way it wouldn't be loaded is if it didn't exist, and the only way it wouldn't exist (I think) is if it got lost in the update. I see two fixes:

1. Try a full 10.1 reinstall (no auto-update from 10.0.1) if you can.
2. Go to your existing install's `lib/mozilla/` folder and copy everything from `distribution/bundles/elastic-tabstops@activestate.com/` into `extensions/elastic-tabstops@activestate.com/`. Then restart Komodo.

**Comment by ANSI-C** [comment] 2016-09-01 20:31
Hi, yes, I did the update in place. Now uninstalled the previous version and trying to install from scratch the _next_ button remains disabled:
![sshot-2016-09-01- 22-29-02](https://cloud.githubusercontent.com/assets/7015883/18183255/d1a2eb04-7093-11e6-9bae-142637ccaf7d.png)

**Comment by mitchell-as** [comment] 2016-09-01 20:38
The directory needs to be empty. Please clear it before proceeding. There may be a residual file or folder or two.

**Comment by ANSI-C** [comment] 2016-09-01 20:42
Directory was non existent, changed the path anyway and then has been able to reinstall from scratch.
Elastic tabstops still not working.

**Comment by mitchell-as** [comment] 2016-09-01 20:48
Okay, it appears that our build system is no longer packaging elastic tabstops correctly. I talked to one of our devs and the packaging for elastic tabstops did change from 10.0 to 10.1. In this case, you must manually copy the `elastic-tabstops@activestate.com/` folder from your installation's `lib/mozilla/distribution/bundles/` to `lib/mozilla/extensions/` folder. Then restart Komodo. Sorry for all the trouble :(

**Closed** 2016-09-01 21:18 UTC
Labels: Bug: Regression

**Comment by ANSI-C** [comment] 2016-09-01 23:01
Hello, the workaround fixed the problem, many thanks.
Let us know if there are other extensions that need to be moved.
