### ISSUE TITLE
Go to definition not working for PHP

### ISSUE THREAD

**Issue by lagbox** [Komodo/KomodoEdit#2826] opened 2017-08-12 04:59 UTC
### Short Summary

Go To Definition on anything that is outside of the current file yields "Could not find definition".

### Steps to Reproduce

Right click -> Go to Definition on any class names or functions defined outside the current file.

### Expected results

Jump to correct file at the correct line for class/function/variable definition.

### Actual results

"Could not find definition"

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.0-alpha1, build 90396, platform linux-x86_64
*Operating System (and version)?* Ubuntu 16.10

### Additional Information

CodeIntel scan has ran for current project.

In log file multiple times:
> [2017-08-12 00:50:51,538] [ERROR] codeintel/service/mediator: Request failed with message: Failed calling API method: getDefinition, message: 'NoneType' object has no attribute 'filename' (-32603)

**Comment by Naatan** [comment] 2017-08-14 15:48
Could you share a code sample that reproduces your issue? This appears to be working fine for me.

**Comment by lagbox** [comment] 2017-08-14 17:00
It is every project I open, which all happen to be Laravel projects.

**Comment by mitchell-as** [comment] 2017-08-14 17:22
Hi, I am not able to reproduce this. I have a simple project with two files:

foo.php:
```
<?php
class Foo {

}
```

bar.php:
```
<?php
include 'foo.php';

$foo = new Foo();
```

After opening the project I right-click on "Foo" in `bar.php`, select "Go to Definition", and Komodo takes me to `foo.php`'s `Foo` class definition.

**Comment by lagbox** [comment] 2017-08-14 17:39
Laravel projects. Modern php uses composer.

**Comment by lagbox** [comment] 2017-08-14 17:56
change your `bar.php`:

```php
<?php

class Bar
{
   public function __construct()
   {
       $foo = new Foo;
   }
}
```
Now try to get the definition of `Foo`.

**Comment by mitchell-as** [comment] 2017-08-14 18:12
@lagbox Yes, with that change I am no longer taken to `foo.php` since Komodo has no reference point as to which "Foo" to go to (it could be literally anywhere in the database).

With the correct include:

```
<?php

include 'foo.php';

class Bar
{
   public function __construct()
   {
       $foo = new Foo;
   }
}
```

I get the expected behavior.

**Comment by Naatan** [comment] 2017-08-14 19:16
I've created a test project that reproduces the problem. Simply open test.php and invoke go to definition on line 7 colum 14 (Date).

[PHP-Autoloader.zip](https://github.com/Komodo/KomodoEdit/files/1223194/PHP-Autoloader.zip)

**Comment by lagbox** [comment] 2017-08-15 14:47
No one writes an include statement any more. The frameworks all use composer to do the autoloading.

**Comment by mitchell-as** [comment] 2017-08-15 16:18
Fixed via https://github.com/Komodo/codeintel/commit/d9292e2c7aef03e1f9a9bbfa56ada8544e49dc56 and https://github.com/Komodo/codeintel/commit/76012eeadff936b1c4c691cd1865791e325ef872

**Closed by mitchell-as** 2017-08-15 16:18 UTC
Labels: Component: CodeIntel, Introduced: 11, Severity: Priority, Type: Bug
