### ISSUE TITLE
Code tree in the right pane is blank after restoring the last workspace on IDE startup

### ISSUE THREAD

**Issue by uFire** [Komodo/KomodoEdit#1618] opened 2016-05-27 07:23 UTC
### Short Summary
If Komodo IDE is set to restore the last workspace on startup, the "Code" tree (right pane) is always blank on startup. The only way to get it filled in is closing/reopening every file/tab one by one.

### Steps to Reproduce
Set Komodo IDE to restore the last workspace on startup (Prefs -> Workspace). Open a few Perl files - you will see their subroutines tree in the right pane's "Code" tab. Exit KomodoIDE and start it again - workspace is restored but "Code" tab in the right pane is blank.

### Expected results
"Code" tab in the right pane should contain the subroutines tree of all opened files.

### Actual results
"Code" tab in the right pane is blank.

### Platform Information
Komodo IDE, version 10.0.0, build 89159
Windows 10 x64 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment] 2016-05-27 14:37
I am not able to reproduce. While my code browser is initially blank, the symbols do show up eventually after a bit of time (a scan is necessary to populate the view). I do not need to close and re-open any of the files.

Is there anything abnormal in your error log? (Help > Troubleshooting > View Log File)

**Comment by uFire** [comment] 2016-05-27 21:22
Well, after playing around with various settings, I've discovered that "Code" tree remains blank on last workspace restore only if background syntax checking AND Perl Critic are "on" in the Prefs->Syntax&Spell Checking. Reproduced multiple times. Here is my log file:

[pystderr.zip](https://github.com/Komodo/KomodoEdit/files/287352/pystderr.zip)

### Platform Information
Komodo IDE, version 10.0.0, build 89159
Activestate Perl 5.16.3 Build 1603
Perl::Critic 1.126
criticism 1.02
Windows 10 x64

**Comment by Naatan** [comment] 2016-05-30 15:26
Are you saying the results are inconsistent/random? Starting to sound like it could be some sort of race condition.

In cases where it doesnt load, does switching back and forth between buffers force it to load?

Also, is it always the same type of file (eg. Perl) which exhibits the problem or have you reproduced it on several languages?

**Comment by uFire** [comment] 2016-05-30 21:06
Yes, results inconsistent. I am on a not very powerful machine - Intel Core2Duo E8200 with 8GB of RAM and it seems like when I turn PerlCritic on, it takes more load on the CPU to load the workspace with a bunch of files opened from remote FTP location on startup and in 95% of cases Code tab not populated. The only way to get it populated with subroutines list is closing and opening each file one by one. Noting else helped. Switching back and forth between buffers doesn't help also.

I don't know about other languages because I am using KomodoIDE for Perl only.

As for the setting Prefs -> Interactive Shell -> Preferred Language: to Perl or Python I mentioned above - I think different results also related to race/load condition because I don't have a Python interpreter installed so setting this to a Python caused less load and that is why percentage of success with Code tab populating were higher.

BTW, this problem has occured sometimes since v9, but in v10 it became a nightmare.

Log file "right after startup" attached: [pystderr.zip](https://github.com/Komodo/KomodoEdit/files/290079/pystderr.zip)

You can see empty Code pane here. Also, there is no breadcrumbs above the editor window and a bunch of errors in the log file attached - I already submitted this issue [#1617](https://github.com/Komodo/KomodoEdit/issues/1617)
![screenshot 2016-05-30 23 55 13](https://cloud.githubusercontent.com/assets/19604379/15658184/0f458d48-26c2-11e6-81e8-dc4c74de3ada.png)

**Comment by Naatan** [comment] 2016-05-31 15:28
Breadcrumbs aren't loaded due to a bug with remote files, we'll look into this for 10.0.1.

Does the code browser fail to load for remote files only or does it fail on all types of files?

**Comment by uFire** [comment] 2016-06-01 00:00
Experimented a bit - it doesn't matter if the file local or remote, code browser fail to load in both cases.

BTW, for the local files where breadcrumbs are working, there are a subroutine list at the end of the string and it is always loaded just fine.

As for the breadcrumbs issue [#1617](https://github.com/Komodo/KomodoEdit/issues/1617) I submitted - I didn't knew you took it into your schedule because my ticket still having "Pending internal" status. Anyway, I am glad you sorted this out, thank you.

**Comment by mitchell-as** [comment] 2016-06-01 13:47
@uFire this is a long shot, but does your "codeintel.log" file show anything abnormal? It's in your Komodo profile directory as well (something like c:\users\username\AppData\local\komodo\10.0\).

**Comment by uFire** [comment] 2016-06-01 18:54
@mitchell-as nothing abnormal in the "codeintel.log" file, it is empty all the time. I did a reset codeintel db - nothing have changed.

**Comment by Naatan** [comment] 2016-06-02 15:50
@mitchell-as anything he could run via the console to see where the problem might reside?

**Comment by mitchell-as** [comment] 2016-06-03 14:19
I really don't know what could be going wrong here other than some sort of race condition that you suggested earlier @Naatan.

**Comment by Naatan** [comment] 2016-06-03 15:07
@mitchell-as but switching back and forth between files ought to fix it. We need to at least figure out what type of state he is in and how it can be addressed.

**Comment by mitchell-as** [comment] 2016-06-03 15:31
@uFire instead of switching between buffers, what happens if you type something in and wait a few seconds? Does that cause the code browser to repopulate?

**Comment by uFire** [comment] 2016-06-04 03:31
@mitchell-as when code browser is blank on startup and if I create a new subroutine in the Perl file opened, I see its name in a dropdown list at the end of the breadcrumbs almost instantly, but code browser keeps blank. You can see that in the screenshot attached.

As I said, the only way to populate the code browser after last workspace restore is closing and re-opening each file one by one. I played a lot with preferences, started it up a few hundred times since I installed it. I have reinstalled Komodo twice - first time cleaned up my sysreg, and a second is installed it to the fresh Windows 10 instance with no other software installed at all (I have backups). No changes, the problem still persists if I have background syntax checking and Perl critic enabled.

You know, I started thinking this might be a result of some other bug not related to the code browser directly and maybe it worth waiting for 10.0.1 to see if things could change.

![screenshot 2016-06-04 06 13 17](https://cloud.githubusercontent.com/assets/19604379/15797304/87da930a-2a1b-11e6-9791-b312381e6402.png)

**Comment by mitchell-as** [comment] 2016-06-06 15:20
Thanks for the screenshot. So Komodo is correctly processing your source file in order to populate the breadcrumb list. For whatever reason Komodo is not doing the same for the section list. @Naatan this appears to rule out Codeintel and friends. Sounds like an issue with the UI code.

**Comment by Naatan** [comment] 2016-06-06 15:43
@uFire Please try the following:

 * Reproduce the issue (ie. get a buffer open for which the code browser widget is "broken")
 * Enter and execute the following in the Console widget (bottom pane):

```
ko.codebrowser.manager.view.remove_buf(ko.views.manager.currentView.koDoc.ciBuf)
ko.codebrowser.manager.view.add_buf(ko.views.manager.currentView.koDoc.ciBuf)
```

Does this force it to load the code browser widget?

**Comment by uFire** [comment] 2016-06-06 16:21
@Naatan Yess!! It worked. Code browser got populated instantly.

By the way, it works even by entering the second command alone. I hope you finally identified the problem. :)

**Comment by Naatan** [comment] 2016-06-06 16:24
I may have.

@mitchell-as is there an appropriate event I can listen to to ensure codeintel is ready?

**Comment by mitchell-as** [comment] 2016-06-07 17:29
@Naatan it looks like https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/codeintel/codeintel.p.js#L85 is run when Komodo gets a notification from the codeintel process that it has activated, and https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/content/codeintel/codeintel.p.js#L95 seems to emit an event. Perhaps you can hook into that.

**Comment by Naatan** [comment] 2016-06-07 18:15
Thanks @mitchell-as, I'll try that.

**Comment by uFire** [comment] 2016-07-23 13:14
Hello Naatan,

Is there a way to create a custom button in the top toolbar to execute the following two console commands on the current file?
```
ko.codebrowser.manager.view.remove_buf(ko.views.manager.currentView.koDoc.ciBuf)
ko.codebrowser.manager.view.add_buf(ko.views.manager.currentView.koDoc.ciBuf)
```
It could be a temporary workaround until you fix this bug in 10.1, because it is a nightmare reloading each file every time I start Komodo to get code browser populated. I tried creating Userscript/Command but can't get it to work.

Thank you!

**Comment by Defman21** [comment] 2016-07-23 13:51
There's `Add - New Custom Toolbar` in `Toolbox` pane (RMB click on it)

**Comment by uFire** [comment] 2016-07-23 14:00
@Defman21 Thank you, I know how to add a custom toolbar, but I stuck with the code itself.

**Comment by Defman21** [comment] 2016-07-23 14:13
```
var koDoc = require('ko/views').current().get('koDoc');
ko.codebrowser.manager.view.remove_buf(koDoc.ciBuf);
ko.codebrowser.manager.view.add_buf(koDoc.ciBuf);
```

This should work.

**Comment by uFire** [comment] 2016-07-23 14:17
@Defman21 Yess! It works! Thank you!

**Comment by Defman21** [comment] 2016-07-23 14:19
You're welcome :)

**Comment by uFire** [comment] 2016-07-29 00:38
Hi @Defman21 

One more question. :) Is there a way to make this code work for all open files? I mean all tabs. 

It would be better clicking that button in toolbar once for all open files rather than clicking it for each file separately, especially if there 20 tabs open :)

Or maybe even make that code run for all open files with a delay of  60 seconds automatically after Komodo starts?

Thanks in advance!

**Comment by cgchoffman** [comment] 2016-07-29 00:58
This should do it:
```
require('ko/views').all().forEach(function(item, index) {
    ko.codebrowser.manager.view.remove_buf(item.koDoc.ciBuf);
    ko.codebrowser.manager.view.add_buf(item.koDoc.ciBuf);
    alert(index);
});
```

```

**Comment by Naatan** [comment] 2016-08-15 16:34
Fixed with https://github.com/Komodo/KomodoIDE/commit/b4e4f3ba2a403db11c71f46735926c28baabf526

**Closed by Naatan** 2016-08-15 16:34 UTC
Labels: Bug, Severity: Priority
