### ISSUE TITLE
KomodoIDE 10 beta UI: Missing Elements with certain interface settings

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#1434] opened 2016-05-10 06:53 UTC
### Short Summary
Using a certain combination of Interface settings results in missing essential UI-Elements 

![komodo_2016-05-10_08-47-39](https://cloud.githubusercontent.com/assets/419075/15137755/f6e8385e-168b-11e6-8f54-fbe6e36eff7b.png)

Following elements are missing:
- Pressing ALT there is no Close/Minimize/Maximize button .... (How to close Komodo with mouse?)

- Button "Toogle focus mode" is available on Toolbar - pressing this button, Komodo switches into focus mode - but there is no button available anymore to toolge back (How to leave focus mode with mouse?)

### Expected results
Missing UI items should be available!

### Platform Information
KomodoIDE 10 nightly 89113
Win7 Ultimate 64bit SP1

**Comment by Naatan** [comment] 2016-05-10 15:28
It seems the window titlebar isnt showing when selecting native window borders on windows. I'll make this issue about that (since you are reporting multiple issues in one ticket).

For ALT not working, please open a new bug if you can reproduce this, although I am not able to reproduce this myself (ALT menu works fine for me).

For toggle focus mode, you can use the ALT menu to toggle this back (ie. ALT > View > Toggle Focus Mode). If ALT isnt working for you it makes sense that this would not also.

**Comment by Naatan** [comment] 2016-05-10 16:33
This was fixed with https://github.com/Komodo/KomodoEdit/commit/e42309891ae280045926d44b2055287691f4de78

**Closed by Naatan** 2016-05-10 16:33 UTC
Labels: Blocker, Bug
