### ISSUE TITLE
Komodo get's stuck when there is now internet connection

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2035] opened 2016-09-22 06:14 UTC
### Short Summary
I recently worked on a project that needs to keep running when there is no internet conection.
To test this I disconnect my computer from the internet (just pulling out the cable) only when I do this, Komodo totaly freezes up and get stuck.

### Steps to Reproduce
Pull out the internetconnection from you're computer, when working on remote files.

### Expected results
Komdo will prompt that it cannot connect to the remote server, or has no connection.

### Actual results
Komodo freezes up and get stuck.

### Platform Information
Komodo 10.1.1 Windows 10

**Comment by Naatan** [comment] 2016-09-22 15:47
This is essentially a duplicate of #1959, as the thing that is making Komodo hang is that it is timing out on those remote connections, and since they're synchronous that makes Komodo hang.

**Closed by Naatan** 2016-09-22 15:47 UTC
