### ISSUE TITLE
IDE X, Subversion status issues

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1523] opened 2016-05-18 15:30 UTC
### Short Summary

1. Not displayed subversion status for files in places and tabs (see screenshot below, compared with IDE 9)
2. Diff not displayed correctly by key combination Ctrl+K, D

### Steps to Reproduce

1. All simple, I not found any config option, but by default svn status for files not displayed

2. When I bind keys Ctrl+K, D - displayed window where should be diff of local copy with latest revision, but really diff not displayed, only show text: "Loading asynchronously..."
But if I select from menu by rigth mouse click: "Source Code Control -> Show Changes in file", than diff display correctly.

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

### Additional Information

![komodo-svn](https://cloud.githubusercontent.com/assets/217520/15364392/73f9c5a4-1d2d-11e6-885e-a6571d3e441a.png)

**Comment by Naatan** [comment] 2016-05-18 15:33
I've not seen this myself. Does your Places pane -never- show the SCC colors or just randomly?

**Comment by landy2005** [comment] 2016-05-18 15:44
I install this version of IDE only today, for today it never show SCC statuses.
(Not know why you said "colors", I mean SCC icons "green check mark", "pen").

About colours - I use changed color scheme "Classic" but with changed background colour for editior.
No other changes in config.

**Comment by landy2005** [comment] 2016-05-18 15:50
Additional info about svn:
```
$ svn --version
svn, version 1.9.3 (r1718519)
   compiled Mar 14 2016, 13:27:08 on x86_64-apple-darwin14.5.0
```
Installed from mac ports, full path: `/opt/local/bin/svn`

**Comment by Naatan** [comment] 2016-05-18 15:59
Thanks, I'll dig in when I can.

**Comment by Naatan** [comment] 2016-05-19 19:53
I'm not able to reproduce this. Can you see if you can reproduce it in safe-mode? Help > Troubleshooting > Restart in safe-mode.

**Comment by landy2005** [comment] 2016-05-20 18:39
I restarted in safe-mode and SVC menu complete not worked now.

**Comment by cgchoffman** [comment] 2016-05-20 18:49
> I restarted in safe-mode and SVC menu complete not worked now.

Make sure it's enabled Prefs > Source Code Control > Subversion.

**Comment by Naatan** [comment] 2016-05-20 18:50
Safe-mode resets all your settings, so you may have to reconfigure subversion again under Preferences > Source Code Control.

**Comment by landy2005** [comment] 2016-05-20 19:24
Well, I restart in safe-mode, set correct svn path {{/opt/local/bin/svn}} and refresh view for project.

Still not have VCS status icons,
"Ctrl+K, D" - still not show diff (hangs window with "Loading async").

**Comment by Naatan** [comment] 2016-05-20 19:44
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by landy2005** [comment] 2016-05-20 21:08
I repeat all steps in safe-mode, and "View Log File" said: "The log file does not exist:"

In normal mode after key combination no new entries in log, fut anyway full log:
```
[2016-05-21 00:00:35,745] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform macosx, running on Darwin 15.5.0 version Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64)
[2016-05-21 00:00:35,745] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed May 11 15:42:24 2016
[2016-05-21 00:00:35,746] [INFO] koInitService: installing Komodo samples to '/Users/mike/Library/Application Support/KomodoIDE/10.0/samples'
[2016-05-21 00:00:35,852] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2016-05-21 00:00:36,235] [WARNING] koLess: Clearing local and file cache
[2016-05-21 00:00:36,295] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-21 00:00:36,799] [ERROR] console-logger: ReferenceError: require is not defined (2) in chrome://komodo/content/bindings/windows.xml:39
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 39, in 

[2016-05-21 00:00:36,824] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-21 00:00:37,047] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 204, in 

[2016-05-21 00:00:37,469] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2016-05-21 00:00:37,469] [WARNING] keybindings: [Ctrl+Shift+Right] was used for 'cmd_endOfWordExtend', overriding to use 'cmd_selectRectCharNext'
[2016-05-21 00:00:37,469] [WARNING] keybindings: [Ctrl+Shift+Left] was used for 'cmd_selectWordLeft', overriding to use 'cmd_selectRectCharPrevious'
[2016-05-21 00:00:38,044] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-21 00:00:38,123] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-21 00:00:38,153] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-21 00:00:38,153] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-21 00:00:38,579] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2016-05-21 00:00:38,886] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-05-21 00:00:38,888] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2016-05-21 00:00:41,072] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-21 00:00:41,077] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
ERROR:xpcom:Creation of class '<class 'component:koCommandmentService.KoCommandmentService'>' failed!
Exception details follow

ERROR:xpcom:Unhandled exception calling 'int8 * createInstance(in nsISomething, in nsIID &, out retval InterfaceIs *);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/server/factory.py", line 57, in createInstance
    return self.klass()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koCommandmentService.py", line 444, in __init__
    self._reader = _CommandmentsReader(koDirs.userDataDir, ver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koCommandmentService.py", line 353, in __init__
    self._pipe = os.open(self._commandmentsFileName, os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/Users/mike/Library/Application Support/KomodoIDE/10.0/commandments.fifo'
[2016-05-21 00:00:41,088] [ERROR] koInitService: Unable to start 'koCommandmentService' service: '@activestate.com/koCommandmentService;1'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 371, in loadStartupCategories
    getService(components.interfaces.nsIObserver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147500037 (NS_ERROR_FAILURE)
[2016-05-21 00:00:41,099] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-21 00:00:50,568] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-21 00:00:50,569] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-21 00:01:46,866] [WARNING] views: Inconsistent view count in view_closed event
[2016-05-21 00:01:46,919] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-21 00:01:46,996] [WARNING] views: Inconsistent view count in view_opened event
[2016-05-21 00:02:15,126] [DEBUG] console: error: TypeError {}
[2016-05-21 00:04:52,139] [WARNING] views: Inconsistent view count in view_closed event
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdog/observers/api.py", line 266, in run
    self._dispatch_events(self.event_queue, self.timeout)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdog/observers/api.py", line 251, in _dispatch_events
    self.dispatch_event(event, watch)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdog/observers/api.py", line 433, in dispatch_event
    handler.dispatch(event)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdog/events.py", line 457, in dispatch
    self.on_any_event(event)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdogFileNotifications.py", line 51, in on_any_event
    self.notify_observer_monitor(event.src_path, flag)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/watchdogFileNotifications.py", line 46, in notify_observer_monitor
    self.observer_monitor.notifyChanges({path: flags})
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/osFileNotificationUtils.py", line 331, in notifyChanges
    self.sendObserverNotifications(observer, uri, change)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/components.py", line 259, in wrapperFn
    threadMgr = classes["@mozilla.org/thread-manager;1"]\
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Naatan** [comment] 2016-05-20 21:09
Is your Places widget pointed at a folder that holds an .svn folder?

**Comment by landy2005** [comment] 2016-05-20 21:13
Yes,
as I said earlier, if select from file menu "Source Code Control > Show Changes in File", than diff showed normally (as expected).

**Comment by landy2005** [comment] 2016-05-20 21:39
Heh, seems as additional issue: Ctrl+K, H (VCS history) also not worked.

I moved dir {{10.0}} to {{10.0.bak}} in {{$HOME/Library/Application Support/KomodoIDE}},
default config created (all questions said yes, without any changes)..
Issue not fixed!

**Comment by Naatan** [comment] 2016-05-24 15:54
Please try executing this code from your Console widget (bottom pane):

```
ko.logging.getLogger("koFileStatusService").setLevel(10);
ko.logging.getLogger("koSVN").setLevel(10);
```

Then close your project and open it again. After that copy your error log into this ticket.

**Comment by landy2005** [comment] 2016-05-24 18:34
done,
now I see in log for loop:
```
[2016-05-24 21:26:06,318] [INFO] koFileStatusService: _process:: starting file status check
[2016-05-24 21:26:06,319] [INFO] koFileStatusService: num files to check: 0, isBackgroundCheck: True
[2016-05-24 21:26:06,319] [DEBUG] koFileStatusService: Skipping bzr, not active
[2016-05-24 21:26:06,320] [DEBUG] koFileStatusService: Skipping hg, not active
[2016-05-24 21:26:06,320] [DEBUG] koFileStatusService: Skipping p4, not active
[2016-05-24 21:26:06,320] [DEBUG] koFileStatusService: Skipping cvs, not active
[2016-05-24 21:26:33,853] [DEBUG] koFileStatusService: fileNotification received 4 for u'file:///Users/mike/Library/Application Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,855] [DEBUG] koFileStatusService: fileNotification received 64 for u'file:///Users/mike/Library/Application Support/KomodoIDE/10.0'
[2016-05-24 21:26:33,902] [INFO] koFileStatusService: _process:: starting file status check
[2016-05-24 21:26:33,902] [INFO] koFileStatusService: num files to check: 1, isBackgroundCheck: False
[2016-05-24 21:26:33,902] [DEBUG] koFileStatusService: examing 'disk': uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: 'disk' updating status of uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: 'disk' sending changed notification for: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,903] [INFO] koFileStatusService: process:: disk: Notified file_status for uris:
file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: examing 'publishing': uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: publishing: no need to update yet
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: examing 'svn': uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,903] [DEBUG] koFileStatusService: 'svn' updating status of uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,904] [DEBUG] koFileStatusService: svn: no change to u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,904] [DEBUG] koFileStatusService: Skipping bzr, not active
[2016-05-24 21:26:33,904] [DEBUG] koFileStatusService: examing 'git': uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,904] [DEBUG] koFileStatusService: 'git' updating status of uri: u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,905] [DEBUG] koFileStatusService: git: no change to u'file:///Users/mike/Library/Application%20Support/KomodoIDE/10.0/pystderr.log'
[2016-05-24 21:26:33,905] [DEBUG] koFileStatusService: Skipping hg, not active
[2016-05-24 21:26:33,905] [DEBUG] koFileStatusService: Skipping p4, not active
[2016-05-24 21:26:33,905] [DEBUG] koFileStatusService: Skipping cvs, not active
[2016-05-24 21:26:37,319] [INFO] koFileStatusService: _process:: starting file status check
[2016-05-24 21:26:37,319] [INFO] koFileStatusService: Removing directory observer for uri: u'file:///Users/mike/observium'
[2016-05-24 21:26:37,320] [INFO] koFileStatusService: num files to check: 0, isBackgroundCheck: True
[2016-05-24 21:26:37,321] [DEBUG] koFileStatusService: Skipping bzr, not active
[2016-05-24 21:26:37,321] [DEBUG] koFileStatusService: Skipping hg, not active
[2016-05-24 21:26:37,321] [DEBUG] koFileStatusService: Skipping p4, not active
[2016-05-24 21:26:37,321] [DEBUG] koFileStatusService: Skipping cvs, not active
[2016-05-24 21:27:08,323] [INFO] koFileStatusService: _process:: starting file status check
[2016-05-24 21:27:08,324] [INFO] koFileStatusService: num files to check: 0, isBackgroundCheck: True
[2016-05-24 21:27:08,324] [DEBUG] koFileStatusService: Skipping bzr, not active
[2016-05-24 21:27:08,325] [DEBUG] koFileStatusService: Skipping hg, not active
[2016-05-24 21:27:08,325] [DEBUG] koFileStatusService: Skipping p4, not active
[2016-05-24 21:27:08,325] [DEBUG] koFileStatusService: Skipping cvs, not active
```

when I try to get diff by keybind:
```
[2016-05-24 21:30:56,683] [DEBUG] koFileStatusService: 'svn' updating status of uri: u'file:///Users/mike/observium'
```

when I get diff from file menu:
_No any new log entries!_

`/Users/mike/observium` - this is root of my repository

**Comment by Naatan** [comment] 2016-05-24 19:52
Could you do the same again and this time right click a file tab which you know is under SVN and hit "Refresh Status". Then copy the log again.

**Comment by landy2005** [comment] 2016-09-23 06:18
Ok, I not used IDE X for long time, now tried to use it again.
IDE updated to 10.1.1.

CMD+K, D (scc diff) - **still not worked** (but select diff from file menu - ok),
CMD+K, H (scc history) - now worked,

When I press CMD+K I see this in console log:
![10308272](https://cloud.githubusercontent.com/assets/217520/18776006/fb596b1e-8176-11e6-88f1-8de11883bd49.png)

P.S. Just for know - you still have not decided to add the option "display scc status icons" or any plans about this?

**Comment by Naatan** [comment] 2016-09-23 16:36
We will not be bringing back the SCC icons.

Does the SCC widget in the bottom pane work properly for your SVN files now?

**Comment by landy2005** [comment] 2016-09-24 06:32
> Does the SCC widget in the bottom pane work properly for your SVN files now?
yes, seems as fine.. tnx!

what about:
> CMD+K, D (scc diff) - still not worked

**Comment by Naatan** [comment] 2016-09-26 15:29
Ctrl+K, D shows the diff for the current project. What you want is the current file, which has no keybinding right now. You can configure this under `Prefs > Key Bindings > Source Code Control: Compare File`.

Given that SVN appears to be working properly for you now I'll close this issue.

**Closed by Naatan** 2016-09-26 15:29 UTC
Labels: Bug: New, Pending: Response

**Comment by landy2005** [comment] 2016-09-26 15:47
No, no, issue still here!
I incorrectly said (not CMD, but Ctrl):
Ctrl+K, D - associated with "SCC: Compare" (cmd_SCCdiff)

**and this key combination not worked in IDE 10** (as I show and said earlier).

**Comment by Naatan** [comment] 2016-09-26 15:51
My response still stands, you should be using "Compare File". Unless your project is also under SVN?

**Comment by landy2005** [comment] 2016-09-26 16:04
What mean project under SVN?
My base project dir is svn base dir, project file also stored in this dir (but not under svn).

What than mean "diff for the current project", diff for all files in svn tree? (ie "svn diff /base/svn/dir")

Why in all previous IDE versions I always see diff for currently edited file for this key combination?

**Comment by cgchoffman** [comment] 2016-09-26 16:20
> Why in all previous IDE versions I always see diff for currently edited file for this key combination?

because we redid the keybindings.  Sounds like you might want the Legacy keybinding set.  Prefs > Keybindings: select the legacy set.

**Comment by Naatan** [comment] 2016-09-26 16:23
Legacy keybindings wouldnt cover this either as I believe the base command has changed and the file specific command was added.

The truth is while we try our best to add backwards compatibility at the end of the day we are an evolving products, and most things will eventually change.

**Comment by landy2005** [comment] 2016-09-26 19:39
Yes, I found "new" keybinding for file, I set it for self.

But my opinion - this is strange old style worked (mostly or always) as diff for file, but now as diff for project.
Better to set as default keybind Ctrl+K,D as diff for file and for project separate keybind, for example Crtl+K,P.

**Comment by Naatan** [comment] 2016-09-26 19:42
Fair point. I'll open a bug.
