### ISSUE TITLE
Choppy and lagging scrolling issue on OSX

### ISSUE THREAD

**Issue by rhoekman** [Komodo/KomodoEdit#2246] opened 2016-12-26 12:13 UTC
### Short Summary

Scrolling is very slow and choppy on OSX and seems to be playing catchup with the 'gutter' (where line numbers and codefolding arrows are present)
### Steps to Reproduce

Open file and start scrolling

### Expected results

Smooth scrolling

### Actual results

Lagged and choppy scrolling

### Platform Information

Komodo Edit, version 10.1.4, build 17456, platform macosx. Built on Fri Dec 16 18:33:26 2016.
macOS Sierra 10.12.2

MacBook Pro (Retina, 13-inch, Mid 2014)
CPU 2,6 GHz Intel Core i5
16 GB 1600 MHz DDR3

### Additional Information

I can do a video screen capture, If needed 
.
 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment] 2017-01-03 15:10
Duplicate of #2064

**Closed by mitchell-as** 2017-01-03 15:10 UTC
Labels: Closed: Duplicate
