### ISSUE TITLE
Combine right panes tab "Symbol Browser" with Toolbox

### ISSUE THREAD

**Issue by kevinlieser** [Komodo/KomodoEdit#3179] opened 2017-09-28 21:31 UTC
###  Summary

I am working with a right pane where the Symbol browser (in Komodo 10 "Code") and the Toolbox is combined together. In Komodo 11 after every start it get separated again because the Symbol browser takes some time (5 seconds approx.) to get initialized, so it seems it is not accessible when the UI get rendered.

### Steps to Reproduce

Combine Toolbox with Symbol browser, restart Komodo. It is separated again.

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0.0
*Operating System (and version)?* macOS Sierra & HighSierra 10.13

**Comment by Naatan** [comment] 2017-09-28 21:33
@cgchoffman seems the workspace restore code is running before the widgets are ready.

**Comment by cgchoffman** [comment] 2017-10-16 20:54
This sounds a LOT like #2000 but I don't think it's the same.  I'm going to try and keep them both in mind though as the code will be in the same place I believe.

**Comment by Naatan** [comment] 2017-10-16 23:46
I don't this our workspace code restores combined panes at all at the moment, it's not a bug as much as it is missing functionality.

**Comment by cgchoffman** [comment] 2017-10-16 23:49
> I don't [think] our workspace code restores combined panes at all at the moment,

It does.  Don't you have OpenFiles in the Places pane?  Are you saying you have to set that up again each time you start Komodo @Naatan?  I do that and it USUALLY reloads the window with Open Files in Places but as #2000 says, some times it doesn't.

**Comment by cdcmicro** [comment] 2017-10-17 17:23
Sounds like the issue I have.  I customize my WS with the symbol browser by itself in the left pane with Toolbox, Open Files, and Places/Projects in the right pane.  Every time K11 starts, the symbol browser ends-up back in the right pane.

**Comment by Naatan** [comment] 2017-10-17 17:52
@cgchoffman I may be wrong, that's just the sense I got. Frankly I stopped using combined panes cause of the issues. I'm glad you're looking into this.

**Closed** 2017-11-11 02:27 UTC
Labels: Type: Bug
