### ISSUE TITLE
keybinding scheme reverts to default

### ISSUE THREAD

**Issue by greatsaltlake** [Komodo/KomodoEdit#482] opened 2015-08-04 23:01 UTC
when restarting the keybinding always go back to default from my custom one.

**Comment by Defman21** [comment] 2015-08-04 23:03
Duplicate of https://github.com/Komodo/KomodoEdit/issues/476

**Comment by Naatan** [comment] 2015-08-05 01:27
Fixed in 9.2 final - http://downloads.activestate.com/Komodo/releases/9.2.0/

**Closed** 2015-08-05 01:26 UTC
