### ISSUE TITLE
Find dialog pinning no longer works in Komodo Edit 9.2 when using Replace All

### ISSUE THREAD

**Issue by testworksau** [Komodo/KomodoEdit#523] opened 2015-08-14 04:24 UTC
After upgrading to Komodo Edit 9.2, I have found that the Find window does not behave as it used to.

When the dialog is pinned, you should be able to click Replace All and have the window remain open. 

As of 9.2, as soon as I click "Replace All", the window closes itself. 

My dialog settings are as follows:

![image](https://cloud.githubusercontent.com/assets/11973031/9267306/006bcd44-4290-11e5-8e28-7dc086b51863.png)

Build info:
Komodo Edit, version 9.2.0, build 15966, platform win32-x86. Built on Tue Aug

**Comment by cgchoffman** [comment] 2015-08-14 05:09
Could you explain your exact use case stpes? The find dialog pin icon has never worked like that.  It is used to "stay on top".  I'm wondering if you're using a different dialog than what I'm thinking of

-----Original Message-----

**Comment by testworksau** [comment] 2015-08-14 05:12
I have been fixing up PEP8 standards violations of late, so here's what I've been doing:

1. Double click a variable
2. CTRL-H
3. Change the "Replace with" text
4. Click "Replace All"

Perhaps it wasn't the pinning that made the dialog stick, but the dialog definitely did not use to close on me pre-upgrade.

**Comment by cgchoffman** [comment] 2015-08-14 06:01
You might have been using "replace"?  Replace All has always closed the
window as long as I can remember.  What version did you upgrade from?




*Carey G.C. Hoffman. ActiveState Technical Support Engineer, Development
and Quality AssuranceP: 604.376.5045  ALT. Email: careyh@activestate.com
<careyh@activestate.com>I must think of my self, from now on, as living
perpetually in the first instance of thefuture ~ Salahuddin Chamchawala*

**Comment by testworksau** [comment] 2015-08-14 06:11
I have always used Replace All.

The previous workflow was useful because the Find dialog would remain on top, but I could still double click the editor to select a variable and ctrl-c it into the clipboard -> into the "Find what" field.

i.e. I could change multiple things in all currently opened files without having to reopen the dialog and change the "Search in" setting from "Current document" to "Open files".

I upgraded from Komodo Edit 9.1.

**Comment by cgchoffman** [comment] 2015-08-14 06:18
Ahh I think you're talking about find and replce IN FILES.  I think that's
what the difference is.  Are you sure you were'nt using crtl + shift + h?




*Carey G.C. Hoffman. ActiveState Technical Support Engineer, Development
and Quality AssuranceP: 604.376.5045  ALT. Email: careyh@activestate.com
<careyh@activestate.com>I must think of my self, from now on, as living
perpetually in the first instance of thefuture ~ Salahuddin Chamchawala*

**Comment by Naatan** [comment] 2015-08-14 14:53
Yep Replace All has always closed itself, nothing changed there in 9.2.

That said replace all is being somewhat overhauled for 9.3, so this issue will resolve itself.

Also Carey, you're on vacation, what the hell are you doing providing support? Getoutahere! :)

**Comment by Defman21** [comment] 2015-08-14 14:55
>Also Carey, you're on vacation, what the hell are you doing providing support? Getoutahere! :)

Lol. Carey reminds me now :smiley:

**Closed** 2015-08-14 15:36 UTC

**Comment by testworksau** [comment] 2015-08-14 22:42
My home PC, which hasn't been upgraded to 9.2 yet, is working as expected (the dialog does not close when clicking "Replace All"). 

Do you need me to send you a screencast or something to prove it?

Komodo Edit, version 9.0.1, build 15745, platform win32-x86. Built on Mon Apr 20 19:05:56 2015.

**Comment by Naatan** [comment] 2015-08-14 23:57
Normally I would very much welcome it, but as this functionality is going to be overhauled for the next version it is redundant. And I don't think the issue is big enough to warrant a fix in a point release.

So to clarify; the issue will be addressed in the next minor version of Komodo (9.3) but we're not tracking it as it's functionality is implied in the planned overhaul.
