### ISSUE TITLE
Komodo SSH client using weak algos

### ISSUE THREAD

**Issue by 01000101** [Komodo/KomodoEdit#2097] opened 2016-10-16 15:19 UTC
### Short Summary
When using remote servers (SFTP, SCP), the Komodo SSH client only sends weak, outdated HMAC algorithm support to the server. If the SSH server is using modern, secure algorithms and rejects outdated ones, the connection will fail. 

### Steps to Reproduce
Using Komodo IDE's "server" tab in the preferences, create a connection to an SSH service that does not accept weak HMAC (SHA1, MD5). 

### Expected results
A good, secure connection

### Actual results
No connection

### Platform Information

*Komodo Edit or IDE? Komodo IDE* 
*Komodo Version? 10.1.1 build 89474* 
*Operating System (and version)? Linux x86_64, Fedora 23* 

### Additional Information

Komodo sends the following HMAC support to the server: 

- hmac-sha1
- hmac-sha1-96
- hmac-md5
- hmac-md5-96

A secure server is not going to accept those and is likely looking for the following:

- hmac-sha2-512
- hmac-sha2-256

Actual error message: fatal: no matching mac found: client hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96 server hmac-sha2-512,hmac-sha2-256 [preauth] 

For completeness, here's the algorithms supported by my SSH service. I've written many security articles and confirmed with many secure professionals that this is a modern, secure, and suggested SSH server configuration and Komodo should be supporting these algorithms (even if it doesn't remove support for weaker ones). 

```
# Message Authentication Code (Hash, only SHA2-512)
#  SHA-256 included for compat with PuTTY-WinCrypt clients
MACs hmac-sha2-512,hmac-sha2-256
# Ciphers (only secure AES-256)
Ciphers aes256-cbc,aes256-ctr
# Key Exchange algorithms (Elliptic Curve Diffie-Hellman)
#  DH-SHA-256 included for compat with PuTTY-WinCrypt clients
KexAlgorithms ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256
```

**Comment by 01000101** [comment] 2016-10-16 15:31
It looks like this is fixed in commit https://github.com/Komodo/KomodoEdit/commit/2776d63b100b7215976e958857d1db205fe0fbf6 but not rolled into Komodo IDE yet.

**Comment by Defman21** [comment] 2016-10-16 15:34
It's probably doesn't, because of Python 2.7.

**Comment by 01000101** [comment] 2016-10-16 15:36
I'm not sure what Python 2.7 has to do with this. This is a Paramiko configuration issue.

**Comment by Defman21** [comment] 2016-10-16 15:37
Ohh, I thought your issue is related to https://github.com/Komodo/KomodoEdit/issues/520
https://github.com/Komodo/KomodoEdit/issues/520#issuecomment-248384535

**Comment by 01000101** [comment] 2016-10-16 15:38
Ah, no, but that also would be nice :)
If anyone does want to set up a test SSH service, here's the config I use and serves as a good starting point. https://joscor.com/blog/hardening-openssh-server-ubuntu-14-04/

**Comment by Defman21** [comment] 2016-10-16 15:39
Or, if the milestone is correct, the change will be in a Komodo 11 build. I'm going to setup a server following the guides in your link and test it with my Komodo IDE release and built from master Komodo Edit.

**Comment by Defman21** [comment] 2016-10-16 15:50
Komodo IDE gives me:
```
Oct 16 11:49:17 defman21 sshd[2869]: fatal: ssh_dispatch_run_fatal: Connection to <hidden>: no matching MAC found [preauth]
```

Gonna try a Komodo Edit build.

**Comment by Defman21** [comment] 2016-10-16 15:55
Custom build: works fine!

```
Oct 16 11:54:58 defman21 sshd[2883]: Accepted publickey for root from <hidden> port 38748 ssh2: RSA SHA256:<hidden>
```

The issue will be resolved in Komodo 11.

**Comment by 01000101** [comment] 2016-10-16 15:57
Great! Thanks for being so quick about testing.

**Comment by Naatan** [comment] 2016-10-17 14:43
Thanks for the follow up @Defman21 :) Closing this in favour of #252.

**Closed by Naatan** 2016-10-17 14:43 UTC

**Comment by 01000101** [comment] 2016-10-17 14:46
OK? I'm not sure why this is closed in favor of a vaguely-related ticket that won't fix this issue.

**Comment by 01000101** [comment] 2016-10-17 14:47
@Naatan Why did you reference that ticket as the duplicate? Was it a mistake?

**Comment by Defman21** [comment] 2016-10-17 14:47
Since the ticket Nathan linked to is fixed by upgrading Paramiko, this has been closed in favor of it.

**Comment by Naatan** [comment] 2016-10-17 15:15
@01000101 The solution to #252 is the same as to this one, even though the problem is slightly different.
