### ISSUE TITLE
Publishing: Force Publish to push (even if it doesn't want to)

### ISSUE THREAD

**Issue by furnox** [Komodo/KomodoEdit#924] opened 2015-12-01 23:15 UTC
When Publishing, would it be possible to force Komodo to push (or pull I suppose) when Komodo doesn't want to? When there's a conflict on the Publish operation, Publish will allow you to specify push or pull. Could that functionality be available at all times?

When developing on different machines with Komodo, they each have their own idea what the files on the remote server "ought to be". However, when Komodo on one machine Publishes a file to the remote server, the Komodo on the *other* machine now can't Publish that file because Komodo feels the remote file needs to be copied locally.

Another, more draconian, way to achieve this would be to allow the capability to reset the Publish state and start over. Perhaps on just the troublesome file(s).

Initially reported on the forums:
http://forum.komodoide.com/t/force-publish-to-push-even-if-it-doesnt-want-to/2327

**Comment by cgchoffman** [comment] 2015-12-02 00:08
Just to clarify, where in the UI are you hoping for this?  I was assuming in the Places context menu but I don't see you mention Places.  You can force push from the Publishing Sync Dialog but it's more involved.

**Comment by furnox** [comment] 2015-12-02 17:51
Well, I didn't want to dictate the "how" figuring that you guys have already done such a great job on the UI.  :-)

I will say that it seems to make the most sense to me to include it in the Publishing Sync Dialog as a right-click context option. Say you've fired up the sync Dialog and Publish decides that a remote file has been changed and ought to be copied locally (yet the logic doesn't detect a conflict to be resolved), but you need to override Publish and push the local file instead.

I am interested when you say that you can force push from the sync dialog. The only time I can see you can force push is when a conflict has been detected.

**Comment by cgchoffman** [comment] 2015-12-02 19:21
> I am interested when you say that you can force push from the sync dialog. The only time I can see you can force push is when a conflict has been detected.

I read your request wrong.  This is different from what I was thinking but still a good idea.  I better file an enhancement for what I was thinking of before I forget again.

**Comment by Naatan** [comment] 2016-03-17 15:30
Duplicate of #148

**Closed by Naatan** 2016-03-17 15:30 UTC
Labels: Duplicate
