### ISSUE TITLE
Crash when drag & drop to watch window

### ISSUE THREAD

**Issue by ovidiubarbu** [Komodo/KomodoEdit#463] opened 2015-07-28 17:41 UTC
On the latest Komodo IDE 9 on MAC OS X 10.10.4 :

0. create a small perl script
1. Select a variable
2. Drag & drop it to Watch window
3. Komodo crashes

Reproduces: always

**Comment by cgchoffman** [comment] 2015-07-28 18:36
This sounds like #371 but I'm able reproduce your issue here 100% as you have.
Did you send in crashreports with your email attached when Komodo crashed?

**Comment by ovidiubarbu** [comment] 2015-07-28 19:19
I have sent several detailing when it happens, but I wanted to add it here, to make sure it's being looked into. Is really annoying.

Similarly it also happens when you select any text, try to drag it anywhere in your code window. It works fine, but after about 10 seconds it also crashes!

**Comment by Naatan** [comment] 2015-07-28 21:59
Note a crash report is completely useful without context, so if you get a crash report and you know what caused it please report a bug and let us know you reported the crash :)

**Comment by cgchoffman** [comment] 2015-07-28 21:59
> Similarly it also happens when you select any text, try to drag it anywhere in your code window. It works fine

That's #371 then.  I've never been able to reproduce that.

> but I wanted to add it here, to make sure it's being looked into. Is really annoying.

YES, PLEASE always do this.  Do not assume we're working on something.  Thank you very much for letting us know about your issue.

**Comment by Naatan** [comment] 2015-07-29 15:44
Closing this as it appears to be a duplicate of #371

**Closed by Naatan** 2015-07-29 15:44 UTC
