### ISSUE TITLE
template crash

### ISSUE THREAD

**Issue by yeknom02** [Komodo/KomodoEdit#1997] opened 2016-09-06 21:13 UTC
### Short Summary
Python3 template did not load properly

### Platform Information

Komodo Edit, version 10.1.0, build 17404
Windows 7

### Additional Information

Error loading template 'file:///C:/Program%20Files%20%28x86%29/ActiveState%20Komodo%20Edit%2010/lib/support/default-templates/Common/Python3.py'

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createFileFromTemplateURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._doFileNewFromTemplate :: line 359"  data: no]

Traceback:
viewManager.prototype._doFileNewFromTemplate@chrome://komodo/content/views.js:359:18
viewManager.prototype._newTemplate@chrome://komodo/content/views.js:273:15
viewManager.prototype.newTemplateAsync/<@chrome://komodo/content/views.js:312:19

Komodo Edit, version 10.1.0, build 17404.
Built on Mon Aug 22 16:43:24 2016.

**Comment by cgchoffman** [comment] 2016-09-06 21:36
I can't reproduce this.  Can you try this in Safe Mode? Help > Troubleshooting > Restart in Safe mode

**Comment by yeknom02** [comment] 2016-09-07 16:09
For whatever reason, I can't reproduce this either. Perhaps it was a
one-time thing since it was my first time using the program.

**Comment by cgchoffman** [comment] 2016-09-07 16:25
If you can remember any more details that lead to you being able to reproduce the issue then please add them but I'm closing this for now.

For future reports please provide more details.  The issue should be reproducible and have steps for us to follow.

**Closed by cgchoffman** 2016-09-07 16:25 UTC
Labels: Pending: Response
