### ISSUE TITLE
De-/Indenting a selection expands the selection

### ISSUE THREAD

**Issue by bbak** [Komodo/KomodoEdit#2208] opened 2016-12-06 09:15 UTC
### Short Summary
When selecting a region of code and hitting either `TAB` oder `SHIFT+TAB` to (de-)indent the selected region, the selection is expanded by one line with each Keypress of `TAB` or `SHIFT+TAB`.

### Steps to Reproduce
- Select several lines of code
- Hit tab

### Expected results
Code is indented. Selection stays the same.

### Actual results
Code is indented. Selection is expanded.

### Platform Information
Komodo IDE 10.1.2 in Windows 10 (Surface Book)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment] 2016-12-06 13:10
Fixed in 10.1.3 nightly.

**Comment by mitchell-as** [comment] 2016-12-06 15:08
Duplicate of #2180.

**Closed by mitchell-as** 2016-12-06 15:08 UTC

**Comment by Naatan** [comment] 2016-12-06 15:40
> Fixed in 10.1.3 nightly.

Fixed in 10.1.3, it was released yesterday :)

**Comment by Defman21** [comment] 2016-12-06 16:16
Huh, just got an update :)
