### ISSUE TITLE
Intel scanning indicator is shown in 2 windows

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1654] opened 2016-06-02 13:25 UTC
### Short Summary
Just noticed, when you have 2 project open in 2 windows, the scanning files indicator form one project is shown on both windows.
Was scanning a large folder so i opened a project in new window.

### Steps to Reproduce
Open a project and set the directory to scan, while the scanning indicator is running, open a project in a new window. In the new window the scanning indicator is shown form the other project.

### Expected results
That the scanning indicator is only shown on the window on the window where it came from

### Platform Information
[2016-06-02 11:15:52,022] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

**Comment by mitchell-as** [comment] 2016-06-02 14:12
Interesting find. Well, codeintel runs only once (not per-project), and both windows would ultimately make use of it. Short of parsing output for paths and then checking against the current project paths, I'm not sure how this would be "fixed" (or even if it's worth spending the time to do so.) Thought's @Naatan? I'm of the opinion this should be closed as "by design".

**Comment by Naatan** [comment] 2016-06-02 15:19
Yeah I agree, this is by design. If we would not show you this then you wouldn't know it was happening (eg. if you were on the window that this was not "contextually relevant" to).

**Comment by cgchoffman** [comment] 2016-06-02 15:20
> If we would not show you this then you wouldn't know it was happening

and you would wonder why code intel wasn't working in the non-scanning window.

**Closed by Naatan** 2016-06-02 15:19 UTC

**Comment by babobski** [comment] 2016-06-02 17:24
> Interesting find. Well, codeintel runs only once (not per-project)

Maybe this has to do with my settings for php, I always point to the directories to scan.
When I open a project and start typing php the intel indicator kicks in.

When I open a other project and start typing php codeintel starts scanning for this project.

So when I saw the indicator wasn't restricted to the window, in my point of view I can get 2 indicators running at the same time, what can be confusing.

The change that this is happening is very slim, but just wanted you guys to know this can occur.

**Comment by Naatan** [comment] 2016-06-02 17:47
That's fair. Did the UI mess up in any way when this happened?
