### ISSUE TITLE
Misspelling of partial words not being cleared

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#1166] opened 2016-03-16 17:00 UTC
### Short Summary

When a misspelling is detected on an incomplete word, the underline is not cleared when the word is completed correctly
### Steps to Reproduce

While typing a word into a comment pause before the word is complete until the IDE indicates a spelling error
# Draw an hou

finish the word
# Draw an hourglass
### Expected results

The IDE should indicate that the word is not misspelled
### Actual results

Part of the word (hor) is underlined, while the rest (rglass) is not
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 9.3.2, build 88191
_Operating System (and version)?_ Windows 7
### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by Defman21** [comment] 2017-04-20 20:46
@mitchell-as this still exists in Komodo 10. Could you add labels and everything else? 😃

**Comment by mitchell-as** [comment] 2017-04-21 14:20
I cannot reproduce this on 10.2.x. It may have been fixed in the meantime.

**Closed by mitchell-as** 2017-04-21 14:20 UTC

**Comment by Defman21** [comment] 2017-04-21 15:03
Hmm you're right, it works for me too. Sorry then :)

**Comment by jcloggins** [comment] 2017-04-24 14:51
I still see it occasionally.

It doesn't happen every time the way it did before. But if my editing session lasts more than a hour, I will see it at least once with 10.2.1.

As something of a workaround, I have increased the check time from the default to 10 sec.

**Comment by Defman21** [comment] 2017-04-24 15:31
Yeah I saw that too a few times while were working on some code.

**Comment by cgchoffman** [comment] 2017-04-24 16:29
I see this quite often.  Though I can't reproduce it.  Any one who does see this try to keep your eyes open for 100% repro steps.

**Comment by jcloggins** [comment] 2017-04-24 16:37
Might I suggest dropping back to an earlier version of Komodo.

Once the problem has been isolated, you will at least have something to check against the current version.
