### ISSUE TITLE
PHP7: built-in xdebug is missing

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1707] opened 2016-06-15 17:31 UTC
### Short Summary

There's no xdebug.so for php 7.0

**Comment by Naatan** [comment] 2016-06-15 17:32
Thanks @Defman21, this is already fixed for 10.0.1 and should be in a nightly soon.

**Comment by Defman21** [comment] 2016-06-15 17:32
I'm using nightly and I don't see this is being fixed. What build will fix that? :) Mine is 89222

**Comment by cgchoffman** [comment] 2016-06-15 18:49
We haven't pushed a nightly for a few days.  Just wait for 10.0.1 to come out.  7.0 Xdebug is there.

**Comment by cgchoffman** [comment] 2016-12-06 19:39
Looks like this got closed too soon then fell off the radar.  Thankfully the bits I built for Windows survived a re-imaging and hard drive swap so at least I don't need to build those again as they were a huge pain.

ref: https://github.com/Komodo/KomodoIDE/commit/78b3cd38ef12ad63640d4f36acce2c45a1af0925#diff-65db6736434bd4389bb20701109cdda6

It's coming back now.  We thought that would get the buildbots to create new bits but we need to build them manually.  Blackfile.py provides the code to do that but it's not run during every build (makes sense not to build the bits every time).  

I also seem to recall that for the Windows builds I had to change the config steps in the commit above to use `compiler_version=14` instead of `11`.

**Comment by Naatan** [comment] 2016-12-07 16:02
Be sure to also update http://code.activestate.com/komodo/remotedebugging/ (probably part of the deploy process already?)

**Comment by garak** [comment] 2016-12-16 19:58
Sadly, the nightly build released yesterday is still missing this. Any hope to get it for the next nighlty?

**Comment by cgchoffman** [comment] 2016-12-16 20:19
@garak The earliest this will get in is 10.2.  The nightly is strictly for #2201.
Unless you're doing code profiling, you don't need custom Komodo bits.  You can use the Xdebug builds here: https://xdebug.org/download.php

**Comment by garak** [comment] 2016-12-16 20:22
@cgchoffman thanks, I already tried with official xdebug.so, no luck

**Comment by cgchoffman** [comment] 2016-12-16 20:25
@garak, they should work find.  Open a forum thread for assistance in configuring your setup community.komodoide.com

**Comment by cgchoffman** [comment] 2016-12-16 20:34
Just to be safe, confirmed Xdebug 2.4.1.  I succeeded in starting a debug session in Komodo.

**Comment by garak** [comment] 2016-12-17 09:00
Debug session is not a problem, problem is profiling

**Comment by cgchoffman** [comment] 2017-01-16 19:29
This is partly resolved.  The prebuilt bits are in place so local debugging will work.  Unfortunately profiling isn't working with our existing patch.  Tracking that here https://github.com/Komodo/KomodoEdit/issues/2256.

Closing this as it was simply about adding the bits to the install.

Note that PHP 5.4 and lower was removed and are no longer supported.

**Comment by cgchoffman** [comment] 2017-01-16 19:29
https://github.com/Komodo/KomodoIDE/commit/b2427b5b2a800a11e829ccfdeeeba29a5ef913c7

**Closed by cgchoffman** 2017-01-16 19:29 UTC
Labels: Enhancement, Severity: Priority
