### ISSUE TITLE
View Minimap toggle broken

### ISSUE THREAD

**Issue by ebucking** [Komodo/KomodoEdit#172] opened 2015-04-14 18:23 UTC
Komodo 9: Turning on "View minimap" turns off minimap. Turning off "View minimap" turns minimap on.

**Comment by Defman21** [comment] 2015-04-14 18:24
Cannot reproduce. Works fine to me.

**Comment by Naatan** [comment] 2015-04-14 19:14
Also cannot reproduce, does this still happen after a restart of Komodo?

**Comment by ebucking** [comment] 2015-04-14 20:10
I had switched the skin to Classic. When I switched back to default, the
toggle worked as expected. Guess it¹s not a problem.

Eugene Buckingham


From:  Nathan Rijksen <notifications@github.com>
Reply-To:  Komodo/KomodoEdit
<reply+00b6525255cf9d052ef49d11bc9a0588ada0f139651aa0e292cf000000011145290a9
2a169ce0414a1eb@reply.github.com>
Date:  Tuesday, April 14, 2015 at 3:14 PM
To:  Komodo/KomodoEdit <KomodoEdit@noreply.github.com>
Cc:  Eugene Buckingham <genebuckingham@verizon.net>
Subject:  Re: [KomodoEdit] View Minimap toggle broken (#172)


Also cannot reproduce, does this still happen after a restart of Komodo?


Reply to this email directly or view it on GitHub
<https://github.com/Komodo/KomodoEdit/issues/172#issuecomment-93024584> .

**Comment by cgchoffman** [comment] 2015-04-15 00:52
This could be related to issue #94.  Different menu but same symptoms. Going to link for now.

@ebucking could you clarify your workaround?  You had to switch to classic then back again and that resolved the issue?

**Comment by ebucking** [comment] 2015-04-15 14:12
Sequence was: Played around with skins (with restarts as required). Set skin
to ³classic². Did not see the minimap. On menu it was turned on. Turned it
off. Now minimap appeared. Set skin back to default. Restarted. Now minimap
behaved correctly.

Eugene Buckingham


From:  Carey Hoffman <notifications@github.com>
Reply-To:  Komodo/KomodoEdit
<reply+00b6525264609d1ccdfbab67ed2261778f2a2bc8f623856792cf000000011145783a9
2a169ce0414a1eb@reply.github.com>
Date:  Tuesday, April 14, 2015 at 8:52 PM
To:  Komodo/KomodoEdit <KomodoEdit@noreply.github.com>
Cc:  Eugene Buckingham <genebuckingham@verizon.net>
Subject:  Re: [KomodoEdit] View Minimap toggle broken (#172)


This could be related to issue #94
<https://github.com/Komodo/KomodoEdit/issues/94> .  Different menu but same
symptoms. Going to link for now.

@ebucking <https://github.com/ebucking>  could you clarify your workaround?
You had to switch to classic then back again and that resolved the issue?


Reply to this email directly or view it on GitHub
<https://github.com/Komodo/KomodoEdit/issues/172#issuecomment-93126334> .

**Comment by Naatan** [comment] 2015-04-15 15:06
Seems to be an issue with the classic skin. Closing this as it's not an issue in Komodo itself.

**Closed by Naatan** 2015-04-15 15:06 UTC
Labels: Pending Response

**Comment by 2114L3** [comment] 2015-05-13 13:02
i might be just a noob, but im getting this on default skin, and toggling to other skins or icon sets and restarting is not fixing the issue. while komodo remembers on the file you're working on, as soon as you open another file (one that prehaps edited in old komodoedit version, but not touched with Komodo Edit, version 9.0.1, build 15745, platform win32-x86. Built on Mon Apr 20 19:05:56 2015) then minimap is missing yet the settings show "view minimap" as toggled on. clicking it toggles on the minimap and the "view minimap" remains ticked. once actioned on said file it seems to play nice until you move onto another existing file (of millions) that you've not opened in this version. this seems repeatable in default or classic


cheers.
![2015-05-13_22-57-24](https://cloud.githubusercontent.com/assets/6963390/7610867/88626e4e-f9c3-11e4-8149-4296883a10b8.png)

![2015-05-13_23-00-47](https://cloud.githubusercontent.com/assets/6963390/7610929/ef8d8ab8-f9c3-11e4-96e2-38560b0a0b87.png)

**Comment by farkass** [comment] 2015-06-18 10:03
It was the same problem for me after installing Komodo Edit, version 9.1.0, build 15798
When using this top-right Menu, the Minimap status is not displayed correctly.
When displaying the classic Menu, it is working correctly there.
Found the same bug in both Linux and windows
Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64.
Built on Sat May 30 05:22:08 2015.
Komodo Edit, version 9.1.0, build 15798, platform win32-x86.
Built on Sat May 30 06:10:24 2015.

**Comment by Naatan** [comment] 2015-06-18 17:17
Let's track this in https://github.com/Komodo/KomodoEdit/issues/94

Thanks guys :)
