### ISSUE TITLE
Komodo Edit 11.0.1 & 11.0.2 Templates non functional

### ISSUE THREAD

**Issue by bruceg1856** [Komodo/KomodoEdit#3417] opened 2018-01-05 02:56 UTC
### Short Summary
Updated version 10.0.1 to 11.0.2-19222

### Steps to Reproduce
selected New from Template, HTML5

### Expected results

expected standard html5 doc type, html head, body tags to be present

### Actual results
blank page

### Platform Information

*Komodo Edit  
*Komodo Version?*  11.0.1 and 11.0.2
*Operating System (and version)?* 
Windows 7 Pro and Window 7 Enterprise
### Additional Information
Uninstalled 11.0.2 and installed 11.0.1 which had been working okay, but now had the same problem.
completely removed both, cleaned registry, installed 10.0.1 ( WORKS as Expected )

**Comment by mitchell-as** [comment] 2018-01-05 15:14
Duplicate of #3398

**Closed by mitchell-as** 2018-01-05 15:14 UTC
