### ISSUE TITLE
Editor steals focus on Save

### ISSUE THREAD

**Issue by globiweb** [Komodo/KomodoEdit#1361] opened 2016-05-03 22:46 UTC
### Short Summary
If you save with CTRL+S and then tab to your browser window too fast, Komodo IDE steals focus back again.

### Steps to Reproduce
While editing a file, press CTRL+S, then immediately press ALT-TAB to move focus to the browser. If done fast, when save has finished, the focused window will be Komodo again.

### Expected results
Focus should stay on my browser window as I've just tabbed there.

### Actual results
Komodo steals focus if ALT+TAB was pressed before the save operation completed.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  9.3.2, build 88191
*Operating System (and version)?* linux-x86_64 (Xubuntu 14.04)

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment] 2016-05-03 23:03
Dupe of #1331.  Please add your details there to see if we can reproduce the issue.

**Closed by cgchoffman** 2016-05-03 23:03 UTC
