### ISSUE TITLE
Show Editor tabs is always "checked"

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1485] opened 2016-05-17 15:23 UTC
### Short Summary

Even if it's disabled, it shows as checked.
### Platform Information

_Komodo Edit or IDE?_ IDE
_Komodo Version?_ 10.0.1-beta 88160
_Operating System (and version)?_ elementary OS 0.4

**Comment by cgchoffman** [comment] 2016-05-17 17:10
I'm not seeing this on Windows or OSX.  Are you able to repro with a clean profile?

**Comment by Defman21** [comment] 2016-05-17 17:20
Able to reproduce in Safe-mode, I'm on Linux though.

**Comment by cgchoffman** [comment] 2016-05-17 17:40
Ok, thanks for confirming.

**Comment by mitchell-as** [comment] 2016-06-08 19:27
I'm not seeing this on Linux in master. @Defman21 are you still seeing this with the latest nightly build?

**Comment by Defman21** [comment] 2016-06-08 19:31
Yes. Gonna try safe mode though.

**Comment by Defman21** [comment] 2016-06-08 19:57
I'm able to reproduce.
Komodo IDE, version 10.0.1, build 89206, platform linux-x86_64.
Built on Tue Jun 7 01:34:39 2016.

**Comment by mitchell-as** [comment] 2016-06-08 19:58
@Naatan can you reproduce this on Linux? I cannot.

**Comment by Naatan** [comment] 2016-06-08 20:05
I am not able to reproduce this either.

@Defman21 exactly what steps are you taking?

**Comment by Defman21** [comment] 2016-06-08 20:07
Open Hamburger Menu - View - Toolbars - Show Editor Tabs.

**Comment by Defman21** [comment] 2016-06-08 20:09
Note I'm not able to reproduce it when using Alt menu.

**Comment by Naatan** [comment] 2016-06-09 16:10
Reproduced using the unified menu.

**Comment by Naatan** [comment] 2016-06-09 17:16
So the issue here is that the Open Files module does not use a controller for its commands, which makes it so that the commands do not update properly. Re-targeting this for 10.1 as I'll need to implement a controller, which is too much for a patch release.

**Comment by cgchoffman** [comment] 2018-03-12 19:03
Taking this.  A silly aesthetic that should be fixed.

**Closed** 2018-03-13 00:37 UTC
Labels: Type: Bug
