### ISSUE TITLE
Editor: Go Back commad seems doesn't work at all 

### ISSUE THREAD

**Issue by miloja** [Komodo/KomodoEdit#2093] opened 2016-10-12 12:02 UTC
### Short Summary

Editor: Go Back commad seems doesn't work at all (cmd_historyBack).
### Steps to Reproduce

Place cursor in several different places in different files and fire the "Editor: Go back" commad by shortcut, "Go to Anything" or Toolbox icon "<".
### Expected results

Cursor move to previos positions like they appears in history (switching files if necessart).
### Actual results

Nothing happens at all. 
### Platform Information

Komodo IDE, version 10.1.1, build 89474, platform win32-x86.
Built on Thu Sep 01 14:27:01 2016.

**Comment by Naatan** [comment] 2016-10-12 15:03
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by miloja** [comment] 2016-10-13 06:39
Nothing interesting here: [pystderr.txt](https://github.com/Komodo/KomodoEdit/files/526355/pystderr.txt)

**Comment by Naatan** [comment] 2016-10-13 15:21
There are some errors in there that are worrying, could be an addon or a userscript causing havock. Does the "Go Back" command work on a fresh start of Komodo?

**Comment by miloja** [comment] 2016-10-14 06:50
I've reistalled Komodo. The bug appears without aby addons. Here is log after reinstal and fresh start: [pystderr.txt](https://github.com/Komodo/KomodoEdit/files/528837/pystderr.txt)

I've tryied "Go back" with commad and shortcut. Nothing works. Maybe I could place some debug code to invastigate it futher. Tell me where.

**Comment by miloja** [comment] 2016-10-14 07:33
Uninstalling Komodo 8.5 and removing my keyboad schema doesn't help.

**Comment by Naatan** [comment] 2016-10-14 14:51
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by hongquan** [comment] 2016-11-04 04:56
I encounter the same problem. Reset everything by deleting the ~/.komodoide folder.

[pystdout.txt](https://github.com/Komodo/KomodoEdit/files/570622/pystdout.txt)

Platform info:
- Ubuntu 16.10
- Komodo IDE, version 10.1.1, build 89474, platform linux-x86_64.
Built on Thu Sep 1 14:52:01 2016.

I tested with a Python 2 project, with use of virtualenv. The setting of that project is as following:
[EasyUni.txt](https://github.com/Komodo/KomodoEdit/files/570627/EasyUni.txt)

**Comment by Naatan** [comment] 2016-11-04 15:06
@hongquan you have some worrying errors in there, they imply either a corrupted install or an addon / userscript messing things up. Please try a new install of Komodo.

**Comment by miloja** [comment] 2016-11-04 15:45
In Safe-mode it works to some extent: I write "abc" in one file. Then jump to other file and write "xyz". Then jump to other place in the same file and write "123". Then executing "Go back" command moves carret after "abc". To should move carret after "xyz" and then after "abc". Afert clicking a while the history carret possitions looks very odd and unexpected.
Another example: I put carret after "xyz", then open first file and put carret after "abc". "Go back" command moves carret 1 line below "xyz". That's very strange. Surely there is sth. wrong with this feature apart from not working without Safe-mode.

**Comment by cgchoffman** [comment] 2016-11-04 17:27
> Another example: I put carret after "xyz", then open first file and put carret after "abc". "Go back" command moves carret 1 line below "xyz"

@miloja I can't reproduce this:
- I have on file open
- I place the cursor at the end of that line
- I open another file
- I press back
- Komodo switches back to the first file and my cursor is at the end of the first line.

Please note the example you give would be a new issue and should be reported separately.  Posting a new issue in the 9th comment of a ticket is a great way to never have looked at, let alone fixed (not because we don't want to, because we won't see it).

**Comment by hongquan** [comment] 2016-11-05 03:00
@Naatan I deleted the whole directory ~/.komodoide, then reinstalled Komodo IDE. But the problem still exists.

I notice that it start to happen since I switch to Ubuntu 16.10. It didn't happen on Ubuntu 16.04.

**Comment by miloja** [comment] 2016-11-07 07:29
I'm not sure if it's a new bug or both bugs are somehow connected that's why I've provided additional details about the "Go back" command.

**Comment by miloja** [comment] 2016-11-07 07:50
To ilustrate the bug more I've recorded a screen screencapture: 
[komodo_bug.zip](https://github.com/Komodo/KomodoEdit/files/574711/komodo_bug.zip)

It's in safe mode. Sometimes in normal mode I can do a few "Go backs", but the looks just as in the recored screen catpture: totaly random.

**Comment by Naatan** [comment] 2016-11-07 15:17
I don't quite follow what the problem is there, it seems to be going back? Of course once you reach the end it will be disabled as there are no further locations to "go back" to.

**Comment by miloja** [comment] 2016-11-08 07:36
Watch the video closely. Carret should return in order: 3, 2, 1, but it returns in some random order. Of course if I reach and of history there is no further location to "go back" to. It's not the issue.

Watch another screen capture (in normal mode this time):
[komodo_history_bug2.zip](https://github.com/Komodo/KomodoEdit/files/577560/komodo_history_bug2.zip)

"Go back" doesn't work at all. "<" button is grayed, shortcut doesn't work. Direct command execution doesn't work. The lack of this feature is really annoying. It's very useful and it worked fine in 8.5.1.

**Comment by Naatan** [comment] 2016-11-08 15:43
So the first video was in safe mode, in which it "worked" (albeit with some caveats), the second video was in normal mode in which it doesn't work at all?

We'll keep this focused on the "doesn't work at all" aspect for now, as that is what the bug was originally about.

Your error log indicates something is very wrong with your Komodo install, the fact that it works in safe-mode indicates that the issue is with your profile (your settings). I'm afraid this will likely need a profile reset, but before we do this there is one more thing we could try.

Please try Help > Troubleshooting > Restart without Tools. And if that doesn't work also give "Restart without Addons" a try.

**Comment by hongquan** [comment] 2016-11-09 06:34
Today I tested various version of Komodo IDE and found that: 10.1.1 & 10.1.0 don't work. 10.0.1 works.

**Comment by miloja** [comment] 2016-11-09 07:51
10.1.0 changelog says: "Editor: Fixed issue where history back/forward stopped working (stopped recording).". Maybe "history issue fix" breaks history at all. :/

**Comment by miloja** [comment] 2016-11-09 15:16
I confirm that in 10.0.1 it works with some issues (described in my comment 5 days ago), but way better than not working at all.

**Comment by Naatan** [comment] 2016-11-09 16:05
Interesting, thanks for the update! I'll have a look.

**Comment by Naatan** [comment] 2016-11-09 16:19
> 10.1.0 changelog says: "Editor: Fixed issue where history back/forward stopped working (stopped recording).". Maybe "history issue fix" breaks history at all. :/

Looked into that commit, it's impossible this caused the issue. Good digging though! Thanks for that.

I'll have a look at what else changed between 10.0.1 and 10.1.0.

**Comment by Naatan** [comment] 2016-11-09 16:23
Found nothing in commits that looks like it could be related.

@miloja the fact is that it works for you in safe-mode, so the issue is somewhere in your profile folder.

Could you zip up your profile folder (the 10.1 one) and send it to support@activestate.com with a reference to this ticket? You can delete the codeintel folder before you do, we don't need that one and it will otherwise make your zip a LOT bigger than it needs to be.

Instructions on locating your profile folder:

http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

**Comment by miloja** [comment] 2016-11-10 07:49
Profile sent in 2 emails (it exceded 20MB server limit). Btw. I've made some experimet and exchanged 10.0 profile with 10.1 one. After this "Go back" in 10.0.1 is still working quite fine (with minor issues described previously), so I don't expect it's connected to the profile.

Looks I'll have to stick to 10.0.1 untill issue will be solved. "Go back" is very quite a time saver.

**Comment by Naatan** [comment] 2016-11-14 16:31
Hey @miloja, I've waited a few days to make sure the email went through but unfortunately have still not seen it come in :\

Could you send it again? This time also add me to CC: nathanr @ activestate . com

And be sure to reference this ticket (include a link).

**Comment by miloja** [comment] 2016-11-15 08:44
Done. Subject "Issue #2093 attachemant". 2 e-mails. Link included in the emals content.

**Comment by Naatan** [comment] 2016-11-15 16:40
Thanks @miloja, that gave me what I needed!

I don't have solution to the actual bug yet, but here's a workaround:

Run the following command in the console widget (bottom pane):

```
require("ko/prefs").setBoolean("runGetStartedTutorial", false);
```

That should resolve your history issue as well as likely some other issues.

**Comment by Naatan** [comment] 2016-11-15 16:55
Closing this in favour of #2150

**Closed by Naatan** 2016-11-15 16:55 UTC
Labels: Pending: Response

**Comment by miloja** [comment] 2016-11-16 07:48
The command is helping. It's some workaround, but working one, so it's enough for me. Thanks for help!
