### ISSUE TITLE
Places category in Preferences broken

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1500] opened 2016-05-17 19:53 UTC
### Short Summary
The Places category in the Preferences window is broken.

### Steps to Reproduce
Open Preferences. Navigate to **Places**.

### Expected results
Something?

### Actual results
An `XML Parsing Error`.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
![image](https://cloud.githubusercontent.com/assets/7350183/15336987/d7b3b41e-1c3e-11e6-88a5-377e0b0c1bfc.png)

### Addendum
Finding Komodo bugs is like my new favorite thing now. Also, issue 1500!

**Comment by Naatan** [comment] 2016-05-17 20:09
Duplicate of #1463

This will be fixed in 10.0.1

**Closed by Naatan** 2016-05-17 20:09 UTC
