### ISSUE TITLE
IDE X, missing column "Revisions" in SCC history

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1534] opened 2016-05-18 18:58 UTC
### Short Summary

Subj, as I said in #1527
Revision column not exist in any SCC history place/window and not exist in column picker.
VCS - subversion 1.9.3

### Platform Information
Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

**Comment by Naatan** [comment] 2016-05-18 20:53
Ah I remember this now. It's not missing, it was removed by design. You can get the revision by selecting a commit. I did not see any merit in having them listed there as they only serve as a unique identifier for as far as I am aware. That said I realize there might be other use cases and am open to bringing it back. Can you explain your use-case?

**Comment by landy2005** [comment] 2016-05-18 23:18
Ouch..
You can make it unchecked by default, but it should be here..
Since this is unique identifier for commit.
My mostly used case: compare some specific revisions (I know revision numbers).
Also in some case log message can be empty..

I know, this is can be not actual for git/hg, but in other VCS (subversion) it still required.
Please back it, I not think that this is impact on performance.

**Comment by landy2005** [comment] 2016-05-18 23:32
Other use-case: I can see (found) revision where made specific change and will revert (manually from console) to this revision..
or if I want to see source tree for specific revision..

(I quick see file history from IDE, than see source tree for this revision by other place)..
I really not know why someone not want to know revision identifiers.. :)

**Comment by Naatan** [comment] 2016-05-19 00:43
Fair points, I will add it back in.

**Comment by Naatan** [comment] 2016-05-19 20:10
Fixed with https://github.com/Komodo/KomodoIDE/commit/0fcaf59a4c9b4e20584ca5368bc07a367d4e793a

**Closed by Naatan** 2016-05-19 20:10 UTC
Labels: Enhancement
