### ISSUE TITLE
Unable to select entries in clip board manager

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2896] opened 2017-08-18 23:29 UTC
### Short Summary

Unable to select entries using up/down arrow key. Also, pressing enter does not add text to the file.

### Steps to Reproduce

1. ctrl+shift+v to bring up clip board manager

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90491, platform macosx.
Built on Thu Aug 17 23:38:33 2017.

**Comment by Naatan** [comment] 2017-08-18 23:31
Please share your error log after reproducing.

**Comment by mjainQA** [comment] 2017-08-18 23:35
[pystderr_2017-08-18_Komodo IDE 11.0.0 Alpha 1 nightly (Build 90491).txt](https://github.com/Komodo/KomodoEdit/files/1235927/pystderr_2017-08-18_Komodo.IDE.11.0.0.Alpha.1.nightly.Build.90491.txt)

**Comment by Naatan** [comment] 2017-08-21 15:45
I cannot reproduce this on linux or macos. @mjainQA can you restart Komodo and try again, also try safe mode.

**Comment by mjainQA** [comment] 2017-08-21 20:45
Unable to reproduce in Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017.

**Comment by Naatan** [comment] 2017-08-22 15:58
Ok, going to close this as it seems to have been a fluke. lmk if you see this again.

**Closed by Naatan** 2017-08-22 15:58 UTC
Labels: Introduced: 11, Type: Bug
