### ISSUE TITLE
Komodo IDE 9.3 Error while saving preferences

### ISSUE THREAD

**Issue by ziermmar** [Komodo/KomodoEdit#809] opened 2015-11-05 12:55 UTC
Fresh install of 9.3 on ArchLinux / Gnome 3.18. (Had used 9.2 before, but deleted ~/KomodoIDE-9 and ~/.komodoide/9.2 beforehand).

When trying to set intendation preferences, I'm getting this error:

Trying to save global indentation settings triggered an exception: 
TypeError: g_prefset is null

pystderr.log:
-- EXCEPTION START --
TypeError: g_prefset is null
+ stack
    getPrefsForLanguage@chrome://komodo/content/pref/pref-indentation.xul:90:1
    changeNewLanguage@chrome://komodo/content/pref/pref-indentation.xul:110:15
    OnPreferencePageOK@chrome://komodo/content/pref/pref-indentation.xul:60:9
    koPrefWindow.prototype._doOKHandlers@chrome://komodo/content/pref/koPrefWindow.js:210:26
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:265:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:296:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
-- EXCEPTION END --

**Comment by Naatan** [comment] 2015-11-05 16:06
Could you try deleting all of `~/.komodoide`? Komodo does inherit from earlier versions too. (You may want to make a backup).

Of course updates should work just fine and generally they do, but glitches happen and unfortunately there doesn't seem to be enough here to figure out what that glitch was.

**Comment by ziermmar** [comment] 2015-11-05 19:13
I've tried deleting ~/.KomodoIDE-9 & ~/.komodoide and doing a fresh installation. Unfortunately still happening.

The error doesn't appear immediately. I have to go to the intendation preferences first, and then hit the save button.

**Comment by Naatan** [comment] 2015-11-05 19:20
What are you changing in preferences exactly?

After you deleted ~/.komodoide, did Komodo start with the "getting started" dialog and ask you to opt-in to analytics?

**Comment by ziermmar** [comment] 2015-11-05 19:27
I don't need to change anything for the error to occur. Initially i wanted to try elastic tabstops. That's when it first happened. After I deleted .komodoide I was indeed asked to opt-in to analytics. (I declined). Also I left the checkbox unchecked for the getting started dialog to not appear on next start.

**Comment by Naatan** [comment] 2015-11-05 19:51
So the indentation prefs you access is under Editor > Preferences, or somewhere else? 

And how do you close the Preference dialog that triggers the error?

**Comment by ziermmar** [comment] 2015-11-05 20:02
It’s in Edit -> Preferences -> Editor -> Indentation.

I checked ‘prefer tab characters over spaces’ and ‘enable elastic tabletops’ for example, hit ok and got the error message. A dialog box opened up, asking me if i want to ignore the error or ‘fix it’, which just got back to the preferences dialog. I’ve noticed then, that several values which were set previously, like for example ‘number of spaces per indent’ were empty now.

Oh… just happened on my home computer as well. This time on Mac OS X even.
![screen shot 2015-11-05 at 21 01 50](https://cloud.githubusercontent.com/assets/1862674/10980095/7aa6236e-8400-11e5-940e-b8cd79911425.png)

**Comment by Naatan** [comment] 2015-11-05 20:05
Are all fields empty like that on your Linux PC as well? that doesn't look right at all.

Can you please post your build info? Help > About Komodo.

**Comment by ziermmar** [comment] 2015-11-05 20:10
Yes, after hitting OK, all fields in that dialog are empty, both in Linux and OS X. I can only give you the build number of komodo edit for os x, which I've just downloaded a few minutes ago. It's 16396. I can give you the build number of the one on the Linux machine (which is komodo ide, btw) tomorrow morning, when I'm back in the office. It might be the same one. (Downloaded earlier today).

**Comment by Naatan** [comment] 2015-11-05 20:27
Tried Edit on Linux, OSX and Windows. Existing and clean profiles. I cannot reproduce this, I don't know how you can reproduce it on 2 different platforms, perhaps I am missing something in the steps you take to reproduce this issue. Would you mind recording a quick screencast of yourself reproducing the issue with a clean profile (Restart in Safe-Mode).

Thanks!

**Comment by ziermmar** [comment] 2015-11-05 20:52
Well, this is odd, i guess? I've been trying to reproduce this after starting in safe mode, but it seems that this fixed it somehow. (At least on OS X). 

I tried deleting those directories:
~/Library/Caches/Komodo Edit
~/Library/Caches/TemporaryItems/ko-temp-*
~/Library/Application Support/Komodo Edit
~/Library/Application Support/KomodoEdit
(am I missing something?)

hoping to delete everything and start fresh, but again couldn't reproduce anymore. Let me try tomorrow on the other machine to get you a screencast recorded...

**Comment by Naatan** [comment] 2015-11-05 21:10
`~/Library/Application Support/KomodoEdit` is your profile directory on OSX. On linux it's `~/.komodoedit`..

**Comment by cgchoffman** [comment] 2015-11-06 01:36
@ziermmar fyi: http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data

Those are the only directories you'll need to move aside

**Comment by maliguen** [comment] 2015-11-16 13:26
I have the exact same problem when saving preferences in Komodo Edit on Windows 7 (version 9.3.0, build 16396, platform win32-x86).

Don't know how to fix it.

**Comment by ziermmar** [comment] 2015-11-16 13:30
I couldn't reproduce it anymore once I started in safe-mode.

**Comment by maliguen** [comment] 2015-11-16 13:52
How do you start in safe-mode and what is the impact of this mode on the app?

**Comment by mitchell-as** [comment] 2015-11-16 15:27
You can start in safe mode by opening KomodoIDE, closing any open files (from a previous session), and then on the "New Tab" screen there is a "Troubleshooting" button at the bottom right. Click it and select "Restart in Safe-Mode". The impact is that Komodo use a temporary directory as your user profile, thus not loading any of your addons, skins, etc. This is primarily for diagnostic purposes, to see if an addon is causing trouble, and not Komodo itself.

**Comment by Naatan** [comment] 2015-11-16 16:42
Could someone with this issue send me their prefs.xml from their profile folder? Either on here (if they don't mind sharing it publicly) or in private: nathanr@activestate.com

**Comment by maliguen** [comment] 2015-11-17 04:34
@Naatan
I just send you by e-mail the file you need. 

By the way, just to let you know that I have installed Komodo Edit a few days ago and I have made some minor modifications to préférences.

**Comment by Naatan** [comment] 2015-11-17 16:53
Thanks @maliguen, unfortunately I cannot reproduce the issue with the prefs.xml provided :\ This was from a profile that was at that time having the issue right?

**Comment by mitchell-as** [comment] 2016-02-09 15:42
Closing as this appears to be a non-issue now. I cannot reproduce this either.

**Closed by mitchell-as** 2016-02-09 15:42 UTC
Labels: Pending Response
