### ISSUE TITLE
Komodo IDE 11.1 abbreviations not honouring indentations

### ISSUE THREAD

**Issue by KrisHarris** [Komodo/KomodoEdit#3569] opened 2018-06-29 12:05 UTC
It would appear that abbreviations aren't honouring indentations. This was working on previous versions.

Have only tried this with PHP so far so unsure if other languages are affected in the same way.

### Steps to Reproduce
Indent line and start typing an abbreviation (for auto) or find abbreviation and insert it to current line.

### Expected results
        if ($test) {
            //code
        }

### Actual results
        if ($test) {
        //code
    }

### Platform Information
*Komodo IDE* 
*Komodo 11.1* 
*Windows7 Pro 64bit*

**Comment by Defman21** [comment] 2018-06-29 12:49
Other languages are affected as well.

**Comment by Naatan** [comment] 2018-06-29 14:54
Did you have the "preserve indentation" toggle checked?

**Comment by KrisHarris** [comment] 2018-06-29 15:10
Can you tell me where this toggle would be?
I have attached the properties of the abbreviation, maybe it is one of these, or is it somewhere else?

![image](https://user-images.githubusercontent.com/3941803/42099827-6c43017e-7bb6-11e8-84c2-6f7765137210.png)

**Comment by Naatan** [comment] 2018-06-29 15:12
Maintain indentation, looks like you have it checked.

**Comment by KrisHarris** [comment] 2018-06-29 15:18
ah, ok I see, yes these are pretty much my default setting for all abbreviations

**Comment by cgchoffman** [comment] 2018-06-29 16:33
huh, that's frustrating.  I filed this bug months ago then subsequently closed it because I couldn't reproduce it again when I wen to fix it.  Thanks for the report @KrisHarris

**Comment by chrisluka** [comment] 2018-07-30 17:05
Do we know when a fix for this is going to be released? I may need to move back to IDE 10 if it's going to take to long, as I rely extensively on snippets in my workflow.

**Closed** 2018-08-03 21:14 UTC
Labels: Introduced: 11.1, Type: Bug

**Comment by mitchell-as** [comment] 2018-08-03 21:15
@cgchoffman I reverted your fix for #3437 in favor of fixing this because this bug affects all snippets. #3437 only affects `[[%s]]` snippets, which is a subset. When you provide a new fix for that bug, please ensure it doesn't trigger this one again.
