### ISSUE TITLE
Komodo Edit 11 Shows up as Komodo Edit 10 on macOS

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3396] opened 2017-12-01 16:39 UTC
### Steps to Reproduce

 * Install Komodo Edit on macOS
 * Launch it through its launcher app by typing the name

### Expected results

 * Shows up as Komodo Edit 11

### Actual results

 * Shows up as Komodo Edit 10

**Comment by cgchoffman** [comment] 2018-01-03 23:08
I can't reproduce this.  Where exactly does it show up as *Komodo Edit 10*?  I'm guess in Launcher?  I'm not seeing that.

**Comment by cgchoffman** [comment] 2018-01-15 23:31
Gonna close this one.

**Closed by cgchoffman** 2018-01-15 23:31 UTC
Labels: Limited to: Edit, Limited to: OSX, Pending: Internal, Type: Bug
