### ISSUE TITLE
Commando ranks findings poorly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2718] opened 2017-07-26 17:21 UTC
### Short Summary

I'm trying to use Commando to open a file in a random path on my computer but it's ranking findings in a way that make it impossible to us it in that manner.

### Steps to Reproduce

Example:
I'm trying to get to my home directory from the root of the C drive.
path: *C:\Users\cgcho*
- I type *C:\U*
- Select *C:\Users* no problem
- then type *c*

### Expected results

*cgcho* to be the first option presented as it's the most relevant in this context.

### Actual results

Files with the letter *c* in their names in the folders found in *C:\Users\* are presented.  I can't even SEE my home directory in the options.  See the screenshot below.

![screenshot 2017-07-26 10 14 35](https://user-images.githubusercontent.com/655154/28634440-107e6c18-71ec-11e7-9a53-c514813feadd.png)

I labelled this as a *bug* rather than *enhancement* since it doesn't seem to make sense why it's doing what it's doing.

**Comment by cgchoffman** [comment] 2017-07-26 17:23
I'm guessing it's just presenting results as they are found so my home dir was likely the first thing found and therefore pushed to the bottom of the list.

**Comment by Naatan** [comment] 2017-07-26 18:04
Yeah that query is way too short, it will reach the limit and provide ordered results of files within that scope, Your cgcho folder likely didnt make it into the scope due to the limit used. You can test this by increasing the limit to like 1000. 

If this is in fact the limit then I would close this as by design, as that limit exists to keep Commando running smooth and the proper solution here is to type a proper query rather than just one character.

**Comment by cgchoffman** [comment] 2017-07-26 18:10
This doesn't make any sense.  I'm IN *C:\Users* for the query.  How can it be "by design" that it gives me sub folder results before it gives me current folder results?

**Comment by cgchoffman** [comment] 2017-07-26 18:11
This works in Komodo 10:
![screenshot 2017-07-26 11 05 29](https://user-images.githubusercontent.com/655154/28636520-3b8916c2-71f3-11e7-8a69-40f9a0f9e3c9.png)

**Comment by Naatan** [comment] 2017-07-26 18:12
Komodo 10 has a larger limit. Can you try increasing the limit to verify my theory?

**Comment by cgchoffman** [comment] 2017-07-26 18:17
It's not the limit.  I didn't change it for this screenshot.  I don't think it's sorting the results.  It's just pushing them to the output pane as they are found.
![screenshot 2017-07-26 11 15 21](https://user-images.githubusercontent.com/655154/28636707-d6797852-71f3-11e7-84fb-3913376afe79.png)

**Comment by Naatan** [comment] 2017-07-26 18:30
Hmm ok, strange. Will dig - thanks!

**Closed** 2017-07-27 19:08 UTC
Labels: Introduced: 11, Type: Bug
