### ISSUE TITLE
Fold Lines are Still not closing after bug reported in April 2017

### ISSUE THREAD

**Issue by Alcyros11** [Komodo/KomodoEdit#2904] opened 2017-08-20 16:40 UTC
Following my original bug report back in April, and after a fresh install of 10.2.3 tonight, those fold lines are still not dissapearing :( The original bug report was #2434. Nothing has changed on my end except I updated Komodo tonight, when that did not fix the problem, I did a fresh install, still hasnt worked, and yes I pressed the Apply button several times and its doing nothing. Dan
![bug-komodo](https://user-images.githubusercontent.com/26843243/29496642-4fae0336-8609-11e7-96b3-87709ee48965.PNG)

**Comment by mitchell-as** [comment] 2017-08-21 12:26
Can you reproduce this in Safe Mode? (Help > Troubleshooting > Restart in Safe Mode) If you do not have this issue in Safe Mode, then something in your profile is causing the problem.

**Comment by Alcyros11** [comment] 2017-08-21 12:48
Hi mate, yes safe mode stopped the lines from appearing when the box was unchecked. Just to add to that though, the checkbox does not show them up at all now (after I reset my pc back into normal mode), the profile I am using is stock standard, I havent changed anything, I only just installed this fresh version yesterday, problem is solved for what I want, but there is still a bug there by the looks of it.

**Comment by Alcyros11** [comment] 2017-08-21 13:28
Actually scrap that, the problem is occuring again

**Comment by Alcyros11** [comment] 2017-08-21 13:31
mate the problem is still occuring even with a default profile :(

**Comment by mitchell-as** [comment] 2017-08-21 13:37
Is the problem still occurring in Safe Mode?

**Comment by Alcyros11** [comment] 2017-08-21 13:47
please also be aware i used to use komodo 9 nightly and the problem was there too, that has been removed off my system previously

**Comment by Alcyros11** [comment] 2017-08-21 13:51
Also it does not matter which type of fold mark style I use, arrows, square etc, the lines still stay there, the only time the lines dissapear is when i select "No fold marks" from the drop down menu

**Comment by Alcyros11** [comment] 2017-08-21 13:52
Can you please direct me how to access this file?

**Comment by mitchell-as** [comment] 2017-08-21 14:03
Please attach the file rather than copy-pasting its contents.

**Comment by Alcyros11** [comment] 2017-08-21 14:04
[prefs.txt](https://github.com/Komodo/KomodoEdit/files/1239027/prefs.txt)

**Comment by Alcyros11** [comment] 2017-08-21 14:27
ok thanks, i will get back you shortly

**Comment by Alcyros11** [comment] 2017-08-21 14:33
Ok, I changed the preferences 3 times, closed komodo each time, loaded up the xml in text form, and its not changing in the xml file at all, i tried +/-, square and curve and the xml file is continuing to show arrows and the 1......lines are also still there

**Comment by mitchell-as** [comment] 2017-08-21 14:42
Okay, I'd like you to close Komodo and temporarily move your Komodo IDE or Komodo Edit user folder somewhere else completely. (This is the folder of the folder that contains your prefs.xml file.) Then start up Komodo again and try the same set of steps.

**Comment by Alcyros11** [comment] 2017-08-21 14:51
It will not load Komodo without the folder in its original place, i then put the folder back into its original spot and komodo loaded but with no changes of course....I have included a screen shot where the file is located, i moved the whole support folder when attempting this
![komodo4](https://user-images.githubusercontent.com/26843243/29524747-402dad98-86c3-11e7-914e-0150236acad0.PNG)

**Comment by mitchell-as** [comment] 2017-08-21 14:55
You need to be working with your user profile folder, which is located in *C:\Users\<user>\AppData\Local\ActiveState\KomodoEdit*. It looks like you are trying to edit Komodo's actual application folder.

**Comment by Alcyros11** [comment] 2017-08-21 15:06
![komodo5](https://user-images.githubusercontent.com/26843243/29525440-368eb82a-86c5-11e7-8735-f425a63b8a07.PNG)

ok i found it, i will try the above step again

**Comment by Alcyros11** [comment] 2017-08-21 15:16
ok, i moved the 10.2 folder to the desktop, then went into start menu and loaded komodo up and it is putting the 10.2 folder back into where I took the folder out of....its loading up a fresh version of the program but the lines are now turning on and off......I think we may of solved this, any ideas how lol?
![komodo6](https://user-images.githubusercontent.com/26843243/29525912-bcf04a22-86c6-11e7-8527-ad0a595e3d14.PNG)

**Comment by Alcyros11** [comment] 2017-08-21 15:18
nope it still is not working :( it was working, now its not

**Comment by Alcyros11** [comment] 2017-08-21 15:45
Mitchell, ok I went and did the step with loading up the xml file and checking the "edit fold lines" , yes it is changing the xml content now based on what i set in komodo, but the lines are still not dissapearing......

**Comment by Naatan** [comment] 2017-08-21 16:01
@Alcyros11 mitchell was saying you should move the entire KomodoEdit folder, not just the version folder.

**Comment by Alcyros11** [comment] 2017-08-21 16:33
It makes no difference, it just moves the folder back to its default position no matter where i move it to as soon as i load it up through the start menu

**Comment by Alcyros11** [comment] 2017-08-21 16:34
it litterally puts it back as soon as i load it, i have ActiveState folder open and when i load komodo up from the start menu it reappears back in there

**Comment by Alcyros11** [comment] 2017-08-21 16:36
I have tried everything tonight and it still has not solved this problem

**Comment by Alcyros11** [comment] 2017-08-21 16:38
The reason i have not just gone onto another program to code with is because I really like Komodo, however i need to sort this it is a ridiculous issue to have

**Comment by mitchell-as** [comment] 2017-08-21 16:39
@Alcyros11 Thank you for going through the steps. The fact that it worked initially when you moved your existing profile, and then stops working later helped me reproduce the problem.

For your information, whenever you move or delete your user profile, Komodo creates a new, default one when it starts. That is what you are observing. With a new profile, the problem does not manifest itself until later. I will work on resolving this as soon as I am able.

Thanks for your patience and sorry for the inconvenience.

**Comment by Alcyros11** [comment] 2017-08-21 16:40
Thx so much! it is strange that i have had this problem with ALL versions of komodo, look forward to working this out

**Comment by mitchell-as** [comment] 2017-08-21 16:41
Note to self: Start with a clean profile, turn off fold lines, quit Komodo, and then restart it. Now no matter how the preference is toggled, the lines always display.

**Comment by Alcyros11** [comment] 2017-08-21 17:06
Hey, its working again mate. I reloaded it three times, changed the color profile about 5 times, and it seems to be working properly. I will keep you informed over the next 48 hours, can you leave it with me to just test it over this time before you spend any more of your time on this, cheers and thanks again for your help. it makes no sense to me why its being a little bitch. will be in touch on this thread.

**Comment by Alcyros11** [comment] 2017-08-21 17:08
scrap the comment i just deleted. I have new info for you, the fold lines are dissapearing when I edit a CSS file but not when I am editing the HTML file, hope this helps :)

**Comment by mitchell-as** [comment] 2017-08-21 17:26
Okay, I'll sit tight. Thanks.

**Comment by mitchell-as** [comment] 2017-08-25 18:52
Well after spending some time investigating this, I found out that this preference is a file-level preference. If toggling the global preference does not seem to work, then either toggle the file preference (Edit > Current File Preferences...) or reset your file preferences (Help > Troubleshooting > Reset File Preferences).

This is not actually a bug.

**Closed by mitchell-as** 2017-08-25 18:52 UTC
Labels: Type: Bug

**Comment by Alcyros11** [comment] 2017-08-27 05:28
Thanks for the emails! I tried what you suggest and it worked, thanks for working through it with me, I appreciate it, its looking a lot better and manageable now, cheers! :)
![yes](https://user-images.githubusercontent.com/26843243/29747362-86839d4a-8b2b-11e7-882a-083408e70927.PNG)
