### ISSUE TITLE
Feature Request: Load Imports

### ISSUE THREAD

**Issue by TangoOversway** [Komodo/KomodoEdit#1016] opened 2016-01-19 20:23 UTC
This is more of a feature request.  I'm using Python, but I'm sure this would work easily with many languages.  When I have the Code sidebar open, I can go to "Imports" and expand it to get a list of what I'm importing.  It'd be nice to be able to double-click on an import or right click on it and be able to load that file or library, if it's text base and not binary.

**Comment by Naatan** [comment] 2016-01-19 21:20
By load you mean open / go to?

**Comment by TangoOversway** [comment] 2016-01-20 00:24
Do you mean to go the specific line?  Or go to the file?

For instance, if I have:

import formprinter

I noticed if I double-click, it will go to that line.  (I forgot it did that - I was on the line itself, so I didn’t see it move to the line.)

But it would be helpful if I could right click on that entry in the Code sidebar and then pick "Load formprinter.py" or something like that and then have that entire file loaded into a new tab.

I didn’t see a way to automatically load the file I’m importing, or to load it and go to it.  If there is a way to do that, it would be helpful, especially since, often, it could be in several different directories in a directory tree somewhere.  (For instance, if I’m using Perl and have "use xyzperlmod", that could be in several different directories, so if Komodo found it and loaded it for me.

Of course, this assumes there’s a text version of the file.  I’m aware that in some languages, such as C or C++, it might be just linking to a binary library that can’t be loaded.


Hal

**Comment by mitchell-as** [comment] 2016-01-20 17:13
You can either Ctrl+Click or Right-Click > Go to Definition to jump to the definition of an import from within the editor view. Therefore it's a two-stage process:

1. Double-click on the import in the code sidebar.
2. Ctrl+Click or Right-Click > Go to Definition on the import library.

I think the current behavior of the sidebar should remain as-is for consistency. Adding a right-click option to the sidebar is an option, but seems unnecessarily complex.

**Comment by TangoOversway** [comment] 2016-01-20 17:23
So it’s already there?  Great!

But it doesn’t work.  When I right click or control-click on the item in the Code sidebar, I don’t get any context menu.

Any idea how I can fix this?  (I’m on OS X, if that makes a difference.)


Hal

**Comment by mitchell-as** [comment] 2016-01-20 17:25
It's not the sidebar where you Ctrl+Click or Right-Click, but the identifier in the editor view (where you type text).

**Comment by TangoOversway** [comment] 2016-01-20 17:31
I right click and pick "Go to definition."  (It says "Ctrl-K, Ctrl-G" on that choice.)  But nothing happens.  Do I have to have the file loaded already?


Hal

**Comment by mitchell-as** [comment] 2016-01-20 17:47
No, when nothing happens that means Komodo cannot find that import in your path.

To illustrate, I have two files in the same directory: "foo.py" and "bar.py". The contents of "foo.py" are simply:

    class Foo:
        pass

The contents of "bar.py" are:

    from foo import Foo

When I open "bar.py" and Ctrl+Click on "Foo", I am taken to the definition in "foo.py".

I hope this is more clear.

**Comment by TangoOversway** [comment] 2016-01-20 19:00
So if the file I’m editing and the file I’m importing are in the same path, it should open it, shouldn’t it?


Hal

**Comment by mitchell-as** [comment] 2016-01-20 19:10
Yes.

**Comment by TangoOversway** [comment] 2016-01-20 19:16
It doesn’t.

I have multiple files in my editor (as part of the IDE).  I go to one file, print1099.py and go to the Code sidebar and click on imports to open up the list.  One is halconfig.  I double-click on halconfig and it takes me to the line in the file that says "import halconfig."  My file halconfig.py is in the same directory as print1099.py.  I right click on "halconfig" in the line with the import statement.  I get the context menu and pick "Go to Definition."  Nothing happens.

I even loaded halconfig.py into the editor, to see if it would go to that tab once it was in the editor.  It doesn’t.


Hal

**Comment by mitchell-as** [comment] 2016-01-22 15:57
The first question I have is can you reproduce the simple example I gave above and get the correct "Go To Definition" behavior?

The second question I have is will you please go to your Komodo user data directory (~/.komodoide/version/) and post the contents of your "codeintel.log" file AFTER you try a "Go To Definition"?

Third question is (if possible) would you please zip up those two files and post them to this thread so I can run some tests myself?

**Comment by TangoOversway** [comment] 2016-02-21 06:43
I’m sorry it took me so long to get back to this.  (We’ve bought land and are dealing with designing and building a house, and at some stages it’s all-encompassing.)

I tried several different things in a file named haldb.py.  (It’s in /Users/hal/Documents/Dev/HalPy/haldb.py.)

At this point, all my Python files are in that same directory.

I have these includes:

from itertools import cycle
import os
import os.path
import sqlite3

import halutil as hu

If I right click on halutil, which is, at this point, loaded into the Komodo IDE’s editor, the "Goto definition" item on the context menu (when I right click) does nothing.

However, if I click on "os" in "import os" and pick "Goto definition," then it will load the file.

I have edited my .bash_profile so PYTHONPATH includes the directory with all my Python modules as well.  Apparently Komodo does not see that directory as being part of the includes and can’t even see that if the file is loaded in the editor, it’s the one being referred to.  Do I need to do something to tell Komodo to use that directory for includes?


Thank you.


Hal

**Comment by mitchell-as** [comment] 2016-02-22 17:23
Hi Hal, I believe you are correct when you say that that Komodo does not see a directory you've specified in your PYTHONPATH. Komodo actually doesn't read from that variable to look for Python libraries. Instead it relies on you to specify it in Edit > Preferences > Languages > Python 3 > Additional Python 3 Import Directories (or "Python" if you're using Python 2). Whichever directories you add to that list will be scanned by Komodo for additional symbol lookups. It sounds like all you have to do is add your directory to this list and you should be good to go.

**Comment by TangoOversway** [comment] 2016-02-23 20:08
I’m using Python 2.7.  I did this and added the path for Python and it didn’t make a difference.  I restarted the IDE and it didn’t help.  Just in case, I added it to Python 3 as well and it didn’t help.  So I restarted and still, no difference.

So I’ve got the directory added as an import for Python and  Python 3.  I’ve included the screenshot below of the Preferences window with it added to Python.  I’ve even verified the path spelling several times and very closely - to be sure I didn’t point to HalPerl or anything else in my development directory, or to a backup, or anything like that.  When I pick "Goto definition" from the context menu, nothing happens.

Is there a chance I need to add or edit any other settings to make this work?

Thank you!


Hal

**Comment by cgchoffman** [comment] 2016-02-23 20:17
> I’ve included the screenshot below of the Preferences window with it added to Python

I assume you attached the image to the email you replied in.  You can't include pictures like that.  You'll have better luck actually commenting in the ticket it's self at github.com rather than replying to the email.

**Comment by TangoOversway** [comment] 2016-02-23 23:35
Okay, image attached.  This goes with my last response, pasted in below:

I’m using Python 2.7.  I did this and added the path for Python and it didn’t make a difference.  I restarted the IDE and it didn’t help.  Just in case, I added it to Python 3 as well and it didn’t help.  So I restarted and still, no difference.

So I’ve got the directory added as an import for Python and  Python 3.  I’ve included the screenshot below of the Preferences window with it added to Python.  I’ve even verified the path spelling several times and very closely - to be sure I didn’t point to HalPerl or anything else in my development directory, or to a backup, or anything like that.  When I pick "Goto definition" from the context menu, nothing happens.

Is there a chance I need to add or edit any other settings to make this work?

Thank you!


Hal



![screen shot 2016-02-23 at 3 05 27 pm](https://cloud.githubusercontent.com/assets/16636093/13270431/2a3ed698-da5c-11e5-90a1-c3c04d631936.png)

**Comment by mitchell-as** [comment] 2016-02-24 15:40
Hi Hal, thanks for your continued patience. I'm really not sure what could be the matter because it still works for me.

I've created a directory "/tmp/test/" and a file "foo.py" within it. Within "foo.py" I have:

    class Foo:
        def bar(self):
            pass

I added "/tmp/test/" to Edit > Preferences > Languages > Python > Additional Python Import Directories.

Then I created a blank, untitled document (Ctrl+N), set the language to "Python", and typed `import `. I got "foo" in the list of completions, so I know that my "foo.py" file was picked up by codeintel. When I hover the mouse over "foo" with the Ctrl key held down, I get a small popup pointing to my "/tmp/test/foo.py" file. When I Ctrl+Click or Right-Click > Go to definition, my "/tmp/test/foo.py" file opens.

Do you have a "/Users/hal/Documents/Dev/HalPy/halutil.py" file? Does codeintel work for your `halutil` or `hu` objects?

**Comment by TangoOversway** [comment] 2016-02-24 17:37
I’m just very appreciative you guys are willing to help me with this.  I’ll have to add I’m basically self-taught in terms of programming.  I had a couple classes in college, back in the 1980s, but at that point had never even heard of an IDE and, aside from a lot in programming itself, there’s so much in the build process and in IDEs that I’m still learning about.

I’m not sure what you mean by "codeintel."  I do have halutil.py in the specified directory and it’s even loaded into my Komodo editor, in a tab in the same window with the haldb.py and when I run my programs from bash or from IDLE, they have no problem finding either of those files and using them.

After reading through your test several times, I went to another file, commented out the "import halutil as hu" statement in it, then, on the next line, typed "import" and halutil was in the list of auto-completions.  So I picked it and that left the line as "import halutil" and used the "Goto definition."

Here’s where the "good news/bad news" thing starts.  The good news is it worked fine and went to the halutil.py file in the editor.  The bad news is once I add "as hu" to the end, it will no longer go to the definition.  I also tested that in my haldb.py file.  It works with "import halutil" but if I use "import halutil as hu" it does not work.

So I would think this indicates a bug, but at least narrows it down enough that it would be clear what to fix.  I figure if you’re fixing it for Python only, it won’t be hard, but I don’t know if other languages would use keywords on import or use statements or allow spaces in file names.


Hal

**Comment by mitchell-as** [comment] 2016-02-24 17:54
Hi Hal, you are awesome! That was it :) Reproduced. The `import X as Y` construct causes goto definition to fail.

**Comment by TangoOversway** [comment] 2016-02-24 18:46
Well, the one thing I *had* to learn was debugging.  I was stuck without a job a while back and found a data mining opportunity.  I had to teach myself 5 or 6 new languages (most of which didn’t exist in the 1980s, when I too Fortran, Assembler, and dropped out of Pascal in college) and get the system working in a hurry.  Within a decade, that business let me retire early.  I know there’s a lot of stuff I never learned in programming, since I was goal driven through it all (get it working, keep clients happy, add the next step before clients get impatient, and so on).  But I had no choice but to learn to debug!  The part of my software I gave to my clients to use on their systems was at version 1.x for five years.  It was the first program I ever "published" for others to use, instead of just me using it.  In that five years, we found 6 or fewer bugs.  (I don’t remember, but I think one was a limitation, not a bug.)

So there’s tons I don’t know, but I can find a bug! ;)

I take it, then, it is a bug?  Should I file it as a new issue?  And I’ll be glad to help with testing and troubleshooting if anything is needed.



Hal

**Comment by mitchell-as** [comment] 2016-02-24 20:23
Actually, yes, would you please go ahead and file it as another issue? I forgot the original subject :) Also please mention this ticket number in the new issue so I can reference it.

Thanks!

**Comment by TangoOversway** [comment] 2016-02-24 22:49
I’ll do it this evening.

As I said, I didn’t learn a lot about IDEs and the build process, but I searched for a long time to find a good programming editor that didn’t have issues.  I really appreciate Komodo, so if I can help in some way, I’m glad to pitch in.

Thanks!


Hal

**Comment by mitchell-as** [comment] 2016-02-25 15:41
Closing in favor of #1107

**Closed by mitchell-as** 2016-02-25 15:41 UTC
Labels: Bug
