### ISSUE TITLE
Source code control (SVN) overlays have disappeared since upgrading to Komodo X

### ISSUE THREAD

**Issue by Graar** [Komodo/KomodoEdit#1894] opened 2016-08-03 20:59 UTC
### Short Summary
Komodo X marketing literature promises enhancements to the source code control functionality.  In reality, I have lost all source code control functionality in Komodo X.  Previosuly files had little icons/overlays that indicated their status e.g. a little pencil to indicate the file was being edited, since Komodo X these have disappeared and we have lost a key part of the functionality of the tool

### Steps to Reproduce
Try and use SCC in Komodo X

### Expected results
A graphical indication of the status of the files

### Actual results
No graphical indication of the status of the files.  The screen shot shows files under version control and some that are not, there is no way to tell them apart.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* Windows 10 and Windows 7

### Additional Information

 -- eg. Error logs, screenshots, workarounds --
![image](https://cloud.githubusercontent.com/assets/8624070/17381772/8cb78458-59c5-11e6-9391-c6d8398bd03f.png)

**Comment by Naatan** [comment] 2016-08-03 21:08
This functionality has changed, nothing has disappeared. File status is now indicated by colors and the tools are accessible from the side toolbar. See the documentation for more info:

http://docs.komodoide.com/Manual/scc#source-code-control-komodo-ide-only_using-source-code-control_file-colors

**Comment by Graar** [comment] 2016-08-04 05:14
Naatan,

I am not sure how having a set of colours that I have to remember is an improvement, I don't see a problem with the meaninful icons.

However, when I go to a file that is marked in blue (which apparently means that the file has been modified locally) and then go to the SCC menu, I see no option to do a commit.  every option on the SCC menu is greyed out.  Likewise I dont think that I see any button on the 'dynamic too bar'.  I am not even sure what this dynamic tool bar is, but I can't find anything related to version control.

So, please could you re-open the ticket.  SCC has gone in Komodo X.

**Comment by Naatan** [comment] 2016-08-04 15:58
Could you try pointing your Places widget at the root directory of your SVN checkout?

Additionally, check out the "Version Control" widget in the bottom pane. If no SVN repository was detected it should show you a refresh button.

**Comment by Graar** [comment] 2016-08-04 20:28
Nataan,

OK, I now have version control and it wont go away (which is a good thing), but means that I can't do experiments.

So how did I get it ?

Well the documentation makes mention of projects.  I have never really seen the benefit of projects, I am OK just opening the files I need from the file system as and when I need them, so I have never used projects in Komodo X or Komodo 9 (which is all I have had installed on my current machine).

After reading the documentation, I thought I would go and check out Projects to see if anything has changed, so I created a project in my current working dir and hey presto version control sudden;ly appears.  It remains even if I delete the project and restart Komodo, so I suspect that the project creation process writes something into your history files and its all good.

I hope this makes some kind of sense to you.  Bottom line, I don't think it is safe to assume that all users use projects and I don't think you should force that, so SCC needs to work in the absence of projects.

**Comment by cgchoffman** [comment] 2016-08-05 00:09
@Graar the clue is in @Naatan's last response:


> Could you try pointing your Places widget at the root directory of your SVN checkout?

You do not have to have a Komodo project.  You just have to have a folder open in Places that under the supervision of a support version control system.  The process of opening the project in Komodo likely changed your places folder to reflect that state and therefore worked.

So far I'm not seeing a bug here, @Naatan?

**Comment by Graar** [comment] 2016-08-05 08:43
@cghoffman the way of working you describe is how I have been working with Komodo X ever since it was launched and yesterday was the first time that I have seen the SCC icon on the left hand side or had any active menu items under the SCC menu drop down.  

To be fair I haven't been looking on a regular basis, since the icons showing file status had gone I assumed that SCC was just fundamentally broken in Komodo X (I still think using colours rather than icons is a bad idea - colours have no inherent meaning, icons do - part of the definition of icon).

What is the expected behaviour if I have files under version control open in the  'Open Files' section, surely, I should also see version control menus ?

**Comment by Naatan** [comment] 2016-08-05 15:47
I think the problem here is just with Komodo's SCC integration sometimes being a bit flaky. This is due to a lot of the actions being Async and there not being a proper callback structure. This is an issue I am working with every release and will slowly get better, but it's not one of those "one silver bullet" type of issues.

> What is the expected behaviour if I have files under version control open in the 'Open Files' section, surely, I should also see version control menus ?

Correct. That is the expected behavior.

I'll close this as the actual issue is too high level to really effectively track on the bug tracker. But rest assured this is something that will be improved in future versions (the reliability of file status updates).

**Closed by Naatan** 2016-08-05 15:47 UTC
Labels: Pending: Response

**Comment by Graar** [comment] 2016-08-06 09:13
@Naatan,
That makes sense.  Callbacks are certainly not working as well they might.

Yesterday, I had to do some major refactoring in one of my files.  I did a commit to capture the working version pre-refactor and then went ahead and made the big changes, even several hours after the first save of those changes the file was still being displayed in white, which I believe means it is up to date .
