### ISSUE TITLE
Preserve dirty/unsaved files when restarting Komodo

### ISSUE THREAD

**Issue by datamafia** [Komodo/KomodoEdit#348] opened 2015-06-16 20:45 UTC
Looking to use MD previewer via this article:

http://komodoide.com/blog/2014-11/live-markdown-viewing-in-komodo/

prompted to install:

http://komodoide.com/resources/addons/komodo--markdownviewer/

Downloaded, dragged into Komodo, restart was required, I hit okay and noticed that a file was unsaved (there was an asterisk on the tab and I remember editing).

Komodo IDE shut down and restarted.

On restart open tabs/files were not loaded as normally happens (no files open).

Diagnosis: Need to use the same shutdown/restart dialog for extensions as in other areas of app.

File was recovered (was only a testing MD file). Regardless, could have been bad.

Additionally. I really count on the app reopening w/same files open. I am sure you appreciate that feature...

Great stuff, reach out if you need me.

Komodo IDE, version 9.1.0, build 87337, platform macosx. Built on Fri May 29 

![screen shot 2015-06-16 at 4 44 08 pm](https://cloud.githubusercontent.com/assets/170310/8194048/f5f744b4-1446-11e5-962f-aba1eac65212.png)

**Comment by cgchoffman** [comment] 2015-06-16 22:26
I'm not able to reproduce this.  Could you pare this down a bit to exact repro steps?
For me:
1. opened a file and edited it, did not save
2. open addons and disabled and add-on
3. clicked restart
4. Komodo asked me to save the dirty file
5. I cancelled and aborted restart.

Komodo should not abandon a dirty file.  We certainly do appreciate this need and definitely didn't write it to throw away your work :)

I've tried this on OSX and Windows.

Could you check Komodo > Preferences > Workspace: when starting Komodo: Restore last workspace

Also  Komodo > Preferences > file saving: make sure you have auto recovery enabled.

That doesn't explain why komodo is skipping the save dialog for you though.

**Comment by we3geeks** [comment] 2015-06-17 03:46
I can reproduce this if I use the "Restart Now" button that appears at the top of the "Add-ons Manager" window, rather than the "Restart now" link within section of the window for the extension which was added/updated. 

![6_16_15__9_42_pm](https://cloud.githubusercontent.com/assets/2390335/8199345/d65283b0-1470-11e5-8b7b-763535126754.png)

Komodo IDE, version 9.1.0, build 87337, platform macosx.
Built on Fri May 29 20:57:45 2015.

Komodo Edit, version 9.1.0, build 15798, platform macosx.
Built on Sat May 30 05:06:11 2015.

**Comment by datamafia** [comment] 2015-06-17 15:17
@we3geeks Thx for checking and adding more detail - yes I was using the top "Restart now" button. Extra bonus for pushing the bug/query further GOOD WORK!

**Comment by cgchoffman** [comment] 2015-06-17 17:07
@we3geeks, thank you.

**Comment by cgchoffman** [comment] 2015-06-17 17:33
Discussed this with nathanr.  We'd like to do this so that Komodo just saves your stuff without asking then restores it without asking (obviously you want to just get back to work without dialogs).  But the easiest fix for now is to make it do the original functionality of prompting to save.  I"ll file a separate bug for the new functionality.

**Comment by Naatan** [comment] 2015-08-06 15:42
Tracking this in #350, so closing this one. Thanks guys!

**Closed by Naatan** 2015-08-06 15:42 UTC
Labels: Bug, Enhancement
