### ISSUE TITLE
Prefs > Places XML parsing error

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#1501] opened 2016-05-17 20:09 UTC
![prefs-places-xml-error](https://cloud.githubusercontent.com/assets/1676348/15337422/a969edb6-1c49-11e6-94cc-51686b6234bd.png)

Komodo Edit, version 10.0.0, build 17209, platform win32-x86.
Built on Thu May 12 00:43:26 2016.

**Comment by Naatan** [comment] 2016-05-17 20:12
Duplicate of #1463

This will be fixed in 10.0.1

**Closed by Naatan** 2016-05-17 20:12 UTC
