### ISSUE TITLE
IDE Crash when closing files

### ISSUE THREAD

**Issue by pemcg** [Komodo/KomodoEdit#2226] opened 2016-12-15 09:45 UTC
### Short Summary
I'm getting a fairly repeatable crash when closing files from Komodo IDE (Mac) 10.1.3. It seems to happen when I have several files open (opened from the left-hand browser pane), and I click the 'x' on the tab of a file that's not the righthand-most tab. 

### Steps to Reproduce
Open two files in Komodo IDE from the browser pane. Click the 'x' on the left-hand file's tab. The crash doesn't seem to happen if I select the files outside of Komodo (say in  Finder), and right-click -> open with Komodo. In this case I can close the file ok.

### Expected results
The file should close

### Actual results
Komodo IDE crashes

### Platform Information

*Komodo IDE* 
*Komodo Version 10.1.3* 
*macOS Sierra 10.12.2* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by pemcg** [comment] 2016-12-15 09:51
[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/654284/pystderr.log.zip)

**Comment by pemcg** [comment] 2016-12-15 09:57
Interestingly Komodo IDE 9.3.2 now also crashes closing any file tab using the 'x' on the tab.

**Comment by Naatan** [comment] 2016-12-15 16:03
Please send in a crash report when prompted, fill out the email field and let us know what email you filled out.

**Comment by pemcg** [comment] 2016-12-15 17:27
Just done, email: pemcg@redhat.com

**Comment by Naatan** [comment] 2016-12-15 17:34
Reproduced on 10.12.2. This is a duplicate of #2201. We're working on a fix. 

The crash is somehow caused by something that changed in the OSX update.

**Closed by Naatan** 2016-12-15 17:34 UTC
Labels: Pending: Response
