### ISSUE TITLE
cmd_paste screws up userscripts

### ISSUE THREAD

**Issue by aflorit** [Komodo/KomodoEdit#2372] opened 2017-02-24 11:12 UTC
I've just installed Komodo Edit 10.2.0 and recorded a macro to change a line of text

from:

aaaa bbbbbb cccccc ddddd

(this is the original line)

to:

aaaa cccccc bbbbbb bbbbbb bbbbbb ddddd

(this is the line after recording the macro)

But when I run the macro on another line (identical with the original line above) I get the following

aaaa cccccc ddddd
bbbbbb bbbbbb bbbbbb

The text of the macro is as follows:

// Macro recorded on: Wed Feb 22 2017 18:11:07 GMT+0100 (CET)
komodo.assertMacroVersion(3);
if (komodo.view) { komodo.view.setFocus(); }
ko.commands.doCommand('cmd_wordRight')
ko.commands.doCommand('cmd_selectWordRight')
ko.commands.doCommand('cmd_cut')
ko.commands.doCommand('cmd_wordRight')
ko.commands.doCommand('cmd_paste')
ko.commands.doCommand('cmd_paste')
ko.commands.doCommand('cmd_paste')
ko.commands.doCommand('cmd_home')
ko.commands.doCommand('cmd_lineNext')

I also noticed some problems running macros I have been using successfully  during the past few years using Komodo Edit 9.x, 10.0 ...

Please help!

Best regards

Andrew Florit

**Comment by mitchell-as** [comment] 2017-02-24 14:49
Thanks for the report Andrew.

**Comment by Naatan** [comment] 2017-02-24 16:33
Seems to be some type of timing issue, my results are slightly different but if I slow down the execution it works properly regardless:

```
// Macro recorded on: Wed Feb 22 2017 18:11:07 GMT+0100 (CET)
komodo.assertMacroVersion(3);
if (komodo.view) { komodo.view.setFocus(); }
ko.commands.doCommand('cmd_wordRight')
setTimeout(function () ko.commands.doCommand('cmd_selectWordRight'), 1000);
setTimeout(function () ko.commands.doCommand('cmd_cut'), 2000);
setTimeout(function () ko.commands.doCommand('cmd_wordRight'), 3000);
setTimeout(function () ko.commands.doCommand('cmd_paste'), 4000);
setTimeout(function () ko.commands.doCommand('cmd_paste'), 5000);
setTimeout(function () ko.commands.doCommand('cmd_paste'), 6000);
setTimeout(function () ko.commands.doCommand('cmd_home'), 7000);
setTimeout(function () ko.commands.doCommand('cmd_lineNext'), 8000);
```

**Comment by Naatan** [comment] 2017-02-24 16:58
Note for devs: As mitchell noted on Slack; this is likely caused by paste being async on GTK. The issue does not occur on Windows or Mac.

**Comment by mitchell-as** [comment] 2017-02-24 18:22
Dev note: this is not a regression, but likely a pyxpcom-related issue that surfaced thanks to some speed improvements in Komodo. A race condition appears to be occurring, with subsequent JS commands being executed before `cmd_paste` can finish. We'll have to work-around this issue.

**Comment by aflorit** [comment] 2017-02-27 12:54
Thank you!

In the meantime I found it works on Komodo-edit 10.0

Regards

Andrew

**Comment by dougplant** [comment] 2017-08-09 23:30
Remains present in 10.2.3 on Linux.
I (would) use the auto-recorded macro on a daily basis. Is there news on this?

**Comment by dougplant** [comment] 2018-03-26 18:23
Still present on Komodo IDE, version 11.0.2, build 90813, platform linux-x86_64

**Comment by Naatan** [comment] 2018-03-27 14:45
hi @dougplant , I appreciate your wanting this bug fixed, but you do not need to keep testing this each release. This bug will be updated once it is resolved. Until that this bug will be present. Note it is marked as a priority for 11.1 so we will try our best to get it done by that timeframe.

**Comment by dougplant** [comment] 2018-03-27 16:03
Hi Nathan - Thanks for the note. I'm not intentionally testing it; it's 
more like I'm logging these episodes. I have much anticipation for 11.1!

**Closed** 2018-04-30 19:32 UTC
Labels: Limited to: Linux, Type: Bug
