### ISSUE TITLE
Can not resize vertically the Komodo 9.1 Window in Remote Desktop.

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#366] opened 2015-06-23 00:56 UTC
Both Machines are Windows 8 x64.

1. Start Komodo on machine A. Machine A is a laptop having a dual monitor setup, the secondary is a Asus VW22AT (just for you to know the specs, among them there is the resolution).
2. On machine B (which is also a laptop, but without a secondary monitor) access machine A via remote desktop.
3. Try to resize the Komodo window using the mouse. You will be able to resize it horizontally, but not vertically.
4. Try to resize the window by Alt+Space menu and arrow keys. You will be able to resize it horizontally, but not vertically.

Note: In the remote desktop window got a Komodo window taller than the height of it / laptop screen. May be it has something to do with Windows 8 "vertically maximized" state of windows.

**Comment by srgloureiro** [comment] 2015-06-23 11:05
Update: I closed the Find Results window at bottom and I could now resize vertically

**Comment by Naatan** [comment] 2015-06-23 15:38
Thanks for reporting! This appears to be a duplicate of #275

**Closed by Naatan** 2015-06-23 15:38 UTC
