### ISSUE TITLE
Paste doesn't work

### ISSUE THREAD

**Issue by artocignus** [Komodo/KomodoEdit#156] opened 2015-04-13 07:56 UTC
I've just started a 21-day trial of Komodo 9. Looks amazing, but there's one fundamental problem. Paste doesn't work, neither as control-V or off the context menu. The copied text is available in clipboard, which I verified by pasting the copied text into Notepad. Control-X also cuts as it should. But the behavior of control-V is not correct. If I paste over a selection of existing text, that text disappears, which seems to indicate that an empty string is pasted. However, the copied text remains available on the clipboard. I'm running Windows 7 64-bit.

**Comment by Naatan** [comment] 2015-04-13 14:51
I am not able to reproduce this. Could you provide a test case (steps to reproduce, including a sample file)?

**Comment by artocignus** [comment] 2015-04-14 07:19
Maybe something has gone wonky in my OS. However, I've tried other editors, and they all work fine. I've just tried the steps again:
1. Launch Komodo 9
2. Create new txt file (repeated it with a PHP file)
3. Type something arbitrary like "Hello"
4. Select what I've typed and press control-C (repeated this with control-insert, and the copy command in the context menu)
5. Move cursor to empty space and press control-V (repeated this with shift-insert, and the paste command in the context menu)
6. Nothing happens
7. Re-select the text I've just copied, and press control-V (repeated this with shift-insert, and the paste command in the context menu), and an empty string gets pasted over the selected text, i.e. the selected text disappears 
8. Open a notepad file and press control-V there - the copied text appears!
9. Open a Word document and press control-V there - the copied text appears!
How do I provide the sample file I've just used? I don't see any upload links.

**Comment by Naatan** [comment] 2015-04-14 15:39
Anything out of the ordinary about your setup? What keyboard do you use?

**Comment by cgchoffman** [comment] 2015-04-15 00:37
This issue has popped up before.  There are a few posts about it on the old forums.
Here's is a comment of possible debugging steps that could help us track down the issue (from a few years younger me): https://community.activestate.com/node/7541#comment-20632

I'll clarify the post.  There are three ways that you can force a copy in Komodo and two ways to force a paste.  If you could download and install the [Komodo Extension Developer](http://komodoide.com/resources/addons/komodo--komododeveloperextension/) and use the Javascript shell tool to test those commands, that would be really helpful.

The commands are as follows:
```javascript
// Forced copy
ko.commands.doCommand("cmd_copy");

ko.views.manager.currentView.scimoz.copy();

xtk.clipboard.setText(ko.views.manager.currentView.scimoz.selText);
```
```javascript
// Paste handling
ko.commands.doCommand("cmd_paste");

alert(xtk.clipboard.getText())
```
Open a blank document, add some text, then highlight said text.  You can then test out the commands above by pasting them into the Javascript shell and running them.

Let us know what you find and thank you very very much in advance for your assistance.

**Comment by artocignus** [comment] 2015-04-15 07:58
I'm using a fairly old Acer 7720G laptop with the built-in keyboard, an
external wireless mouse, and the trackpad turned off. The only unusual
thing I can think of is that I have two keyboard layouts installed: English
and Spanish. The behaviour is the same with both keyboard layouts. And as I
mentioned before, the commands also don't work off any of the menus, i.e.
even if I don't access them with keyboards shortcuts.

**Comment by artocignus** [comment] 2015-04-15 08:44
Sorry, I need some help here with the Javascript shell. I've now installed
the Komodo Extension Developer and have selected Tools->Extension
Developer->Javascript Shell. This opens a pop-up window with the heading
"JavaScript Shell Extended" and ends with "Scope is now [object
ChromeWindow]. If a variable is not found in this scope, window will also
be searched. New variables will still go on window". There are no run or
execute buttons where I can execute the code you gave me.

**Comment by Defman21** [comment] 2015-04-15 09:24
The code given by @cgchoffman is a "macro" code. Just create a macro and use the code.

**Comment by artocignus** [comment] 2015-04-15 10:42
Ok, I've created a macro. Not sure if I should bind any keys? I assumed I
should create the macro only for the paste portion, since copy seems to
work, and I did a key binding of control-v for the macro. I also specified
that it should run at startup. When I restarted Komodo, this is what I got:

NS_ERROR_FAILURE: Component returned failure code: 0x80004005
(NS_ERROR_FAILURE) [nsITransferable.getTransferData]

exception[fileName] = New_Macro.js
exception[toString] = function toString() {
    [native code]
}
exception[message] = Component returned failure code: 0x80004005
(NS_ERROR_FAILURE) [nsITransferable.getTransferData]
exception[result] = 2147500037
exception[name] = NS_ERROR_FAILURE
exception[filename] = chrome://xtk/content/clipboard.js
exception[lineNumber] = 114
exception[columnNumber] = 0
exception[inner] = null
exception[data] = null
exception[stack] = this.getTextFlavor
@chrome://xtk/content/clipboard.js:114:8
this.getText@chrome://xtk/content/clipboard.js:176:11
anonymous@chrome://komodo/content/project/peMacro.js line 696 >
Function:10:6
macro_evalAsJavascript@chrome://komodo/content/project/peMacro.js:701:150
_executeMacro@chrome://komodo/content/project/peMacro.js:106:29

exception[location] = JS frame :: chrome://xtk/content/clipboard.js ::
this.getTextFlavor :: line 114

**Comment by cgchoffman** [comment] 2015-04-15 16:16
I do not want to you to run it as a macro.  @Defman21, I explicitly asked @artocignus to use Javascript shell.  
@artocignus,  all you need to do is copy and paste those commands into the javascript shell and press enter.  You can then press up to cycle back through your previous command, like other consoles.  The idea being for you to test the various permutations between the 3 copy commands and the 2 paste commands and see if you can find a sequence that is broken.

**Comment by artocignus** [comment] 2015-04-15 16:34
Sorry, Sergey said it was a macro code... Just needed info on how to run
the code in the shell. So, I've copied (dragged in fact, since paste
doesn't work), pressed enter, and got the following:

NS_ERROR_FAILURE on line 114: Component returned failure code: 0x80004005
(NS_ERROR_FAILURE) [nsITransferable.getTransferData]

**Comment by cgchoffman** [comment] 2015-04-15 16:46
Awesome, that was fast.  Do all of the copy commands fail like that?

**Comment by Naatan** [comment] 2015-04-15 16:53
Sorry to interject - Wondering if this may be an issue in your keybindings. Could you try selecting "Default" under `Prefs > Key Bindings > Key Binding Schemes`.

If that has no effect, could you try starting Komodo with a clean profile? https://community.activestate.com/node/15233

If none of this works please refer back to Carey's suggestion.

**Comment by artocignus** [comment] 2015-04-15 16:55
Now that I've created the macros, I get a similar error message when I try
to copy inside a Komodo document. Also just checked my key binding
preferences, and it's set at default....

**Comment by Naatan** [comment] 2015-04-15 16:58
Please try a clean profile.

**Comment by artocignus** [comment] 2015-04-15 17:08
Ok, now I need help again. How do I get a clean profile. I don't see
anywhere I can delete the macros.

**Comment by cgchoffman** [comment] 2015-04-15 17:20
Here you go https://community.activestate.com/node/15233

**Comment by artocignus** [comment] 2015-04-15 18:01
Right, so I followed the steps and seemed to get a clean profile (the
Developer Extension was gone), but the macros were still there, and still
gave the same error on startup. So, I just did a re-install. Repeated all
the steps. Now I still get the following error when running the code you
gave me in the Javascript shell:

NS_ERROR_FAILURE on line 114: Component returned failure code: 0x80004005
(NS_ERROR_FAILURE) [nsITransferable.getTransferData]

But when trying to copy or paste inside a document, just the same behavior
as before: i.e. copy to clipboard works, but pasting doesn't, and when I
paste over selected text, it disappears.... No error alerts or messages of
any kind. I saw in the previous post relating to a similar problem in
Komodo 7, that there's an error log. I searched for the relevant filename
they mentioned, but couldn't find it...

**Comment by Naatan** [comment] 2015-04-15 18:04
Do you have any software installed that deals with your clipboard?

Does copy/pasting work in Firefox?

**Comment by artocignus** [comment] 2015-04-15 18:09
I had Firefox Nightly installed, but recently uninstalled it because I'm on
limited bandwidth at the moment and didn't want to spend it on nightly
updates. Now I'm mostly using Chrome. I've just opened the Javascript
console in Chrome, and copy/paste does work there. I also started using
Zend Studio for coding because of problem with Komodo and everything also
works as it should there.

**Comment by Naatan** [comment] 2015-04-15 18:14
Thanks @artocignus, the reason I asked for Firefox specifically is because it's based on Mozilla, just like Komodo. Any chance you could try installing it again?

Also you didn't answer my question about software installed; 

> Do you have any software installed that deals with your clipboard?

**Comment by Defman21** [comment] 2015-04-15 18:16
>@Defman21, I explicitly asked @artocignus to use Javascript shell.

Sorry @cgchoffman, I didn't see that.

**Comment by artocignus** [comment] 2015-04-15 18:17
Ok, I'll download Firefox and see what it does.

Software dealing with my clipboard? You mean specific clipboard software,
or just anything that uses clipboard. I obviously have the usual Office
etc, but nothing specific for clipboard. I actually tried to get to the
Windows clipbrd.exe after reading a Komodo post, but apparently this is no
longer accessible in Windows 7.

**Comment by Naatan** [comment] 2015-04-15 18:24
Yeah any sort of software that would deal with your clipboard in an implicit way.

**Comment by artocignus** [comment] 2015-04-15 18:28
No, nothing I know of....

I still had Firefox on my computer after all! When I started it up, I got
messages about KeyFind malicious software or something. But copy/paste does
work in Firefox's scratch pad and style editor. Am doing a scan on my
Firefox folder to see if it's got a worm or something...

**Comment by Naatan** [comment] 2015-04-15 18:33
http://malwaretips.com/blogs/key-find-com-virus/

I would try a full system scan with an up-to-date anti-virus. The virus itself probably wouldnt embed itself in Firefox itself.

Are you able to copy/paste elsewhere in Komodo, ie. parts that are outside the editor. Eg. try copy/pasting in the `Prefs > Key Bindings > Commands` input field.

**Comment by artocignus** [comment] 2015-04-15 18:35
Yep, paste works there!

**Comment by artocignus** [comment] 2015-04-15 18:35
So, maybe it's a virus affecting Firefox?

**Comment by Defman21** [comment] 2015-04-15 18:37
Can you paste anything in `Prefs - Color Scheme` editor window?

**Comment by artocignus** [comment] 2015-04-15 18:40
In the sample text window? No paste doesn't work there. Copy does work
though. Just copied this from the sample text window:

import math
class Class:
    """ this is a docstring """
    def __init__(self, arg): # one line comment
        self.x = arg + math.cos(arg + arg)
        s = 'a string'

**Comment by Naatan** [comment] 2015-04-15 18:52
@Defman21 appreciate your help but we've got this :)

Ok so it seems the problem is Scintilla specific.

Could you try seeing if the following code works:

```
ko.views.manager.currentView.scimoz.paste()
```

You can execute this either as a macro or through the JS shell.

**Comment by artocignus** [comment] 2015-04-15 19:05
Got this message in the JS shell:

TypeError on line 1: ko.views.manager.currentView is null

**Comment by Naatan** [comment] 2015-04-15 19:17
Make sure you have a file opened.

**Comment by artocignus** [comment] 2015-04-15 19:26
Oh, sorry. Same behavior as control-v. In other words, nothing pastes in
the document, but if I have text selected it disappears.

**Comment by Naatan** [comment] 2015-04-15 20:41
So scintilla exclusively is somehow incapable of pasting text for you.

Could you see if 8.5 has the same problem?

http://downloads.activestate.com/Komodo/releases/8.5.4/

**Comment by artocignus** [comment] 2015-04-16 07:46
Thanks for the link to Komodo 8.5. I'm happy to confirm that copy/paste
works as it should in 8.5!

**Comment by cgchoffman** [comment] 2015-07-14 23:40
@cloudgryphon, if you show up here, I would like you to do the following:
- When you're experiencing this issue, please get your logs and paste them here: Help > Troubleshooting > View Log File
- Open a macro in the tool box and try copy and pasting stuff in the editor area

**Comment by silvahwuff** [comment] 2015-07-15 01:59
@cgchoffman this is @cloudgryphon. Here are my logs in Komodo Edit 9.1.0 (8.5.4 is on it's way down now):
```
[2015-07-14 20:56:08,618] [INFO] Startup: Welcome to Komodo Edit 9.1.0 build 15798 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2015-07-14 20:56:08,618] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\komodo.exe built on Sat May 30 06:10:24 2015
[2015-07-14 20:56:09,000] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-07-14 20:56:09,002] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-07-14 20:56:09,002] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-07-14 20:56:09,003] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-07-14 20:56:09,003] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///C:/Users/Ben/AppData/Local/ActiveState/KomodoEdit/9.1/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///C:/Users/Ben/AppData/Local/ActiveState/KomodoEdit/9.1/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2015-07-14 20:56:09,046] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-07-14 20:56:09,244] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:68
[2015-07-14 20:56:09,246] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:69
[2015-07-14 20:56:09,536] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-07-14 20:56:09,911] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-14 20:56:09,911] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-14 20:56:09,911] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-14 20:56:09,911] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-14 20:56:09,927] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-14 20:56:09,927] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-14 20:56:09,927] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-14 20:56:10,497] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-07-14 20:56:10,513] [DEBUG] places_js: waiting for document complete
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-14 20:56:10,908] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-14 20:56:11,447] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/components/koamAddonManager.js:138
[2015-07-14 20:56:11,897] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-14 20:56:11,897] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-14 20:56:11,897] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-14 20:56:11,897] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-14 20:56:11,898] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-14 20:56:11,898] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-14 20:56:11,898] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-14 20:56:13,395] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-07-14 20:56:13,395] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-14 20:56:19,434] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-14 20:56:24,174] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-07-14 20:56:24,174] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by cgchoffman** [comment] 2015-07-15 16:49
@silvahwuff, @mitchell-as found the following: http://sourceforge.net/p/scintilla/bugs/1621/ (cgchoffman hangs head).  Do you have security software called Webroot SecureAnywhere on your system that could be blocking silently blocking Komodo from accessing your clipboard?

**Comment by silvahwuff** [comment] 2015-07-15 22:55
@cgchoffman yes, and Webroot seems to have been the source of the problem. Upon disabling automatic silent blocking and giving Komodo access to my clipboard, pasting works perfectly in Komodo 9. Thanks for the help!

**Comment by cgchoffman** [comment] 2015-07-15 22:58
That is the best news I've had all day!  Thanks for letting us know!  Closing this one is going to feel soooo gooood.

**Closed by cgchoffman** 2015-07-15 22:58 UTC
Labels: Pending Response
