### ISSUE TITLE
Cannot Move Color Picker Window

### ISSUE THREAD

**Issue by penggunaphp** [Komodo/KomodoEdit#2103] opened 2016-10-19 15:33 UTC
The color picker window cannot moved.

![untitled](https://cloud.githubusercontent.com/assets/11702917/19525641/d8ae7f2a-964b-11e6-8360-ea3785ee9cce.png)

**Comment by Naatan** [comment] 2016-10-19 15:34
Thanks for reporting. This appears to be a duplicate of #2036.

**Closed by Naatan** 2016-10-19 15:34 UTC
