### ISSUE TITLE
Komodo X, Error notificaition on panel display

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#1546] opened 2016-05-19 08:59 UTC
### Short Summary
I installed Komodo Edit 10 today, though i have KomodoEdit 9.3 from PPA
I renamed .komodoedit directory in my home folder, but things are still same.
I got unusual errors while showing the left "file" panel or right "snippets " panel.

### Steps to Reproduce
CTRL+SHIFT+P
CTRL+SHIFT+L

### Expected results

no errors should be shown

### Actual results
Error notification (screenshots)

### Platform Information
Komodo Edit, version 10.0.0, build 17209, platform linux-x86_64.
Built on Wed May 11 22:00:36 2016.

Ubuntu 16.04

### Additional Information
![selection_021](https://cloud.githubusercontent.com/assets/6584304/15388104/e8f3834a-1dcd-11e6-86bd-0ed702d10202.png)
[log.txt](https://github.com/Komodo/KomodoEdit/files/272189/log.txt)

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment] 2016-05-19 14:45
Duplicate of #1488.

**Closed by mitchell-as** 2016-05-19 14:45 UTC
