### ISSUE TITLE
Komodo v10 UI: "Interface Colors" list leave some choices invisible

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1364] opened 2016-05-04 11:30 UTC
### Short Summary

The dropdown list of choices under Preferences > Appearance > Interface Colors renders some choices invisible (e.g., white on white) in the default color scheme.
### Expected results

All choices should be at least marginally visible.
### Actual results

Some choices are invisible. In this specific instance, the two rendered in that manner are dark text on light background color schemes that were automigrated over to Komodo v10 on its initial startup.
### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88986, platform macosx.
Built on Wed Apr 27 01:55:56 2016.
### Additional Information

![k10-20160503a](https://cloud.githubusercontent.com/assets/2390335/15012855/29eeef04-11b9-11e6-9427-272674ce23d0.png)

**Comment by mitchell-as** [comment] 2016-05-04 14:38
I don't think there's much we can do with 3rd party or "ported" schemes. All of Komodo 10's default schemes are visible, and that is by design. @Naatan might have more input on this though. Closing for now.

**Comment by we3geeks** [comment] 2016-05-04 14:45
Both of those that are not visible are dark text on light background, in terms of the color schemes and are valid schemes in Komodo v9.x. That they are not visible in this context kind of raises the question of what is being used to determine how they are rendered in the list of available choices. And if they are not visible based on how they were migrated from v9.x to v10 as part of the first-run process, that seems like there's something amiss with how they were migrated.

**Comment by Naatan** [comment] 2016-05-04 15:10
> Edit: I can provide a copy of one of those color schemes from the v9.x profile and from v10, if that will help?

Yes please. I have my suspicions about what the problem is, but would need to verify.

**Comment by we3geeks** [comment] 2016-05-04 22:07
@Naatan Just sent via email.

**Closed** 2017-02-21 16:04 UTC
Labels: Pending: Response
