### ISSUE TITLE
Komodo IDE 10 Preview: not rendering editor or something

### ISSUE THREAD

**Issue by robclancy** [Komodo/KomodoEdit#1240] opened 2016-04-12 21:56 UTC
### Short Summary
Sometimes I see the open files but then soon after they just go blank, no editor, no panes, no open file tabs.

### Platform Information

Komodo IDE 10 Preview
Arch Linux with i3

### Additional Information

> 
> [2016-04-13 07:47:46,137] [INFO] Startup: Welcome to Komodo IDE 10.0.0-alpha1 build 88789 (platform linux-x86_64, running on Linux 4.4.5-1-ARCH version #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016)
> [2016-04-13 07:47:46,137] [INFO] Startup: /usr/bin/python built on Fri Apr 8 10:30:36 2016
> [2016-04-13 07:47:46,184] [INFO] koInitService: Setting LC_CTYPE to utf-8
> [2016-04-13 07:47:46,434] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
> [2016-04-13 07:47:46,439] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///home/robbo/.komodoide/10.0/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
> [2016-04-13 07:47:46,538] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
>     @chrome://komodo/content/komodo.js:15:1
> 
> ERROR:xpcom:Unhandled exception calling 'int8 * register(in nsISomething, in nsISomething);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
>     return 0, func(*params)
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koDocumentSettingsManager.py", line 84, in register
>     scimoz.text = buffer
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/client/__init__.py", line 419, in __setattr__
>     setattr(interface, attr, val)
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/client/__init__.py", line 522, in __setattr__
>     return NS_InvokeByIndex(self._comobj_, method_index, real_param_infos)
> Exception: 2147500037 (NS_ERROR_FAILURE)
> ERROR:xpcom:Unhandled exception calling 'int8 * addView(in nsISomething);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
>     return 0, func(*params)
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
>     return fn(*args, **kwargs)
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koDocument.py", line 1763, in addView
>     self.docSettingsMgr.register(xpself, scintilla)
>   File "<XPCOMObject method 'register'>", line 3, in register
> Exception: 2147500037 (NS_ERROR_FAILURE)
> [2016-04-13 07:47:53,478] [ERROR] view.editor: 
> -- EXCEPTION START --
> [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.addView]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: set_koDoc :: line 235"  data: no]
> + toString (function) 3 lines
> + message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.addView]'
> + result (number) 2147500037
> + name (string) 'NS_ERROR_FAILURE'
> + filename (string) 'vieweditor'
> + lineNumber (number) 235
> + columnNumber (number) 0
> + inner (object) null
> | + data (object) null
> | + stack (string) 'set_koDoc@vieweditor:235:16
> initWithDocument@vieweditor:384:12
> setState@viewtabbedlist:421:24
> setSta'...432 chars
> + location (object) JS frame :: vieweditor :: set_koDoc :: line 235
> | + QueryInterface (function) 3 lines
> | + language (number) 2
> | + languageName (string) 'JavaScript'
> | + filename (string) 'vieweditor'
> | + name (string) 'set_koDoc'
> | + lineNumber (number) 235
> | + columnNumber (number) 16
> | + sourceLine (string) ''
> | + caller (object) JS frame :: vieweditor :: initWithDocument :: line 384
> | + formattedStack (string) 'set_koDoc@vieweditor:235:16
> initWithDocument@vieweditor:384:12
> setState@viewtabbedlist:421:24
> setSta'...432 chars
> | + stack
>     set_koDoc@vieweditor:235:16
>     initWithDocument@vieweditor:384:12
>     setState@viewtabbedlist:421:24
>     setState@viewmultiview:458:20
>     this._restoreWindowWorkspace@chrome://komodo/content/workspace.js:446:16
>     view_restoreWorkspace@chrome://komodo/content/workspace.js:225:0
>     ko_workspace_restore@chrome://komodo/content/workspace.js:90:12
>     onloadDelay@chrome://komodo/content/komodo.js:396:8
>     window.onload@chrome://komodo/content/komodo.js:538:8
> -- EXCEPTION END --
> [2016-04-13 07:47:55,071] [DEBUG] editorconfig: Setting editorconfig: {"encodingDefault": "utf-8", "cleanLineEnds": true, "tabWidth": 2, "ensureFinalEOL": true, "indentWidth": 2, "useTabs": false, "endOfLine": "LF"}
> [2016-04-13 07:47:55,085] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
> [2016-04-13 07:47:55,237] [INFO] komodospellchecker: Spell checker loaded.
> [2016-04-13 07:47:55,238] [INFO] komodospellchecker: Using dictionary en-US
> [2016-04-13 07:47:55,263] [INFO] elastic_tabstops: Elastic tabstops loaded.
> [2016-04-13 07:47:55,287] [ERROR] koScopeDocs-Py: Could not find cix for ext
> [2016-04-13 07:47:55,300] [ERROR] koScopeDocs-Py: Could not find cix for html5
> [2016-04-13 07:47:55,828] [ERROR] console-logger: allocation size overflow (0) in :0
> Traceback (most recent call last):
>   File "", line 0, in 
> 
> [2016-04-13 07:47:57,233] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/robbo/Komodo-IDE-10/lib/mozilla/components/koamAddonManager.js:138
> [2016-04-13 07:47:57,258] [WARNING] console-logger: Key event not available on some keyboard layouts: key="z" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:57,259] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:57,259] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:57,260] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:57,260] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:57,261] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-04-13 07:47:58,355] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
> [2016-04-13 07:47:58,356] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
> [2016-04-13 07:47:58,357] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
> [2016-04-13 07:47:58,403] [WARNING] koLess: Reloading Skin
> [2016-04-13 07:47:58,403] [WARNING] koLess: Clearing local and file cache
> [2016-04-13 07:47:59,172] [WARNING] koLess: Reloading Skin
> [2016-04-13 07:47:59,350] [ERROR] console-logger: bad script XDR magic number (0) in :0
> Traceback (most recent call last):
>   File "", line 0, in 
> 
> [2016-04-13 07:48:00,185] [WARNING] console-logger: Error in parsing value for 'left'.  Declaration dropped. (1) in chrome://console/content/views/console.html:0
> [2016-04-13 07:48:01,998] [WARNING] console-logger: Error in parsing value for 'left'.  Declaration dropped. (1) in chrome://console/content/views/console.html:0
> [2016-04-13 07:48:09,550] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:09,551] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:09,552] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:09,571] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:12,518] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:12,519] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:12,536] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:12,537] [WARNING] codeintel.langintel: don't know how to get cb detail for 'element' elem
> [2016-04-13 07:48:27,291] [WARNING] console-logger: Error in parsing value for 'left'.  Declaration dropped. (1) in chrome://console/content/views/console.html:0
> [2016-04-13 07:48:27,291] [WARNING] console-logger: Error in parsing value for 'left'.  Declaration dropped. (1) in chrome://console/content/views/console.html:0
> [2016-04-13 07:49:54,050] [WARNING] console-logger: Key event not available on some keyboard layouts: key="z" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-04-13 07:49:54,051] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-04-13 07:49:54,051] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-04-13 07:49:54,052] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-04-13 07:49:54,052] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
> [2016-04-13 07:49:54,053] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
>

**Comment by cgchoffman** [comment] 2016-04-12 21:59
Screenshot and reproduction steps (if you can) please.

**Comment by Naatan** [comment] 2016-04-12 21:59
Hard to say exactly what is going on here, but it's related to the workspace code.

@cgchoffman we should disable file and workspace restoring after a major update.

**Comment by cgchoffman** [comment] 2016-04-12 22:00
Oh you reproduced it already?

**Comment by Naatan** [comment] 2016-04-12 22:02
No, I can't reproduce it cause I have no steps to reproduce. And @robclancy deleted his profile dir already (I'm talking to him on IRC).

The only actionable item I can see here is that we reset workspare restoring when you do a major upgrade.

Basically the relevant prefs in prefs.xml need to be given a `nonvital="true"` attribute. @cgchoffman you should know more or less what prefs those are.

**Comment by Naatan** [comment] 2016-04-12 22:24
Gonna have to close this as the data we need is in the old profile, which has been deleted. Impossible to find out what went wrong.

**Closed by Naatan** 2016-04-12 22:24 UTC
Labels: Bug
