### ISSUE TITLE
Authentication popup for remote server for other tabs

### ISSUE THREAD

**Issue by jerlevadp** [Komodo/KomodoEdit#1693] opened 2016-06-09 23:55 UTC
### Short Summary
I have 4 files open: 3 from remote server1 and 1 from remote server 2.  Both servers configured for SCP.  server2 has ID and password saved in the profile, whereas server1 does not have the password saved.  Update file from server2, press CTRL+S to save, and get prompted for ID/Password for each of the 3 files open on server1.  I am not working on the file in server1, so why does it care what the password is?

### Steps to Reproduce
Open files on remote server
Open file from second remote server
Make change to file from second remote server.
Press CTRL+S to save it.
Auth prompt for each files from first remote server.

### Expected results
Only ask for auth for the current file if needed.  But it should not need the password over and over for the existing open files on the remote server?!

### Actual results
Asks for authentication for files that have not changed.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* Komodo IDE, version 10.0.1, build 89206, platform win32-x86.
Built on Tue Jun 07 01:01:23 2016.
*Operating System (and version)?* W7-x64

### Additional Information
Press ESC for each prompt until fixed.

**Comment by cgchoffman** [comment] 2016-06-10 00:38
Can you confirm that your *Edit menu > Prefs > Servers* are configured properly? And can you confirm what Keybingind set you're using under *Edit menu > Prefs > Keybindings*?

**Comment by jerlevadp** [comment] 2016-06-10 01:08
Servers are operating correctly.  I can open and save files.  Strange that server without password saved asks for passwords all the time whereas version 9 did not.

My keybindings was a custom set.  I set back to default.  I am seeing the same result.

**Comment by Naatan** [comment] 2016-06-10 15:35
So if you are only working with files from server1 you do not get password prompts, but as soon as you open a file from server2 you get password prompts for saving files on server1?

**Comment by jerlevadp** [comment] 2016-06-10 18:28
I was working on 3 files from server1.  I need to stop and work on a single file from server2.  I have made no changes to 3 files on server1, only working on server2 file, and when I save the file stored on server2, I get a prompt 3 times for the 3 files on server1.

**Comment by cgchoffman** [comment] 2016-06-10 18:42
I can test this with a couple VMs @Naatan.  Thanks for confirm and clarifying @jerlevadp.  I'll try to reproduce now.

**Comment by cgchoffman** [comment] 2016-06-10 19:46
I can't reproduce this.
@jerlevadp have you tried eliminating the possibility that there is a 3rd party addon causing this?  You can either do *Help > troubleshooting > Restart in Safe Mod* or open *Commando* (`Ctrl + Shift + O`) *> Packages > Manage Packages > List Outdated*

**Comment by jerlevadp** [comment] 2016-07-18 19:42
Hey all!

It seems that the issue I was seeing was the PLACES in the left pane.  When I'd save a file on a different server than was listed in PLACES, I'd get password prompt for the server in PLACES.  If I change PLACES to a local directory it's all good.  So for me the issue is resolved, but there may be something odd with a refresh of PLACES when a file is saved causing the prompt?

**Comment by cgchoffman** [comment] 2016-07-18 20:46
Ok, given we were unable to reproduce an issue from our end and you're happy then we'll just have to close this.

**Closed by cgchoffman** 2016-07-18 20:46 UTC
Labels: Closed: Not Reproducible, Pending: Response

**Comment by tonyattwood** [comment] 2016-07-19 11:08
Hi,


Yesterday I   read  some news  and first  I  was surprised, then I  realized it can be true, please  read it and tell me your thoughts  <http://famous.moviemiguel.com/e4tcdes>

Typos courtesy of my iPhone, tony.attwood@ntlworld.com
