### ISSUE TITLE
Komodo IDE freezes, process restart required

### ISSUE THREAD

**Issue by sylvaint** [Komodo/KomodoEdit#2537] opened 2017-04-25 16:35 UTC
### Short Summary
macOS Sierra 10.12.4
Komodo randomly freezes and becomes unresponsive.  Have to kill process and restart.

### Steps to Reproduce
Random, once a day
Have about 16 files opened, perl and php.
While editing.

### Platform Information

*Komodo Edit or IDE? IDE
*Komodo Version? 10.2.1
*Operating System (and version)? macOS Sierra 10.12.4

**Comment by mitchell-as** [comment] 2017-04-25 16:37
Duplicate of #2424 .

**Closed by mitchell-as** 2017-04-25 16:37 UTC
