### ISSUE TITLE
Threaded file scanner doesn't always stop

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2770] opened 2017-08-07 19:52 UTC
No consistent reproduction steps, but sometimes I see the following in the log:

```
[2017-08-07 15:49:21,957] [INFO]  Server: Exiting
[2017-08-07 15:49:21,957] [DEBUG]  SocketServer: RequestHandler: stop called
[2017-08-07 15:49:21,958] [INFO]  codeintel.scanner: Stopping threaded file scanner...
```

And it just hangs there. It should be logging "Threaded file scanner stopped".

**Comment by mitchell-as** [comment] 2017-08-10 14:19
Is this maybe due to aggressively killing threads now? When the codeintel wants to stop the threaded file scanner it sends a halt request to the thread. This allows the thread to finish scanning the current file in the queue, and then exits the thread gracefully. Since the thread may be in the middle of something, if you kill it aggressively, or if you stop the logger before the thread is finished (is that even possible?), you won't see the final "stopped" log result.

**Comment by Naatan** [comment] 2017-08-10 15:33
Codeintel doesn't kill threads, it only kills itself (the process). So the stop being called here goes through all the regular motions, nothing crafty is happening until the end where it kills the process (if a thread has been found hanging, which is happening here).

**Comment by Naatan** [comment] 2017-08-10 15:36
This might be due to #2780 ?

**Comment by mitchell-as** [comment] 2017-08-11 13:55
Maybe. Until there are consistent steps to reproduce this, I don't have anything to go on.

**Comment by mitchell-as** [comment] 2017-09-21 21:13
Closing since we haven't seen this.

**Closed by mitchell-as** 2017-09-21 21:13 UTC
Labels: Component: CodeIntel, Introduced: 11, Pending: Internal, Type: Bug
