### ISSUE TITLE
unit testing - komodo becomes less responsive as number of tests increases

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#2364] opened 2017-02-23 03:37 UTC
### Short Summary

Running a large number of tests in the unittest tab can result in a laggy response, with larger number causing non-response.

### Steps to Reproduce

Configure the unit test system to run the code below.  Use the prove framework.

Change $num_tests to use values of 100, 500, 700 and 1000, re-running the unit test each time.  

```perl
use warnings;
use strict;
use Test::More;
use Time::HiRes qw/time/;

my $num_tests = 500;

my $epoch_time = time();

for my $i (1 .. $num_tests) {
    ok ($i, "i is $i");
}

print "Time taken (s): ", (time() - $epoch_time), "\n";

done_testing();
```

### Expected results

Linear completion times, and other parts of Komodo continue to respond when clicked on.  

### Actual results

Completion times seem to go quadratic.  

Komodo response on my system is OK up to 500, 700 has a slow response, and 1000 has almost no response until completion (editing code responds reasonably well but any other widgets respond very slowly or do not respond at all).  

Setting $num_tests to 10,000 results in a completely non-responsive system.

### Platform Information

*Komodo IDE* 
*Komodo Version 10.2* 
*Windows 10* 

### Additional Information

Running the code directly (using "Run without debugging") takes less than one second for $num_tests values between 100-1000.  It takes ~1.7 seconds for 10,000.  Run times are shorter if running externally to komodo and the verbose flag is off, so I assume there is some log processing overhead in the "Run without debugging" times.

The unit test tab's stdout log for these runs shows times taken lines that are broadly consistent with running prove externally without the verbose flag, so the slowdown is perhaps in komodo's unit test result processing.

For reference, my own code base has close to 3800 main tests (with a grand total of ~98,000 if one includes subtests).

**Comment by Naatan** [comment] 2017-02-23 04:46
Thanks for the excellent report, your test case is incredibly helpful. 

I want to note that unit testing in Komodo is intended to help developers with testing features. Realistically you shouldn't really be running thousands of tests in Komodo, as it's unlikely you'd be working on a single feature that has thousands of tests. For that you would likely using some sort of continuous integration system.

That said, we will do our best to support use-cases that we had not imagined. I'll see what I can do about improving performance with large test cases.

**Comment by shawnlaffan** [comment] 2017-02-23 05:01
No problem.  I figured I would run it and see what happened.

The unit test tab does indeed simplify the process for test subsets, and multiple configs are very useful when working across features.

**Comment by Naatan** [comment] 2017-02-24 21:59
Fixed with https://github.com/Komodo/KomodoIDE/commit/dd210e7f8db979eea10a128d6cbee5af31472fa6

This is too big a change for it to go into 10.2.1, so 11 it is.

Note that performance will still not be 100%, but will be a lot better. We won't be able to get consistent performance when you run this amount of tests, this is unfortunately just a limitation of XUL. One we would only be able to get around by compromising the functionality of the feature, which is not something I'm wiling to do considering the use-case is one that isn't what the feature was intended for.

**Closed by Naatan** 2017-02-24 21:59 UTC
Labels: Enhancement
