### ISSUE TITLE
Tab-aware past does not replace selection

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2835] opened 2017-08-14 19:56 UTC
### Short Summary

title.

### Steps to Reproduce

1. Copy something to your clipboard.
2. Select something.
3. Fire the tab-aware insert command

### Expected results

The selection is replaced with the content of the clipboard.

### Actual results

The content of the clipboard appended to the selection.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11

**Comment by mitchell-as** [comment] 2017-08-14 20:48
Duplicate of #2714

**Closed by mitchell-as** 2017-08-14 20:48 UTC
Labels: Type: Bug

**Comment by mjainQA** [comment] 2017-08-22 07:01
Verified in Komodo IDE, version 11.0.0-alpha1, build 90514, platform macosx.
Built on Sun Aug 20 23:39:49 2017

Test case steps: see 2714
