### ISSUE TITLE
Project Search Enhancements

### ISSUE THREAD

**Issue by seattledeveloper** [Komodo/KomodoEdit#804] opened 2015-11-05 03:20 UTC
This request first started as a How To question, here:

http://forum.komodoide.com/t/how-to-ignore-symlink-files-on-search/2182

I would like to propose that the "Find in Files..." feature be enhanced to provide more granularity into what files are actually searched.  I find that if I use the "Search in: Files" option (specifying the extensions I want searched) that the searches can take a significant amount of time if there are a large number of non-matching files in the path being specified.  An example is to filter to include *.html;*.phtml;*.php, but if the path included contains a large number of folders, each of those folders needs to be opened to examine for files containing an extension match.

To get around this, I was hoping to use the "Search in: Project" option, by adding specific folders and files to the project using the "New Group" and "Existing Files" commands.  Unfortunately when specifying the "Search in: Project" option, Komodo searches all the files in the Project Base Directory rather than limiting the search to the folders and files that I have explicitly included in the search.

It seems to me that the project search option would be better served if it only searched those files specifically added to the project.  The Files option can then be used to search all the folders inside the Project Base Directory simply by including it in the Directories: box.

This enhancement would also allow me to solve my original issue, which is to not search symlinks as I simply wouldn't add them to my project files.

Please let me know if you'd like any clarification on my suggestion.

Thanks!

Ed

**Comment by Naatan** [comment] 2015-11-05 19:00
I'm a bit confused, search in Projects should indeed only search for files that were added to the project, if it does not do this for you then you should ideally report a bug on this.

I think Search in Files is exactly what you'd want, you can specify exactly what directories you'd want it to search in and what files to exclude. Honestly a directory would need to include a LOOOT of files for it to bog down the exclude filter, Python is pretty fast ..

**Comment by seattledeveloper** [comment] 2015-11-05 20:49
Hi Nathan,

I want to make sure I have this set up correctly before reporting a bug.

Here's my Find in Files dialog box:

![find-dialog](https://cloud.githubusercontent.com/assets/9749337/10981109/9b8baa0e-83ba-11e5-9a2a-704f893c2593.png)

Here's my project pane showing 2 files added to the project (note that tmp is a Group):

![project-pane](https://cloud.githubusercontent.com/assets/9749337/10981123/b1f8571a-83ba-11e5-88a4-ec3803ecffb4.png)

Here's my search results pane:

![results-pane](https://cloud.githubusercontent.com/assets/9749337/10981147/d2c67fd0-83ba-11e5-92d7-f088eafb3e57.png)

And finally here's the search status pane showing how many files were searched (notice over 10,000 files searched):

![status-pane](https://cloud.githubusercontent.com/assets/9749337/10981159/e11790ba-83ba-11e5-80a3-632bd60a4bd7.png)

Note that the reason I don't use Search in Files is that one of my projects is located in 6 distinct folders (representing 6 different subdomains on the live site) and multiple files are included by symlink.  I am trying to prevent them from showing up more than once in the search results by only including actual files in my project, but I need project search to work in order to do this.

So, before I enter a bug (or this ticket is converted this to a bug), I want to make sure that I've configured my project correctly.  I am new to Komodo, so I may not have this right.

Thanks!

Ed

**Comment by Naatan** [comment] 2015-11-05 20:52
What is your project source aimed at? Does it need to be including over 10k files? I think you need to play around with your project preferences, ie. Project > Project Preferences.

**Comment by seattledeveloper** [comment] 2015-11-05 21:05
I have the project source set to the /var/www/html folder of my development server, where is needs to be to include multiple folders all off that webroot folder.

To try what you suggested, I deleted the project base directory.  It then defaults to my local machine where I've stored the project file itself.  If I then do the Find in Files, the search status says there are no files to search.

My question is why is there an ability to add files to a project and not have those files included in the project search?  This is the part that I'm confused by.

**Comment by Naatan** [comment] 2015-11-05 21:10
Your project should be pointing at eg. the website you are working on. If you only have one website under /var/www/html then I suppose this is the right place, if you have more than one then you should point it at the specific folder for the site you are working on. A project is something you work on. eg. if I work on website foo then I open my project foo, if I work on project bar I open project bar.

A project should not be used as a global state for how Komodo is configured, that is not how Komodo is intended to be used. If you point 10k files at Komodo it will work with 10k files. I cannot imagine this to actually be a valid use-case though, it sounds to me like you need to better specify what your "project" is.

**Comment by seattledeveloper** [comment] 2015-11-05 21:20
I have about 50 folders in my webroot, but my problem is that one client (one project) is in 6 of them.  This is the cause of my problem.

Getting back to my request, I am asking for your team to consider defining a search in project to only include the files that have specifically been added to the project.

From my perspective, there is no difference from specifying /var/www/html/tmp as the *project path* when searching by Project, or specifying as the *directories* when searching by Files.

That's why I am asking for consolidation of changing the Project search to include only those files that have been actually added to the project.  That, in my mind, is what Project search really means.  Especially considering I can easily accomplish the other.

**Comment by Naatan** [comment] 2015-11-05 21:34
Your project source is what has been specifically added to your project, you are using projects in a way that they were not intended and asking for us to support it, I don't think your use-case is a good one and it seems to me you could easily move your folders into one common parent folder to achieve what you want without handicapping your IDE.

Simply put; do not point your project root at a directory which primarily contains files that you are not interested in within the context of your project. You are miss-using the project mechanic and are therefore dealing with consequences that are undesirable.

Alternatively if you really want to point your project at /var/www/html you could use the Project excludes to exclude any folders that you are not interested in within the context of that project, this should affect search results as well.

Adding a folder manually the way you are is intended for edge cases, it is not intended to be used as the goto method of including files in your project, that is what the project root is for.

I'm closing this as this does not affect the Komodo core, but I'm happy to answer more questions.

**Closed by Naatan** 2015-11-05 21:34 UTC
Labels: Pending Response

**Comment by seattledeveloper** [comment] 2015-11-05 21:47
Thanks for your reply.

Even if I were to combine the project files under a single folder, it still doesn't get around the issue where symlinks are included in the search results, which was really my first ask in the forum.

I go back to Allaire's Homesite (which regrettably got purchased by Adobe).  They had a project where you specifically added folders and files that were included in the project.  When doing an "Extended Find", you could pick a group of one or more folders (same as you), or you could pick a project, which only included the folders and files specifically added to the project.

That's why I don't think this is such a crazy suggestion.  That and you have two ways to do the exact same thing (project search or specifying the project file in the location), but no way to do what I am talking about.

**Comment by Naatan** [comment] 2015-11-05 21:54
You've only very briefly touched on symlinks here, I'm happy to take a request for that but let's not get side tracked. Please file a separate ticket for symlinks.

You can in fact use Find in Files to do what you want, the Directories field allows you to specify any number of directories to search.

The reason I am holding back on this is twofold;

 1. you are not using projects as intended, so your use-case and the reason for wanting this functionality is "flawed". I mean no disrespect by this, I am simply looking at the situation objectively and considering it from an "average user" perspective.
 2. Continuing on that point, I don't think the average user would need this feature, and adding it would further bog down the find window which is already quite full of features. Usually when these kinds of issues come up where one or two users have a very specific need for an uncommon use case the best approach I can think of is to simply write a small addon that does this.

I really don't mean to sound unwelcoming to the idea, it is a very interesting idea and I thank you for bringing it to us. I just personally don't feel that it makes sense for us to implement this. If you and others feel different I am happy to discuss and hear your point of view. Although I will say that I think it would benefit your request if you were to try and use the Komodo projects as intended, if after doing so you still feel strongly about this feature then you will undoubtedly be able to give fresh insights as to why that is the case.

**Comment by seattledeveloper** [comment] 2015-11-06 01:28
Hi Naatan,

Thanks.  I will work with Komodo and possibly reopen this ticket in the future.

And I will open a new ticket for symlinks in the morning.

Ed
