### ISSUE TITLE
Komodo 10 UI: text color on "check for updates" window

### ISSUE THREAD

**Issue by we3geeks** [Komodo/KomodoEdit#1424] opened 2016-05-07 19:26 UTC
### Short Summary
Some of the text on the "check for updates" dialog using various dark color schemes leaves it hard to see.

### Steps to Reproduce
Use the default colors or Solarized colors. Select Help > Check for Updates...

### Actual results
See attached screenie. Some, but not all, of the text is rendered in black text on dark background.

### Platform Information

Komodo IDE, version 10.0.0-beta1, build 89113, platform macosx.
Built on Fri May 6 01:55:28 2016.

### Additional Information
![k10-20160507b](https://cloud.githubusercontent.com/assets/2390335/15094084/370862e2-1457-11e6-931f-ddf18a9030e2.png)

**Comment by Defman21** [comment] 2016-05-07 19:30
Dupe of #1401

**Comment by we3geeks** [comment] 2016-05-07 19:36
Yup; sorry. My fault. I keep forgetting that github's issues search defaults to open issues.

**Comment by Defman21** [comment] 2016-05-07 19:36
Yeah, me too. I just remember that one.

**Closed** 2016-05-08 01:10 UTC
Labels: Duplicate
