### ISSUE TITLE
Last opened poject not remembered

### ISSUE THREAD

**Issue by petewulf** [Komodo/KomodoEdit#1726] opened 2016-06-21 10:16 UTC
### Short Summary

If you startup Komodo with the the last project is no more active as "current project". Normally it should be active and you would be able to close the project but its greyed out and only showing "open project" although its files are currently opened. As a following error a second newly opened project gets added to the current files in "open files dialog" and crowds up the whole list.

### Steps to Reproduce

Preferences: 

Workspace > Opening and Closing Projects: "Open recent files" and "Close all open files in project"
Open a project with files in "open files dialog"
Close Komodo
Restart Komodo
Right click on current opened project - you can open the project again although its currently opened
Open a second project - instead of closing the old files the new files from the second project will be added in "open files" list.

### Platform Information

*Komodo IDE 10* 
*Komodo Version 10.0.1* 
*Windows 10*

**Comment by Naatan** [comment] 2016-06-21 15:21
Thanks @petewulf. This appears to be a duplicate of #1560.

**Closed by Naatan** 2016-06-21 15:21 UTC
