### ISSUE TITLE
Can't move interpolation dialogs

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1621] opened 2016-05-27 18:34 UTC
### Short Summary

Run the following code in the console:
```
var input = ko.interpolate.interpolateString(
    "%(ask:your name)",
    false,
    "Pick a name."
);
```
Resulting dialog cannot be moved.  Might be Windows only.

**Comment by Naatan** [comment] 2016-10-03 15:48
Duplicate of #2036 (the issue is in the window decorations, not the specific window).

**Closed by Naatan** 2016-10-03 15:48 UTC
Labels: Bug, Enhancement: UX
