### ISSUE TITLE
Ctrl+Shift+U shows wrong binding

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#331] opened 2015-06-09 18:04 UTC
In the menu bar under Code->Convert Selected Text->Make Lowercase, the keyboard shortcut is shown as Ctrl+Shift+U.

The actual result of using that combination is to display the outline of the file and its subroutines.

**Comment by cgchoffman** [comment] 2015-06-09 20:43
It got usurped.  You can fix this by removing setting it in Preferences > Key bindings > Open Commando with the Sections scope.

**Comment by Naatan** [comment] 2015-07-13 19:56
Duplicate of #206

**Closed by Naatan** 2015-07-13 19:56 UTC
Labels: Bug
