### ISSUE TITLE
[9.3] search/replace dialog box is broken again

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#676] opened 2015-10-07 12:54 UTC
Basic functionality in search/replace seem to be broken:

## tab order

when bringing up search/replace dialog box via key command, the expected tab order is:

- search regex
- replace regex

instead, all the relatively unused option toggles come first.

## shortcuts

control-A to replace everywhere when the dialog box is open seems to have been over-ridden by other shortcuts at least on OSX

## detection of selected text area

when a bunch of lines have been selected, invoking the search dialog box should assume that the target area for replace is the selected text, not entire files.

**Comment by Naatan** [comment] 2015-10-07 14:52
The search dialog has been significantly overhauled and will likely go through some more changes before we release 9.3 final. I think your "expectations" came simply from the way the old dialog worked, and an overhaul is meant to be throwing things around here. Give it some time and see if it grows on you. I personally do not feel that eg. the regex option should come before the "case sensitive" option, as it is not one that people are more likely to use.

Just to confirm that you are looking at the right thing though, this is what the "dialog" (widget) should look like (more or less):

![ojaycl6nolelzzqaomn954h0q62zqm6pbn6wddkmygk](https://cloud.githubusercontent.com/assets/278649/10341137/7eeaab24-6ce1-11e5-9123-f0bde0c714a9.png)

**Comment by Naatan** [comment] 2015-10-07 14:54
Also, please try to report each issue in a separate ticket. I see you are basically reporting 3 issues here. I really appreciate you spending the time to report them but it becomes very hard to track and manage if a single ticket tracks multiple issues (even if they are related to the same feature).

**Comment by Naatan** [comment] 2015-10-07 14:56
Cannot reproduce Ctrl+A, but this is already starting to get messy. Please report separate issues. Closing this as the main issue here (UX) is subjective and will be polished before final.

**Closed by Naatan** 2015-10-07 14:56 UTC

**Comment by cgchoffman** [comment] 2015-10-07 18:17
> detection of selected text area

@dch:  https://github.com/Komodo/KomodoEdit/issues/687 I was going to file that any way.

**Comment by dch** [comment] 2015-10-12 21:19
Hi Nathan,

The tabbing issue is not about the dialog (toggle?) options on the
right, but with the 2 most used text area fields:

- where you enter the regex text for the find selected / active by
default
- where you enter the regex text for the replacement as the 2nd tab

I see how my original phrasing wasn't clear, I can open a new ticket if
need be.

**Comment by Naatan** [comment] 2015-10-13 16:40
Please do open a new ticket, and maybe include an annotated screenshot, as I am still not quite sure what you mean.

Thank you :)
