### ISSUE TITLE
Toolboxes disappears after running SikuliX

### ISSUE THREAD

**Issue by arwankhoiruddin** [Komodo/KomodoEdit#2159] opened 2016-11-17 19:33 UTC
### Short Summary
I use [sikuli](http://sikulix.com) to automate GUI testing (I use python for sikulix). Rather than use their IDE, I use Komodo Edit as it feels more convenient for me and it gives flexibility to add custom command. I use two OSX laptop on my work. I did not have any problem when running Komodo Edit 9.3 on my Yosemite. However, I got problem on my second laptop. I installed Komodo Edit 10.1.1 on El Capitan. I created a custom command to run SikuliX (below - first image). However, after finishing to run SikuliX, all custom commands including my custom command disappear (below - second image). 

### Steps to Reproduce

- Install SikuliX
- Put SikuliX inside /Application folder
- Run Komodo Edit 10.1.1
- Add the following command: `/Applications/SikuliX.app/run -r %D`
- Create any sikulix script, run it using the added command
- When SikuliX script finish running, the custom commands and any other commands in Toolbars disappear

### Expected results

Custom commands does not disappear after finished running SikuliX script

### Actual results

Custom command in the right panel disappear after finished running SikuliX script

### Platform Information

*Komodo Edit or IDE?* Komodo Edit
*Komodo Version?*  10.1.1
*Operating System (and version)?* El Capitan 10.11.6

### Additional Information

**Error logs**
None

**Workaround**
Restart Komodo Edit

**Screenshots**
![](https://s6.postimg.org/9n3ka8eip/Screen_Shot_2016_11_17_at_8_13_04_PM.png)

![](https://s6.postimg.org/yuegahhmp/Screen_Shot_2016_11_17_at_8_18_21_PM.png)

**Comment by cgchoffman** [comment] 2016-11-17 19:43
When you say "Custom Commands" are you referring to all items in your Toolbox?  

Please grab your logs after reproducing this issue: `Help > Troubleshooting > View Log File`.

*NOTE*: the command in your screenshot does not match the command in your reproduction steps.  One is pointing at your `~/Application` folder and the other is pointing at the `/Application`.  Not that the Toolbox should break if your command breaks :(  Hopefully your log file will shed some light on what happened to the Toolbox.

**Comment by arwankhoiruddin** [comment] 2016-11-17 19:53
Hi, cgchoffman, thank you for the prompt reply. 

Yes, "custom commands" refers to all items in Toolbox. And you are right. It was my mistake that I put that `~` in front of `/Application`. I can run it now. However, the items in the toolbox is still missing. So, please just concentrate on that part and forget about the `~` part. :)

I uploaded the log [here](https://www.dropbox.com/s/2bwsd5lxqgpt9ct/komodo_log.txt?dl=0)

**Comment by Naatan** [comment] 2016-11-17 21:03
I'm a bit confused, your summary says you get an error saying the command basically cannot be run, but your steps to reproduce describe a different problem (command is disappearing from the toolbox). Can you please elaborate?

**Comment by cgchoffman** [comment] 2016-11-17 21:22
@arwankhoiruddin.  have you tried restarting Komodo yet?  And do you perhaps have reproduction steps that don't require installing and using a 3rd party application?  I'll try and repro myself using a broken command.

**Comment by cgchoffman** [comment] 2016-11-17 21:23
@Naatan, i'm under the impression that the command not running properly is what is breaking the toolbox but I most certainly could be wrong.  It could be two totally separate issue.

**Comment by arwankhoiruddin** [comment] 2016-11-17 21:42
@Naatan the title and the summary has now been updated. Please let me know if I need to elaborate or update.

@cgchoffman unfortunately this happens only with SikuliX. I use Komodo for SikuliX and "normal" python script programming.

**Comment by cgchoffman** [comment] 2016-11-17 21:48
@arwankhoiruddin, so this still occurs even you fixed the path in your Commman?

Did your toolbox  come back after a restart?

**Comment by arwankhoiruddin** [comment] 2016-11-17 21:49
@cgchoffman yes, it still occur after fixing the path in my command and the toolbox come back after a restart.

**Comment by Naatan** [comment] 2016-11-17 21:49
@arwankhoiruddin ok next issue then :p Your screenshots are of Komodo 9 but your summary talks about Komodo 10.

Have you in-fact reproduced the issue on Komodo 10?

**Comment by arwankhoiruddin** [comment] 2016-11-17 21:56
@cgchoffman great that you notice that. In fact, I installed Komodo 10 and faced this problem. Because the problem does not happen on Komodo 9 on my Yosemite, I was thinking it is due to problem with Komodo 10. Thus I uninstalled Komodo 10 and copy the .app of Komodo 9 and the folders from ~/Library/Application Support from my Yosemite laptop into my El Capitan laptop. And I still have similar problem.

**Comment by arwankhoiruddin** [comment] 2016-11-17 22:07
The log for Komodo 10 is posted [here](https://www.dropbox.com/s/y8z0m0bh0hpd8am/pystderr.log?dl=0) 

Following is the Toolbar. All commands are missing as in Komodo 9.

![](https://s6.postimg.org/es4rrurgh/Screen_Shot_2016_11_17_at_11_01_24_PM.png)

**Comment by Naatan** [comment] 2016-11-17 22:12
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by arwankhoiruddin** [comment] 2016-11-17 22:21
@Naatan, yes. It is reproducible after `Restart in Safe-mode`. However, in safe mode, I cannot get the log file. It said that the log file does not exist

**Comment by cgchoffman** [comment] 2016-11-17 23:22
> I cannot get the log file. It said that the log file does not exist

That's because we hide your profile from Komodo but it unfortunately doesn't trickle up to that command.  It's ok.  I didn't see an error before.  I doubt there would be one this time.  Looks like it's time for me to try installing SikuliX.

In the meantime, could you see if running the following command in the Console (View > Tabs & Sidebars > Console) fixes your broken toolbox:
`ko.toolbox2.manager.view.reloadToolsDirectoryView(0)`

**Comment by arwankhoiruddin** [comment] 2016-11-18 04:30
@cgchoffman, so sorry for the late reply. I open the console and put `ko.toolbox2.manager.view.reloadToolsDirectoryView(0)' as suggested. I still cannot see any changes on the Toolbox. Followings are the output in the console.

'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2HTreeView.reloadToolsDirectoryView]
    05:27:41 632ms
    Boolean
    false
    05:27:41 635ms
`

**Comment by cgchoffman** [comment] 2016-11-18 19:30
OK, i'll have to reproduce this as these errors aren't actually telling me whats wrong with the Toolbox.  Is this the software you installed and are using? http://sikulix.com/

If not could you send me the download link for it?

**Comment by arwankhoiruddin** [comment] 2016-11-18 19:37
@cgchoffman yups, that's the software I installed and is using. To make it easy, you can just download SikuliX from lunchpad in this [link](https://launchpad.net/sikuli/sikulix/1.1.0/+download/sikulixsetup-1.1.0.jar)

**Comment by Naatan** [comment] 2016-11-18 20:39
Does the problem only happen with that specific command? Could you try creating a new command that just runs `whoami` and see if the same issue happens?

**Comment by cgchoffman** [comment] 2016-11-18 21:42
I installed SikuliX, created a Toolbox Command with the following `/Applications/SikuliX.app/run -r %D`.  I created a Python file with `print("pizza")` in it and then ran the command.  My toolbox is fine still.  I'm going to see if i can get more log output from you @arwankhoiruddin.  Stand by for a command to run.

**Comment by cgchoffman** [comment] 2016-11-18 21:51
Ok, not a command.  You'll have to edit a file.
- open `[Komodo install dir]/Content/Resources/Python/komodo/koToolbox2.py`
- Uncomment line 37and save
- restart Komodo
- reproduce the issue
- send us the logs

Also do what @Naatan mentioned above please.

**Comment by arwankhoiruddin** [comment] 2016-11-20 07:09
@Naatan @cgchoffman 

I am sorry for the late reply. After trying for several times from yesterday, my toolbox never disappear again. Is it caused by `ko.toolbox2.manager.view.reloadToolsDirectoryView(0)` command? It was not reloading when I execute that command. But after restarting komodo, I never experience the problem anymore. As I currently cannot reproduce the problem any longer, should I close this ticket?

**Comment by arwankhoiruddin** [comment] 2016-11-21 00:30
@Naatan @cgchoffman 

I have this problem again, but I am not really sure when it happens. I tried to rerun SikuliX for my code for several times, but it does not always get this problem. It is quite a long code. As it belongs to my company, I do sorry that I cannot disclose it here

Hereby I attach the log when I got the Toolbox disappear. Hope you can get some ideas from the log.

[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/602444/pystderr.log.zip)

**Comment by Naatan** [comment] 2016-11-21 16:16
This seems relevant:

```
ERROR:xpcom:Unhandled exception calling 'int8 * isContainer(in int32, out retval boolean);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 10.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 10.app/Contents/Resources/components/koToolbox2HTreeView.py", line 1021, in isContainer
    return self._rows_view[index].isContainer
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Looks like you might have a tool that is corrupted somehow. 

Would you be able to share your toolbox with us? It's located in your [profile folder](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data) (folder called tools).

**Comment by cgchoffman** [comment] 2016-11-21 17:37
I'm pretty confident this is #2159 now.  I'm going to close it in favor of this ticket.

**Comment by arwankhoiruddin** [comment] 2016-11-21 18:08
@Naatan, please find the tools I have in the following attachment.

[tools.zip](https://github.com/Komodo/KomodoEdit/files/604413/tools.zip)

**Comment by cgchoffman** [comment] 2016-11-23 21:01
My toolbox just imploded while I was editing snippets and executing them.  Every thing is normal before the first error below.  These are the errors:
```
ERROR:xpcom:Unhandled exception calling 'int8 * setFilter(in wstring);'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koToolbox2HTreeView.py", line 1085, in setFilter
    self.clearFilter()
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koToolbox2HTreeView.py", line 1128, in clearFilter
    self._filter_std_toolbox()
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koToolbox2HTreeView.py", line 1172, in _filter_std_toolbox
    if len(self._rows_model) == 0:
TypeError: object of type 'NoneType' has no len()
[2016-11-23 12:54:18,887] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2HTreeView.setFilter] (2) in chrome://komodo/content/toolbox/toolbox2.js:185
Traceback (most recent call last):
  File "chrome://komodo/content/toolbox/toolbox2.js", line 185, in 

ERROR:xpcom:Unhandled exception calling 'int8 * isContainer(in int32, out retval boolean);'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koToolbox2HTreeView.py", line 992, in isContainer
    return self._rows_view[index].isContainer
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR:xpcom:Unhandled exception calling 'int8 * getLevel(in int32, out retval int32);'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koToolbox2HTreeView.py", line 1047, in getLevel
    return self._rows_view[index].level
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The `TypeError: 'NoneType' object has no attribute '__getitem__'` go on repeating for (I'm guessing) every tool in my toolbox.

**Comment by Naatan** [comment] 2016-11-23 21:07
@cgchoffman Assuming your toolbox disappeared afterwards?

**Comment by cgchoffman** [comment] 2016-11-23 21:08
yep, that's what I meant by "imploded".

**Comment by Naatan** [comment] 2016-11-23 21:20
Were you able to find a way to show it again?

**Comment by cgchoffman** [comment] 2016-11-23 21:24
That wasn't on my mind, sorry.  I just pasted the error, restarted and got back to work.  I"ll be doing this for a couple days, I'm bound to hit it again.  I'll remember to try and reload the toolbox next time.

**Closed** 2017-02-21 16:06 UTC
Labels: Pending: Response
