### ISSUE TITLE
Menu gets stuck when selecting sub-menu item

### ISSUE THREAD

**Issue by abkothman** [Komodo/KomodoEdit#1663] opened 2016-06-05 02:15 UTC
### Short Summary

Selecting a sub-menu item in the menu causes the sub-menu to get stuck open until you click away from the menu.

### Steps to Reproduce

1. Click on the Hamburger Menu icon in the top right
2. Hover over an option, like "Edit", until you see all of the options available for edit
3. Instead of selecting something under Edit, try to select anything else at the same level as Edit (i.e. Preferences, Code, Navigation, View, Save Workspace) and you will be unable to do so

### Expected results

I would expect that moving my mouse away would get rid of the sub-menu, and I would be able to select something else in the parent menu without having to actually click elsewhere.

### Actual results

The menu gets stuck in whatever sub-menu you select until clicking away.

### Platform Information

*Komodo IDE* 
*Komodo Version 10.0.0, build 89159, platform linux-x86_64* 
*Ubuntu 14.04*

**Comment by coathanger3** [comment] 2016-06-05 15:48
I had/have the same issue.  Are you using Classic mode?  I was having the same problem with certain classic mode options set.  Once I turned off classic mode (but I left Classic toolbar layout), it seemed to fix the frozen menu.

**Comment by Defman21** [comment] 2016-06-05 16:15
It's a Mozilla bug: https://github.com/Komodo/KomodoEdit/issues/640#issuecomment-144125056

**Comment by mitchell-as** [comment] 2016-06-06 14:29
Duplicate of #1155. Press the Escape key to "unstick" the menu rather than clicking away from it.

**Closed by mitchell-as** 2016-06-06 14:29 UTC
