### ISSUE TITLE
Auto-Indent inserts wrong number of spaces

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1248] opened 2016-04-13 16:17 UTC
### Short Summary

My prefs are: 

* Number of spaces per indent: 2
* Width of each tab character: 2

But it always insert 8 spaces.

### Steps to Reproduce

```php
function test() { | - cursor
```

Press Enter.

### Expected results

```php
function test() {
  | - cursor
}
```

### Actual results

```php
function test() {
        | - cursor
}
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04

### Additional Information

**Comment by mitchell-as** [comment] 2016-04-13 16:39
I'm not seeing this with a clean profile. I can change the tab width to 2, 4, and 8 spaces without issue. I can toggle between tabs and spaces as well.

**Comment by Defman21** [comment] 2016-04-13 16:43
Yeah, not able to reproduce it with a clean profile.

**Comment by Naatan** [comment] 2016-04-13 16:44
Workarounds aren't fixes.

Does resetting file preferences also fix the issue?

**Comment by Defman21** [comment] 2016-04-13 16:46
How to do it?

**Comment by cgchoffman** [comment] 2016-04-13 16:47
This sounds like the prefs bug that was fixed for a nightly.  @Defman21 are you certain that the provided content is the exact repro code?  or was there other code in the file?

To reset file prefs: Help > troubleshooting > reset file prefs

**Comment by Defman21** [comment] 2016-04-13 16:50
Resetting doesn't help.
Yes @cgchoffman. There's no other code, only what I gave.

**Comment by Naatan** [comment] 2016-04-13 17:00
Does your project have any indentation preferences? Try closing the project and see if you can still reproduce the issue (with freshly opened files).

**Comment by Defman21** [comment] 2016-04-13 17:01
I don't even have opened any projects when I've reproduced it.

**Comment by Naatan** [comment] 2016-04-13 17:06
Can you share your prefs.xml?

**Comment by Defman21** [comment] 2016-04-13 17:06
Is it safe? :)

**Comment by Defman21** [comment] 2016-04-13 17:10
Fast-looking of it says it's not, there are too many of my super secure project listed in.

**Comment by Naatan** [comment] 2016-04-13 17:11
You could email it instead to support@activestate.com and mention this ticket. Promise we won't use it for anything but debugging :)

**Comment by Defman21** [comment] 2016-04-13 17:12
I trust you guys for sure :)

**Comment by Naatan** [comment] 2016-04-15 15:00
@Defman21 can you verify that the email was sent? We have not received anything.

**Comment by Defman21** [comment] 2016-04-15 15:14
Anyway I've detected a very interesting warning when I've tried to press Tab in a HTML5 file:
```
[2016-04-15 18:13:55,374] [WARNING] koLanguageCommandHandler: scimoz indent is 0 - that should never happen
```

**Comment by Naatan** [comment] 2016-04-15 15:39
Please try sending th email again, and make the subject plain text.

**Comment by Defman21** [comment] 2016-04-17 08:29
```
[2016-04-17 11:28:44,244] [ERROR] koLanguageServiceBase.indenting: indent was 0, defaulting to 8
```
Hmm...

**Comment by Defman21** [comment] 2016-04-17 08:46
Okay, I've re-checked "Use tabs instead of spaces" in Indentation settings and then re-started Komodo, now it works fine for me!

**Comment by Defman21** [comment] 2016-04-17 08:57
I've sent you 2 e-mails with plain prefs.xml and non-plain subject (I'm jerk) and with plain subject and attached prefs.xml.

**Comment by Naatan** [comment] 2016-04-19 15:30
OTRS #48819

**Comment by mitchell-as** [comment] 2016-04-19 21:26
I've imported your preferences and cannot reproduce this @Defman21. I recently fixed some indentation issues, so perhaps those issues fixed this problem too. I'm going to close this for now and if you see it after we issue a new build (or you yourself build from master), then we can reopen.

**Comment by Defman21** [comment] 2016-04-20 04:41
Ok I'll try a new build. Thanks :)

**Comment by lagbox** [comment] 2016-04-29 12:43
I just started running into this on my current profile (inserting 8 spaces instead of my pref 4) out of the blue. The error in the log will say indent is set to 0, defaulting to 8.
If I change these to any number, apply, then set them back to 4, they work as expected again.
Build: 88986

**Comment by cgchoffman** [comment] 2016-04-29 15:23
> The error in the log will say indent is set to 0, defaulting to 8.

@mitchell-as didn't we figure this out last week?

**Comment by mitchell-as** [comment] 2016-04-29 15:24
Yeah, the latest build should not be giving that warning.

**Comment by cgchoffman** [comment] 2016-04-29 15:33
The build @lagbox is using is from Wednesday night so it should contain the fix right? ie. the fix went in on Tuesday April 26th?  Maybe there is another code path that leads to this issue.  If that's the case we should get another bug report and start from scratch.

**Comment by mitchell-as** [comment] 2016-04-29 15:34
Yeah, I'd need the actual warning text to search for an alternate tree.

**Comment by mitchell-as** [comment] 2016-04-29 15:42
@lagbox would you please post your exact message from the error log? Thanks.

**Comment by Defman21** [comment] 2016-04-29 15:43
His is the same as mine above

**Comment by mitchell-as** [comment] 2016-04-29 15:49
Okay, thanks @Defman21. No need for more information @lagbox. I think I got it.

**Closed** 2016-04-29 15:48 UTC
Labels: Bug, Pending Response, Regression

**Comment by tonyattwood** [comment] 2016-07-19 11:42
Hi,


It's just amazing  what some people can create, I love  it, look  at that <http://expert.awesumassistants.com/e4jrsx>


Best regards, tony.attwood@ntlworld.com
