### ISSUE TITLE
Enhancement Request: Update Python Syntax Checking to Use pycodestyle Instead of pep8.

### ISSUE THREAD

**Issue by jaysmith1** [Komodo/KomodoEdit#3325] opened 2017-10-25 22:24 UTC
### Short Summary
The pep8 project was forked to pycodestyle nearly two years ago. The pep8 project is no longer maintained/updated. The pep8 changelog at [pypi](https://pypi.python.org/pypi/pep8/1.7.1) has the following as its most recent entry: 
> Prominently note via warning message that the tool is no longer released as pep8 and will only be fixed in the pycodestyle package

Thanks in advance!

**Comment by mitchell-as** [comment] 2017-11-21 16:55
Duplicate of #2063.

**Closed by mitchell-as** 2017-11-21 16:55 UTC
Labels: Type: Enhancement
