### ISSUE TITLE
Commando / sections in pain

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#132] opened 2015-04-07 13:18 UTC
Hitting the hotkey for the Commando / sections brings no results, despite having an active .py file.
Hitting the ```right-arrow``` key populates the list for one file but not for an other.
Restarting KO9 makes it work again.

![screenshot - 04072015 - 03 12 29 pm](https://cloud.githubusercontent.com/assets/350912/7023833/98b5f164-dd38-11e4-8f86-2d74c12c5cb5.png)

log entries:
```
[2015-04-07 15:10:57,975] [ERROR] console-logger: TypeError: data is undefined (2) in chrome://scope-sections/content/sections.js:151
Traceback (most recent call last):
  File "chrome://scope-sections/content/sections.js", line 151, in 

[2015-04-07 15:11:01,628] [ERROR] commando: Subscope does not exist: undefined
Traceback from ERROR in 'commando' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    this.setSubscope@chrome://commando/content/sdk/commando.js:1036:1
    this.expandResult@chrome://commando/content/sdk/commando.js:565:9
    onExpandResult@chrome://commando/content/sdk/commando.js:273:9
    onKeyNav@chrome://commando/content/sdk/commando.js:166:17
```

**Comment by Naatan** [comment] 2015-04-07 15:10
Do you have steps to reproduce for the "Right arrow" issue?

Section scope issue is duplicate of #114 and should be fixed in the nightly that is going up later today (please don't combine multiple issues in one report).

**Comment by agroszer** [comment] 2015-04-08 07:17
For the file that does not populate on right arrow? That's not opensource... As I remember I was switching back and forth between the 2, but no sorry, no details.

**Comment by Naatan** [comment] 2015-04-08 16:00
I'm confused what opensource has to do with this?

Are you saying you're not able to reproduce the issue at all anymore?

**Comment by agroszer** [comment] 2015-04-09 06:28
I mean the file that caused the error isn't open source, so can't give that to you.

Repro usually isn't that easy, because if the error happens after some hours of work and 30+ files open KO seems to collect some garbage. Restart helps.

**Comment by Naatan** [comment] 2015-06-30 16:32
Fairly certain this is fixed in the latest Komodo version.

**Closed by Naatan** 2015-06-30 16:32 UTC
Labels: Pending Response
