### ISSUE TITLE
VIM emu: Allow cursor movement in virtual space

### ISSUE THREAD

**Issue by rawktron** [Komodo/KomodoEdit#2560] opened 2017-04-28 16:52 UTC
Make it an option for the cursor to move in virtual space and have that option actually work. Flapping cursor syndrome drives me crazy.

Platform: Win/Linux

**Comment by mitchell-as** [comment] 2017-04-28 16:57
Duplicate of #2383.

**Closed by mitchell-as** 2017-04-28 16:57 UTC
