### ISSUE TITLE
Komodo Edit 10.0.0 text in open file disappears after application is hidden and then shown on OSX

### ISSUE THREAD

**Issue by elo2112** [Komodo/KomodoEdit#1615] opened 2016-05-27 01:31 UTC
### Short Summary

While using Komodo Edit, text in an open file file disappears (i.e. is not rendered on the solid editor background color) when the application is hidden and then shown again.

### Steps to Reproduce

1. Open Komodo Edit 10.0.0.
2. Create a new file and type a few characters, or open an existing file.
3. Hide the application (top OSX bar "Komodo" menu -> "Hide Komodo Edit").
4. Show the application by clicking its OSX dock icon, or by using command+tab to switch back to it.
5. Text will not appear in the open tab.

You can get the text to reappear by opening up a new file and then switching back to your original tab with the missing text.

### Platform Information

Komodo Edit, version 10.0.0, build 17209, platform macosx.
Built on Wed May 11 22:00:40 2016.

Mac OSX 10.11.5

**Comment by mitchell-as** [comment] 2016-05-27 14:28
Duplicate of #564

**Closed by mitchell-as** 2016-05-27 14:28 UTC
Labels: Duplicate
