### ISSUE TITLE
Komodo 11 Multiple CodeIntell Popups

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#3422] opened 2018-01-12 18:43 UTC
**DEV NOTE**: *Thanks to @tunedin76 patients and help we have narrowed this down to Komodo presenting stale completions.  Komodo requests completions on each key stroke and depends on newer request results removing older request results from the screen.  We need a mechanism to invalidate and not show certain requests, like passing in a line context and invalidating requests that arrive that no longer match the current line context.  We could even invalidate certain contexts before they are sent.*

My Company has purchased Komodo 11, because I liked 10 so much.
Since Install on Windows 10 machine Code completion popups come up to the point of it not being usable.
Maybe it is an oversight on my end, but I look online to the Komodo 11 docs and the CodeIntel options are not the same as on my version.

I would like to show completion of vars and classes/props/methods with possible syntax popup after a ( is placed folowing a function.

It should be noted that I am programming in PHP, and also that this was the behavior of my last version Komodo 10.

If this is not a bug, then please forgive me and point me in the right direction.

In another thought, when Komodo 11 restarts after a preference change requires it - I loose my "Recent Projects" in the project window and have to reload them.

Thank You
James

**Comment by Naatan** [comment] 2018-01-12 19:17
What version are you using exactly?

**Comment by tunedin76** [comment] 2018-01-13 00:35
I'm using version 11 I also noticed one more thing the Box pops up if I don't move my cursor or type after a very short time and it's always on the last variable that the Box popped up with now if I change it to a different file or a different tab that same box will pop up I have to hit Escape in order to get rid of it after I hit Escape it doesn't seem to come up again until I let my cursor sit on another variable for more than about a second

James

________________________________

**Comment by tunedin76** [comment] 2018-01-15 13:41
In another note - I now have all calltips turned off in prefs under codeintel - and these boxes still pop up. 
![capture](https://user-images.githubusercontent.com/16789318/34944983-9fd50df2-f9cf-11e7-94a2-f21968f502e4.PNG)

**Comment by mitchell-as** [comment] 2018-01-15 15:34
Hi, what exact version are you using? Help > About Komodo. 11.0.0? 11.0.1? 11.0.2?

Also, the image you showed is not a call tip, it's the completion list. You'd have to uncheck "Enable Completions" to have that box go away.

**Comment by tunedin76** [comment] 2018-01-15 15:55
I am using Komodo IDE 11.0.2, and thank you, I will disable completions so I can use. 
I guess I will find out, but will I still be able to auto insert variables?

**Comment by tunedin76** [comment] 2018-01-15 15:58
I had it set off.. Completions.  But it did not ask me to restart, I will continue to see if they pop up again
![capture](https://user-images.githubusercontent.com/16789318/34951054-00673588-f9e3-11e7-95b0-378dbf7edaed.PNG)

**Comment by tunedin76** [comment] 2018-01-15 17:53
It looks to be operating normal in safe mode.

**Comment by Naatan** [comment] 2018-01-15 20:07
Are the two completion popups identical? Can you share a screenshot?

**Comment by tunedin76** [comment] 2018-01-16 13:52
They are different. They also pop up when window is not in focus, over other windows. 
![untitled](https://user-images.githubusercontent.com/16789318/34992258-8a4b5fe2-fa9a-11e7-9a65-d9efbddc9a7d.png)

**Comment by Naatan** [comment] 2018-01-16 16:07
I'm confused, your screenshot only shows one popup?

**Comment by tunedin76** [comment] 2018-01-16 17:22
Only one pop up shows at a time... If I hit Escape or cancel it or click off of it it appears a quarter a second later the same pop up until I type something in that becomes a different variable the pop-up will even display above other windows when Komodo is not active

James

________________________________

**Comment by Naatan** [comment] 2018-01-16 18:12
> Could you try Help > Troubleshooting > Reset CodeIndel DB.

**Comment by tunedin76** [comment] 2018-01-16 19:40
![untitled](https://user-images.githubusercontent.com/16789318/35008527-ceb34cbe-faca-11e7-96a3-a3610bf39404.png)
I reset the Code Intell and then I typed:
Mail::raw() and let the cursor sit for a second and this popped up and continued to pop up. Before I reset the Code Intell Database, I limited my scanning directory (previously it scanned the root of a laravel project) I limited it to just the classes directory...

**Comment by Naatan** [comment] 2018-01-17 16:49
Could you try shutting down Komodo, then navigating to your [profile directory](http://docs.activestate.com/komodo/11/manual/trouble.html#appdata_dir), once there locate the prefs.xml file and make a backup of it, then delete it.

Now start komodo again and see if the issue still reproduces.

**Comment by tunedin76** [comment] 2018-01-18 14:18
I did what you said, and to this point I have not had a re-occurance of the issue, however now my class properties and methods are not being displayed in an auto-complete way.. I checked prefs and all the boxes were checked in CodeIntell, and I reset the database with only about 50 files and I have waited over an hour. It appears through notification that the scan was done..... Hopefully the class and function autocompletion will just take some time and fix itself, the popup issue seems to be ok for now, maybe it was just a bad import of version 10 settings? Anyway let me know if there is anything I need to do to speed up getting my autocomplete back.

**Comment by tunedin76** [comment] 2018-01-18 15:02
![untitled](https://user-images.githubusercontent.com/16789318/35104207-296d0eb2-fc36-11e7-8965-bfa31921d841.png)
Just happened again, on the bottom pic I changed the var above it from public to private, then every time I move down a line the popup comes up. Tapping esc and clicking off the box and moving cursor eventually gets it to go away.

In the top picture I did not complete a object call, and the box poped up serveral times until I hit escape - i suppose a number of times

**Comment by Naatan** [comment] 2018-01-18 16:54
I have a feeling this has to do with php completions being a bit slow at the moment, which is targeted for a fix in 11.1. Does the same issue occur on other languages, eg. JavaScript?

**Comment by tunedin76** [comment] 2018-01-18 18:06
No it does not at all

James

________________________________

**Comment by mitchell-as** [comment] 2018-01-22 15:40
Yes, @Naatan is correct that this is due to the fact that PHP completions can be a bit on the slow side in your particular scenario. Every time you type, Komodo asks for completions. If each request takes a second (I just made that up), and you typed 5 characters (again, made it up), the first completion popup would show completions "5 characters ago". If you pressed escape, that's fine, but about second later you'd get completions from "4 characters ago". I don't know of a fix for this other than 11.1 may have improved performance enough to avoid this problem altogether.

**Comment by tunedin76** [comment] 2018-01-22 15:49
Is there an eta for 11.1? The use is unusable to me right now.

James

________________________________

**Comment by Naatan** [comment] 2018-01-22 15:55
No ETA. Fwiw you can likely work around this issue by limiting the folders CodeIntel scans. Simply add folders to your exclude pattern (Project Properties) that you want to exclude from CodeIntel. Your vendor dir would likely be a good start.

**Comment by tunedin76** [comment] 2018-01-22 15:56
Thank you I will do that

James

________________________________

**Comment by tunedin76** [comment] 2018-01-25 21:16
Just an additional comment, I now have codeintell scanning 3 directories, with about 20 classes / functions (about 12 files - ~1000 lines or less)

Popups still come up sometimes (I can't isolate exactly when, but usually when I cut and paste, but sometimes when I hit the ';' key)

The contents of the popup have no relation to what I am doing, for instance a single popup entry for "exif"

It also seems to happen in spurts... in other words - no inconsistent popups for a bit, but if I leave the IDE to another task and come back they will happen after almost every word, but then again until I hit the escape key a couple of times.

Also I have a class at the beginning of a file and the properties never (that I have seen) auto-fill, I have also not seen autofill for properties from an included class that is in code intell directory - Komodo 10 works great .

I know you are working on it - I just wanted to make some final observations in case they help you any - the IDE is by far the best one I have used (bug aside - that I know will be fixed), that's why I keep buying and recommending! - Keep up the good work!

**Comment by tunedin76** [comment] 2018-01-30 19:35
I have done what you said, and after about 3 hours of coding in PHP Komodo 11 begins becoming non-responsive, then crashing.... memory leak?

**Comment by Naatan** [comment] 2018-01-30 19:48
Is there evidence of a memory leak? Is your memory ever increasing?

**Comment by tunedin76** [comment] 2018-02-01 13:14
I'd have to see.  It takes hours for it to happen.  It acts that way.  Only in pho files. Ill let you know what I see

James

________________________________

**Comment by cgchoffman** [comment] 2018-03-21 21:59
Is this the Race condition issue @Naatan, or is there a specific issue for that that I haven't come across yet?

**Comment by Naatan** [comment] 2018-03-22 15:33
It is most likely a race condition.

**Comment by cgchoffman** [comment] 2018-03-22 16:58
@Naatan,  I thought completions had the ability to invalidate calls that were no longer relevant.  Is that not the case?

**Comment by cgchoffman** [comment] 2018-03-22 17:55
Also, the root issue is not only in PHP, it's a general completions issue that it provides stale completions.  I see this in Python and Javascript.

**Comment by Naatan** [comment] 2018-03-22 18:02
@cgchoffman just add a dev note to the main post, no need to close and open a new one.

**Comment by cgchoffman** [comment] 2018-03-22 18:39
Done.

**Comment by Naatan** [comment] 2018-05-03 17:58
https://github.com/Komodo/KomodoIDE/commit/9788faf8bddec3c17aeefa38010b1271953c2be5

**Closed by Naatan** 2018-05-03 17:58 UTC
Labels: Severity: Priority, Type: Bug
