### ISSUE TITLE
'∞' is converted to '8' by the python REPL in Komodo

### ISSUE THREAD

**Issue by DavidHowlett** [Komodo/KomodoEdit#1760] opened 2016-06-29 14:31 UTC
### Short Summary

Python can handle unicode strings and the Komodo REPL allows me to add unicode characters but it seems like there is some weird conversion step between the two.

### Steps to Reproduce

Open the python REPL in Komodo and enter a string literal that contains '∞'.

### Expected results

```python3
>>>  '∞'
'∞'
>>> '∞' == '\u221e'
True
```

### Actual results

```python3
>>>  '∞'
'8'
>>> '∞' == '\u221e'
False
```

### Platform Information

I have seen the problem on:
Windows 10
Python 3.5
Komodo IDE
* Version 9.3.2
* Version 10.0.1

### Additional Information

I originally incorrectly filed this as a bug against cpython. The original bug report can be found at:
[http://bugs.python.org/issue27412](url)

This may be related to issue #1759

**Comment by mitchell-as** [comment] 2016-06-29 14:34
I'm going to mark this as a duplicate of #1759 because the same component is being used here as in #1759, and that component clearly has issues with UTF-8 characters. Thanks for the additional data point though.

**Closed by mitchell-as** 2016-06-29 14:34 UTC
