### ISSUE TITLE
Go to Def not working in a Python class

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3245] opened 2017-10-04 23:18 UTC
This works in K 10
### Steps to Reproduce

- open koWindowIntegration.p.py
- Go to line 284
- Right click > Go to Definition on `_appKeyPath` in `self._appKeyPath, "editAssociations")`.

### Expected results

Cursor to jump to line 123

### Actual results

`Could not find definition`

**Comment by mitchell-as** [comment] 2017-10-05 15:39
This was actually a duplicate of #3241.

**Closed by mitchell-as** 2017-10-05 15:39 UTC
Labels: Introduced: 11, Type: Bug, Type: Regression

**Comment by cgchoffman** [comment] 2017-10-05 15:45
Perfect.  Thanks Mitchell.
