### ISSUE TITLE
duplicate line/selection up/down does not work with selections

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#84] opened 2015-03-27 17:04 UTC
It always duplicates the entire line.

**Comment by aaroncampbell** [comment] 2015-03-31 20:18
This is closed, but what exacly was the fix?
If it is fixed, is there a way to get a nightly or something that includes this fix? This is a feature I use a lot (didn't even realize how much I used it until I upgraded from 8.5 and it quit working).

**Comment by cgchoffman** [comment] 2015-03-31 20:29
I think it got closed by accident?  I'm not sure.  Naatan?  I'm not actually able to reproduce this.
- Select a line
- Ctrl + shift + up[down]

Duplicates my current selected line as expected.  What platform are you on Aaron?

**Comment by aaroncampbell** [comment] 2015-03-31 20:34
I'm on Ubuntu.

ctrl+shift+up/down does nothing. Looking at the key bindings, I don't see those linked to anything. Maybe that's because it imported my settings from Komodo 8?

I added the key binding of ctrl+d (pretty standard for "duplicate" in other programs) for "Editor: Duplicate Line/Selection Down" and it works for duplicating a line, but if I have a text selection it still just duplicates the line.

**Comment by cgchoffman** [comment] 2015-03-31 21:16
My mistake.  I was SELECTING an entire LINE rather than just a portion.  Duplicating a selection is not working for me, unless it's an entire line.  Sorry for the confusion.

**Comment by Defman21** [comment] 2015-03-31 21:20
Duplicate a selection works fine if you select more than one line. If you just select a piece of string - Komodo will duplicate the entire line. But I don't understand how Komodo should duplicate only a portion of the line to before/after the line. So can you guys say what you want to see?

**Comment by aaroncampbell** [comment] 2015-03-31 21:28
It should go before or after (left or right, based on the user's text direction). Just like it did in Komodo 8 with "Editor: Duplicate Line or Selection" (but I guess adding in the before/after option)

**Comment by aaroncampbell** [comment] 2015-03-31 22:20
This has been [long standing functionality](https://bugs.activestate.com/show_bug.cgi?id=78819). Also, I'm not sure if it was my own bindings or default bindings that set it to CTRL+D. If it was mine, no big deal I'll just set them again. If it was default, I'm curious why that keybinding was repurposed.

**Comment by Naatan** [comment] 2015-04-01 15:24
This isnt closed, the issue this bug is referencing got closed. Github UX can be a bit weird sometimes.

**Comment by aaroncampbell** [comment] 2015-04-01 18:02
Yeah, sorry, I saw that after cgchoffman's reply.

However, the change from bug to enhancement doesn't seem right. This is a regression from KomodoIDE 8 to 9.

**Comment by Naatan** [comment] 2015-04-01 18:06
Duplicate up/down didnt exist in Komodo 8, so it is definitely not a regression :) It sounds like you may be confusing this with another feature?

**Comment by aaroncampbell** [comment] 2015-04-01 21:24
You had "Editor: Duplicate Line or Selection" which has been REPLACED with "Editor: Duplicate Line/Selection Down" and "Editor: Duplicate Line/Selection Up". I would consider it a regression because the old method worked for this but was *removed* in favor of these new ones, which don't work for a partial-line selection. At least I'm pretty sure it was removed as I don't see the original one anywhere, and my previous keybinding for it was free even though my other keybindings were imported.

**Comment by cgchoffman** [comment] 2015-04-02 00:35
Ctrl+D is bound to cmd_addNextWordToCaretSet and was added in [Komodo 8.5](https://github.com/Komodo/Komodoedit/blob/master/src/chrome/komodo/content/keybindings/keybindings.p.js#L330)
You can get the Ctrl+D functionality back by adding a macro with the following code in it
```javascript

//grab the editor scimoz object
var scimoz = ko.views.manager.currentView.scimoz;
// now duplicate the selection
sicmoz.selectionDuplicate();

```

It won't be identical I'm sure but should work, let us know.  You can then set the properties > Keybindings of the macro to Ctrl+D.  That should do for a workaround for now. 

Looks like we may need to revisit the implementation during [Komodo 9 development](https://github.com/Komodo/KomodoEdit/commit/e6a47d1c249e8c13d592b4dcb125e7dc210c7eba) and/or bring back the original code to be included as well as the new.

**Comment by aaroncampbell** [comment] 2015-04-07 16:28
The macro works as expected, with one minor fix. There's a typo, `sicmoz` should me `scimoz` in the selectionDuplicate line.
```javascript
//grab the editor scimoz object
var scimoz = ko.views.manager.currentView.scimoz;
// now duplicate the selection
scimoz.selectionDuplicate();
```

**Comment by cgchoffman** [comment] 2015-04-07 17:12
Yep, that would probably break it :dancer:

**Comment by thybzi** [comment] 2015-09-24 07:20
Is there any chance to modify a macro suggested by @cgchoffman and @aaroncampbell to function it a little bit different way: duplicated text should appear *before* (not after) selected text?

It would be perfectly the same way as *Duplicate Line/Selection* worked before, and as it works in WebStorm, NuSphere etc.

**Closed** 2015-11-25 17:51 UTC
Labels: Enhancement

**Comment by cgchoffman** [comment] 2015-11-25 21:57
> Is there any chance to modify a macro suggested by @cgchoffman and @aaroncampbell to function it a little bit different way: duplicated text should appear before (not after) selected text?

@thybzi please open a forum post for this http://forum.komodoide.com/

**Comment by mitchell-as** [comment] 2015-11-25 22:06
Actually, the fix I committed does this :) You can reference it if you want to create such a macro. It just involves moving the selection after duplicating the selection.

**Comment by aaroncampbell** [comment] 2016-03-30 14:27
Is there something preventing this from going into the 9.3 branch? It's really my biggest frustration with KomodoIDE now, and the fix seems to be here but hasn't been made available yet.

**Comment by mitchell-as** [comment] 2016-03-30 15:16
This cannot go into 9.3.x because it was tagged as an enhancement and we cannot put enhancements into bugfix releases.

**Comment by aaroncampbell** [comment] 2016-03-30 21:30
I would argue that this isn't an enhancement but a fix for a regression (as I mentioned in [previous](https://github.com/Komodo/KomodoEdit/issues/84#issuecomment-88577632) [comments](https://github.com/Komodo/KomodoEdit/issues/84#issuecomment-88635563) )

> You had "Editor: Duplicate Line or Selection" which has been REPLACED with "Editor: Duplicate Line/Selection Down" and "Editor: Duplicate Line/Selection Up". I would consider it a regression because the old method worked for this but was _removed_ in favor of these new ones, which don't work for a partial-line selection.

**Comment by aaroncampbell** [comment] 2016-03-30 23:30
Well, this bug is currently closed, and was closed by a commit that supposedly fixed it (6e93df9). It looks like the commit was only in the master branch though, and not the 9.3 branch. Is there a place that explains how to modify that file locally and test it? I'd be happy to test, but I'm not sure how to generate the .pyo file from the modified .py file, and I think the .pyo file is what Komodo IDE actually uses (sorry, I'm not super familiar with Python).

**Comment by cgchoffman** [comment] 2016-03-31 14:35
@aaroncampbell I missed that commit.  Thanks for pointing that out.  Just edit the `.py` file.  A new `.pyo` file should be generated automatically when you run Komodo again.  To be sure, you can delete the `.pyo` file.

**Comment by aaroncampbell** [comment] 2016-03-31 22:33
The actual diff didn't apply cleanly for me because the file has changed (although I'm honestly not sure if they is because it's the 9.3 branch or if it's because I'm on Komodo IDE vs Komodo Edit), but it was easy enough to find the lines in question and make the changes. The change works EXACTLY how I had expected/hoped. Specifically, if your cursor is on a line it duplicates that line, if you have multiple lines selected it duplicates all of them, and if you have part of a line selected it duplicates only the selection.

Thank you so much @cgchoffman and @mitchell-as

**Comment by cgchoffman** [comment] 2016-03-31 22:36
Not sure why the patch didn't apply but it's not because it's for IDE.  You wouldn't have access to that patch.  That's great to hear that it's working for you though!
