### ISSUE TITLE
Update PHPUnit Compatibility

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#302] opened 2015-05-28 14:47 UTC
Komodo does not work properly with PHPUnit 4.x

**Comment by girvo** [comment] 2015-09-10 01:37
:+1: really important feature I'd love to see. Is there any API documentation on the test harness stuff around?

**Comment by Naatan** [comment] 2015-09-24 15:02
Relevant: https://github.com/darnellefunk/komodo-phpunit-harness 

Thanks for sharing @darnellefunk!

**Comment by Defman21** [comment] 2015-12-12 10:14
Duplicate of #519, isn't it?

**Comment by Naatan** [comment] 2015-12-12 17:34
Technically the other way around, since this one is older. Thanks @Defman21.

**Comment by Naatan** [comment] 2016-02-22 16:26
Another one: https://github.com/mike-shmatov/KomodoPHPUnitDriver

**Comment by mitchell-as** [comment] 2016-03-22 21:44
Fixed via https://github.com/Komodo/KomodoIDE/commit/8e3f0321a1cf7925c742b3023332b41fc18a8e39

Note: Users need to ensure 'phpunit.phar' is in Komodo's PHP include path. (This may be obvious, but I know next to nothing about PHP.)

**Closed by mitchell-as** 2016-03-22 21:44 UTC
Labels: Enhancement

**Comment by Defman21** [comment] 2016-04-13 16:48
@mitchell-as could you say where I can set the include path for Komodo's PHP language? I have phpunit.phar on my $PATH but seems like it doesn't work or I'm using too new version (5.3.2)

**Comment by mitchell-as** [comment] 2016-04-13 17:02
PHPUnit 4+ requires PHP 5.6.0 or greater it looks like. So it seems you're using too "old" of a version :(

**Comment by Defman21** [comment] 2016-04-13 17:04
Nah, I'm using PHP 7.0.4 and PHPUnit 5.3.2, everything is working! Thanks @mitchell-as :+1:
