### ISSUE TITLE
YAML: invalid highlight in blocks

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1909] opened 2016-08-08 15:27 UTC
### Short Summary

This block is highlighted incorrectly:

```yaml
test: |
    Hello, world

    Bye
```

This one works fine:

```yaml
test: |
    Hello, world
    
    Bye
```

The difference between them is lack of spaces between "Hello, world" and "Bye".

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.0.1
*Operating System (and version)?* elementary OS 0.4

**Comment by cgchoffman** [comment] 2016-08-08 15:31
If you mean that there are no spaces (aka indenting) in the first example then that is not a bug as far as I know.  Indenting is very important, like Python, and indicates the block to YAML so it thinks that "Bye" is a new block with the missing indent.  But having said that, I have no idea which example you're referring to with your last comment.

**Comment by Naatan** [comment] 2016-08-08 15:34
I think both are correct YAML. The `|` indicates a raw text dump iirc. I'm able to parse both strings with yaml.

**Comment by cgchoffman** [comment] 2016-08-08 15:35
@Naatan I don't think so nathanr.  The specs tell me that a block is defined by indenting.  
Scalar:Scalar content can be written in block notation, using a literal style (indicated by “|”) where all line breaks are significant.  
Block: YAML’s block styles employ indentation rather than indicators to denote structure. This results in a more human readable (though less compact) notation.

ref: http://www.yaml.org/spec/1.2/spec.html#id2760844

**Comment by Defman21** [comment] 2016-08-08 15:45
I have "Clean trailing whitespace" enabled and those empty indents will be cleared. Highlight will be broken. I'll be pissed off a bit :(

**Comment by cgchoffman** [comment] 2016-08-08 16:29
> I have "Clean trailing whitespace" enabled and those empty indents will be cleared. Highlight will be broken. I'll be pissed off a bit :(

I don't understand your point.  Are you saying we should show that it's correct YAML when it's not because you want to have "Clean  trailing whitespace" enabled?  

If there is no indent between `Hello, world` and `Bye` then the "block" is broken it's not proper YAML.

**Comment by Defman21** [comment] 2016-08-08 16:38
Can YAML handle blocks inside Scalars?

```yaml
block: |
    Scalar text

    block: really
```

If yes, then I agree with you and my first example with empty line is incorrect.

**Comment by cgchoffman** [comment] 2016-08-08 16:41
> Can YAML handle blocks inside Scalars?

I'm not sure what you mean by "handle" in this context.  My understanding of how "literal scalars" are handled in YAML is written above. If you need more information then have a look at the spec I linked in my response: 
https://github.com/Komodo/KomodoEdit/issues/1909#issuecomment-238275779

**Comment by Defman21** [comment] 2016-08-08 16:44
I updated my previous message with an example of how YAML seems to be parsing Scalar blocks. I've read the link you gave and according to it, I made an informative trace of parsing.

**Comment by cgchoffman** [comment] 2016-08-08 20:28
@Defman21 did you use a tool to get the output in this comment? 
https://github.com/Komodo/KomodoEdit/issues/1909#issuecomment-238294638

**Comment by Defman21** [comment] 2016-08-08 20:29
Nope. I were thinking of writing a tool for that but.. 😛

**Comment by cgchoffman** [comment] 2016-08-08 20:46
Ok, I appreciate the effort but it's more confusing than any thing :p .  I'm going to close this now as I'm pretty sure we agree that Komodo does the right thing according to the spec.

**Closed by cgchoffman** 2016-08-08 20:46 UTC
Labels: Bug

**Comment by Defman21** [comment] 2016-08-08 20:50
Alright.
