### ISSUE TITLE
IDE X, Smart Editing, no highlights variables

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1544] opened 2016-05-19 08:07 UTC
### Short Summary

I have checked highlight variables (by click and by type) in Smart Editing, see screenshot below.
But variables never highlighted (in Default and any other color scheme).

### Steps to Reproduce

Tested on PHP code.
Click on any variable or type any variable..

### Platform Information

Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

### Additional Information

![ide10_highlight](https://cloud.githubusercontent.com/assets/217520/15386538/6d09834c-1db9-11e6-884d-9d0b2e700de6.png)

**Comment by mitchell-as** [comment] 2016-05-19 14:39
Hi, is Komodo providing any autocompletions for your PHP file? If not, it may still be scanning your project. Also, the right pane's code browser should show an outline of your file, including variables. If this is not populated, then Komodo's code intelligence has not scanned your file yet, and that is why you're not getting highlighting.

There is always a chance that code intelligence has thrown an error. Check your error log (Help > Troubleshooting > View Log File) for any errors related to code intelligence ("codeintel"). If there are any, please report them here.

**Comment by landy2005** [comment] 2016-05-19 17:32
Autocomplete provided normally (for functions/vars).

Not sure that this log entries relevant to trouble, but last log entries (when I try to select variables):
```
[2016-05-19 20:26:59,864] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-05-19 20:26:59,867] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-05-19 20:30:13,084] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-05-19 20:30:13,084] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by mitchell-as** [comment] 2016-05-20 14:13
I cannot reproduce this with a simple PHP file:

    <?php
    $test = "hi";
    echo $test;

When I click in the middle of `$test`, both `$test` instances are underlined. Maybe the color scheme is to blame. Edit > Preferences > Color Scheme > Editor > tag matching is the preference. You can see a sample on the right with "Variable and tag highlighting" as the last item. Do you get a colored underline?

**Comment by landy2005** [comment] 2016-05-20 15:29
Hrm, strange.. today I test same case at work and here issue do not reproduced..
I test with Default theme without any changes.
![ide10_select](https://cloud.githubusercontent.com/assets/217520/15432907/2249fa36-1ec1-11e6-85a7-0c59a523d579.png)

I'll test again at home today.
But only differences which I know now:
* work - normal screen (FullHD)
* home - HiDPI screens (Retina and 4k)

**Comment by Naatan** [comment] 2016-05-20 15:37
What OS do you use at home?

**Comment by landy2005** [comment] 2016-05-20 18:06
OS X El Capitan (10.11.5)
MacBook Pro (Retina, 15-inch, Late 2013)

Still issue at home version
![ide10_version](https://cloud.githubusercontent.com/assets/217520/15437229/fe307664-1ed6-11e6-9c5f-386528160345.png)

**Comment by landy2005** [comment] 2016-05-20 18:15
I changed in Default theme (for testing) "tag_matching" style to "Square box" and still same issue, variables not highlighted.

**Comment by cgchoffman** [comment] 2016-05-20 18:45
I wonder if this is a color scheme issue?  Perhaps Komodo is actually highlight the variables but you can't see it.  Could you try a different  color scheme?

**Comment by landy2005** [comment] 2016-05-20 18:51
Hrm, I restarted IDE in safe-mode and highlight worked now...

But I not know what installed (I not install in 10 anything).
In "Installed Packages" list empty.
I have IDE9 with some additional packages..

**Comment by Naatan** [comment] 2016-05-20 18:53
Do you have `Preferences > Editor > Smart Editing > Variable highlighting` checked?

**Comment by landy2005** [comment] 2016-05-20 18:55
Of course (see screenshot in first message).

**Comment by cgchoffman** [comment] 2016-05-20 19:05
> In "Installed Packages" list empty.

It resets your preferences too.  You may have a corrupt preferences file at home.

**Comment by landy2005** [comment] 2016-05-20 19:08
Additional tests:
- Restart without Addons - has no effect (no highlight)
- Restart without Tools - has no effect (no highlight)
- Reset Caches - has no effect (no highlight)
- Reset Everything - has no effect (no highlight)

**Comment by landy2005** [comment] 2016-05-20 19:12
log file since reset:
```
[2016-05-20 22:06:39,711] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform macosx, running on Darwin 15.5.0 version Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64)
[2016-05-20 22:06:39,711] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed May 11 15:42:24 2016
[2016-05-20 22:06:39,712] [ERROR] koInitService: 'list' object has no attribute 'push'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 290, in __init__
    self.checkStartupFlags()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 481, in checkStartupFlags
    paths.push(d[2])
AttributeError: 'list' object has no attribute 'push'
[2016-05-20 22:06:39,801] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2016-05-20 22:06:40,046] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-20 22:06:40,249] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-20 22:06:40,392] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 204, in 

[2016-05-20 22:06:40,461] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-20 22:06:40,759] [WARNING] keybindings: [Ctrl+Shift+K] was used for 'cmd_invokeTool', overriding to use 'cmd_scope-combined-toolscmds'
[2016-05-20 22:06:40,760] [WARNING] keybindings: [Ctrl+Shift+O] was used for 'cmd_goToFile', overriding to use 'cmd_scope-files'
[2016-05-20 22:06:41,916] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-20 22:06:42,379] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-20 22:06:42,478] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-20 22:06:42,478] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-20 22:06:42,528] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-20 22:06:42,659] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-20 22:06:42,660] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-20 22:06:42,848] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-20 22:06:43,507] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-05-20 22:06:43,508] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2016-05-20 22:06:45,334] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-20 22:06:45,335] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-05-20 22:06:45,337] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-20 22:06:46,092] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
```

**Comment by Naatan** [comment] 2016-05-20 20:28
Wait, "Reset Everything" had no effect but restart in safe-mode did? That makes no sense.

Did reset everything work?

**Comment by landy2005** [comment] 2016-05-20 20:59
> Wait, "Reset Everything" had no effect but restart in safe-mode did? That makes no sense.

Yes, this is really true. I Reset Everything again, same effect (mean no effect about highlight).

**Comment by Naatan** [comment] 2016-05-20 21:10
Did "Reset Everything" actually reset your settings?

**Comment by landy2005** [comment] 2016-05-20 21:17
Not sure, since I anyway use default config (after upgrade from ide9).

Hrm, seems as no.. I change theme (to Classic) and reset again - theme not changed.

**Comment by landy2005** [comment] 2016-05-20 21:36
Heh, seems as 2 additional issues: Reset not worked and Ctrl+K, H (VCS history) also not worked.

I moved dir {{10.0}} to {{10.0.bak}} in {{$HOME/Library/Application Support/KomodoIDE}},
default config created (all questions said yes, without any changes)..
Issue not fixed!

(And additionally I try to reset again - still no effect).

**Comment by Naatan** [comment] 2016-05-24 15:56
Could you share your prefs.xml (from the profile that doesnt work)? You can send it to support@activestate.com with a reference to this ticket (as it contains private information such as paths and server names (not passwords).

**Comment by landy2005** [comment] 2016-05-24 18:39
mail sent

**Comment by Naatan** [comment] 2016-05-25 15:11
Are you sure that's the one that doesn't work? I just tried it and it works fine for me. Note that you have the "Classic" editor scheme selected in the prefs.xml that you send me, which is unlike what you were showing in your screenshots.

**Comment by landy2005** [comment] 2016-05-25 19:45
Classic (not dark) theme is my more prefer theme and default.
But when I do screenshots, I specifically switched to Default to ensure that the same issue happen there.

Currently issue is not reproduced, but this happen only after I reset 2 or more times all configs/prefs.
In the beginning, after the first run, it is very annoying, I hope will not arise again.

**Comment by Naatan** [comment] 2016-05-25 19:53
As it stands you are the only one that has reported this issue and was able to reproduce it. As such I will close this issue. Let us know if it happens again.

**Closed by Naatan** 2016-05-25 19:53 UTC
Labels: Pending Response

**Comment by dubaaron** [comment] 2016-10-26 22:43
I've also been having this same issue on OS X El Capitan, Komodo 10.1.1.  No problem on my work computer running Windows 7/8/10.

**Comment by dubaaron** [comment] 2016-10-26 22:58
Restarted in safe mode, and highlighting came back.
