### ISSUE TITLE
Color Scheme Editor: Changing something in default schemes produces a buggy prompt dialogue

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1235] opened 2016-04-12 19:32 UTC
### Short Summary

Changing something in default schemes produces a buggy prompt dialogue. You're able to create a new color scheme from the one you tried to edit or press Cancel to continue changing the default one (the color picker will appear only after the dialogue closes). I think I should able to edit default schemes without any prompts about creating a new one (I can do it with "New..." button, which has the same functionality as the dialogue).

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 alpha
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment] 2016-04-12 19:34
Agreed the UX there is buggy. But no you cannot edit default color schemes, what the prompt does it ask you to basically clone the default one which you can then edit.

**Comment by Naatan** [comment] 2016-04-13 20:51
Dupe of #1150

**Closed by Naatan** 2016-04-13 20:51 UTC
Labels: Bug, New
