### ISSUE TITLE
Go to definition mangles path case on Windows

### ISSUE THREAD

**Issue by pageer** [Komodo/KomodoEdit#2156] opened 2016-11-17 16:23 UTC
### Short Summary
The "Go To Definition" feature incorrectly lower-cases the file path when opening a files.  This sounds like a trivial annoyance, but it is actually a causes a variety of subtle and non-obvious problems when interfacing with case-sensitive systems (see additional info).

### Steps to Reproduce
On windows, create a new project.  Create two new files, `Foo.php` and `Bar.php` - note the initial caps.  Add the following content to them:

```
# Foo.php
<?php
class Foo { }

# Bar.php
<?php
class Bar extends Foo { }
```
Open Bar.php in a Komodo tab and _close_ Foo.php.  Now right-click on the word "Foo" in the editing tab and select "Go To Definition".  Note that the issue will *NOT* occur if Foo.php is already open in another tab.

### Expected results
The file is opened in a new tab and the name and path should match what is stored on disk and is displayed when the file is opened via other mechanisms like the places tab.  See screenshot.

![goto-expected](https://cloud.githubusercontent.com/assets/1608240/20396488/58512984-acb4-11e6-9c9f-1e2f827f6213.png)

### Actual results
The file is opened, but the entire path is lower-cased, including the file name and the all the directory names.  In addition, the full path is displayed, even for files that are within the current project.  See screenshot.

![goto-actual](https://cloud.githubusercontent.com/assets/1608240/20396560/9c0d9c20-acb4-11e6-94d1-56951f2835fb.png)

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.1
*Operating System (and version)?* Windows 10 Enterprise

### Additional Information
The only work-around I know for this is to close the file and then re-open it using a mechanism other than "Go To Definition".  However, that pretty much defeats the point of having that feature in the first place.

Because Windows is case-insensitive, this isn't a problem for editing and viewing files.  However, it has unpleasant side effects when integrating with other systems.  Here are a couple of examples that I've noticed:
1. *Git integration breaks.*  If you click on the tab and try to view history, for example, you get no results because Git uses the case-sensitive file name.
2. *It plays havoc with publishing.*  I had set up the publishing feature to automatically push changes to a Linux box when I save a file and encountered this issue.  Komodo somehow ended up pushing the lower-cased filename to the server, so I ended up with two versions of the file on the server.  My changes were being pushed to the lower-case version of the file, but the server was actually executing the mixed-case version.

**Comment by Naatan** [comment] 2016-11-17 16:40
Thanks @pageer, this is a known limitation in our current version of CodeIntel and will be addressed in Komodo 11. I will leave this open as a reminder :)

**Comment by pageer** [comment] 2016-11-17 16:53
Oh, awesome!  Thanks @Naatan, good to know that's already on the roadmap.

**Comment by mitchell-as** [comment] 2016-11-17 16:54
Related to #1297

**Comment by Naatan** [comment] 2016-11-17 17:39
@mitchell-as that's not just related is it? Seems like this is a duplicate of that one.

**Comment by mitchell-as** [comment] 2016-11-17 17:58
That one demonstrates the fact that our version control is not case-insensitive on Windows.

**Comment by Naatan** [comment] 2016-11-17 18:08
Ok, but it seems like the same core issue to me. I'll close this in favour of that one.

**Closed by Naatan** 2016-11-17 18:08 UTC
Labels: Bug, Component: CodeIntel
