### ISSUE TITLE
mouse cursor flashing between arrow and insert in non-editor part of window

### ISSUE THREAD

**Issue by hobbsd** [Komodo/KomodoEdit#247] opened 2015-05-04 16:47 UTC
When the mouse cursor is over the editor part of the application window it shows the insert cursor steadily, but when it's moved over any other part of the window (e.g. menu buttons, places, etc.) it flashes rapidly between the arrow and the insert cursor and ends with insert when still.

Komodo Edit, version 9.0.1, build 15745, platform win32-x86.
Built on Mon Apr 20 19:05:56 2015.

**Comment by cgchoffman** [comment] 2015-05-04 20:45
I'm not seeing this in the Komodo Edit, version 9.0.1, build 15745, platform win32-x86.
Built on Mon Apr 20 19:05:56 2015.  Can you attach your logs as well?  Either in Gist form or  in a code section.

Is any one else experiencing this on Windows?

**Comment by hobbsd** [comment] 2015-05-05 17:08
It only seems to happen after having Komodo Edit open for an hour or so. I made a gist of the [log file](https://gist.github.com/hobbsd/2bae47ef5ee2e13a998b#file-mouse-cursor-error).

**Comment by cgchoffman** [comment] 2015-05-05 18:51
What color scheme are you using?  And can you try switching to a different one and see if the problem persists?

**Comment by hobbsd** [comment] 2015-05-05 18:58
I'm using "Monokai_Dark". Wouldn't the color scheme only affect the editor window? This problem is only occurring in the non-editor parts of the application window. Anyway, I'll try a different scheme and see if it happens.

**Comment by hobbsd** [comment] 2015-05-08 16:46
I switched scheme to "Chalk_Dark", and it has now happened again. Here's the relevant chunk of log file:
```
[2015-05-08 11:57:50,607] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-08 12:23:20,282] [WARNING] views: Inconsistent view count in view_closed event
[2015-05-08 12:28:27,400] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-05-08 12:28:27,400] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-05-08 12:28:30,992] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[2015-05-08 12:33:33,842] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[2015-05-08 12:36:47,450] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-08 12:36:47,450] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-08 12:36:47,450] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-08 12:36:47,451] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-08 12:36:47,453] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-08 12:36:47,453] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-08 12:36:47,454] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-08 12:36:47,591] [ERROR] analytics: 
-- EXCEPTION START --
TypeError: proxy is undefined
+ stack
    ko.analytics</this._proxyGa@chrome://analytics/content/analytics.js:476:9
    ko.analytics</this._proxySend@chrome://analytics/content/analytics.js:457:9
    ko.analytics</this.trackPageView@chrome://analytics/content/analytics.js:403:9
    ko.analytics</this.onWindowFocus@chrome://analytics/content/analytics.js:378:9
    ko.analytics</this._eventProxy@chrome://analytics/content/analytics.js:500:13
-- EXCEPTION END --
[2015-05-08 12:36:47,864] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-08 12:37:32,154] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-08 12:37:57,796] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-05-08 12:37:57,796] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by Naatan** [comment] 2015-05-11 19:18
Hmm those are some odd errors. Could you try using a clean profile to see if that reproduces the issue still? 

See https://community.activestate.com/node/15233

**Comment by hobbsd** [comment] 2015-05-12 18:55
It still happens with a clean profile.

**Comment by Naatan** [comment] 2015-05-12 22:30
Are you running on old hardware by chance?

**Comment by hobbsd** [comment] 2015-05-13 15:40
It's about 4 years old -- a dual-core Pentium running at 2.6 GHz. It's not being overtaxed at the time the error occurs.

**Comment by Naatan** [comment] 2015-05-28 15:34
Unfortunately not much we can do if we cant reproduce the issue :( You're the only person seemingly experiencing this bug. If you find out anything else please let us know, but until then I'm afraid I'll have to close this. I'm sorry :\

**Closed by Naatan** 2015-05-28 15:34 UTC

**Comment by hobbsd** [comment] 2015-05-28 15:45
I understand. I'll let you know if I can shed any light on it.
