### ISSUE TITLE
Komodo IDE css autocompletion not working with dashes

### ISSUE THREAD

**Issue by jwdeitch** [Komodo/KomodoEdit#52] opened 2015-03-25 15:03 UTC
Hi!

On Komodo IDE 9 mac, autocompletion for CSS doesn't seem to be entirely functional - typing in "font" will bring up the font-family, font-size, float, etc. suggestions like it should, however, once you add a dash ('-'), then the autocompletion should narrow down it's suggestions to things like font-family, font-size... however this is not the case: there is simply no autocompletion after a dash is appended..

**Comment by Naatan** [comment] 2015-03-25 15:05
I cannot reproduce this on mac. Could you try it with a brand new CSS file?

**Comment by Defman21** [comment] 2015-03-25 15:06
The bug exist in `<style>` tag. That's all I can say.

**Comment by jwdeitch** [comment] 2015-03-25 15:08
I just tried again and it works! Very strange.

**Comment by Naatan** [comment] 2015-03-25 15:08
Cannot repro with a style tag either;

```
<style>
    * {
        font-|
    }
</style>
```

Pops up font-family, font-size, etc. (using HTML5)

Could you supply a test-case?

**Comment by Naatan** [comment] 2015-03-25 15:09
@jwdeitch maybe it was something about the file you were working on when you encountered the bug, do you recall what it was?

**Comment by Defman21** [comment] 2015-03-25 15:11
Just tested it with a `<style>` tag in a HTML5 document. Works fine for me now :/
Komodo IDE, version 9.0.0-rc1, build 87167.

**Comment by jwdeitch** [comment] 2015-03-25 15:11
It was a blank file set to HTML5 syntax, with the html4 snippet inserted. I then added the <style> tag. The issue seems to be resolved for me as well.

**Comment by Naatan** [comment] 2015-03-25 15:12
It could be that Komodo was scanning your project/files at the time and so the autcomplete got delayed. Just an assumption though, hard to tell without being able to reproduce.

Will close this issue, let me know if you run into it again.

**Closed by Naatan** 2015-03-25 15:12 UTC
