### ISSUE TITLE
Search in files hangs at "Preparing..."

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#1978] opened 2016-08-30 10:15 UTC
### Short Summary

Search in Files hangs with output "Preparing..."

### Steps to Reproduce

   *   Komodo 10.0.1.0
   *   Press Ctrl+Shift+F
   *   Find: Text: ZTNum
   *   Where: Files
   *   Directories: pasted from Windows Explorer: "C:\oehhar\elmicron\projekte\el1061_dm_rect_extended\gen\source\zint_git_vc9_edit\backend\cdb_edit"
   * Press [Enter]

![komodo_find_start](https://cloud.githubusercontent.com/assets/12413997/18085318/f54e5538-6eaa-11e6-8392-f85f25c781e5.png)

### Expected results

Matches are listed

### Actual results

The search stalls in preparing 

![komodo_find_stall](https://cloud.githubusercontent.com/assets/12413997/18085364/24d5ea8c-6eab-11e6-92c7-f6ba0b5b8e33.png)

After 1 minuite, one may press the "X" to stop it preparing.

The folder to search contains 6 small source files and a subfolder with 3 empty sub-.folders and 3 files.
So this was searched with older komodo in 100ms max.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.1.0
*Operating System (and version)?* MS-Win10 Pro Ger

**Comment by mitchell-as** [comment] 2016-08-30 14:08
Is there anything odd in your Help > Troubleshooting > View Log File? I cannot reproduce this. Your files are not mounted to a remote machine are they? Your directory path doesn't seem to indicate so, but I thought I'd ask anyway.

**Comment by Defman21** [comment] 2016-08-30 14:10
I think there's an issue with 255-length of paths in Windows.

**Comment by oehhar** [comment] 2016-08-30 14:14
Thank you for the answer.

Network drive: no

Here is the log entry when I redo the issue:

```
[2016-08-30 14:52:51,378] [WARNING] views: Inconsistent view count in view_opened event
ERROR:xpcom:Unhandled exception calling 'int8 * AddFindResults(in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[], in uint32, in Array[]);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFindResultsView.py", line 141, in AddFindResults
    "findresults-filename": self.NormalizeFilename(fileName),
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFindResultsView.py", line 93, in NormalizeFilename
    if fileName.index(self.rootPath) is not 0:
ValueError: substring not found
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFinder.py", line 158, in AddFindResults
    return self.obj.AddFindResults(*args)
  File "<XPCOMObject method 'AddFindResults'>", line 3, in AddFindResults
Exception: 2147500037 (NS_ERROR_FAILURE)
Exception in thread Find/Replace Thread 5:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFinder.py", line 209, in run
    self._report(flush=True)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFinder.py", line 419, in _report
    self._r_lineNums, self._r_columnNums, self._r_contexts)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)
```

**Comment by mitchell-as** [comment] 2016-08-30 14:38
Okay, thanks for the log. This is a duplicate of #1964 and has been fixed in a nightly build, which you can get from here: https://github.com/Komodo/KomodoEdit/issues/1964#issuecomment-242841243

**Closed by mitchell-as** 2016-08-30 14:38 UTC
Labels: Pending: Response

**Comment by oehhar** [comment] 2016-08-31 08:09
Thank you for the message. I downloaded the "nightly build". When I start the setup, windows gives the message "not a valid setup program"...

**Comment by Defman21** [comment] 2016-08-31 12:06
@cgchoffman seems like your windows build does not work.

**Comment by cgchoffman** [comment] 2016-08-31 19:19
@oehhar Try downloading it again.  It's working fine for me.

**Comment by oehhar** [comment] 2016-08-31 19:49
When I download "Komodo-IDE-10.1.0-89457.msi" on my desktop and I do a double-clock, I get the following message:
![komodo-ide-10 1 0-89457_msi](https://cloud.githubusercontent.com/assets/12413997/18143929/8635e4c0-6fc4-11e6-8fb3-f87fc600a18d.png)
Rough translation: "This install packet may not be opened. Check by the manufacturer if it is a valid windows install packet."
This is not so important, you may close the issue.
Thank you anyway,
Harald

**Comment by cgchoffman** [comment] 2016-08-31 19:54
If this is reproducible then it is extremely important.  Can you confirm that you downloaded the installer again?

**Comment by oehhar** [comment] 2016-08-31 20:17
> Can you confirm that you downloaded the installer again?
yes

**Comment by cgchoffman** [comment] 2016-08-31 20:18
Ok. i'll look in to this and see what's up.

**Comment by cgchoffman** [comment] 2016-08-31 20:48
Hrm, looks like the staging of the installer wasn't completed.  The file was missing almost 5 MB.  I'm sorry i missed that @oehhar.  That's what I get for pushing bits on a weekend I guess.  I've replaced the broken installer with a working one and tested to confirm it works.  Putting things in motion to get those bits live now.

**Comment by cgchoffman** [comment] 2016-08-31 21:16
@oehhar if you're interested, you can set your update channel to "nightly" and have Komodo auto-update for you.  If you have Komodo 10.1 open do the following
- open the JS console: View menu > Tabs & Sidebars > Console
- run this command: `require("sdk/preferences/service").set("app.update.channel", "nightly");`
- Help > Check for Updates

**Comment by cgchoffman** [comment] 2016-08-31 22:49
Fixed installer is in place now: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by oehhar** [comment] 2016-09-08 13:43
I confirm that the bug is fixed in the nightly builds. Thank you, Harald
