### ISSUE TITLE
Komodo edit

### ISSUE THREAD

**Issue by Cardknox** [Komodo/KomodoEdit#1969] opened 2016-08-26 15:47 UTC
### Short Summary
seaching  js file for the $ symbol

### Steps to Reproduce
search current doc for $

### Expected results
results

### Actual results
error
![kerror](https://cloud.githubusercontent.com/assets/12068809/18011371/e4739000-6b82-11e6-9d4b-70dfc8c9741a.png)

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment] 2016-08-26 15:49
Duplicate of #1964

**Closed by mitchell-as** 2016-08-26 15:49 UTC
