### ISSUE TITLE
9.2 Auto Push to Server not working

### ISSUE THREAD

**Issue by JohnWSteel** [Komodo/KomodoEdit#505] opened 2015-08-08 13:16 UTC
Using Windows 8.1 and  Komodo IDE, version 9.2.0, build 87616, platform win32-x86.
Built on Tue Aug 04 10:31:35 2015.
Auto Push to server not working and I have to resynch after every save.
In 9.1 this would happen occasionally, but in 9.2 it happens all the time.
I have checked that the autopush option in publishing is checked.

**Comment by Defman21** [comment] 2015-08-09 00:02
Is this post relevant to your issue? http://forum.komodoide.com/t/publishing-from-places-publish-on-save-broken-with-9-2-0-ide-update/1875/6?u=defman

**Comment by JohnWSteel** [comment] 2015-08-09 12:03
Yes I had seen that thanks, but had also reported it here as a bug.

**Comment by Defman21** [comment] 2015-08-09 12:05
2devs: the problem is in a space in the name of a folder.

**Comment by Naatan** [comment] 2015-08-14 17:47
Fixed on IDE repo - https://github.com/Komodo/KomodoIDE/commit/10e87e4caf40af12010d8306abc69e784c434280

Nightly with fix should be available tomorrow.

**Closed by Naatan** 2015-08-14 17:47 UTC
Labels: Bug, Regression
