### ISSUE TITLE
No changelog on Nightly-Updates?

### ISSUE THREAD

**Issue by hoppfrosch** [Komodo/KomodoEdit#2379] opened 2017-03-01 09:31 UTC
### Short Summary
On nighlty updates, the update procedure is triggered within KomodoIDE. Within the Komodo IDE Update-Dialog box there is a link [View more Information about this update](http://downloads.activestate.com/Komodo/nightly/komodoide/2017/02/2017-02-28-00-10.2.x/updates/Komodo-IDE-10.2.1-89846-win32-x86-partial-10.2.1-89837.html) 

Following this link leads to a page only containing a headline ("Komodo Changelog (build 89846, previous build 89838)" - and nothing else (empty page)

This is valid since the last few updates .... (cannot remember whether it had worked anytime)

### Expected results

Provide a page with USEFUL information!

### Actual results

Empty page!

### Platform Information

Latest KomodoIDE beta

**Comment by cgchoffman** [comment] 2017-03-01 21:31
Just an FYI, we don't generate release notes for nightlies so there wouldn't be anything else to link to.  The best we could do for now is link to the previous major release release-notes.

**Comment by cgchoffman** [comment] 2017-03-01 21:33
Oh we could link to a search of closed 10.2.x bugs on github. That would be helpful.  There is currently no way to do this though other than manually change the update server source to provide a new link.  I'll investigate if we can make this a little less painful and error prone.

**Comment by Naatan** [comment] 2017-03-01 21:54
Maybe we should just link it to our github commit log.

**Comment by cgchoffman** [comment] 2017-03-01 21:56
That would only show edit commits.  The issues link would show all X.Y.x issues closed even if their commit is in the IDE repo.  Although, it would also show stuff we just closed as any other possible close reason outside of "fixed", eg. not reproducible, dupe, etc.

**Comment by Naatan** [comment] 2017-03-01 22:04
I know, just trying to find a compromise. We can't just show an IDE commit log as that may contain sensitive information, and only showing `rn=` commits will often result in an empty log.

**Comment by cgchoffman** [comment] 2017-03-01 22:28
> just trying to find a compromise

Me too.  Just providing information.

**Comment by hoppfrosch** [comment] 2017-03-02 05:22
My opinion: if there's a link, it just shouldn't lead to ... nowhere (esp. if I'm a willing to act as a beta-tester on nightly builds, I would like to know at least what has changed with latest build and what I should/might have a special look at ...)

**Comment by cgchoffman** [comment] 2017-03-02 16:43
> My opinion: if there's a link, it just shouldn't lead to ... nowhere

@hoppfrosch, we all agree there.  It's a bug that the link goes nowhere.

**Comment by Naatan** [comment] 2017-03-02 18:19
I've created a note on our changelog here:

http://docs.komodoide.com/changelog#komodo-ide-edit-10-release-notes_nightly-changelog

Let's link there for now.

**Comment by cgchoffman** [comment] 2017-03-02 22:46
Revisions 92440 for updates server:
/sites/komodo.activestate.com/branches/production/

**Closed by cgchoffman** 2017-03-02 22:46 UTC
Labels: Bug, Bug: UX
