### ISSUE TITLE
Edit 11 install only says "lets get started" - no editor: ????

### ISSUE THREAD

**Issue by SoftMoonWebWare** [Komodo/KomodoEdit#3650] opened 2019-01-08 19:39 UTC
### Short Summary
Was using Komodo Edit 10.2.3 on Windows 7, Intel CORE i7, 6GB-RAM; mostly no probs, other than missing scrollbar arrows at top/bottom of scrollbar.  Hard to work when your mouse wheel goes out and the file is several thousand lines....
Just yesterday (Jan 7, 2019) downloaded Komodo Edit 11.1.0
Installed it today.  Started Komodo Edit 11, and a small window showed up with "Let's Get Started" in the titlebar and a snippet of code in the display showing the code-highlighter example I remember from Komodo Edit 10's Color Scheme editor.  This window has no functionality, other than being able to highlight the text.  Clicking left or right buttons does nothing.   No menu bar is present.

### Steps to Reproduce
I did not try to reproduce this

### Expected results
I expected to have a new working version of Komodo Edit: version 11

### Actual results
A useless window that does nothing

### Platform Information
See above
*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information
Thanks for creating this product.  I have enjoyed programming with it since version 8.

**Comment by SoftMoonWebWare** [comment] 2019-01-08 20:09
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/2738285/pystderr.log)

**Comment by Naatan** [comment] 2019-01-09 16:07
You said that you removed the scheme files, did this make a difference? ie. was the dialog functional when you did this?

**Comment by SoftMoonWebWare** [comment] 2019-01-09 17:36
Naatan: no, never any functionality, other than being able to drag the mouse to select the code snippet shown in the window (can't do anything with the selected text); maximize, minimize, and restore/shrink the window (with title that says "Let's Get Started").  The window starts small: 6"×6" on my 20"×11" full 1080p monitor.  I can not drag the window's side edge and widen it, however, I can drag its bottom edge and lengthen it, all the way down into the monitor below.  I believe this is what this window is SUPPOSED to do.  It is not the actual Edit 11 application window, but the code-demo window from the "edit colors" function of the application.

Also, by the way, I have two (2) monitors, my laptop monitor and the external.  External is setup as main monitor, above laptop, since it is bigger (Windows' idiosyncrasies, I think it was the background image).  Windows' main toolbar is set up as a pull-down from the top, since the main is the top monitor.

I think at first the Edit 11 window appeared about where the Edit 10 window last was when I had it shrunk (not maximized, but showing; i.e. "Restore Down").  After playing with it a bit, it now appears in the upper-left corner of my main monitor (the top external one) when I start the application.

With Edit 10, the dual monitors cause problems on some pop-ups.  For example, if I click on the left side of the code where it is highlighted to show changes have occurred, the popup showing the changes may appear on the lower monitor, while the Edit 10 window is maximized in the upper (main) window, if the line of code that I click on is below the center of the Edit 10 window.  If the line of code is above the center of the Edit 10 window, the pop-up appears where it should be.  I am not complaining about that here (Edit 10 is too old now to complain), but I just wonder how much of this current problem with Edit 11 is due to the monitor confusion issue.

The Edit 11 window I do see is not supposed to be a functioning window in any sense, just an example of code highlighting.  It does not do anything on Edit 10, either.  I am wondering if the real Edit 11 application window is just hiding somewhere, or can not figure out how to appear due to a bug as my system is set up.

Meanwhile.......Komodo Edit 10 is still working just like it always has...

**Comment by SoftMoonWebWare** [comment] 2019-01-09 17:40
When I think about it, maybe the old scheme files from Komodo Edit 8 confused Edit 11, and caused it to fire-up the "Let's Get Started" dialog, and that sub-app expected nothing, and got something....now it is just stuck in a limbo....
About to give up on it Edit 11 altogether.  Too much wasted time already...

**Comment by Naatan** [comment] 2019-01-09 19:10
Before you do, try completely resetting your Komodo prefs:

https://docs.activestate.com/komodo/11/manual/trouble.html#start-komodo-from-a-temporary-profile

I can't tell what the issue is you're experiencing, but I'm fairly certain it has something to do with the inherited settings from Komodo 10

**Comment by cgchoffman** [comment] 2019-02-05 01:07
@SoftMoonWebWare any update on this?

**Comment by SoftMoonWebWare** [comment] 2019-02-05 15:57
I gave up on 11.  Now I'm just trying to find out why Edit 10.2 expands my tabs to 4 characters instead of 2 on a newly created file.  Default new filetype is text.  Tabspacing in the preferences for text=2.  I changed the filetype to JavaScript in the bottom-right corner.  Tabspacing for JavaScript also =2.  I pasted a section of .js code from another open .js file.  All was fine.  I chose "save as" from the "file" menu, and saved it with a .js extension.  The tabs immediately expanded to 4 spaces.  "Show whitespace" shows only tab characters leading the lines.  I tried closing the file and reopening it.  I tried renaming the file and opening it.  I tried closing Edit 10.2 and reopening all.  Still 4-char-width tabs display in the editor.  I guess Edit 10 is rude enough to insert unseen tab-spacing data into the file?  Or is it just that buggy?

**Comment by cgchoffman** [comment] 2019-02-05 18:14
@SoftMoonWebWare this forum post should help you with tab prefs in Komodo: https://community.activestate.com/taxonomy/term/559

I'm going to close this ticket now.

**Closed by cgchoffman** 2019-02-05 18:14 UTC
Labels: Pending: Response

**Comment by SoftMoonWebWare** [comment] 2019-02-09 17:51
Yea, I know all that.
there were no tab settings info in the file.  All Komodo settings were for 2 spaces per tab.
the Editor showed 4.  Bug.
I appreciate the free software. but would not pay for the level of quality found in this project.  Now that I use GitHub more, I have been thinking of an IDE, but not KOMODO! AND NOT WITH THIS POOR LEVEL OF HELP!.
I fixed the tab file bug by highlighting a single tab, EDIT > REPLACE > REPLACE ALL: replacing them all with 2 spaces.  Then, by typing a tab into an existing line, all spaces became tabs ("prefer tabs over spaces" in preferences)
Thanks for the doc links, but I can already read.  The software needs its bugs fixed!!!  I was hoping EDIT 11 would address that, but it is so buggy it won't even load.  
What LAME assistance!  You did not even address the real issue!
EDIT 11 WON'T LOAD.,

**Comment by cgchoffman** [comment] 2019-02-11 18:31
@SoftMoonWebWare please file a new bug report.  This has diverge greatly from the original ticket.   In the mean time:

@SoftMoonWebWare did you disable "Allow files contents to override Tab and Indentation settings"? in your *Editor > Indentation* prefs?

> ("prefer tabs over spaces" in preferences)

Are you referencing this because it's enabled?  Or disabled?  It sounds like you've enabled it.

> Then, by typing a tab into an existing line, all spaces became tabs ("prefer tabs over spaces" in preferences)

That's not how that feature works.  This sounds like you've enabled some addon or Userscript that is causing this to occur.  Prefer tabs over spaces only acts on single key presses, it doesn't update the entire document.  See gif below.  Please try to reproduce this issue in Safe Mode (*Help > Troubleshooting > Restart in Safe-Mode*).  If you're able to reproduce it please file a new ticket.
![tabs-spaces](https://user-images.githubusercontent.com/655154/52584874-15a04b80-2de8-11e9-9152-323bd4645e30.GIF)

**Comment by SoftMoonWebWare** [comment] 2019-02-15 19:15
why file a bug ticket on Edit 10?
when you save a file, Edit tends to convert spaces to tabs.
it seems it converted each "space in a tab" to a tab; with tab-spacing at 2, this doubled each tab.
Just wish I could move on to Edit 11.  If it still is a problem, then I'll file another bug.
Done wasting time (days!) trying to get Edit 11 to work.  I'll wait for 12 and see what happens then.
just hope I get scrollbars and less bugs.
I could spend a week on this forum describing bugs in 10.
But why file tickets on Edit 10?  it is out of date...

**Comment by cgchoffman** [comment] 2019-02-15 19:32
> why file a bug ticket on Edit 10?

You wouldn't.  I missed that you had moved to 10.  I see you didn't try resetting your preferences for Komodo 11.  That will likely resolve your issue.
