### ISSUE TITLE
Upgrading KomodoEdit 10.x -> 11.0, Toolbox is empty

### ISSUE THREAD

**Issue by baldmantom** [Komodo/KomodoEdit#3242] opened 2017-10-04 21:01 UTC
### Short Summary
When I upgraded from KomodoEdit 10.x to 11.0, my Toolbox was empty.

### Steps to Reproduce

- Need a KomodoEdit 10.2 profile
- Remove ~/Library/Application Support/KomodoEdit/11.0 folder if present
- Start KomodoEdit 11 

### Expected results

After upgrade, Toolbox should be populated with previous tools

### Actual results

Toolbox is empty.

### Platform Information

Upgrade KomodoEdit 10.2 to 11.1

OS - macOS Sierra 10.12.6

### Additional Information

![screen shot 2017-10-04 at 4 55 10 pm](https://user-images.githubusercontent.com/11304664/31199462-73ae7312-a925-11e7-964a-c94bcd413b56.png)

**Comment by Naatan** [comment] 2017-10-04 21:34
Does removing `~/Library/Application Support/KomodoEdit/11.0/tools/Tutorials` make it load (close Komodo before removing)?

**Comment by Naatan** [comment] 2017-10-04 21:34
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by baldmantom** [comment] 2017-10-05 19:42
Log file attached.

[KomodoEdit-Upgrade.txt](https://github.com/Komodo/KomodoEdit/files/1360656/KomodoEdit-Upgrade.txt)

**Comment by cgchoffman** [comment] 2017-10-05 20:58
ref: https://community.komodoide.com/t/komodo-11-using-custom-templates/3904/8

**Comment by Naatan** [comment] 2017-10-05 21:09
@baldmantom any chance you could share your toolbox with us? You can send it to support@activestate.com with subject "attachment for Komodo issue 3242".

**Comment by baldmantom** [comment] 2017-10-05 23:10
Sent. Please let me know if you need any additional info.

**Comment by Naatan** [comment] 2017-10-06 15:01
It seems we already fixed the issue that was causing this, you can try out latest nightly to get the fix early, or wait until the 11.0.1 release.

Nightly link: http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by baldmantom** [comment] 2017-11-02 22:47
I downloaded 11.0.1 tonight, deleted ~/Library/Application Support/KomodoEdit/11.0 and launched the new version. My toolbox is still empty. I'm attaching a log file from my latest attempt, in case there is any new information contained therein.

[Komodo.txt](https://github.com/Komodo/KomodoEdit/files/1439615/Komodo.txt)

**Comment by Naatan** [comment] 2017-11-03 15:13
Try renaming the "templates" folder in your old profile folder, then repeat your upgrade steps (delete or move 11.0).

**Comment by baldmantom** [comment] 2017-11-03 16:11
That got the toolbox to show up. It seems like it'll be a manual step to add the templates back, then?

**Comment by Naatan** [comment] 2017-11-03 16:43
Unfortunately it is. I'll have a look at fixing the underlying error, thank you for reporting!

**Comment by cgchoffman** [comment] 2018-01-24 18:31
I can't reproduce this.  Closing unless someone can still reproduce it.

**Closed by cgchoffman** 2018-01-24 18:31 UTC
Labels: Type: Bug
