### ISSUE TITLE
Go to definition is not working for Python

### ISSUE THREAD

**Issue by mjainQA** [Komodo/KomodoEdit#2837] opened 2017-08-14 20:48 UTC
### Short Summary

Go to definition is not working for functions defined outside the script. 

### Steps to Reproduce
1. Use the attached sample scripts. 
2. Try viewing definition of a function in verifyPythonAdditionalPkgList_smoke.py
3. To execute the script, use command 'python3 verifyPythonAdditionalPkgList_smoke.py 3.5'

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 
Komodo IDE, version 11.0.0-alpha1, build 90438, platform macosx.
Built on Mon Aug 14 09:36:30 2017.

**Comment by mjainQA** [comment] 2017-08-14 20:49
[Archive.zip](https://github.com/Komodo/KomodoEdit/files/1223419/Archive.zip)

**Comment by mitchell-as** [comment] 2017-08-14 21:05
Hi, it seems you need to create a project that contains these files first in order for it to work. Without a project, these files are not stored in the codeintel database.

@Naatan perhaps we should have a way of storing non-project files in the codeintel database?

**Comment by Naatan** [comment] 2017-08-14 21:18
It works with the "Places" root also. But besides those two I can't think of a way that wouldn't lead to scanning folders that shouldn't be scanned.

**Comment by Naatan** [comment] 2017-08-14 21:18
@mjainQA can you verify that creating a project with those files or pointing your Places widget at those files resolves the issue?

**Comment by mjainQA** [comment] 2017-08-14 21:43
@Naatan Created a project and added the existing attached files. I am still able to reproduce the issue.


![image.png](https://zube.io/files/komodo/caa56b04cdfe093d5428be4a87deed55.png)

**Comment by Naatan** [comment] 2017-08-14 21:56
That's not what we meant. You have to point your project itself at the files. 

![image](https://user-images.githubusercontent.com/278649/29293682-e8187010-8119-11e7-91a8-6514ac08e5f9.png)

**Comment by mjainQA** [comment] 2017-08-14 22:01
Here is what my preferences look like:

![image](https://user-images.githubusercontent.com/26605593/29293836-6ccc65a0-8101-11e7-88c3-9285076728a6.png)

**Comment by Naatan** [comment] 2017-08-14 23:27
Can you share your error log (all of it) after reproducing the issue?

**Comment by mjainQA** [comment] 2017-08-15 20:28
Logs: 
[pystderr_2017-08-15_Komodo IDE 11.0.0 Alpha 1 nightly (Build 90443).txt](https://github.com/Komodo/KomodoEdit/files/1226314/pystderr_2017-08-15_Komodo.IDE.11.0.0.Alpha.1.nightly.Build.90443.txt)

**Comment by Naatan** [comment] 2017-08-15 20:45
Assigning to myself to test this in Windows / Mac when I have the time. Log didn't have anything useful.

**Comment by Zebrafish007** [comment] 2017-11-22 10:44
In my case the `go to definition` information is not updated frequently if a script changed class or definition names (python) . Perhaps the "temporary" file Komodo uses for this type of data is not updated frequently enough? Lets say... I''l check in two weeks again.. and if changed I'll do that?

**Comment by mitchell-as** [comment] 2017-12-11 17:14
This must have been fixed recently. I am not able to reproduce on master in Windows.

**Closed by mitchell-as** 2017-12-11 17:14 UTC
Labels: Introduced: 11, Pending: Response
